### ISSUE TITLE
bug: GC doesn't work as expected due to timezone

### ISSUE THREAD

**Issue by Xuanwo** [juicedata/juicefs#1002]
**What happened**: GC doesn't work on minio for timezone is different.

**What you expected to happen**: GC work as expected

**How to reproduce it (as minimally and precisely as possible)**: https://github.com/juicedata/juicefs/discussions/717

**Comment by SandyXSD** [comment]
Could you provide more information about the problem? As you mentioned in #717, timezone should not raise any issue for gc.

**Comment by Xuanwo** [comment]
Well, I need the confirmation from @201341. For now, I think the behavior is expected:

https://github.com/juicedata/juicefs/blob/ccb13303eabbed684e392f018a025a684a197012/cmd/gc.go#L196

Because we always skip the newly created (in one hour) object during gc.

**Comment by 201341** [comment]
@Xuanwo hi, It's not the timezone problem. It's the sql delete bug, And I solve it at the pr https://github.com/juicedata/juicefs/pull/728

**Comment by Xuanwo** [comment]
OK, we can close this issue safely now!

**Comment by Xuanwo** [comment]
It's a bad case that is normally in open source projects: An issue has been resolved in PR but not reflected in the original discussion or issue. So every people here (me, SandyXSD, davies, and 201341) all are wasting time to resolve an issue that has been resolved.

ping juicefs's maintainers (maybe @davies and @SandyXSD?) to take some actions to prevent those problems happen again.
