### ISSUE TITLE
Add a tool to do benchmark

### ISSUE THREAD

**Issue by davies** [juicedata/juicefs#101]
**What would you like to be added**:

Add a tool to do benchmark the mounted JuiceFS

**Why is this needed**:

After a volume is mounted, we would like to how it is performing.

**Comment by suzaku** [comment]
This can be implemented as a set of Go Benchmarks if we have  #104 done.

**Comment by davies** [comment]
Actually, this tool is used to benchmark the mount point (similar to the juicefs cli), not just the client.
