### ISSUE TITLE
fail to create pvc with redis-sentinel 

### ISSUE THREAD

**Issue by liyansong** [juicedata/juicefs#1034]
背景：使用宿主机搭建三个节点redis sentinel 创建pvc 报错如下
结论：解析 redis sentrinel 地址的时候有点问题，把 masterName 当成 ip，所以走了 DNS 解析，timeout 之后才能解析后面的 ip

![image](https://user-images.githubusercontent.com/20124391/142811171-ee5a9166-b33a-4a4c-a756-36d135f87e9b.png)
![image](https://user-images.githubusercontent.com/20124391/142811189-e6409387-47a9-4d8c-97eb-0ed7f2f1cc85.png)

**Comment by davies** [comment]
麻烦看一下 host 以及容器里面的 juicefs 的版本，最近修复过 setinel 地址的解析问题，可能已经修复了

**Comment by davies** [comment]
This is already fixed by 0.17.2
