### ISSUE TITLE
Refactor this repo to present a well documented Go library

### ISSUE THREAD

**Issue by suzaku** [juicedata/juicefs#104]
**What would you like to be added**:

Refactor this repo to present a well documented Go library. This library should provide interfaces similar to `os.Open` so that we can use JuiceFS without actually mounting it.

**Why is this needed**:

1. We can't easily mount a filesystem in some environments (eg. testing / serverless)
2. The Go implementation is already here in this repo

**Comment by davies** [comment]
Added path based API in Go.
