### ISSUE TITLE
Support s3 storageclass

### ISSUE THREAD

**Issue by fakemoon** [juicedata/juicefs#1043]
**What would you like to be added**:
For s3-like object storage backend, storageclass is used to control redundancy level of a object (https://docs.aws.amazon.com/AmazonS3/latest/userguide/storage-class-intro.html) and it has been implemented by s3 client library. It would be great if we could have this property on juicefs format to let user have the choice of what level of redundancy they want and reduce the cost of s3.

**Why is this needed**:
I want to use “Reduced Redundancy” level of storageclass for non-important files.

**Comment by davies** [comment]
Currently, we can create the S3 bucket manually and pick the storage class as you like. We should document this.

Since different vendor has different storage classes, it will be a burden to maintain them.

**Comment by geevarghesest** [comment]
Hi, I am currently using juicefs in production.
When creating a bucket in S3, the storage class cannot be specified.
Existing bucket objects can have their storage classes changed using lifecycle configuration, but doing so requires an object expiry value of at least 30 days. I am in need of instantly moving every file uploaded by juicefs to a different storage class. Would appreciate any assistance.

**Comment by davies** [comment]
Just realized that we can't change the default storage class of S3 bucket, let's reopen this issue, target it for v1.1 release

**Comment by zhijian-pro** [comment]
done by #3534
