### ISSUE TITLE
Using JuiceFS via configuration file

### ISSUE THREAD

**Issue by yuhr123** [juicedata/juicefs#1070]
**What would you like to be added**:

Options related to formatting, mounting file systems are written to a configuration file, use `/etc/juicefs` as the default configuration file path, also available specified using something like `--config` or `-c`. 

For example, the config file:

```
[myjfs1]
storage = minio
bucket = http://127.0.0.1:9000/pics
access-key = minioadmin
secret-key = minioadmin
meta-url = redis://127.0.0.1:6379/1
```

And then create or mount the file system:

```shell
$ juicefs format myjfs1
$ juicefs mount myjfs1 ~/mnt/jfs
```

**Why is this needed**:

This simplifies use and management by eliminating the need to repeatedly enter relevant information

**Comment by davies** [comment]
@yuhr123 A filesystem only need to be formatted once, then these will be stored into redis or other database, so I think this configuration is not that useful for end users.

**Comment by yuhr123** [comment]
The configuration file does not break the existing working form, the information that makes up the file system is still recorded in the database. Just one more way to manage it.

More than just mounting, I think the use of configuration file can improve the user experience, based on the following considerations:

1. usually, the database address is too long and inconvenient to remember, as in the example above, it is more user-friendly to use `myjfs1` directly instead of the lengthy url.
2. it would be more intuitive to adjust the various mounting parameters of the file system in the configuration file, e.g.
```
[myjfs1]
storage = minio
bucket = http://127.0.0.1:9000/pics
access-key = minioadmin
secret-key = minioadmin
meta-url = redis://127.0.0.1:6379/1
cache-dir = /var/myjfs
cache-size = 20480
buffer-size = 512
...
```
3. when using multiple JuiceFS file systems on one host, the parameters of each file system can be fine-tuned through the configuration file, and each file system defines a separate name to avoid confusion in management.

**Comment by davies** [comment]
As we discussed offline, we can have these options in /etc/fstab, then use `mount  /jfs` to simplify it. We should document it some where.

**Comment by yuhr123** [comment]
> As we discussed offline, we can have these options in /etc/fstab, then use `mount /jfs` to simplify it. We should document it some where.

👌 Currently in the "Auto-mount" section of the documentation [Quick Start Guide](https://juicefs.com/docs/community/quick_start_guide/#6-automatically-mount-juicefs-on-boot)
