### ISSUE TITLE
The upload and download rate limit is difficult to reach the actual value, so corresponding optimization needs to be added

### ISSUE THREAD

**Issue by dannyfe** [juicedata/juicefs#1080]
There seems to be a gap between the QoS management speed limit upload and download rate and the set value and the actual transmission value. For example, the upload rate set to 1000Mbps is actually affected, and the real data should be far less than 125mb / s. After personal testing, it is found that the impact is great. Can the speed limit function of QoS be optimized to control QoS more accurately, For example, the adaptive function can be designed or modified manually

**Comment by davies** [comment]
@dannyfe The current implementation is not accurate, the actual bandwidth is only half of configured, we will fix it.
