### ISSUE TITLE
The Used and Size values in df -h are still inaccurate 

### ISSUE THREAD

**Issue by aland-zhang** [juicedata/juicefs#1081]
This issue is linked to https://github.com/juicedata/juicefs/issues/1069
I docker pull juicedata/juicefs-csi-driver:nightly
juicefs --version
juicefs version 1.0-dev (2021-11-30 4179214)
df -h are inaccurate too!

ls -alth /data
total 1.1G
-rw-r--r-- 1 root root 1.0G Nov 30 09:45 bbbb
drwxrwxrwx 2 root root 4.0K Nov 30 09:45 .
-rw-r--r-- 1 root root 0 Nov 30 09:34 1.txt

/data/bbbb file create by ：
fio --name=test --rw=write --direct=1 --numjobs=30 --ioengine=libaio --iodepth=64 --bs=64k --time_based=1 --runtime=30 --size=1G --filename=./bbbb -group_reporting

but df -h /data used 32G!

Filesystem Size Used Avail Use% Mounted on
JuiceFS:myfs 1.0P 32G 1.0P 1% /data

juicefs dump redis://redis-master:6379/1 --subdir pvc-8a23158c-558a-41d9-909d-b5de550e852f    
"Counters": {
    "usedSpace": 33286025216,
    "usedInodes": 38,
    "nextInodes": 497,
    "nextChunk": 74282,
    "nextSession": 22,
    "nextCleanupSlices": 0
  },
  "Sustained": [],
  "DelFiles": [],
  "FSTree": {
    "attr": {"inode":297,"type":"directory","mode":511,"uid":0,"gid":0,"atime":1638264447,"mtime":1638265516,"ctime":1638265516,"atimensec":880254866,"mtimensec":533290166,"ctimensec":533290166,"nlink":2,"length":0},
    "entries": {
      "1.txt": {
        "attr": {"inode":397,"type":"regular","mode":420,"uid":0,"gid":0,"atime":1638264889,"mtime":1638264889,"ctime":1638264889,"atimensec":102199296,"mtimensec":102199296,"ctimensec":102199296,"nlink":1,"length":0}
      },
      "bbbb": {
        "attr": {"inode":398,"type":"regular","mode":420,"uid":0,"gid":0,"atime":1638265516,"mtime":1638265546,"ctime":1638265546,"atimensec":533290166,"mtimensec":949348954,"ctimensec":949348954,"nlink":1,"length":1073741824},
        "chunks": [
          {"index":0,"slices":[{"chunkid":74265,"pos":0,"size":67108864,"off":0,"len":67108864}]},
          {"index":1,"slices":[{"chunkid":74278,"pos":0,"size":67108864,"off":0,"len":67108864}]},
          {"index":2,"slices":[{"chunkid":74281,"pos":0,"size":67108864,"off":0,"len":67108864}]},
          {"index":3,"slices":[{"chunkid":74234,"pos":0,"size":20250624,"off":0,"len":20250624}]},
          {"index":4,"slices":[]},
          {"index":5,"slices":[]},
          {"index":6,"slices":[]},
          {"index":7,"slices":[]},
          {"index":8,"slices":[]},
          {"index":9,"slices":[]},
          {"index":10,"slices":[]},
          {"index":11,"slices":[]},
          {"index":12,"slices":[]},
          {"index":13,"slices":[]},
          {"index":14,"slices":[]},
          {"index":15,"slices":[]}
        ]
      }
    }
  }
}
2021/12/01 04:31:58.330907 juicefs[12928] <INFO>: Dump metadata into  succeed

**Comment by davies** [comment]
Currently, `df` show all the used data of a whole volume, not just the current mounted directory, so this behavior is expected.

**Comment by liyongxian** [comment]
The Volume Size in kubernetes is declarative and limited,But Not The Whole  Size. I think it is a bug.

**Comment by davies** [comment]
@liyongxian JuiceFS does not support capacity in K8S yet, it's on the roadmap.
