### ISSUE TITLE
add support for Oracle Cloud Storage

### ISSUE THREAD

**Issue by tigerinus** [juicedata/juicefs#1083]
**What would you like to be added**:

support for Oracle Cloud Storage

**Why is this needed**:

Oracle Cloud has a free-tier plan that comes with 10 GB of alway-free Object Storage. It's an excellent option for people want to try JuiceFS on the cloud.

**Comment by xiaogaozi** [comment]
Hi @tigerinus, it seems like the API of Oracle Cloud Storage is [S3 compatible](https://docs.oracle.com/en-us/iaas/Content/Object/Tasks/s3compatibleapi.htm), you could use [S3 storage type](https://juicefs.com/docs/community/how_to_setup_object_storage#amazon-s3) directly.

**Comment by tigerinus** [comment]
@xiaogaozi - That sounds great. But how exactly do I choose in the JuiceFS console in order to get integrated with Oracle Cloud?

![image](https://user-images.githubusercontent.com/7172560/144166376-8c87a516-a974-4d7b-87b1-59d961cbae04.png)

**Comment by xiaogaozi** [comment]
The issue of JuiceFS console belongs to [JuiceFS Hosted Service](https://juicefs.com/docs/cloud/hosted_service), not the community version of JuiceFS.

I'll close this issue and create an internal issue for JuiceFS console, thanks for your feedback.

**Comment by davies** [comment]
Based on https://docs.oracle.com/en-us/iaas/Content/Object/Tasks/s3compatibleapi.htm, we still need to parse the region from endpoint for oracle object storage.

We can support it using S3 SDK with some parsing rules.
