### ISSUE TITLE
Build JuiceFS release staticly which can run on alpine

### ISSUE THREAD

**Issue by chnliyong** [juicedata/juicefs#109]
**What would you like to be added**:
Build JuiceFS staticly with [musl libc](https://www.musl-libc.org/)

**Why is this needed**:
Currently the release binary is built using glibc，[Alpine Linux](https://alpinelinux.org/) which is largely used under container environments as its small size, only has musl libc, we can add support for it.

**Comment by davies** [comment]
Fixed by #147
