### ISSUE TITLE
Question: Is it required using Redis with persistence enabled?

### ISSUE THREAD

**Issue by wi1dcard** [juicedata/juicefs#11]
Since JuiceFS relies on Redis to store the metadata of files. Is it required to enable the persistence features such as RDB, AOF, or both to make sure the metadata won't lose once the Redis server gets restarted?

P.S. I Can't log in to the Slack channel (error: `<my-email> doesn’t have an account on this workspace.`) so I posted my question here.

**Comment by davies** [comment]
@wi1dcard Good question, we will check that to make sure that the Redis is correctly persistented.

**Comment by davies** [comment]
@wi1dcard You need to create an account for each workspace (same to juicefs here).

**Comment by wi1dcard** [comment]
@davies  Sure! I'd like to create an account for the JuiceFS workspace. However, I think I can only join workspaces that I've been invited into. Is it possible to send me an invitation link? I can also send an email to request an invitation. Thanks!

**Comment by davies** [comment]
I have created #16 to track this.

**Comment by xiaogaozi** [comment]
@wi1dcard Have you been tried use this [URL](https://join.slack.com/t/juicefs/shared_invite/zt-kjbre7de-K8jeTMouDZE8nKEZVHLAMQ) to join Slack?
