### ISSUE TITLE
IPv6 cannot assign requested address

### ISSUE THREAD

**Issue by MyTheValentinus** [juicedata/juicefs#112]
**What happened**:
I don't have active IPv6 link and no ipv6 is configured on any inteface.
I have this error log: 
```
2021/01/23 19:12:06.391177 juicefs[15700] <WARNING>: upload chunks/0/0/1_0_4096: RequestError: send request failed
caused by: Put "https://dvc-juicefs-test.s3.fr-par.scw.cloud/test/chunks/0/0/1_0_4096": dial tcp [2001:bc8:1002::30]:443: connect: cannot assign requested address (try 1)
```
**What you expected to happen**:
use ipv4 when no ipv6 is available

**Environment**:
- JuiceFS version (use `./juicefs --version`): juicefs version dev (now HEAD)
- Cloud provider or hardware configuration running JuiceFS: dedicated server
- OS (e.g: `cat /etc/os-release`): Ubuntu 20.04
- Kernel (e.g. `uname -a`): Linux 5.4.0-64-generic 
- Object storage (cloud provider and region): Scaleway fr-par
- Redis info (version, cloud provider managed or self maintained): Simple docker redis container
- Network connectivity (JuiceFS to Redis, JuiceFS to object storage): localhost

**Comment by davies** [comment]
@MyTheValentinus Thanks for reporting this, it should be fixed by https://github.com/juicedata/juicesync/commit/dc40ea723a9ecfff91cb33e001370751b0752049 and 169b9c4
