### ISSUE TITLE
gateway create or delete dir wrong  

### ISSUE THREAD

**Issue by sjp00556** [juicedata/juicefs#1129]
https://github.com/juicedata/juicefs/blob/e85b22f4d12c7f044a06a66f348066da0d1372f5/pkg/gateway/gateway.go#L155

this should be `sep + path.Join(p...)`, we don't need retain trailing SlashSeparator of the last element

`curl -X PUT "endpoint/bucket/path/"`  expect to create dir path, but now it will create path/path

**Comment by davies** [comment]
@sjp00556 Is there a document for this behavior?

**Comment by sjp00556** [comment]
when object is end with / , n.path shouldn't retain the last /. we treat dir and file samely in fs.FileSystem, dir no need end with /.   i have already tested put/get/head/copy/deletet/multipart api.  it went well

i fix it here: https://github.com/juicedata/juicefs/pull/1130

**Comment by sjp00556** [comment]
here is delete example to understand this bug:
`curl -X DELETE sjpdev:8889/starfstest/path/`  we expect to delete` /path`,  but it will delete `/path/path `

![image](https://user-images.githubusercontent.com/6017354/146168905-f93e8765-4b84-4e8a-ba7a-a3842c61816d.png)

**Comment by davies** [comment]
@sjp00556 We sent #1149 to fix the bug in fs.Mkdir() and fs.Delete(), thanks for reporting it.

For Put with trailing slash, JuiceFS can't be compatible with S3, so we follow the behavior in MinIO: 1) create the directory when the body is empty 2) fail the request when body is not empty.
