### ISSUE TITLE
juicefs doesn't remove chunks from S3 after file rewrite

### ISSUE THREAD

**Issue by kariedo** [juicedata/juicefs#113]
**What happened**:

juicefs doesn't remove chunks from S3 after file rewrite

**What you expected to happen**:

juicefs clean up chunks from the previous versions of the file

**How to reproduce it (as minimally and precisely as possible)**:

```
juicefs mount -d localhost /s3storage
mkdir /s3storage/test/
for i in {1..100}; do dd if=/dev/urandom of=/s3storage/test/testrewrite bs=1M count=1; done
```
As a result S3 bucket has 106 objects and is 106MB in size

**Anything else we need to know?**:

**Environment**:
- JuiceFS version (use `./juicefs --version`): juicefs version dev (now HEAD) (but it's 0.9.3)
- Cloud provider or hardware configuration running JuiceFS: DO Spaces
- OS (e.g: `cat /etc/os-release`):  20.04.1 LTS
- Kernel (e.g. `uname -a`): 5.4.0-51-generic
- Object storage (cloud provider and region): DigitalOcean NYC
- Redis info (version, cloud provider managed or self maintained): 5.0.7-2
- Network connectivity (JuiceFS to Redis, JuiceFS to object storage): local Redis

**Comment by davies** [comment]
@kariedo Thanks, we are investigating it.

**Comment by davies** [comment]
@kariedo The bugs are fixed. JuiceFS compact the slices in background, so there will be some objects left in your test cases, they will be deleted after reading them or deleting the file.
