### ISSUE TITLE
check if the file already sync to the backend when enable writeback mode

### ISSUE THREAD

**Issue by zphj1987** [juicedata/juicefs#1139]
when i  enable the writeback mode, and i have two host mount the redis, after the client complete write,the object will push to the backend async, the other client only can read the right file data after the object all push to the backend 

so  i want to check  if myfile alredy push all object to the backend,  is there a file list to see ,which file is syncing?

**Comment by davies** [comment]
Inside the cache-dir, there is a sub-dir called `rawstagging`, which has all the pending blocks. 

The `info` command can find all the blocks for given file, so may be we can check the status of all the blocks there.

Btw, if you need to read the file from another machine immediately, please don't enable writeback mode.

**Comment by zphj1987** [comment]
thank you for your reply ,i will try it

Davies Liu ***@***.***> 于2021年12月16日周四 12:29写道：

**Comment by SandyXSD** [comment]
Will add metrics in p8s showing the number of pending objects.
