### ISSUE TITLE
Implement OVH S3 Storage.

### ISSUE THREAD

**Issue by yctn** [juicedata/juicefs#1168]
OVH is a major cloud provider here in Europe.

the OVH S3 implementation requires you to define the region. since it is currently not possible to specify this seperaly from the endpoint i cannot use the OVH S3 bucket for now.

`AuthorizationHeaderMalformed: The authorization header is malformed; the region 'us-east-1' is wrong; expecting 'SBG'`

Please Add OVH as a supported provider. or consider to add a --region flag so the user can decide on there own which value should be here.

**Comment by davies** [comment]
@yctn We tried to OVH as an supported provider, but can't get a verified account to test it. Do you have the bandwidth to work on this?  Please follow the code in pkg/object/ as examples.
