### ISSUE TITLE
Support multi s3 bucket

### ISSUE THREAD

**Issue by rongfengliang** [juicedata/juicefs#1215]
Currently I do some tests. juicefs only support on bucket. any plan for support multi bucket

**Comment by davies** [comment]
Multiple buckets is support in latest main branch, please build it from source.

```
   --multi-buckets           use top level of directories as buckets (default: false)
```

**Comment by rongfengliang** [comment]
@davies  from docs I see that's for gateway. Can we support adding multi buckets  for  juicefs format

**Comment by xiaogaozi** [comment]
@rongfengliang Yes you can, the `format` command supports `--shards` option, you could specify multi-buckets for one JuiceFS file system. For more information, please see https://github.com/juicedata/juicefs/pull/349 here.

**Comment by rongfengliang** [comment]
> @rongfengliang Yes you can, the `format` command supports `--shards` option, you could specify multi-buckets for one JuiceFS file system. For more information, please see https://github.com/juicedata/juicefs/pull/349 here.

ok thanks!
