### ISSUE TITLE
s3 gateway even degrade the s3 object read performance

### ISSUE THREAD

**Issue by dengzhh** [juicedata/juicefs#1223]
**What happened**:
I use juicefs to run a s3 gateway to Ceph s3 and use cosbench to test the s3 read/write performance. The test result show the write performance imporoved as expected, but read performance get degraded, even the metrics blockcache_hit_bytes show the cache 100 percent hitted.

**What you expected to happen**:
s3 gateway should imporove read performance when cached hitted.

**Anything else we need to know?**
juicefs gateway commandd line parameters: juicefs gateway  --cache-dir memory --cache-size 2048 --writeback --metrics 0.0.0.0:9568 redis://xxx.xxx.xxx.xxx:6379/3 0.0.0.0:9000

**Environment**:
- JuiceFS version: 0.17.5
- OS: centos 7
- Kernel: 3.10.0-693
- Object storage : Ceph S3
- Metadata engine info : redis 6.2.6

**Comment by SandyXSD** [comment]
Could you provide more information? e.g:
1. parameters of the cosbench test
2. total memory of your test node running the gateway
3. results of the write/read tests on juicefs gateway / Ceph s3

The objects should be read from cache-dir (i.e. memory) directly if cache hit.

**Comment by dengzhh** [comment]
1. cosbench workload config  file : 
<?xml version="1.0" encoding="UTF-8"?>
<workload name="juices3read" description="sample workload configuration" config="">
    <auth type="none" config=""/>
    <storage type="s3" config="accesskey=UYLM5WCCFLX6MWRBYP46;secretkey=vluS7nv2dSrC7ClXyWQ5NKMQddA7a387Y5mShRHP;endpoint=http://rgw.vndapp.com:9000;path_style_access=true"/>
    <workflow config="">
        <workstage name="normal" closuredelay="0" config="">
            <auth type="none" config=""/>
            <storage type="s3" config="accesskey=UYLM5WCCFLX6MWRBYP46;secretkey=vluS7nv2dSrC7ClXyWQ5NKMQddA7a387Y5mShRHP;endpoint=http://rgw.vndapp.com:9000;path_style_access=true"/>
            <work name="normal" type="normal" workers="1" interval="5"
                division="none" runtime="30" rampup="0" rampdown="0"
                afr="200000" totalOps="0" totalBytes="0" config="">
                <auth type="none" config=""/>
                <storage type="s3" config="accesskey=UYLM5WCCFLX6MWRBYP46;secretkey=vluS7nv2dSrC7ClXyWQ5NKMQddA7a387Y5mShRHP;endpoint=http://rgw.vndapp.com:9000;path_style_access=true"/>
                <operation type="read" ratio="100" division="none"
                    config="containers=u(1,1);objects=u(1,50);" id="none"/>
            </work>
        </workstage>
    </workflow>
</workload>

2. total memory of test node: 16G

3. result of read test on Ceph s3:
Op-Type	Op-Count	Byte-Count	Avg-ResTime	Avg-ProcTime	Throughput	Bandwidth	Succ-Ratio
read	121 ops	3.9 GB	246.65 ms	37.82 ms	4.05 op/s	130.77 MB/S	100%

4. result of read test on Juicefs gateway:
Op-Type	Op-Count	Byte-Count	Avg-ResTime	Avg-ProcTime	Throughput	Bandwidth	Succ-Ratio
op1: read	60 ops	1.92 GB	495.7 ms	17.97 ms	2.02 op/s	64.55 MB/S	100%

**Comment by dengzhh** [comment]
> Could you provide more information? e.g:
> 
> 1. parameters of the cosbench test
> 2. total memory of your test node running the gateway
> 3. results of the write/read tests on juicefs gateway / Ceph s3
> 
> The objects should be
