### ISSUE TITLE
make juicefs.ceph failed

### ISSUE THREAD

**Issue by ldd91** [juicedata/juicefs#1227]
**What happened**:
When  exec make juicefs.ceph,it throws "/opt/mygo/pkg/mod/github.com/ceph/go-ceph@v0.4.0/rados/command.go:106:9: could not determine kind of name for C.rados_mgr_command" 
**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**

**Environment**:
- JuiceFS version (use `juicefs --version`) or Hadoop Java SDK version: 0.17.5
- Cloud provider or hardware configuration running JuiceFS: ardware configuration running JuiceFS
- OS (e.g `cat /etc/os-release`): CentOS Linux release 7.3.1611 (Core)
- Kernel (e.g. `uname -a`): 4.4.146-1.el7.elrepo.x86_64
- Object storage (cloud provider and region, or self maintained): Ceph RADOS
- Metadata engine info (version, cloud provider managed or self maintained):
- Network connectivity (JuiceFS to metadata engine, JuiceFS to object storage):
- Others: go version :1.16   gcc version gcc-7

**Comment by chnliyong** [comment]
JuiceFS use [go-ceph](https://github.com/ceph/go-ceph) v0.4.0 to access rados. `go-ceph v0.4.0` support ceph versions: luminous, mimic, nautilus, octopus (**version 12~15**) as noted [here](https://github.com/ceph/go-ceph#supported-ceph-versions). 
This means JuiceFS doesn't support accessing rados older than **luminous(version 12)**

On CentOS 7, I installed librados development files from official yum repository:
```
# yum search librados
已加载插件：fastestmirror
Loading mirror speeds from cached hostfile
=========================================================================== N/S matched: librados ===========================================================================
librados2.i686 : RADOS distributed object store client library
librados2.x86_64 : RADOS distributed object store client library
librados2-devel.i686 : RADOS headers
librados2-devel.x86_64 : RADOS headers


# yum install -y librados2-devel.x86_64
.....
....
已安装:
  librados2-devel.x86_64 1:10.2.5-4.el7

作为依赖被安装:
  boost-iostreams.x86_64 0:1.53.0-28.el7       boost-random.x86_64 0:1.53.0-28.el7       boost-system.x86_64 0:1.53.0-28.el7       boost-thread.x86_64 0:1.53.0-28.el7
  librados2.x86_64 1:10.2.5-4.el7

完毕！
```
The `make juicefs.ceph` can reproduce your problem. You can check your `librados-devel` version like this:
```
# rpm -qa | grep librados
librados2-10.2.5-4.el7.x86_64
librados2-devel-10.2.5-4.el7.x86_64
```
Here on my server, version 10, older than **luminous**.

**Comment by ldd91** [comment]
Our Ceph version is octopus, rpm -qa |grep  librados in my server shows:
[root@xxxxx-xxx ~]# rpm -qa |grep librados
librados2-10.2.5-4.el7.x86_64
librados2-devel-10.2.5-4.el7.x86_64

**Comment by ldd91** [comment]
down librados2-15.2.10-0.el7.x86_64.rpm and librados-devel-15.2.10-0.el7.x86_64.rpm  from http://fr.ceph.com/rpm-15.2.10/el7/x86_64/ ,Then exec  yum install -y *.rpm can resolve this probelm
