### ISSUE TITLE
cmd.NotImplemented

### ISSUE THREAD

**Issue by xdchangfu** [juicedata/juicefs#1248]
在 Kubernetes 中部署 S3 网关
部署成功
访问网关地址 http://localhost:9000 后台报异常

API: SYSTEM(bucket=5e76d207cf4ab20866fdc03c83e8a0f4e8f458e880777956ec0bae4e9f23f6c5, object=5e76d207cf4ab20866fdc03c83e8a0f4e8f458e880777956ec0bae4e9f23f6c5)
Time: 01:15:31 UTC 01/05/2022
DeploymentID: 51cc0143-1868-4ecc-940b-ea57246af263
RemoteHost: 5e76d207cf4ab20866fdc03c83e8a0f4e8f458e880777956ec0bae4e9f23f6c5
Error: cmd.NotImplemented
       3: /go/pkg/mod/github.com/juicedata/minio@v0.0.0-20210222051636-e7cabdf948f4/cmd/bucket-policy.go:52:cmd.(*PolicySys).IsAllowed()
       2: /go/pkg/mod/github.com/juicedata/minio@v0.0.0-20210222051636-e7cabdf948f4/cmd/object-handlers.go:354:cmd.objectAPIHandlers.GetObjectHandler()
       1: net/http/server.go:2050:http.HandlerFunc.ServeHTTP()

**Comment by davies** [comment]
@xdchangfu Could you provide the steps to reproduce the issue?

**Comment by zhijian-pro** [comment]
Open it when there is feedback.
