### ISSUE TITLE
Add oceanbase support

### ISSUE THREAD

**Issue by rongfengliang** [juicedata/juicefs#1262]
**What would you like to be added**:

oceanbase use mysql protocol . but current do test not working 
some reasons

- init

m.updateCollate

- NewSession

sync2 flock and plock 

**Why is this needed**:

we can use oceanbase as juicefs metastorage

**Comment by davies** [comment]
Do you know how to find out whether the server is OceanBase?  The `updateCollate` is used the fix the case-censitivity of index, what's the case for OceanBase?

**Comment by rongfengliang** [comment]
@davies  We want use OceanBase as metadata storage for ha && scale. I had test 

some fail test

- `while parameter _ob_enable_prepared_statement is disabled, prepared statement not supported`

this can be solved by `ALTER system set _ob_enable_prepared_statement =true; `




- `juicefs[8618] <FATAL>: update collate: Error 1235: Alter charset or collation type not supported`

this caused by oceanbase not support change charset  so diable updateCollate for current MySQL will work

- duplicate for UQE_jfs_flock_flock
I find it caused by `sql.go`  `NewSession ` method. we connect it will update table definition. current  oceanbase 

not better  compatible with MySQL

**Comment by davies** [comment]
Based on the discussion in oceanbase/oceanbase#742 , this depends on  xorm or oceanbase.

**Comment by SandyXSD** [comment]
We need https://github.com/oceanbase/oceanbase/issues/756 fixed, which should provide a proper way to determine if the server is OceanBase

**Comment by longdafeng** [comment]
https://github.com/oceanbase/oceanbase/issues/756  this bug has been fixed

**Comment by davies** [comment]
@longdafeng Can you test latest main branch with latest Oceanbase and post the result here?

**Comment by davies** [comment]
The latest main branch support OceanBase, please try it.
