### ISSUE TITLE
Use pure Go Zstd implementation

### ISSUE THREAD

**Issue by xiaogaozi** [juicedata/juicefs#1272]
**What would you like to be added**:

Use [klauspost/compress](https://github.com/klauspost/compress) to replace [DataDog/zstd](https://github.com/DataDog/zstd)

**Why is this needed**:

The DataDog/zstd library relies on CGO, but klauspost/compress is pure Go implementation. And according to [benchmark](https://github.com/dgraph-io/badger/issues/1162#issuecomment-646958797) from Badger, klauspost/compress has better performance than DataDog/zstd.

**Comment by suzaku** [comment]
@davies Can you share the benchmark script? Maybe we can try again with newer versions of Go and the library?

**Comment by SandyXSD** [comment]
There seems no obvious improvement to switch to the pure Go implementation, so we'll just keep the current one.
