### ISSUE TITLE
password will be exposed in cmd `juicefs mount METAURL MOUNTPOINT`

### ISSUE THREAD

**Issue by zwwhdls** [juicedata/juicefs#1313]
**What happened**:
If I use password in METAURL, and then run `juicefs mount METAURL MOUNTPOINT`. The password will be exposed:

```
$ ps -ef |grep juicefs
root      363941  363909  0 08:18 ?        00:00:00 sh -c /bin/mount.juicefs redis://:password@10.96.118.10/0 /jfs/pvc-59bb01ed-0f55-4263-a5f3-c95e588780d3 -o metrics=0.0.0.0:9567
root      363961  363941  0 08:18 ?        00:00:00 /bin/mount.juicefs redis://:password@10.96.118.10/0 /jfs/pvc-59bb01ed-0f55-4263-a5f3-c95e588780d3 -o metrics=0.0.0.0:9567
```

**What you expected to happen**:
Hide passwords  running processes

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**

**Environment**:
- JuiceFS version (use `juicefs --version`) or Hadoop Java SDK version:
- Cloud provider or hardware configuration running JuiceFS:
- OS (e.g `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Object storage (cloud provider and region, or self maintained):
- Metadata engine info (version, cloud provider managed or self maintained):
- Network connectivity (JuiceFS to metadata engine, JuiceFS to object storage):
- Others:

**Comment by davies** [comment]
Fixed by #1333
