### ISSUE TITLE
Add BadgerDB support

### ISSUE THREAD

**Issue by diluga** [juicedata/juicefs#1326]
JuiceFS currently provides an implementation of Sqlite3, but there are several problems with this metadata engine.
1. non-native golang, cgo performance loss is large
2. not suitable for cross-platform deployment, such as windows systems
3. kv engine is more suitable for single-computer scenarios

Benefits of implementing a badgerDB-based metadata engine
1. Based on the existing KV engine extensions, enriching the software ecology
2. LSM optimization, which can improve better performance
3. native golang implementation, good cross-platform support

Application scenarios for stand-alone kv engines
1. poor network connection quality
2. No need for multiple nodes to share data
3. Greater use of local SSD, NVMe performance advantages

Introduction of badgedb : https://dgraph.io/docs/badger/get-started/

**Comment by davies** [comment]
Badger has all the features we need, is more popular than other KV engine for Go, sounds good.

**Comment by 201341** [comment]
Could juicefs offer a general interface to adapt to all kv engine?  If I want to add any other kv engines except tikv, I have to rewrite some duplicate codes. @davies

**Comment by SandyXSD** [comment]
It won't be much. You only have to implement tkvClient and kvTxn interfaces [here](https://github.com/juicedata/juicefs/blob/main/pkg/meta/tkv.go#L42-L60)
You may take a look at [memkv](https://github.com/juicedata/juicefs/blob/main/pkg/meta/tkv_mem.go) for a quick reference as it’s simple and designed for test purpose. The implementation of TiKV engine can be found [here](https://github.com/juicedata/juicefs/blob/main/pkg/meta/tkv_tikv.go) with 200+ lines

**Comment by 201341** [comment]
> It won't be much. You only have to implement tkvClient and kvTxn interfaces [here](https://github.com/juicedata/juicefs/blob/main/pkg/meta/tkv.go#L42-L60) You may take a look at [memkv](https://github.com/juicedata/juicefs/blob/main/pkg/meta/tkv_mem.go) for a quick reference as it’s simple and designed for test purpose. The implementation of TiKV engine can be found [here](https://github.com/juicedata/juicefs/blob/main/pkg/meta/tkv_tikv.go) with 200+ lines



> It won't be much. You only have to implement tkvClient and kvTxn interfaces [here](https://github.com/juicedata/juicefs/blob/main/pkg/meta/tkv.go#L42-L60) You may take a look at [memkv](https://github.com/juicedata/juicefs/blob/main/pkg/meta/tkv_mem.go) for a quick reference as it’s simple and designed for test purpose. The implementation of TiKV engine can be found [here](https://github.com/juicedata/juicefs/blob/main/pkg/meta/tkv_tikv.go) with 200+ lines

Got it.
