### ISSUE TITLE
support gc control in NewSession

### ISSUE THREAD

**Issue by fishincat** [juicedata/juicefs#1337]
**What would you like to be added**:
support gc control in NewSession

**Why is this needed**:
gc is a heavy task, all the client do the same gc task will cause meta server a high pressure!

**Comment by davies** [comment]
Currently, only the lightweight jobs will be done concurrently by clients. There could a rare case that the lightweight job become a heavy one, we should provide another layer of protection to avoid them (do it concurrently).

**Comment by fishincat** [comment]
> Currently, only the lightweight jobs will be done concurrently by clients. There could a rare case that the lightweight job become a heavy one, we should provide another layer of protection to avoid them (do it concurrently).

```
func (m *kvMeta) cleanupDeletedFiles() {
	for {
		time.Sleep(time.Minute)
		klen := 1 + 8 + 8
		now := time.Now().Unix()
		vals, _ := m.scanValues(m.fmtKey("D"), func(k, v []byte) bool {
			// filter out invalid ones
			return len(k) == klen && len(v) == 8 && m.parseInt64(v)+60 < now
		})
		for k := range vals {
			rb := utils.FromBuffer([]byte(k)[1:])
			inode := m.decodeInode(rb.Get(8))
			length := rb.Get64()
			logger.Debugf("cleanup chunks of inode %d with %d bytes", inode, length)
			m.doDeleteFileData(inode, length)
		}
	}
}
```
this function could be a heavy one for example.
