### ISSUE TITLE
Support path-style URL for S3 (or S3-compatible) storage

### ISSUE THREAD

**Issue by xiaogaozi** [juicedata/juicefs#134]
**What would you like to be added**:

Support path-style URL for S3 (or S3-compatible) storage

**Why is this needed**:

Currently, JuiceFS only support [virtual hosted-style URI](https://docs.aws.amazon.com/AmazonS3/latest/dev/VirtualHosting.html). The difference between virtual hosted-style and path-style is:

- Virtual hosted-style: `https://<bucket>.s3.<region>.amazonaws.com`
- Path-style: `https://s3.<region>.amazonaws.com/<bucket>`

Although AWS would [deprecate](https://aws.amazon.com/blogs/aws/amazon-s3-path-deprecation-plan-the-rest-of-the-story) path-style URI in the future, but some S3-compatible storage still use path-style (e.g. [Ceph RGW](https://docs.ceph.com/en/latest/radosgw/s3/commons)). So we may need support this type URI.

**Comment by solracsf** [comment]
Path-style does not seem supported by `juicefs sync` command after https://github.com/juicedata/juicefs/pull/224
