### ISSUE TITLE
Provide a command to make the application read and write a subdirectory under the juicefs mount path like a local operation

### ISSUE THREAD

**Issue by lipengchengcs** [juicedata/juicefs#1346]
Juicefs provides the function of `warm up` to cache data to local . But we now have a scenario where our application will write data in a subdirectory, and when writing, it will call close() every time 64K is written. This caused us to have a lot of put calls to s3. So I think it is possible to provide a command similar to `warm up`, which can specify a directory. The reading and writing of this directory are local operations, not related to S3, which can reduce a lot of S3 costs and obtain optimal performance.

**What would you like to be added**:
Provide a command to make the application read and write a subdirectory under the juicefs mount path like a local operation
**Why is this needed**:
Reduce the cost of S3 and get the best performance。

**Why not simply use a local path **
We use the entire directory mounted by juicefs as the working directory for the application. The application will create a subdirectory under the working directory for writing operations. This subdirectory cannot be specified through configuration and commands.

**Comment by SandyXSD** [comment]
There are two options that may be workable for you:
1. Mount juicefs with `--writeback` and `--upload-delay 1h`.
It will force juicefs to write all new blocks locally in the cache-dir, and upload them to S3 after a certain period (say, 1h). Within this period you can read corresponding files locally; or, if you remove the files, these blocks will be removed as well and never be uploaded to S3. The blocks may be uploaded in advance if local cache-dir is too full.
2. Create a symbolic link in juicefs, referring to a local directory out side of juicefs. e.g: `ln -s /local/dir /jfs/dir`, then most operations in `/jfs/dir` will be redirected to `/local/dir`

**Comment by lipengchengcs** [comment]
It sounds like the second method can solve our problem, thanks.

**Comment by lipengchengcs** [comment]
For the first solution, it may cause the disk to store the written data for 1 hour.

**Comment by lipengchengcs** [comment]
But I think this function can still be provided, because it can provide a direct solution to solve the behavior of a large number of put operations on S3 in the temporary directory when Juicefs is mounted

**Comment by lipengchengcs** [comment]
![image](https://user-images.githubusercontent.com/90176164/151312648-9a902c0f-5808-4d55-85f9-6f72b41e213f.png)

The second option is not feasible, because the Rename command called by our application will fail

**Comment by SandyXSD** [comment]
> It sounds like the second method can solve our problem. But, after test, we found that Our application cannot rename file because in java.io `The rename operation might not be able to move a file from one filesystem to another`,

Yes, `rename` is limited within the same filesystem; you have to do `read` then `write` in the application level, just like the `mv` command.

**Comment by lipengchengcs** [comment]
Run the following command three times to write a file
```
dd if=/dev/zero  of=/disk1/jfs/data/file2 bs=64K count=1 conv=notrunc oflag=append
```
![image](https://user-images.githubusercontent.com/90176164/153135638-ed310056-22c5-4c05-af7b-6383edfc0022.png)
Correspondingly, three 64KB blocks appear in the corresponding rawstaging directory
![image](https://user-images.githubusercontent.com/90176164/153135698-22b4da35-22a9-43fb-81c6-5d795fe05e26.png)
But the three blocks were not merged when finally uploaded to s3. Is this as expected?
![image](https://user-images.githubusercontent.com/90176164/153135572-edbc681d-680b-4dea-94d4-41a598406db0.png)
cc @SandyXSD 
```
/juicefs mount    -d    -o=allow_other    --metrics=0.0.0.0:9568    --io-retries=30    --writeback=true    --cache-size=100    --enable-xattr=false    --read-only=false    --log=/home/hadoop/logs/juicefs_disk1.log    --free-space-ratio=0.1    --buffer-size=4096    --entry-cache=5    --prefetch=6    --get-timeout=60    --attr-cache=5    --no-syslog=true    --put-timeout=60    --cache-partial-only=false    --max-deletes=0    --upload-limit=0    --dir-entry-cache=5    --max-uploads=120    --open-cache=10    --upload-delay=1m    --download-limit=0    --cache-dir=/disk1/jfs/cache    localhost/1     /disk1/jfs/data
```

**Comment by SandyXSD** [comment]
Yes, it's expected. `writeback` with `upload-delay` only delays the upload of blocks(objects), but not triggers the compaction.

**Comment by SandyXSD** [comment]
For now, creating a symbolic link in JuiceFS is workable.
