### ISSUE TITLE
badger: gc/config command can't use when juicefs is mounting

### ISSUE THREAD

**Issue by 201341** [juicedata/juicefs#1415]
**What happened**:
When I use badger for meta server, I can't use juicefs gc/config and other command, the reason is that badger can't be init twice. 

**What you expected to happen**:
I hope to use juicefs gc/config command

**How to reproduce it (as minimally and precisely as possible)**:
mount the juicefs first, then run ./juicefs gc badger://test_db
<img width="1784" alt="截屏2022-02-11 15 21 45" src="https://user-images.githubusercontent.com/13047679/153551790-2d23393b-89b3-44b1-9a84-06453c1551c3.png">
Then unmount the juicefs, ./juicefs gc can work.

**Anything else we need to know?**

**Environment**:
- JuiceFS version (use `juicefs --version`) or Hadoop Java SDK version:
` juicefs version 1.0-dev (2022-02-10 01d32d01)`

- Cloud provider or hardware configuration running JuiceFS:
`minio`
- OS (e.g `cat /etc/os-release`):
`macos`
- Kernel (e.g. `uname -a`):
- Object storage (cloud provider and region, or self maintained):
- Metadata engine info (version, cloud provider managed or self maintained):
- Network connectivity (JuiceFS to metadata engine, JuiceFS to object storage):
- Others:

**Comment by SandyXSD** [comment]
It's a constraint of BadgerDB, allowing only one process to use the database.

**Comment by 201341** [comment]
Yes, I know, Is there any way to solve this problem?

**Comment by davies** [comment]
@201341 Unfortunately, we don't have a solution.

**Comment by 201341** [comment]
> @201341 Unfortunately, we don't have a solution.

Ok. Maybe we could mention this point on the doc.

**Comment by SandyXSD** [comment]
Will be fixed (adding doc) by #1430
