### ISSUE TITLE
CI：travis failed, because of TestSQLiteClient case

### ISSUE THREAD

**Issue by sanwan** [juicedata/juicefs#1419]
=== RUN   TestSQLiteClient
2022/02/10 14:37:36.034434 juicefs[20317] <ERROR>: error: no such table: jfs_node
goroutine 622 [running]:
runtime/debug.Stack(0xc000440030, 0x1531b63, 0x3)
	/home/travis/.gimme/versions/go1.16.linux.amd64/src/runtime/debug/stack.go:24 +0x9f
github.com/juicedata/juicefs/pkg/meta.errno(0x16bee80, 0xc0002ba6a0, 0xc00011adc0)
	/home/travis/gopath/src/github.com/juicedata/juicefs/pkg/meta/utils.go:76 +0x105
github.com/juicedata/juicefs/pkg/meta.(*dbMeta).doGetAttr(0xc0000ea000, 0x16ed0e8, 0x2135600, 0x1, 0xc00011ad70, 0x0)
	/home/travis/gopath/src/github.com/juicedata/juicefs/pkg/meta/sql.go:634 +0xca
github.com/juicedata/juicefs/pkg/meta.(*baseMeta).GetAttr.func1(0xc0006a2000, 0x16ed0e8)
	/home/travis/gopath/src/github.com/juicedata/juicefs/pkg/meta/base.go:523 +0x75
github.com/juicedata/juicefs/pkg/utils.WithTimeout.func1(0xc000386500, 0xc000637550, 0xc00049e070)
	/home/travis/gopath/src/github.com/juicedata/juicefs/pkg/utils/utils.go:68 +0x27
created by github.com/juicedata/juicefs/pkg/utils.WithTimeout
	/home/travis/gopath/src/github.com/juicedata/juicefs/pkg/utils/utils.go:67 +0xbd
2022/02/10 14:37:36.634004 juicefs[20317] <INFO>: cleanup trash: deleted 4 files in 21.139738ms
2022/02/10 14:38:02.232419 juicefs[20317] <INFO>: chunk 4129:1 was changed 72 -> 24
2022/02/10 14:38:02.232667 juicefs[20317] <INFO>: compacted chunk 1118 was not used
2022/02/10 14:38:02.232688 juicefs[20317] <INFO>: compaction for 4129:1 is wasted, delete slice 1118 (67108864 bytes)
    redis_test.go:1089: incorrect session: flock 0 plock 1 sustained 1
--- FAIL: TestSQLiteClient (28.88s)

more details may refer to  https://app.travis-ci.com/github/juicedata/juicefs/builds/246232768#L423

**Comment by SandyXSD** [comment]
Duplicated of #1405
