### ISSUE TITLE
s3 ListObjectsV2 api  Owner is empty

### ISSUE THREAD

**Issue by lidaohang** [juicedata/juicefs#1427]
s3 ListObjectsV2 response:
`
  Contents: [
    {
      ETag: "",
      Key: "juicefs.log",
      LastModified: 2022-02-14 07:12:13.75 +0000 UTC,
      Owner: {
        DisplayName: "",
        ID: ""
      },
      Size: 869,
      StorageClass: "STANDARD"
    }
  ],
  Delimiter: "/",
  IsTruncated: false,
  KeyCount: 4,
  MaxKeys: 100,
  Name: "store-data",
  Prefix: "/"
}`

**Comment by zhijian-pro** [comment]
Please make sure the request comes with the `--fetch-owner` parameter, you can refer to [this](https://docs.aws.amazon.com/cli/latest/reference/s3api/list-objects-v2.html#:~:text=%5B%2D%2Dfetch%2Downer%20%7C%20%2D%2Dno%2Dfetch%2Downer%5D)

**Comment by lidaohang** [comment]
Owner: {
        DisplayName: "",
        ID: "02d6176db174dc93cb1b899f7c6078f08654445fe8cf1b6ce98d8855f66bdbf4"
      }

**Comment by lidaohang** [comment]
add user, group in  tikv

**Comment by xiaogaozi** [comment]
According to the S3 [documentation](https://docs.aws.amazon.com/AmazonS3/latest/userguide/about-object-ownership.html), the owner property of an object in S3 represents the owner of the current bucket (i.e., an AWS account), which is a different concept than user and group in Linux.
