### ISSUE TITLE
Performance: slow metadata service 

### ISSUE THREAD

**Issue by steven-varga** [juicedata/juicefs#145]
**What happened**:
copying linux kernel tree show few KB/sec throughput at best, mdtest showed 5 - 10 transactions per second
**What you expected to happen**:
10MB/sec throughput for similar class file systems for linux kernel tree copy, 1000 - 10000 transaction per second based on redis performance 
**How to reproduce it (as minimally and precisely as possible)**:
on decent/non-virtual AWS EC2 instance setup/run redis, 22ms latency away run juiceFS mounted as a local directory, copy a recent linux kernel tree using {rsync, cp, midnight commander, ...}
**Anything else we need to know?**:
Great project/undertaking! 
When the mounted directory is much 'closer' to redis, the metadata service exhibits fair behaviour. IO ops for larger files are OK, and for multi GB files JuiceFS has excellent performance; although this has not been verified for multi host mixed read/write scenerio. 
**Environment**:
- JuiceFS version (use `./juicefs --version`): 0.9.3-211 (2021-01-28 9cdfa8a)
- Cloud provider or hardware configuration running JuiceFS: a1.2xlarge 
- OS (e.g: `cat /etc/os-release`): ubuntu 20.04
- Kernel (e.g. `uname -a`): 0.9.3-211 (2021-01-28 9cdfa8a)
- Object storage (cloud provider and region):  aws s3 us-east-1
- Redis info (version, cloud provider managed or self maintained): 6.0.10
- Network connectivity (JuiceFS to Redis, JuiceFS to object storage): 500Mbit/sec bell fiber to redis, same for s3 
- Others:

**Comment by davies** [comment]
@steven-varga The latency of meta operation is critical to JuiceFS, that's why we choose to use Redis here. It's usually expected that the latency to Redis server is less than 2ms. JuiceFS will be unusable if the latency goes above 10ms, and there is not much we can do for now.

So I'd say the current performance is expected under your network condition.

What's the use case there?

**Comment by davies** [comment]
Move it into discussion.
