### ISSUE TITLE
Refine missing mount options in the `.config` file

### ISSUE THREAD

**Issue by xiaogaozi** [juicedata/juicefs#1452]
**What would you like to be added**:

Add more mount options to `.config` file, e.g. `--backup-meta`.

**Why is this needed**:

Instead of using the `ps` command, users can view all mount options uniformly in the `.config` file.

**Comment by SandyXSD** [comment]
Other options requiring discussions:
- metrics
- consul
- usage-report
- syslog
- o (extra FUSE options)
- enable-xattr
- bucket (will be reset to the value of that in `format`, which might be different)
- io-retries (not work for now: https://github.com/juicedata/juicefs/issues/1413)

**Comment by davies** [comment]
File .config is provided for debug, not a public interface for end users, so we don't have a plan to expose all the configurations in it, close it for now.
