### ISSUE TITLE
backup metadata failed: runtime error: slice bounds out of range [16:11]

### ISSUE THREAD

**Issue by lidaohang** [juicedata/juicefs#1454]
2022/02/14 11:54:30.662942 juicefs[60492] <INFO>: Mounting volume aidi-store-data at /wll_test ...
2022/02/14 12:00:30.690357 juicefs[60492] <WARNING>: backup metadata failed: runtime error: slice bounds out of range [16:11]
2022/02/14 13:00:30.719926 juicefs[60492] <WARNING>: backup metadata failed: runtime error: slice bounds out of range [16:11]
2022/02/14 14:00:30.752828 juicefs[60492] <WARNING>: backup metadata failed: runtime error: slice bounds out of range [16:11]
2022/02/14 14:18:28.583281 juicefs[60492] <INFO>: cleanup session 111: %!s(<nil>)

![image](https://user-images.githubusercontent.com/4077643/154781033-2d163d15-6f0b-43dc-9676-6a7229059158.png)

**Comment by SandyXSD** [comment]
Do you get the stack? It looks weird since `b.Len()` is checked. `b.Get64()` and `b.Get(8)` should both consume 8 bytes.
