### ISSUE TITLE
high cpu usage during idle

### ISSUE THREAD

**Issue by steven-varga** [juicedata/juicefs#148]
**What happened**:
2 cores running at 100% once complex filesystem layout copied to JuiceFS
**What you expected to happen**:
After remount / and or reasonable time the cpu usage be minimal
**How to reproduce it (as minimally and precisely as possible)**:
create aws s3 based bucket store and a redis metadata server, then copy linux kernel tree from the node where redis is located -- otherwise will take too long, see [reported performance issue](https://github.com/juicedata/juicefs/issues/145), mount juiceFS from a different host, or remount it on the same one.

**Anything else we need to know?**:
The profiler indicates majority of the time is spent on `mallocgc` see attached files
![juicefs-lz4-1mb-block](https://user-images.githubusercontent.com/10566766/106230980-a5e71f00-61be-11eb-86d7-88c3948fa707.png)
![cachegrind](https://user-images.githubusercontent.com/10566766/106231075-d333cd00-61be-11eb-9069-1344ce272503.png)

**Environment**:
- JuiceFS version (use `./juicefs --version`): 0.9.3-211 (2021-01-28 9cdfa8a)
- Cloud provider or hardware configuration running JuiceFS: lenovo x1 7th gen 16GB ram I7 version
- OS (e.g: `cat /etc/os-release`): ubuntu 20.04
- Kernel (e.g. `uname -a`):
- Object storage (cloud provider and region): aws s3 us-east-1
- Redis info (version, cloud provider managed or self maintained): v6.0.10
- Network connectivity (JuiceFS to Redis, JuiceFS to object storage):  500Mbit/s bell fiber 22ms latency between redis server
- Others:

**Comment by davies** [comment]
Based on the profile, juicefs is busy to deleting chunks (once started, and then do that every minute). Have your observe this every time you mount it?

**Comment by steven-varga** [comment]
Thanks for the feedback! Yes I have. Can you let me know if this trimming process distributed among nodes?

**Comment by davies** [comment]
The trimming process will be tried by every nodes for every minute. It scan all the chunks that should be deleted but failed by random reasons. I will add more logging and get back to you.
