### ISSUE TITLE
self signed CA minIO configuration with Juicefs

### ISSUE THREAD

**Issue by sanjeev3d** [juicedata/juicefs#1482]
We have minio configured with self signed CA certificate, getting following error while formatting using juiceFS

`[cloud@uhn7ttsm3cvmg001-dp-03 ~]$ ./juicefs format --storage s3 \
>     --bucket https://datalake.minio.prod.rmn.local/juicefs?tls-insecure-skip-verify=true \
>     --access-key ABCDEFGHIJKLMNopqXYZ \
>     --secret-key ZYXwvutsrqpoNMLkJiHgfeDCBA \
>     sqlite3://myjfs.db juicefs
2022/02/24 16:17:55.050036 juicefs[20275] <INFO>: Meta address: sqlite3://myjfs.db
[xorm] [info]  2022/02/24 16:17:55.050179 PING DATABASE sqlite3
2022/02/24 16:17:55.051094 juicefs[20275] <INFO>: Data use s3://juicefs/juicefs/
2022/02/24 16:18:10.373131 juicefs[20275] <FATAL>: Storage s3://juicefs/juicefs/ is not configured correctly: Failed to create s3://juicefs/juicefs/: RequestError: send request failed
caused by: Put "https://datalake.minio.prod.rmn.local/juicefs": x509: certificate signed by unknown authority,  previous error: RequestError: send request failed
caused by: Put "https://datalake.minio.prod.rmn.local/juicefs/juicefs/testing/UstfsJTPom": x509: certificate signed by unknown authority
please create bucket s3://juicefs/juicefs/ manually, then format again
`

**Comment by zhijian-pro** [comment]
@sanjeev3d  Are you testing the binary compiled with the latest main branch? This feature was added recently, please use our main branch to compile the latest binaries.

**Comment by sanjeev3d** [comment]
@zhijian-pro I'm using Pre-compiled Binary, and used two version and getting same error in both version
juicefs-1.0.0-beta1-linux-amd64.tar.gz and
juicefs-0.17.5-linux-amd64.tar.gz

**Comment by davies** [comment]
@sanjeev3d This depends on a  not-released new feature, you need to build juicefs using latest main branch, or wait for next release (hopefully next week).

**Comment by davies** [comment]
@sanjeev3d This feature is included in 1.0.0-beta2, please try that.
