### ISSUE TITLE
How to get hadoop java sdk in ARM architecture

### ISSUE THREAD

**Issue by huzk8** [juicedata/juicefs#1485]
Env :
- Huawei Cloud ECS
- arm architecture （kunpeng）
- UnionTech OS Server 20 Euler (1000) 64bit with ARM

From Release Page we can get hadoop sdk in X86 architecture，How to get hadoop java sdk in ARM architecture
![image](https://user-images.githubusercontent.com/18548053/155832367-b8b59c15-9fa4-48c7-b118-47a64196f0b6.png)

when i just use `juicefs-hadoop-1.0.0-beta1-linux-amd64.jar` , the error appear like below.
![image](https://user-images.githubusercontent.com/18548053/155833847-e2db2c5e-9d40-4585-8bfc-2c1bc40ae7f7.png)

**Comment by xiaogaozi** [comment]
You could compile JuiceFS Hadoop Java SDK for ARM architecture by yourself, please refer to [the document](https://juicefs.com/docs/community/hadoop_java_sdk/#client-compilation).

**Comment by huzk8** [comment]
> You could compile JuiceFS Hadoop Java SDK for ARM architecture by yourself, please refer to [the document](https://juicefs.com/docs/community/hadoop_java_sdk/#client-compilation).

Useful for me
