### ISSUE TITLE
JuiceFS doesn't support kerberos hadoop ecosystem

### ISSUE THREAD

**Issue by qq619618919** [juicedata/juicefs#1487]
We have faced the problem that JuiceFS doesn't support kerberized hadoop environment.

**Comment by tangyoupeng** [comment]
Currently, JuiceFS does not support kerberos authentication

**Comment by qq619618919** [comment]
Does the community have plans to support this?

**Comment by tangyoupeng** [comment]
JuiceFS can use the authenticated user by keberos (for example, kinit). What's the exact problem you have faced

**Comment by davies** [comment]
@qq619618919 As @tangyoupeng said, JuiceFS can be used in kerberized Hadoop environment, but does not have strong protection comparing to HDFS. What's the problem you are facing?
