### ISSUE TITLE
Build Windows Client Failed

### ISSUE THREAD

**Issue by diluga** [juicedata/juicefs#1490]
I try builded juicefs.exe on Windows 10,It Failed with below。

```
PS D:\github\juicefs> systeminfo.exe

主机名:           xx
OS 名称:          Microsoft Windows 10 专业版
OS 版本:          10.0.19044 暂缺 Build 19044
OS 制造商:        Microsoft Corporation
OS 配置:          独立工作站
OS 构建类型:      Multiprocessor Free
```

```
PS D:\github\juicefs> go version
go version go1.17.6 windows/amd64

PS D:\github\juicefs>  mkdir "C:\WinFsp\inc\fuse"


    目录: C:\WinFsp\inc


Mode                 LastWriteTime         Length Name
----                 -------------         ------ ----
d-----         2022/2/28     16:17                fuse


PS D:\github\juicefs>   copy .\hack\winfsp_headers\* C:\WinFsp\inc\fuse\
PS D:\github\juicefs> dir "C:\WinFsp\inc\fuse"


    目录: C:\WinFsp\inc\fuse


Mode                 LastWriteTime         Length Name
----                 -------------         ------ ----
-a----         2022/2/28     16:13           9709 fuse.h
-a----         2022/2/28     16:13           5765 fuse_common.h
-a----         2022/2/28     16:13           3981 fuse_opt.h
-a----         2022/2/28     16:13          11376 winfsp_fuse.h


PS D:\github\juicefs>  set CGO_CFLAGS=-IC:/WinFsp/inc/fuse
PS D:\github\juicefs>  go env
set GO111MODULE=
set GOARCH=amd64
set GOBIN=
set GOCACHE=C:\Users\Juicefs\AppData\Local\go-build
set GOENV=C:\Users\Juicefs\AppData\Roaming\go\env
set GOEXE=.exe
set GOEXPERIMENT=
set GOFLAGS=
set GOHOSTARCH=amd64
set GOMODCACHE=C:\Users\Juicefs\go\pkg\mod
set GONOPROXY=
set GONOSUMDB=
set GOOS=windows
set GOPATH=C:\Users\Juicefs\go
set GOPRIVATE=
set GOPROXY=https://proxy.golang.org,direct
set GOROOT=C:\Program Files\Go
set GOSUMDB=sum.golang.org
set GOTMPDIR=
set GOTOOLDIR=C:\Program Files\Go\pkg\tool\windows_amd64
set GOVCS=
set GOVERSION=go1.17.6
set GCCGO=gccgo
set AR=ar
set CC=gcc
set CXX=g++
set CGO_ENABLED=1
set GOMOD=D:\github\juicefs\go.mod
set CGO_CFLAGS=-IC:\Program Files (x86)\WinFsp\inc\fuse
set CGO_CPPFLAGS=
set CGO_CXXFLAGS=-g -O2
set CGO_FFLAGS=-g -O2
set CGO_LDFLAGS=-g -O2
set PKG_CONFIG=pkg-config
set GOGCCFLAGS=-m64 -mthreads -fmessage-length=0 -fdebug-prefix-map=C:\Users\Juicefs\AppData\Local\Temp\go-build2142462842=/tmp/go-build -gno-record-gcc-switches
PS D:\github\juicefs>  go env -w CGO_CFLAGS=-IC:/WinFsp/inc/fuse
PS D:\github\juicefs>  go env
set GO111MODULE=
set GOARCH=amd64
set GOBIN=
set GOCACHE=C:\Users\Juicefs\AppData\Local\go-build
set GOENV=C:\Users\Juicefs\AppData\Roaming\go\env
set GOEXE=.exe
set GOEXPERIMENT=
set GOFLAGS=
set GOHOSTARCH=amd64
set GOINSECURE=
set GOMODCACHE=C:\Users\Juicefs\go\pkg\mod
set GONOPROXY=
set GONOSUMDB=
set GOOS=windows
set GOPATH=C:\Users\Juicefs\go
set GOPRIVATE=
set GOPROXY=https://proxy.golang.org,direct
set GOROOT=C:\Program Files\Go
set GOSUMDB=sum.golang.org
set GOTMPDIR=
set GOTOOLDIR=C:\Program Files\Go\pkg\tool\windows_amd64
set GOVCS=
set GOVERSION=go1.17.6
set GCCGO=gccgo
set AR=ar
set CC=gcc
set CXX=g++
set CGO_ENABLED=1
set GOMOD=D:\github\juicefs\go.mod
set CGO_CFLAGS=-IC:/WinFsp/inc/fuse
set CGO_CPPFLAGS=
set CGO_CXXFLAGS=-g -O2
set CGO_FFLAGS=-g -O2
set CGO_LDFLAGS=-g -O2
set PKG_CONFIG=pkg-config
set GOGCCFLAGS=-m64 -mthreads -fmessage-length=0 -fdebug-prefix-map=C:\Users\Juicefs\AppData\Local\Temp\go-build1496759721=/tmp/go-build -gno-record-gcc-switches
PS D:\github\juicefs>  go build -ldflags="-s -w" -o juicefs.exe ./cmd
go: downloading golang.org/x/text v0.3.6
C:\Users\Juicefs\go\pkg\mod\github.com\shirou\gopsutil@v3.21.3+incompatible\cpu\cpu_windows.go:10:2: read C:\Users\Juicefs\go\pkg\mod\github.com\!stack!exchange\wmi@v0.0.0-20190523213315-cbe66965904d\wmi_test.go: unexpected NUL in input
C:\Users\Juicefs\go\pkg\mod\github.com\!stack!exchange\wmi@v0.0.0-20190523213315-cbe66965904d\swbemservices.go:11:2: cannot find package
C:\Users\Juicefs\go\pkg\mod\github.com\!stack!exchange\wmi@v0.0.0-20190523213315-cbe66965904d\swbemservices.go:12:2: cannot find package
C:\Users\Juicefs\go\pkg\mod\github.com\juicedata\minio@v0.0.0-20210222051636-e7cabdf948f4\pkg\s3select\sql\evaluate.go:27:2: read C:\Users\Juicefs\go\pkg\mod\github.com\minio\simdjson-go@v0.2.1\benchmarks_test.go: unexpected NUL in input
C:\Users\Juicefs\go\pkg\mod\google.golang.org\api@v0.5.0\transport\http\dial.go:25:2: read C:\Users\Juicefs\go\pkg\mod\go.opencensus.io@v0.22.5\plugin\ochttp\client.go: unexpected NUL in input
C:\Users\Juicefs\go\pkg\mod\go.opencensus.io@v0.22.5\plugin\ochttp\trace.go:22:2: cannot find package
C:\Users\Juicefs\go\pkg\mod\go.opencensus.io@v0.22.5\plugin\ochttp\server.go:25:2: cannot find package
C:\Users\Juicefs\go\pkg\mod\go.opencensus.io@v0.22.5\plugin\ochttp\stats.go:19:2: cannot find package
C:\Users\Juicefs\go\pkg\mod\go.opencensus.io@v0.22.5\plugin\ochttp\route.go:21:2: cannot find package
C:\Users\Juicefs\go\pkg\mod\cloud.google.com\go@v0.39.0\internal\trace\trace.go:21:2: read C:\Users\Juicefs\go\pkg\mod\go.opencensus.io@v0.22.5\trace\basetypes.go: unexpected NUL in input
C:\Users\Juicefs\go\pkg\mod\go.opencensus.io@v0.22.5\plugin\ochttp\server.go:28:2: read C:\Users\Juicefs\go\pkg\mod\go.opencensus.io@v0.22.5\trace\propagation\propagation.go: unexpected NUL in input
C:\Users\Juicefs\go\pkg\mod\golang.org\x\net@v0.0.0-20210405180319-a5a99cb37ef4\idna\idna10.0.0.go:26:2: zip: not a valid zip file
C:\Users\Juicefs\go\pkg\mod\golang.org\x\net@v0.0.0-20210405180319-a5a99cb37ef4\idna\idna10.0.0.go:27:2: zip: not a valid zip file
C:\Users\Juicefs\go\pkg\mod\golang.org\x\net@v0.0.0-20210405180319-a5a99cb37ef4\idna\idna10.0.0.go:28:2: zip: not a valid zip file
C:\Users\Juicefs\go\pkg\mod\cloud.google.com\go@v0.39.0\internal\trace\trace.go:23:2: read C:\Users\Juicefs\go\pkg\mod\google.golang.org\genproto@v0.0.0-20200224152610-e50cd9704f63\googleapis\rpc\code\code.pb.go: unexpected NUL in input
C:\Users\Juicefs\go\pkg\mod\google.golang.org\grpc@v1.27.1\status\status.go:37:2: read C:\Users\Juicefs\go\pkg\mod\google.golang.org\genproto@v0.0.0-20200224152610-e50cd9704f63\googleapis\rpc\status\status.pb.go: unexpected NUL in input
```

**Comment by davies** [comment]
@zhijian-pro Do we have docs to cover this?

**Comment by zhijian-pro** [comment]
@davies  not obvious enough, I will improve it later.

**Comment by diluga** [comment]
after try it again,it sucessful!
···
PS D:\github\juicefs> git status
On branch main
Your branch is up to date with 'origin/main'.

nothing to commit, working tree clean
PS D:\github\juicefs> copy .\hack\winfsp_headers\* C:\WinFsp\inc\fuse\
PS D:\github\juicefs>  dir "C:\WinFsp\inc\fuse"


    目录: C:\WinFsp\inc\fuse


Mode                 LastWriteTime         Length Name
----                 -------------         ------ ----
-a----         2022/2/28     16:13           9709 fuse.h
-a----         2022/2/28     16:13           5765 fuse_common.h
-a----         2022/2/28     16:13           3981 fuse_opt.h
-a----         2022/2/28     16:13          11376 winfsp_fuse.h


PS D:\github\juicefs> set CGO_CFLAGS=-IC:/WinFsp/inc/fuse
PS D:\github\juicefs>  go env
set GO111MODULE=
set GOARCH=amd64
set GOBIN=
set GOCACHE=C:\Users\Juicefs\AppData\Local\go-build
set GOENV=C:\Users\Juicefs\AppData\Roaming\go\env
set GOEXE=.exe
set GOEXPERIMENT=
set GOFLAGS=
set GOHOSTARCH=amd64
set GONOPROXY=
set GONOSUMDB=
set GOOS=windows
set GOPATH=C:\Users\Juicefs\go
set GOPRIVATE=
set GOPROXY=https://goproxy.cn,direct
set GOROOT=C:\Program Files\Go
set GOSUMDB=sum.golang.org
set GOTMPDIR=
set GOTOOLDIR=C:\Program Files\Go\pkg\tool\windows_amd64
set GOVCS=
set GOVERSION=go1.17.6
set GCCGO=gccgo
set AR=ar
set CC=gcc
set CXX=g++
set CGO_ENABLED=1
set GOMOD=D:\github\juicefs\go.mod
set CGO_CFLAGS=-IC:/WinFsp/inc/fuse
set CGO_CPPFLAGS=
set CGO_CXXFLAGS=-g -O2
set CGO_FFLAGS=-g -O2
set CGO_LDFLAGS=-g -O2
set PKG_CONFIG=pkg-config
set GOGCCFLAGS=-m64 -mthreads -fmessage-length=0 -fdebug-prefix-map=C:\Users\Juicefs\AppData\Local\Temp\go-build820106864=/tmp/go-build -gno-record-gcc-switches
PS D:\github\juicefs>  go env -w CGO_CFLAGS=-IC:/WinFsp/inc/fuse
PS D:\github\juicefs> go env -w GOPROXY=https://goproxy.cn,direct
PS D:\github\juicefs> go env
set GO111MODULE=
set GOARCH=amd64
set GOBIN=
set GOCACHE=C:\Users\Juicefs\AppData\Local\go-build
set GOENV=C:\Users\Juicefs\AppData\Roaming\go\env
set GOEXE=.exe
set GOEXPERIMENT=
set GOFLAGS=
set GOHOSTARCH=amd64
set GOINSECURE=
set GOMODCACHE=C:\Users\Juicefs\go\pkg\mod
set GONOSUMDB=
set GOOS=windows
set GOPATH=C:\Users\Juicefs\go
set GOPRIVATE=
set GOPROXY=https://goproxy.cn,direct
set GOROOT=C:\Program Files\Go
set GOSUMDB=sum.golang.org
set GOTMPDIR=
set GOTOOLDIR=C:\Program Files\Go\pkg\tool\windows_amd64
set GOVCS=
set GOVERSION=go1.17.6
set GCCGO=gccgo
set AR=ar
set CC=gcc
set CXX=g++
set CGO_ENABLED=1
set GOMOD=D:\github\juicefs\go.mod
set CGO_CFLAGS=-IC:/WinFsp/inc/fuse
set CGO_CPPFLAGS=
set CGO_CXXFLAGS=-g -O2
set CGO_FFLAGS=-g -O2
set CGO_LDFLAGS=-g -O2
set PKG_CONFIG=pkg-config
set GOGCCFLAGS=-m64 -mthreads -fmessage-length=0 -fdebug-prefix-map=C:\Users\Juicefs\AppData\Local\Temp\go-build1107313163=/tmp/go-build -gno-record-gcc-switches
PS D:\github\juicefs> go build -ldflags="-s -w" -o juicefs.exe ./cmd
go: downloading google.golang.org/grpc v1.27.1
go: downloading go.opencensus.io v0.22.5
PS D:\github\juicefs> dir


    目录: D:\github\juicefs


Mode                 LastWriteTime         Length Name
----                 -------------         ------ ----
d-----         2022/2/28     16:13                .github
d-----         2022/2/28     16:13                cmd
d-----         2022/2/28     16:13                deploy
d-----         2022/2/28     16:13                docs
d-----         2022/2/28     16:13                fstests
d-----         2022/2/28     16:13                hack
d-----         2022/2/28     16:13                integration
d-----         2022/2/28     16:13                pkg
d-----         2022/2/28     16:13                sdk
-a----         2022/2/28     16:13            262 .gitignore
-a----         2022/2/28     16:13             66 .golangci.yml
-a----         2022/2/28     16:13           2378 .goreleaser.yml
-a----         2022/2/28     16:13            337 .pre-commit-config.yaml
-a----         2022/2/28     16:13           4441 .travis.yml
-a----         2022/2/28     16:13           3814 ADOPTERS.md
-a----         2022/2/28     16:13           3458 ADOPTERS_CN.md
-a----         2022/2/28     16:13              0 CODE_OF_CONDUCT.md
-a----         2022/2/28     16:13           2595 CONTRIBUTING.md
-a----         2022/2/28     16:13          11560 LICENSE
-a----         2022/2/28     16:13           2653 Makefile
-a----         2022/2/28     16:13          13672 README.md
-a----         2022/2/28     16:13          12630 README_CN.md
-a----         2022/2/28     16:13            376 check-changed.sh
-a----         2022/2/28     16:13           2413 travis-setup-hdfs.sh
-a----          2022/3/1     11:53           4220 go.mod
-a----          2022/3/1     11:53         138685 go.sum
-a----          2022/3/1     11:56       72883200 juicefs.exe

···
