### ISSUE TITLE
juicefs client out of memory

### ISSUE THREAD

**Issue by davies** [juicedata/juicefs#1558]
### Discussed in https://github.com/juicedata/juicefs/discussions/1529

<div type='discussions-op-text'>

<sup>Originally posted by **deelaaay** March  7, 2022</sup>
Out of memory: Kill process 2523920 (juicefs) score 444 or sacrifice child
Killed process 2523920 (juicefs) total-vm:15826948kB, anon-rss:14931252kB, file-rss:0kB, shmem-rss:0kB
oom_reaper: reaped process 2523920 (juicefs), now anon-rss:0kB, file-rss:0kB, shmem-rss:0kB

exec  dmesg  ,display the above content。 how do I control the JuiceFS client  physical memory usage?
</div>

**Comment by SandyXSD** [comment]
> We can see there are lots of goroutines (2.7 millions) waiting to upload the blocks, and lots of objects used by goroutines are not freed. So it's caused by slow upload of objects in writeback mode.

- [ ] limit number of goroutines used for uploading objects

**Comment by solracsf** [comment]
Does this only affects `--writeback` mode?

**Comment by davies** [comment]
> Does this only affects `--writeback` mode?
Yes
