### ISSUE TITLE
Hide password/connection string from process arguments in ps

### ISSUE THREAD

**Issue by lazy-capybara** [juicedata/juicefs#1564]
Hello guys, 

Currently juicefs only accepts connection string as a command line argument for mount command, and then it is exposed through process list viewer. We do not want to trust the environment in which we run juicefs mount client so we would want sensitive input to be hidden. I think it is fine that connection string is passed through command line and certainly moving to fully fledged configuration file is not really needed. Implementing loading secret from file is fine too.
We cannot use systemd environment files due to not having enough privileges to do that, so we do not have any other option to sanitize the input from process list.

**What would you like to be added**: 
- JuiceFS binary to hide it's sensitive input from command line arguments exposed in process list (ps auxf)
- Load secrets from file

**Why is this needed**:
To enhance security by hiding sensitive input from other users.

**Comment by SandyXSD** [comment]
The secret will be hidden in the latest release [1.0.0-beta2](https://github.com/juicedata/juicefs/releases/tag/v1.0.0-beta2).

**Comment by SandyXSD** [comment]
@lazy-capybara Hi, could you try the new version to see if it meets your needs?

**Comment by davies** [comment]
@lazy-capybara Hide secrets from meta-url is done by https://github.com/juicedata/juicefs/pull/1333
