### ISSUE TITLE
Insert primary keys in all MySQL tables

### ISSUE THREAD

**Issue by solracsf** [juicedata/juicefs#1576]
**What would you like to be added**:

Some tables doesn't have a PK.

**Why is this needed**:

Clusters (like Galera) need a PK in all InnoDB tables.
See https://galeracluster.com/library/documentation/mysql-wsrep-options.html#wsrep-certify-nonpk
See https://mariadb.com/kb/en/mariadb-galera-cluster-known-limitations/

This is also a MySQL good practice.

**Comment by davies** [comment]
@solracsf Do you have suggestion on how to add a PK for those table which don't actually need it?

**Comment by SandyXSD** [comment]
More info: MySQL 8.0.13 introduced a new option `sql-require-primary-key` to force using PK, which has to be OFF for now.
https://dev.mysql.com/doc/refman/8.0/en/server-system-variables.html#sysvar_sql_require_primary_key

**Comment by solracsf** [comment]
> Do you have suggestion on how to add a PK for those table which **don't actually need it**?

Sorry to disagree on this @davies. A PK should be added to **every** table. Here's a detailled explanation of why.
https://vettabase.com/blog/why-tables-need-a-primary-key-in-mariadb-and-mysql/
