### ISSUE TITLE
Check settings on Redis

### ISSUE THREAD

**Issue by davies** [juicedata/juicefs#16]
**What would you like to be added**:

After connected to Redis, check the following settings on redis:

1. AOF is ON
2. RDB is ON
3. no in cluster mode (cluster_enabled is 0)
4. maxmemory_policy is set to noeviction
5. show a warning if it's not replicated
6. version should be >= 2.2

**Why is this needed**:

Redis is responsible for persistence of metadata, so it should NOT lose any data, otherwise the data in JuiceFS will be lost.

**Comment by suzaku** [comment]
How do we check if RDB is disabled? The only related configuration seems to be the "save" interval.

**Comment by vision9527** [comment]
What is the best redis's deployment strategy? Is there some more detail about it?

**Comment by davies** [comment]
> How do we check if RDB is disabled? The only related configuration seems to be the "save" interval.

Yeah, may be just ignore it (assume RDB is always enabled).

**Comment by davies** [comment]
> What is the best redis's deployment strategy? Is there some more detail about it?

There should be many articles on this topic, for example, https://redis.io/topics/persistence

We can build a best practice for JuiceFS.

**Comment by suzaku** [comment]
> > How do we check if RDB is disabled? The only related configuration seems to be the "save" interval.
> 
> Yeah, may be just ignore it (assume RDB is always enabled).

Seems straight forward enough, could you assign this issue to me? I'll work on it when I have some time to spare.
