### ISSUE TITLE
listAll prefix meta/: not supported

### ISSUE THREAD

**Issue by davies** [juicedata/juicefs#1614]
### Discussed in https://github.com/juicedata/juicefs/discussions/1577

<div type='discussions-op-text'>

<sup>Originally posted by **solracsf** March 14, 2022</sup>
I'm getting these with **Scaleway** and **JuiceFS 1.0.0 beta2**; does this mean that the provider doesn't support these methods or is something wrong here?

```
<ERROR>: Can't list s3://jfsdata-shard1/: RequestError: send request failed
caused by: Get "https://s3.fr-par.scw.cloud/jfsdata-shard1?marker=&max-keys=10000&prefix=": net/http: timeout awaiting response headers [sharding.go:82]
<ERROR>: Can't list shard16://s3://jfsdata-shard0/jfs/(encrypted)meta/: not supported [sync.go:116]
<WARNING>: listAll prefix meta/: not supported [backup.go:100]
```

Thanks.</div>

**Comment by SandyXSD** [comment]
Maybe need `List` for sharded object.
