### ISSUE TITLE
bad object for metadata backup

### ISSUE THREAD

**Issue by davies** [juicedata/juicefs#1615]
### Discussed in https://github.com/juicedata/juicefs/discussions/1600

<div type='discussions-op-text'>

<sup>Originally posted by **solracsf** March 18, 2022</sup>
I can observe **hundreds of thousands** of lines like these in the log, should I be worried about?

```
<WARNING>: bad object for metadata backup s/0/0/110_0_224297: length 18 [backup.go:143]
```

JuiceFS 1.0.0-beta2 on Redis 6.2.2</div>

**Comment by SandyXSD** [comment]
Probably related to #1614, which returns a malformed list of objects.
len("chunk") == len("meta/")

**Comment by SandyXSD** [comment]
Looks like the prefix is ignored here: https://github.com/juicedata/juicefs/blob/main/pkg/object/sharding.go#L80
