### ISSUE TITLE
How do I set parameters for mountPod

### ISSUE THREAD

**Issue by mytting** [juicedata/juicefs#1626]
**What happened**:

How do I set parameters for mountPod

For example, configure CSI mountPod stain tolerance (remove some default stain tolerance so that nodes can be migrated automatically when they go down?). 

Can I use a configMap or CRD to configure mountPod?

**Environment**:
- JuiceFS version (use `juicefs --version`) or Hadoop Java SDK version:  1.0.0-beta1 (2022-01-13 28a42cf6)
- Cloud provider or hardware configuration running JuiceFS: Kubernetes csi
- OS (e.g `cat /etc/os-release`): CentOS7
- Kernel (e.g. `uname -a`): 4.19
- Object storage (cloud provider and region, or self maintained):  self maintained Minio 
- Metadata engine info (version, cloud provider managed or self maintained): self maintained Redis 
- Network connectivity (JuiceFS to metadata engine, JuiceFS to object storage): 
- Others:

**Comment by mytting** [comment]
I used JuicEFS PVC to run a mysql server, trying to automatically migrate mysql to other available nodes in case of host downtime, but now mysql Pod and JuicEFS mountPod seem to have affinity?
Can't mysql Pod migrate to other nodes because juicefs mountPod tolerates all stains?

**Comment by zwwhdls** [comment]
Hi @mytting , JuiceFS mount pod is scheduled on which mysql pod is deployed on and it will be deleted after mysql pod is deleted. So, as I understood, JuiceFS mount pod did not affect the schedule of mysql pod.

**Comment by mytting** [comment]
Configuration problem, solved, thanks @zwwhdls
