### ISSUE TITLE
Permission problem

### ISSUE THREAD

**Issue by jueshali** [juicedata/juicefs#166]
**What happened**:
When I modified the file permissions, other users lost the permissions to get the file. But he can rm this file.

![image](https://user-images.githubusercontent.com/37365357/106709098-f501d980-662e-11eb-923e-cd986825b080.png)

**What you expected to happen**:
he lost the permission of this file.
**How to reproduce it (as minimally and precisely as possible)**:
hadoop fs -put file jfs://hadoop/
hadoop fs -chmod o-x jfs://hadoop/file
su other
hadoop fs -get jfs://hadoop/file
hadoop fs -rm jfs://hadoop/file

**Anything else we need to know?**
There are also problems with user group permissions

**Environment**:
- JuiceFS version (use `./juicefs --version`): 0.9.3
- Cloud provider or hardware configuration running JuiceFS:S3
- OS (e.g: `cat /etc/os-release`):Debian 8
- Kernel (e.g. `uname -a`):Linux debian 3.16
- Object storage (cloud provider and region):
- Redis info (version, cloud provider managed or self maintained):6.0.10
- Network connectivity (JuiceFS to Redis, JuiceFS to object storage):
- Others:

**Comment by chnliyong** [comment]
The [HDFS permission](https://hadoop.apache.org/docs/current/hadoop-project-dist/hadoop-hdfs/HdfsPermissionsGuide.html) delete operation only need the write permission of the parent.
