### ISSUE TITLE
the old version juicefs can't read secret key from the new version of meta.

### ISSUE THREAD

**Issue by zhoucheng361** [juicedata/juicefs#1667]
**What happened**:
the old juicefs can't read AKSK from the new version of meta, which gives the following error:

Destroy error, gc ok 
Proceed anyway? [y/N]: y
2022/03/28 15:29:52.804417 juicefs[307352] <ERROR>: Can't list minio://172.27.0.2:9005/juicefs-fio-benchmark/fio-benchmark/: SignatureDoesNotMatch: The request signature we calculated does not match the signature you provided. Check your key and signing method.
	status code: 403, request id: 16E07AE6372585CB, host id:  [sync.go:116]

**What you expected to happen**:
if we use the old version of juicefs to read a new version meta, we should quit at the very beginning.

**How to reproduce it (as minimally and precisely as possible)**:
1. juicefs(old version : 1.0.0-beta2+2022-03-04T03:00:41Z.9e26080) format xxx
2. juicefs(new version: juicefs version 1.0.0-dev+2022-03-28.6dabbcf) format xxx
3. juicefs(old version: 1.0.0-beta2+2022-03-04T03:00:41Z.9e26080) destroy xxx

**Anything else we need to know?**

**Environment**:
- JuiceFS version (use `juicefs --version`) or Hadoop Java SDK version:
- Cloud provider or hardware configuration running JuiceFS:
- OS (e.g `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Object storage (cloud provider and region, or self maintained):
- Metadata engine info (version, cloud provider managed or self maintained):
- Network connectivity (JuiceFS to metadata engine, JuiceFS to object storage):
- Others:

**Comment by davies** [comment]
Fixed by #1726

**Comment by SandyXSD** [comment]
Secret key in new formatted volume is encrypted, while old client will use it directly, resulting in the error SignatureDoesNotMatch.
