### ISSUE TITLE
PGsql ERROR: invalid byte sequence for encoding "UTF8"

### ISSUE THREAD

**Issue by solracsf** [juicedata/juicefs#1684]
On the server (postgres 14.2) log, multiple entries:

```
ERROR:  invalid byte sequence for encoding "UTF8": 0xe9 0x73 0x61
CONTEXT:  unnamed portal parameter $2
STATEMENT:  SELECT * FROM "jfs_edge" INNER JOIN "jfs_node" ON jfs_edge.inode=jfs_node.inode
            WHERE "jfs_edge"."parent"=$1 AND "jfs_edge"."name"=$2 LIMIT 1
```
Enconding params:
```
# sudo -u postgres psql
psql (14.2 (Ubuntu 14.2-1.pgdg20.04+1))
Type "help" for help.

postgres=# SHOW server_encoding;
 server_encoding
-----------------
 UTF8
(1 row)

postgres=# SHOW client_encoding;
 client_encoding
-----------------
 UTF8
(1 row)
```

Similar to https://github.com/juicedata/juicefs/issues/1567 (same dataset)

**Comment by solracsf** [comment]
I believe this is the file, actually stored on a ZFS pool, which is causing these problems:

`-rw-rw-r-- 1 data data 77384 Mar 16  2021 'R'$'\351''sa salle - VP - Case1.xlsx.v1615571504'`

**Comment by zhijian-pro** [comment]
The reason for this is that we use `varchar` as the field type instead of `bytea`, so this error occurs when the client writes in a different encoding than the database itself, and we're thinking about how to fix it.

**Comment by solracsf** [comment]
May I ask if it would not make sense to store data as JSONB instead of SQL when using Postgres?
https://www.postgresql.org/docs/current/datatype-json.html
