### ISSUE TITLE
xattr value does not support GBK encoding

### ISSUE THREAD

**Issue by zhoucheng361** [juicedata/juicefs#1748]
**What happened**:

```
root@bench-03:~/zhoucheng# ./juicefs format sqlite3://jfs1.db jfs1
2022/04/08 14:57:04.672950 juicefs[701979] <INFO>: Meta address: sqlite3://jfs1.db [interface.go:383]
2022/04/08 14:57:04.674222 juicefs[701979] <INFO>: Data use file:///var/jfs/jfs1/ [format.go:407]
2022/04/08 14:57:04.678725 juicefs[701979] <INFO>: Volume is formatted as {Name:jfs1 UUID:3d328931-ca37-4a94-af51-1c5abbddf50d Storage:file Bucket:/var/jfs/ AccessKey: SecretKey: BlockSize:4096 Compression:none Shards:0 HashPrefix:false Capacity:0 Inodes:0 EncryptKey: KeyEncrypted:false TrashDays:1 MetaVersion:1 MinClientVersion: MaxClientVersion:} [format.go:442]
root@bench-03:~/zhoucheng# ./juicefs mount --enable-xattr sqlite3://jfs1.db jfs1 -d
2022/04/08 14:57:16.318833 juicefs[701994] <INFO>: Meta address: sqlite3://jfs1.db [interface.go:383]
2022/04/08 14:57:16.319665 juicefs[701994] <INFO>: Data use file:///var/jfs/jfs1/ [mount.go:274]
2022/04/08 14:57:16.319747 juicefs[701994] <INFO>: Disk cache (/var/jfsCache/3d328931-ca37-4a94-af51-1c5abbddf50d/): capacity (102400 MB), free ratio (10%), max pending pages (15) [disk_cache.go:90]
2022/04/08 14:57:16.820564 juicefs[701994] <INFO>: OK, jfs1 is ready at jfs1 [mount_unix.go:45]
root@bench-03:~/zhoucheng# touch jfs1/中国.txt && echo "果汁数据JuiceData">jfs1/中国.txt
root@bench-03:~/zhoucheng# setfattr -n user.k -v "果汁数据" jfs1/中国.txt
root@bench-03:~/zhoucheng# getfattr -n user.k jfs1/中国.txt
# file: jfs1/中国.txt
user.k=0s5p6c5rGB5pWw5o2u
```

**What you expected to happen**:
user.k should be equal to "果汁数据" which is set before.

**How to reproduce it (as minimally and precisely as possible)**:
./juicefs format sqlite3://jfs1.db jfs1
./juicefs mount --enable-xattr sqlite3://jfs1.db jfs1 -d 
touch jfs1/中国.txt && echo "果汁数据JuiceData">jfs1/中国.txt
setfattr -n user.k -v "果汁数据" jfs1/中国.txt
getfattr -n user.k jfs1/中国.txt

**Anything else we need to know?**

**Environment**:
- JuiceFS version (use `juicefs --version`) or Hadoop Java SDK version:
- Cloud provider or hardware configuration running JuiceFS:
- OS (e.g `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Object storage (cloud provider and region, or self maintained):
- Metadata engine info (version, cloud provider managed or self maintained):
- Network connectivity (JuiceFS to metadata engine, JuiceFS to object storage):
- Others:

**Comment by zhijian-pro** [comment]
<img width="1268" alt="image" src="https://user-images.githubusercontent.com/31313340/162384342-37474df7-e02b-4a0b-9918-daed1b1907bf.png">
