### ISSUE TITLE
should clean the meta file when format failed.

### ISSUE THREAD

**Issue by zhoucheng361** [juicedata/juicefs#1785]
**What happened**:

```
root@bench-01:~# ./jfs_new format sqlite3:///tmp/encoding-test2.db myjfs
2022/04/14 17:49:25.422900 juicefs[1008649] <INFO>: Meta address: sqlite3:///tmp/encoding-test2.db [interface.go:383]
2022/04/14 17:49:25.423574 juicefs[1008649] <INFO>: Data use file:///var/jfs/myjfs/ [format.go:409]
2022/04/14 17:49:25.427828 juicefs[1008649] <INFO>: Volume is formatted as {Name:myjfs UUID:8bdf724e-ccb8-4515-9f2b-52af7f6b68c1 Storage:file Bucket:/var/jfs/ AccessKey: SecretKey: BlockSize:4096 Compression:none Shards:0 HashPrefix:false Capacity:0 Inodes:0 EncryptKey: KeyEncrypted:false TrashDays:1 MetaVersion:1 MinClientVersion: MaxClientVersion:} [format.go:447]
root@bench-01:~# ./jfs_new format sqlite3:///tmp/encoding-test3.db myjfs
2022/04/14 17:51:24.362300 juicefs[1008665] <INFO>: Meta address: sqlite3:///tmp/encoding-test3.db [interface.go:383]
2022/04/14 17:51:24.362825 juicefs[1008665] <INFO>: Data use file:///var/jfs/myjfs/ [format.go:409]
2022/04/14 17:51:24.363315 juicefs[1008665] <FATAL>: Storage file:///var/jfs/myjfs/ is not empty; please clean it up or pick another volume name [format.go:423]
root@bench-01:~# ls /tmp/encoding-test3.db -l
-rw-r--r-- 1 root root 0 Apr 14 17:51 /tmp/encoding-test3.db
```

**What you expected to happen**:
we should clean the meta file when format failed. 

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**

**Environment**:
- JuiceFS version (use `juicefs --version`) or Hadoop Java SDK version:
- Cloud provider or hardware configuration running JuiceFS:
- OS (e.g `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Object storage (cloud provider and region, or self maintained):
- Metadata engine info (version, cloud provider managed or self maintained):
- Network connectivity (JuiceFS to metadata engine, JuiceFS to object storage):
- Others:

**Comment by SandyXSD** [comment]
There is no table created, only left an empty file.
We should not delete the db file directly because we don't know if there's any other table in it, and doing such check is redundant.
