### ISSUE TITLE
should clean the data dir when update meta failed.

### ISSUE THREAD

**Issue by zhoucheng361** [juicedata/juicefs#1799]
**What happened**:

root@bench-01:~# juicefs format sqlite3://abc.db  myjxyz
2022/04/15 16:02:41.871970 juicefs[1078529] <INFO>: Meta address: sqlite3://abc.db [interface.go:383]
2022/04/15 16:02:41.872758 juicefs[1078529] <INFO>: Data use file:///var/jfs/myjxyz/ [format.go:409]
2022/04/15 16:02:41.877937 juicefs[1078529] <INFO>: Volume is formatted as {Name:myjxyz UUID:44394cf1-bee7-4b11-9a8a-1988519ca2c6 Storage:file Bucket:/var/jfs/ AccessKey: SecretKey: BlockSize:4096 Compression:none Shards:0 HashPrefix:false Capacity:0 Inodes:0 EncryptKey: KeyEncrypted:false TrashDays:1 MetaVersion:1 MinClientVersion: MaxClientVersion:} [format.go:447]
root@bench-01:~# juicefs format sqlite3://abc.db  myjxyzxa
2022/04/15 16:07:40.501380 juicefs[1078665] <INFO>: Meta address: sqlite3://abc.db [interface.go:383]
2022/04/15 16:07:40.502162 juicefs[1078665] <INFO>: Data use file:///var/jfs/myjxyzxa/ [format.go:409]
2022/04/15 16:07:40.503600 juicefs[1078665] <FATAL>: format: cannot update volume name from myjxyz to myjxyzxa [format.go:444]
root@bench-01:~# ls /var/jfs/myjxyzxa/
testing

**What you expected to happen**:
/var/jfs/myjxyzxa/ should be removed.

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**

**Environment**:
- JuiceFS version (use `juicefs --version`) or Hadoop Java SDK version:
- Cloud provider or hardware configuration running JuiceFS:
- OS (e.g `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Object storage (cloud provider and region, or self maintained):
- Metadata engine info (version, cloud provider managed or self maintained):
- Network connectivity (JuiceFS to metadata engine, JuiceFS to object storage):
- Others:

**Comment by davies** [comment]
Fixed by #1804
