### ISSUE TITLE
Error  writing file to TiKV

### ISSUE THREAD

**Issue by wanshicheng** [juicedata/juicefs#1805]
**What happened**:
https://asktug.com/t/topic/663540
**What you expected to happen**:
Write a big file to TiKV.
**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**

**Environment**:
- JuiceFS version (use `juicefs --version`) or Hadoop Java SDK version: 1.0.0-beta2
- OS (e.g `cat /etc/os-release`): CentOS Linux 7 (Core)
- Kernel (e.g. `uname -a`): Linux node01 3.10.0-1062.el7.x86_64 #1 SMP Wed Aug 7 18:08:02 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
- Object storage (cloud provider and region, or self maintained): TiKV (TiDB 5.4.0)
- Metadata engine info (version, cloud provider managed or self maintained): TiKV (TiDB 5.4.0)

**Comment by SandyXSD** [comment]
JuiceFS uses txnkv api to store metadata, and rawkv api to store data. Generally you have to deploy two TiKV clusters, see: https://tikv.org/docs/5.1/develop/clients/introduction/

**Comment by wanshicheng** [comment]
> Are you using the same TiKV for both metadata and data? JuiceFS uses txnkv api to store metadata, and rawkv api to store data. Generally you have to deploy two TiKV clusters, see: https://tikv.org/docs/5.1/develop/clients/introduction/

Yes, I use the same TiKV for both metadata and data.

**Comment by SandyXSD** [comment]
Details: https://asktug.com/t/topic/663540/9
