### ISSUE TITLE
duplicated "for" in Quick Start Doc

### ISSUE THREAD

**Issue by showjason** [juicedata/juicefs#1806]
Hi community, maybe here below is a doc fault.If yes, I'd like to commit a PR
<img width="773" alt="image" src="https://user-images.githubusercontent.com/27723125/163677196-aee3bb0e-db6b-460b-a345-b74709d28356.png">

**Comment by davies** [comment]
yes, go ahead to summit a PR, thanks!

**Comment by SandyXSD** [comment]
fixed by #1807
