### ISSUE TITLE
load meta with 4M empty files  to redis failed 

### ISSUE THREAD

**Issue by zhoucheng361** [juicedata/juicefs#1814]
**What happened**:
test1.json have 4M empty files.

root@bench-01:~/zhoucheng# juicefs load  redis://mymaster,172.27.0.1,172.27.0.2,172.27.0.3:26379/11   test1.json 
2022/04/18 13:56:18.383902 juicefs[1150283] <INFO>: Meta address: redis://mymaster,172.27.0.1,172.27.0.2,172.27.0.3:26379/11 [interface.go:383]
redis: 2022/04/18 13:56:18 sentinel.go:661: sentinel: new master="mymaster" addr="172.27.0.1:6379"
2022/04/18 13:56:18.385274 juicefs[1150283] <INFO>: Ping redis: 53.945µs [redis.go:2599]

Collected entries count: 4000940 / 4000940 [==============================================================]  done      
   Loaded entries count: 2266280 / 4000940 [==================================>---------------------------]  57 %   18s
2022-04-18 13:57:10.459782 I | write tcp 172.27.0.1:58284->172.27.0.1:6379: write: connection reset by peer

**What you expected to happen**:
should load succeed.

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**

**Environment**:
- JuiceFS version (use `juicefs --version`) or Hadoop Java SDK version:
- Cloud provider or hardware configuration running JuiceFS:
- OS (e.g `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Object storage (cloud provider and region, or self maintained):
- Metadata engine info (version, cloud provider managed or self maintained):
- Network connectivity (JuiceFS to metadata engine, JuiceFS to object storage):
- Others:

**Comment by zhijian-pro** [comment]
fix by https://github.com/juicedata/juicefs/pull/1858
