### ISSUE TITLE
JuiceFS  make a mistake while fio write test

### ISSUE THREAD

**Issue by sword0307** [juicedata/juicefs#182]
**What happened**:
When I use fio to test ,JuiceFS get wrong because of redis connection error.eg:
Feb  8 22:44:55 localhost juicefs[22291]: juicefs[22291] <ERROR>: error: redis: Conn is in a bad state: read tcp 172.16.11.140:50526->172.16.11.140:6379: i/o timeout
Feb  8 22:44:58 localhost juicefs[22291]: juicefs[22291] <WARNING>: write inode:5 error: input/output error
Feb  8 22:45:00 localhost juicefs[22291]: juicefs[22291] <ERROR>: write inode:5 indx:27  input/output error
And fio logs are below
tarting 16 processes
sequential-write: Laying out IO file (1 file / 4096MiB)
sequential-write: Laying out IO file (1 file / 4096MiB)
sequential-write: Laying out IO file (1 file / 4096MiB)
sequential-write: Laying out IO file (1 file / 4096MiB)
sequential-write: Laying out IO file (1 file / 4096MiB)
sequential-write: Laying out IO file (1 file / 4096MiB)
sequential-write: Laying out IO file (1 file / 4096MiB)
sequential-write: Laying out IO file (1 file / 4096MiB)
sequential-write: Laying out IO file (1 file / 4096MiB)
sequential-write: Laying out IO file (1 file / 4096MiB)
sequential-write: Laying out IO file (1 file / 4096MiB)
sequential-write: Laying out IO file (1 file / 4096MiB)
sequential-write: Laying out IO file (1 file / 4096MiB)
sequential-write: Laying out IO file (1 file / 4096MiB)
sequential-write: Laying out IO file (1 file / 4096MiB)
sequential-write: Laying out IO file (1 file / 4096MiB)
fio: io_u error on file /root/jfs/sequential-write.5.0: Input/output error: write offset=2029780992, buflen=262144
fio: io_u error on file /root/jfs/sequential-write.3.0: Input/output error: write offset=2017722368, buflen=3932160
fio: io_u error on file /root/jfs/sequential-write.2.0: Input/output error: write offset=2022965248, buflen=2883584
fio: io_u error on file /root/jfs/sequential-write.0.0: Input/output error: write offset=2025979904, buflen=4063232
fio: io_u error on file /root/jfs/sequential-write.15.0: Input/output error: write offset=2041315328, buflen=1310720
fio: io_u error on file /root/jfs/sequential-write.10.0: Input/output error: write offset=2060320768, buflen=3276800
fio: io_u error on file /root/jfs/sequential-write.8.0: Input/output error: write offset=2027421696, buflen=2621440
fio: io_u error on file /root/jfs/sequential-write.13.0: Input/output error: write offset=2017329152, buflen=131072
fio: io_u error on file /root/jfs/sequential-write.7.0: Input/output error: write offset=1987706880, buflen=393216
fio: io_u error on file /root/jfs/sequential-write.9.0: Input/output error: write offset=2010513408, buflen=2752512
fio: io_u error on file /root/jfs/sequential-write.1.0: Input/output error: write offset=2028208128, buflen=1835008a 18m:08s]
fio: pid=22318, err=5/file:io_u.c:1747, func=io_u error, error=Input/output error
fio: io_u error on file /root/jfs/sequential-write.6.0: Input/output error: write offset=2024407040, buflen=1441792
fio: pid=22320, err=5/file:io_u.c:1747, func=io_u error, error=Input/output error
fio: pid=22324, err=5/file:io_u.c:1747, func=io_u error, error=Input/output error
fio: pid=22319, err=5/file:io_u.c:1747, func=io_u error, error=Input/output error
fio: pid=22310, err=5/file:io_u.c:1747, func=io_u error, error=Input/output error
fio: pid=22321, err=5/file:io_u.c:1747, func=io_u error, error=Input/output error
fio: pid=22311, err=5/file:io_u.c:1747, func=io_u error, error=Input/output error
fio: pid=22323, err=5/file:io_u.c:1747, func=io_u error, error=Input/output error
fio: pid=22325, err=5/file:io_u.c:1747, func=io_u error, error=Input/output error
fio: pid=22317, err=5/file:io_u.c:1747, func=io_u error, error=Input/output error][r=0,w=4 IOPS][eta 18m:01s]                
fio: pid=22316, err=5/file:io_u.c:1747, func=io_u error, error=Input/output error
fio: pid=22313, err=5/file:io_u.c:1747, func=io_u error, error=Input/output error
**What you expected to happen**:
I execpted there is no mistake.
**How to reproduce it (as minimally and precisely as possible)**:
1.docker run -itd -p 9000:9000 -e "MINIO_ROOT_USER=XXXX" -e "MINIO_ROOT_PASSWORD=XXXX"  -v /root/data:/data  minio/minio:edge server /data
2.docker run -itd -p 6379:6379 --name minio-redis redis:latest
3.juicefs format  --storage minio --bucket http://MinIO/jfs --access-key XXX --secret-key XXX  redis://IP:6379/1 juicefs
4.fio --name=sequential-write --directory=/root/jfs --rw=write --refill_buffers --bs=4M --size=4G  --group_reporting --numjobs=16 --end_fsync=1
**Anything else we need to know?**
redis、minio and JuiceFS are developed on the same centos7 server
**Environment**:
- JuiceFS version (use `./juicefs --version`) or Hadoop Java SDK version:juicefs version 0.10.0-21 (2021-02-08 d4686ba)
- Cloud provider or hardware configuration running JuiceFS:
- OS (e.g: `cat /etc/os-release`):NAME="CentOS Linux"
VERSION="7 (Core)"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="7"
PRETTY_NAME="CentOS Linux 7 (Core)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:centos:centos:7"
HOME_URL="https://www.centos.org/"
BUG_REPORT_URL="https://bugs.centos.org/"

CENTOS_MANTISBT_PROJECT="CentOS-7"
CENTOS_MANTISBT_PROJECT_VERSION="7"
REDHAT_SUPPORT_PRODUCT="centos"
REDHAT_SUPPORT_PRODUCT_VERSION="7"
- Kernel (e.g. `uname -a`):Linux anna140 3.10.0-1062.el7.x86_64 #1 SMP Wed Aug 7 18:08:02 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
- Object storage (cloud provider and region):
- Redis info (version, cloud provider managed or self maintained):
- Network connectivity (JuiceFS to Redis, JuiceFS to object storage):
- Others:

**Comment by chnliyong** [comment]
@sword0307 How much memory does the centos7 server have? Can you reproduce it? I couldn't reproduce this error (AWS EC2 _c5.2xlarge_ instance).

**Comment by davies** [comment]
After stop the redis-server a few times, I was able to reproduce issue:

```
2021/02/22 13:55:24.702158 juicefs[60254] <ERROR>: error: read tcp 127.0.0.1:61428->127.0.0.1:6379: i/o timeout
2021/02/22 13:55:24.702249 juicefs[60254] <WARNING>: write inode:5836 error: input/output error
2021/02/22 13:55:24.702299 juicefs[60254] <ERROR>: write inode:5836 indx:0  input/output error
```

It looks like the redis client does not retry for some failed requests, will dig into this.

**Comment by pzj6868** [comment]
Using juicefs，I have happened this question，redis server is normal
Feb 23 14:08:22 localhost /usr/local/bin/juicefs[15590]: juicefs[15590] <ERROR>: error: redis: Conn is in a bad state: read tcp 172.16.10.27:33611->172.16.10.26:6379: i/o timeout
Feb 23 14:08:22 localhost /usr/local/bin/juicefs[15590]: juicefs[15590] <WARNING>: write inode:1209840 error: input/output error
Feb 23 14:08:22 localhost /usr/local/bin/juicefs[15590]: juicefs[15590] <ERROR>: write inode:1209840 indx:0  input/output error
Feb 23 14:08:22 localhost /usr/local/bin/juicefs[15590]: juicefs[15590] <ERROR>: error: redis: Conn is in a bad state: read tcp 172.16.10.27:33546->172.16.10.26:6379: i/o timeout
Feb 23 14:08:22 localhost /usr/local/bin/juicefs[15590]: juicefs[15590] <WARNING>: write inode:9 error: input/output error
Feb 23 14:08:22 localhost /usr/local/bin/juicefs[15590]: juicefs[15590] <ERROR>: write inode:9 indx:0  input/output error
Feb 23 14:08:22 localhost /usr/local/bin/juicefs[15022]: juicefs[15022] <ERROR>: error: redis: Conn is in a bad state: read tcp 172.16.10.27:32868->172.16.10.26:6379: i/o timeout
Feb 23 14:08:22 localhost /usr/local/bin/juicefs[15022]: juicefs[15022] <WARNING>: write inode:1521978 error: input/output error
Feb 23 14:08:22 localhost /usr/local/bin/juicefs[15022]: juicefs[15022] <ERROR>: write inode:1521978 indx:0  input/output error

**Comment by sword0307** [comment]
> @sword0307 How much memory does the centos7 server have? Can you reproduce it? I couldn't reproduce this error (AWS EC2 _c5.2xlarge_ instance).

16G memory.And same as other people meet the same error.@pzj6868@davies@chnliyong
