### ISSUE TITLE
Support metadata database other than Redis

### ISSUE THREAD

**Issue by lqhl** [juicedata/juicefs#183]
**What would you like to be added**:
I believe juicefs should support more powerful metadata db other than Redis.

**Why is this needed**:
- Since all metadata are stored in a single Redis instance (juicefs doesn't support Redis cluster because it uses transactions heavily), the Redis instance may require very large RAM if we store billions of small files in juicefs.
  - I hope the development team can give some data on how much RAM is required for 1M/1B files
- A single Redis instance becomes a SPOF which is bad for fault tolerance.
- A single Redis instance may become a throughput bottleneck.
- Using only memory makes the metadata storage very expensive.

Some alternatives to consider:
- [ardb](https://github.com/yinqiwen/ardb/) is compatible with Redis and uses SSD for storage (it's not active though).
- [anna](https://github.com/hydro-project/anna) is a distributed KVS which claims to be as fast as Redis.
- some more traditional options like cassandra, mysql, pg...

**Comment by angristan** [comment]
FYI, it looks like Redis Sentinel support has been added: https://github.com/juicedata/juicefs/pull/180

**Comment by xiaogaozi** [comment]
#287 mentions an new project called [Titan](https://github.com/distributedio/titan)

**Comment by cayolblake** [comment]
Worth mentioning https://github.com/yongman/tidis
