### ISSUE TITLE
error message not clear when create file with gbk name

### ISSUE THREAD

**Issue by zhoucheng361** [juicedata/juicefs#1839]
**What happened**:
root@bench-01:~/zhoucheng# ./juicefs-1.0.0-beta1 format mysql://root:pass@(172.27.0.1)/test7 test7
root@bench-01:~/zhoucheng# juicefs mount mysql://root:pass@(172.27.0.1)/test7 test7
(root@bench-01:~/zhoucheng# echo abc > `printf "test7/file_\xb9\xfb\xd6\xad\xca\xfd\xbe\xdd"`
-bash: `printf "test7/file_\xb9\xfb\xd6\xad\xca\xfd\xbe\xdd"`: Input/output error

**What you expected to happen**:
the error message is wired.

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**

**Environment**:
- JuiceFS version (use `juicefs --version`) or Hadoop Java SDK version:
- Cloud provider or hardware configuration running JuiceFS:
- OS (e.g `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Object storage (cloud provider and region, or self maintained):
- Metadata engine info (version, cloud provider managed or self maintained):
- Network connectivity (JuiceFS to metadata engine, JuiceFS to object storage):
- Others:

**Comment by davies** [comment]
This is fixed in main, user should upgrade to latest main branch and change the column to varbinary(255) to support GBK.
