### ISSUE TITLE
invalid character '%' after object key on juicefs load 

### ISSUE THREAD

**Issue by zhoucheng361** [juicedata/juicefs#1845]
**What happened**:
1. format with 1.0.0-beta2
2. mount with 1.0.0-beta2
3. alter db to binary
4. dump with 1.0.0-beta2
5. load json just dumped to another db which does not exist with latest client.
6. load failed with error message "invalid character '%' after object key"

Ref: https://github.com/juicedata/juicefs/runs/6091883941?check_suite_focus=true

**What you expected to happen**:
can load succeed.

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**

**Environment**:
- JuiceFS version (use `juicefs --version`) or Hadoop Java SDK version:
- Cloud provider or hardware configuration running JuiceFS:
- OS (e.g `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Object storage (cloud provider and region, or self maintained):
- Metadata engine info (version, cloud provider managed or self maintained):
- Network connectivity (JuiceFS to metadata engine, JuiceFS to object storage):
- Others:

**Comment by zhoucheng361** [comment]
should load with new client after db changed.

**Comment by davies** [comment]
New client can load a file dumped by old clients, but old client may NOT load JSON file dumped by new client.
