### ISSUE TITLE
/var/log/juicefs.log permission denied.

### ISSUE THREAD

**Issue by zhoucheng361** [juicedata/juicefs#1851]
**What happened**:
run juicefs with non-root user, will show this error:

2022/04/21 02:48:42.565676 juicefs[7575] <ERROR>: open log file /var/log/juicefs.log: open /var/log/juicefs.log: permission denied [mount_unix.go:83]

https://github.com/juicedata/juicefs/runs/6105515257?check_suite_focus=true

**What you expected to happen**:
should not permission denied.

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**

**Environment**:
- JuiceFS version (use `juicefs --version`) or Hadoop Java SDK version:
- Cloud provider or hardware configuration running JuiceFS:
- OS (e.g `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Object storage (cloud provider and region, or self maintained):
- Metadata engine info (version, cloud provider managed or self maintained):
- Network connectivity (JuiceFS to metadata engine, JuiceFS to object storage):
- Others:

**Comment by SandyXSD** [comment]
It's because the user running JuiceFS doesn't have write permission in `/var/log`. Add `--log <log_file>` to use a permitted file, e.g. `/tmp/juicefs.log`

**Comment by SandyXSD** [comment]
Better change the default log path when user is not root.

**Comment by zhoucheng361** [comment]
still have the Error message.

https://github.com/juicedata/juicefs/runs/6145081892?check_suite_focus=true

<img width="1050" alt="image" src="https://user-images.githubusercontent.com/100545994/164962782-f0ec93f8-e17f-4375-ad93-5639547a8f34.png">

**Comment by zhoucheng361** [comment]
it is fixed in latest client.
