### ISSUE TITLE
can't sync .accesslog file 

### ISSUE THREAD

**Issue by zhoucheng361** [juicedata/juicefs#1859]
**What happened**:
can't sync .accesslog file because it is always appended with logs

![image](https://user-images.githubusercontent.com/100545994/164408214-d9e4bf6b-0e8a-4e98-aa8c-a98c6739e761.png)

**What you expected to happen**:
should let user know he is sync an infinity file so he can exclude it 

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**

**Environment**:
- JuiceFS version (use `juicefs --version`) or Hadoop Java SDK version:
- Cloud provider or hardware configuration running JuiceFS:
- OS (e.g `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Object storage (cloud provider and region, or self maintained):
- Metadata engine info (version, cloud provider managed or self maintained):
- Network connectivity (JuiceFS to metadata engine, JuiceFS to object storage):
- Others:

**Comment by davies** [comment]
.accesslog is a special file, it's OK to fail (rsync may also fail).

We should exclude it when coping a whole file system.
