### ISSUE TITLE
The xorm sync2 method does not modify the database fields when the table structure is different

### ISSUE THREAD

**Issue by zhijian-pro** [juicedata/juicefs#1863]
We need to check whether sync2 in the current code needs to be adjusted. 
e.g.
https://github.com/juicedata/juicefs/blob/bcb4c01ae662050d0b9a8d74131580506655c992/pkg/meta/sql.go#L356-L365
[xorm sync2 reference documentation
](https://www.kancloud.cn/kancloud/xorm-manual-zh-cn/56006#:~:text=Sync2%E5%AF%B9Sync%E8%BF%9B%E8%A1%8C%E4%BA%86%E6%94%B9%E8%BF%9B%EF%BC%8C%E7%9B%AE%E5%89%8D%E6%8E%A8%E8%8D%90%E4%BD%BF%E7%94%A8Sync2%E3%80%82Sync2%E5%87%BD%E6%95%B0%E5%B0%86%E8%BF%9B%E8%A1%8C%E5%A6%82%E4%B8%8B%E7%9A%84%E5%90%8C%E6%AD%A5%E6%93%8D%E4%BD%9C%EF%BC%9A)

**Comment by davies** [comment]
That's OK, when users see a warning (the column type is not expected), they can alter it by themself.
