### ISSUE TITLE
When I try to dump meta data from etcd ，one node of the cluster will fail

### ISSUE THREAD

**Issue by sanwan** [juicedata/juicefs#1864]
root@bench-02:~/sanwan/juicefs# time ./juicefs dump etcd://172.27.0.1:3380,172.27.0.2:3380,172.27.0.3:3380/ /datadata/dump0421_400w.json 
2022/04/21 22:03:28.678862 juicefs[75607] <INFO>: Meta address: etcd://172.27.0.1:3380,172.27.0.2:3380,172.27.0.3:3380/ [interface.go:383]
Snapshot keys count: 0 / 12218658 [--------------------------------------------------------------]   0 %    0s
{"level":"warn","ts":"2022-04-21T22:03:33.691+0800","logger":"etcd-client","caller":"v3@v3.5.2/retry_interceptor.go:62","msg":"retrying of unary invoker failed","target":"etcd-endpoints://0xc0007c1500/172.27.0.1:3380","attempt":0,"error":"rpc error: code = Unavailable desc = error Snapshot keys count: 0 / 12218658 [--------------------------------------------------------------]   0 %    0s
{"level":"warn","ts":"2022-04-21T22:03:38.692+0800","logger":"etcd-client","caller":"v3@v3.5.2/retry_interceptor.go:62","msg":"retrying of unary invoker failed","target":"etcd-endpoints://0xc0007c1500/172.27.0.1:3380","attempt":1,"error":"rpc error: code = Unavailable desc = error Snapshot keys count: 0 / 12218658 [--------------------------------------------------------------]   0 %    0s
{"level":"warn","ts":"2022-04-21T22:03:43.720+0800","logger":"etcd-client","caller":"v3@v3.5.2/retry_interceptor.go:62","msg":"retrying of unary invoker failed","target":"etcd-endpoints://0xc0007c1500/172.27.0.1:3380","attempt":2,"error":"rpc error: code = Unavailable desc = error Snapshot keys count: 0 / 12218658 [--------------------------------------------------------------]   0 %    0s
{"level":"warn","ts":"2022-04-21T22:03:48.721+0800","logger":"etcd-client","caller":"v3@v3.5.2/retry_interceptor.go:62","msg":"retrying of unary invoker failed","target":"etcd-endpoints://0xc0007c1500/172.27.0.1:3380","attempt":3,"error":"rpc error: code = Unavailable desc = error Snapshot keys count: 0 / 12218658 [--------------------------------------------------------------]   0 %    0s
{"level":"warn","ts":"2022-04-21T22:03:53.746+0800","logger":"etcd-client","caller":"v3@v3.5.2/retry_interceptor.go:62","msg":"retrying of unary invoker failed","target":"etcd-endpoints://0xc0007c1500/172.27.0.1:3380","attempt":4,"error":"rpc error: code = Unavailable desc = error Snapshot keys count: 0 / 12218658 [--------------------------------------------------------------]   0 %    0s
{"level":"warn","ts":"2022-04-21T22:03:58.747+0800","logger":"etcd-client","caller":"v3@v3.5.2/retry_interceptor.go:62","msg":"retrying of unary invoker failed","target":"etcd-endpoints://0xc0007c1500/172.27.0.1:3380","attempt":5,"error":"rpc error: code = Unavailable desc = error Snapshot keys count: 0 / 12218658 [--------------------------------------------------------------]   0 %    0s
{"level":"warn","ts":"2022-04-21T22:04:03.774+0800","logger":"etcd-client","caller":"v3@v3.5.2/retry_interceptor.go:62","msg":"retrying of unary invoker failed","target":"etcd-endpoints://0xc0007c1500/172.27.0.1:3380","attempt":6,"error":"rpc error: code = Unavailable desc = error Snapshot keys count: 0 / 12218658 [--------------------------------------------------------------]   0 %    0s
{"level":"warn","ts":"2022-04-21T22:04:08.788+0800","logger":"etcd-client","caller":"v3@v3.5.2/retry_interceptor.go:62","msg":"retrying of unary invoker failed","target":"etcd-endpoints://0xc0007c1500/172.27.0.1:3380","attempt":7,"error":"rpc error: code = Unavailable desc = error Snapshot keys count: 0 / 12218658 [--------------------------------------------------------------]   0 %    0s
{"level":"warn","ts":"2022-04-21T22:04:13.815+0800","logger":"etcd-client","caller":"v3@v3.5.2/retry_interceptor.go:62","msg":"retrying of unary invoker failed","target":"etcd-endpoints://0xc0007c1500/172.27.0.1:3380","attempt":8,"error":"rpc error: code = Unavailable desc = error Snapshot keys count: 0 / 12218658 [--------------------------------------------------------------]   0 %    0s
{"level":"warn","ts":"2022-04-21T22:04:18.829+0800","logger":"etcd-client","caller":"v3@v3.5.2/retry_interceptor.go:62","msg":"retrying of unary invoker failed","target":"etcd-endpoints://0xc0007c1500/172.27.0.1:3380","attempt":9,"error":"rpc error: code = Unavailable desc = error Snapshot keys count: 0 / 12218658 [--------------------------------------------------------------]   0 %    0s
{"level":"warn","ts":"2022-04-21T22:06:42.267+0800","logger":"etcd-client","caller":"v3@v3.5.2/retry_interceptor.go:62","msg":"retrying of unary invoker failed","target":"etcd-endpoints://0xc0007c1500/172.27.0.1:3380","attempt":10,"error":"rpc error: code = Unavailable desc = errorSnapshot keys count: 0 / 12218658 [--------------------------------------------------------------]   0 %    0s
^C
real	3m43.151s
user	0m0.293s
sys	0m0.180s

### **Above info is the action，and all the files are  400,0000.In addition, I succeed dump  meta data of 2600000 files from etcd.**

root@bench-02:/datadata# etcdctl --write-out=table --endpoints=http://172.27.0.1:3380,http://172.27.0.2:3380,http://172.27.0.3:3380 endpoint status
{"level":"warn","ts":"2022-04-21T23:18:36.410+0800","logger":"etcd-client","caller":"v3/retry_interceptor.go:62","msg":"retrying of unary invoker failed","target":"etcd-endpoints://0xc0003d4700/#initially=[http://172.27.0.1:3380;http://172.27.0.2:3380;http://172.27.0.3:3380]","attempt":0,"error":"rpc error: code = DeadlineExceeded desc = latest balancer error: last connection error: connection error: desc = \"transport: Error while dialing dial tcp 172.27.0.2:3380: connect: connection refused\""}
Failed to get the status of endpoint http://172.27.0.2:3380 (context deadline exceeded)
+------------------------+------------------+---------+---------+-----------+------------+-----------+------------+--------------------+--------+
|        ENDPOINT        |        ID        | VERSION | DB SIZE | IS LEADER | IS LEARNER | RAFT TERM | RAFT INDEX | RAFT APPLIED INDEX | ERRORS |
+------------------------+------------------+---------+---------+-----------+------------+-----------+------------+--------------------+--------+
| http://172.27.0.1:3380 | 7f07316fbe59d309 |   3.5.0 |  3.4 GB |     false |      false |         3 |   12268558 |           12268558 |        |
| http://172.27.0.3:3380 | 41fe1c9b37be2217 |   3.5.0 |  3.4 GB |      true |      false |         3 |   12268560 |           12268560 |        |
+------------------------+------------------+---------+---------+-----------+------------+-----------+------------+--------------------+--------+

**### After the etcd crashed， the dump process will be killed.**

root@bench-02:/datadata# cd -
/root/sanwan/juicefs
root@bench-02:~/sanwan/juicefs# time ./juicefs dump etcd://172.27.0.1:3380,172.27.0.2:3380,172.27.0.3:3380/ /datadata/dump0421_400w.json
2022/04/21 23:42:22.014345 juicefs[76568] <INFO>: Meta address: etcd://172.27.0.1:3380,172.27.0.2:3380,172.27.0.3:3380/ [interface.go:383]
Snapshot keys count: 0 / 12218658 [--------------------------------------------------------------]   0 %    0s
{"level":"warn","ts":"2022-04-21T23:42:27.018+0800","logger":"etcd-client","caller":"v3@v3.5.2/retry_interceptor.go:62","msg":"retrying of unary invoker failed","target":"etcd-endpoints://0xc0009ff340/172.27.0.1:3380","attempt":0,"error":"rpc error: code = Unavailable desc = error Snapshot keys count: 0 / 12218658 [--------------------------------------------------------------]   0 %    0s
{"level":"warn","ts":"2022-04-21T23:42:32.019+0800","logger":"etcd-client","caller":"v3@v3.5.2/retry_interceptor.go:62","msg":"retrying of unary invoker failed","target":"etcd-endpoints://0xc0009ff340/172.27.0.1:3380","attempt":1,"error":"rpc error: code = Unavailable desc = error Snapshot keys count: 0 / 12218658 [--------------------------------------------------------------]   0 %    0s
{"level":"warn","ts":"2022-04-21T23:42:37.046+0800","logger":"etcd-client","caller":"v3@v3.5.2/retry_interceptor.go:62","msg":"retrying of unary invoker failed","target":"etcd-endpoints://0xc0009ff340/172.27.0.1:3380","attempt":2,"error":"rpc error: code = Unavailable desc = error Snapshot keys count: 0 / 12218658 [--------------------------------------------------------------]   0 %    0s
{"level":"warn","ts":"2022-04-21T23:42:42.046+0800","logger":"etcd-client","caller":"v3@v3.5.2/retry_interceptor.go:62","msg":"retrying of unary invoker failed","target":"etcd-endpoints://0xc0009ff340/172.27.0.1:3380","attempt":3,"error":"rpc error: code = Unavailable desc = error Snapshot keys count: 0 / 12218658 [--------------------------------------------------------------]   0 %    0s
{"level":"warn","ts":"2022-04-21T23:42:47.075+0800","logger":"etcd-client","caller":"v3@v3.5.2/retry_interceptor.go:62","msg":"retrying of unary invoker failed","target":"etcd-endpoints://0xc0009ff340/172.27.0.1:3380","attempt":4,"error":"rpc error: code = Unavailable desc = error Snapshot keys count: 0 / 12218658 [--------------------------------------------------------------]   0 %    0s
{"level":"warn","ts":"2022-04-21T23:42:52.077+0800","logger":"etcd-client","caller":"v3@v3.5.2/retry_interceptor.go:62","msg":"retrying of unary invoker failed","target":"etcd-endpoints://0xc0009ff340/172.27.0.1:3380","attempt":5,"error":"rpc error: code = Unavailable desc = error Snapshot keys count: 0 / 12218658 [--------------------------------------------------------------]   0 %    0s
{"level":"warn","ts":"2022-04-21T23:42:57.107+0800","logger":"etcd-client","caller":"v3@v3.5.2/retry_interceptor.go:62","msg":"retrying of unary invoker failed","target":"etcd-endpoints://0xc0009ff340/172.27.0.1:3380","attempt":6,"error":"rpc error: code = Unavailable desc = error Snapshot keys count: 0 / 12218658 [--------------------------------------------------------------]   0 %    0s
{"level":"warn","ts":"2022-04-21T23:43:02.109+0800","logger":"etcd-client","caller":"v3@v3.5.2/retry_interceptor.go:62","msg":"retrying of unary invoker failed","target":"etcd-endpoints://0xc0009ff340/172.27.0.1:3380","attempt":7,"error":"rpc error: code = Unavailable desc = error Snapshot keys count: 0 / 12218658 [--------------------------------------------------------------]   0 %    0s
{"level":"warn","ts":"2022-04-21T23:43:07.137+0800","logger":"etcd-client","caller":"v3@v3.5.2/retry_interceptor.go:62","msg":"retrying of unary invoker failed","target":"etcd-endpoints://0xc0009ff340/172.27.0.1:3380","attempt":8,"error":"rpc error: code = Unavailable desc = error Snapshot keys count: 0 / 12218658 [--------------------------------------------------------------]   0 %    0s
{"level":"warn","ts":"2022-04-21T23:43:12.155+0800","logger":"etcd-client","caller":"v3@v3.5.2/retry_interceptor.go:62","msg":"retrying of unary invoker failed","target":"etcd-endpoints://0xc0009ff340/172.27.0.1:3380","attempt":9,"error":"rpc error: code = Unavailable desc = error Snapshot keys count: 0 / 12218658 [--------------------------------------------------------------]   0 %    0s
{"level":"warn","ts":"2022-04-21T23:43:17.182+0800","logger":"etcd-client","caller":"v3@v3.5.2/retry_interceptor.go:62","msg":"retrying of unary invoker failed","target":"etcd-endpoints://0xc0009ff340/172.27.0.1:3380","attempt":10,"error":"rpc error: code = Unavailable desc = errorSnapshot keys count: 0 / 12218658 [--------------------------------------------------------------]   0 %    0s
{"level":"warn","ts":"2022-04-21T23:43:27.181+0800","logger":"etcd-client","caller":"v3@v3.5.2/retry_interceptor.go:62","msg":"retrying of unary invoker failed","target":"etcd-endpoints://0xc0009ff340/172.27.0.1:3380","attempt":11,"error":"rpc error: code = Unavailable desc = errorSnapshot keys count: 1388010 / 12218658 [======>-------------------------------------------------------]  11 % 36m6s
{"level":"warn","ts":"2022-04-21T23:48:00.793+0800","logger":"etcd-client","caller":"v3@v3.5.2/retry_interceptor.go:62","msg":"retrying of unary invoker failed","target":"etcd-endpoints://0xc0009ff340/172.27.0.1:3380","attempt":0,"error":"rpc error: code = DeadlineExceeded desc = cSnapshot keys count: 1393965 / 12218658 [======>-------------------------------------------------------]  11 %45m25s
{"level":"info","ts":"2022-04-21T23:48:23.543+0800","logger":"etcd-client","caller":"v3@v3.5.2/client.go:207","msg":"Auto sync endpoints fail Snapshot keys count: 12165914 / 12165914 [==============================================================]  done      
Dumped entries count: 291151 / 4000004 [====>---------------------------------------------------------]   7 % 2m19s
Killed

real  10m53.371s
user  1m17.606s
sys   0m8.346s
root@bench-02:~/sanwan/juicefs#

**Comment by davies** [comment]
Since we can dump 2.6 millions of files but fail with 4mil, I think it reach the limit in current environment, it's expected.
