### ISSUE TITLE
should return real size when stat .config 

### ISSUE THREAD

**Issue by zhoucheng361** [juicedata/juicefs#1893]
**What happened**:

root@bench-01:~/zhoucheng# stat /tmp/sync-test/.config
  File: /tmp/sync-test/.config
  Size: 0         	Blocks: 0          IO Block: 65536  regular empty file
Device: 6eh/110d	Inode: 9223372032559808516  Links: 1
Access: (0400/-r--------)  Uid: (    0/    root)   Gid: (    0/    root)
Access: 2022-04-25 13:19:47.000000000 +0800
Modify: 2022-04-25 13:19:47.000000000 +0800
Change: 2022-04-25 13:19:47.000000000 +0800
 Birth: -

root@bench-01:~/zhoucheng# stat /tmp/sync-test/.stats 
  File: /tmp/sync-test/.stats
  Size: 0         	Blocks: 0          IO Block: 65536  regular empty file
Device: 6eh/110d	Inode: 9223372032559808515  Links: 1
Access: (0444/-r--r--r--)  Uid: (    0/    root)   Gid: (    0/    root)
Access: 2022-04-25 13:19:47.000000000 +0800
Modify: 2022-04-25 13:19:47.000000000 +0800
Change: 2022-04-25 13:19:47.000000000 +0800
 Birth: -

root@bench-01:~/zhoucheng# stat /tmp/sync-test/.control 
  File: /tmp/sync-test/.control
  Size: 0         	Blocks: 0          IO Block: 65536  regular empty file
Device: 6eh/110d	Inode: 9223372032559808514  Links: 1
Access: (0666/-rw-rw-rw-)  Uid: (    0/    root)   Gid: (    0/    root)
Access: 2022-04-25 13:19:47.000000000 +0800
Modify: 2022-04-25 13:19:47.000000000 +0800
Change: 2022-04-25 13:19:47.000000000 +0800
 Birth: -

**What you expected to happen**:
stat should return real size of the file instead 0.

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**

**Environment**:
- JuiceFS version (use `juicefs --version`) or Hadoop Java SDK version:
- Cloud provider or hardware configuration running JuiceFS:
- OS (e.g `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Object storage (cloud provider and region, or self maintained):
- Metadata engine info (version, cloud provider managed or self maintained):
- Network connectivity (JuiceFS to metadata engine, JuiceFS to object storage):
- Others:

**Comment by davies** [comment]
.accesslog and .stats are generated when it's open or read, so we don't know the size in advance, keep them as 0.
