### ISSUE TITLE
could not create pvc with backend aliyun-oss

### ISSUE THREAD

**Issue by bigkun** [juicedata/juicefs#1920]
**What happened**:
```
$ kubectl describe pvc ali-oss-pvc
 Warning  ProvisioningFailed    8s (x3 over 28s)   csi.juicefs.com_juicefs-csi-controller-0_47c92e0c-8a8b-4e6d-941c-bbfc656303c8  failed to provision volume with StorageClass "juicefs-sc": rpc error: code = Internal desc = Could not createVol in juicefs: rpc error: code = Internal desc = exit status 1
```
**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**

**Environment**:
- JuiceFS version (use `juicefs --version`) or Hadoop Java SDK version:  juicefs version 1.0.0-beta2+2022-03-04T03:00:41Z.9e26080

- Cloud provider or hardware configuration running JuiceFS:  vagrant
- OS (e.g `cat /etc/os-release`):
 ```
NAME="Anolis OS"
VERSION="8.5"
ID="anolis"
ID_LIKE="rhel fedora centos"
VERSION_ID="8.5"
PLATFORM_ID="platform:an8"
PRETTY_NAME="Anolis OS 8.5"
ANSI_COLOR="0;31"
HOME_URL="https://openanolis.cn/"

```
- Kernel (e.g. `uname -a`): Linux juicefs 4.19.91-23.4.an8.x86_64 #1 SMP Fri Apr 30 14:39:15 CST 2021 x86_64 x86_64 x86_64 GNU/Linux
- Object storage (cloud provider and region, or self maintained): aliyun oss shanghai
- Metadata engine info (version, cloud provider managed or self maintained): redis 
- Network connectivity (JuiceFS to metadata engine, JuiceFS to object storage):
- Others:

**Comment by zwwhdls** [comment]
Hi @bigkun ,

Can you check juicefs-csi-controller log ?
```
kubectl -n kube-system logs juicefs-csi-controller-0 -c juicefs-plugin
```

**Comment by bigkun** [comment]
@zwwhdls thx. it's my mistake!
I checked the juicefs-csi-controller log, and found: `is not configured correctly: Failed to create bucket oss://csi-***/csi-oss/: Put "https://csi-oss-***.oss-cn-shanghai.aliyuncs.comhttps:/": d`.
So, I edit the `juicefs-sc-secret.yaml`,and fix the incorrect configurations.
