### ISSUE TITLE
Endpoint Store of Chunk in MariaDB SQL

### ISSUE THREAD

**Issue by proceau** [juicedata/juicefs#1928]
Add in list of endpoint for chunk storage the MariaDB driver

Ideale it's support 2 IP backend by bucket

The target it's use JuiceFS in MariaDB / MariaDB mode for high integrity mode.

**Comment by davies** [comment]
Do you mean use SQL database to store data of files in JuiceFS?

**Comment by proceau** [comment]
it's exact:
  use MariaDB-meta for store Meta
 & use MariaDB-chunk0 to 9 ( with shards set to 10 ) for store Chunk/Slice

**Comment by davies** [comment]
That's interesting, we have done that for Redis and TiKV, may also do that for SQL database and etcd.

**Comment by proceau** [comment]
that's why I allowed myself to make this issue, because it was in the logic of plugins and I prefer SQL :p

thx

**Comment by davies** [comment]
@proceau We can support SQL database as data store now, please try the latest main branch. 

```
export META_PASSWORD=xxx
juicefs format mysql://user@xxxx/db --storage mysql --bucket xxx/db  --access-key user --secret-key pass
```
