### ISSUE TITLE
should not create db file when mount failed.

### ISSUE THREAD

**Issue by zhoucheng361** [juicedata/juicefs#1931]
**What happened**:
```
root@bench-01:~/zhoucheng/juicefs_source# ls abd.db
ls: cannot access 'abd.db': No such file or directory
root@bench-01:~/zhoucheng/juicefs_source# ./juicefs mount sqlite3://abd.db myjfs2 -d
2022/04/28 10:50:53.966383 juicefs[1677601] <INFO>: Meta address: sqlite3://abd.db [interface.go:385]
2022/04/28 10:50:53.975430 juicefs[1677601] <FATAL>: load setting: database is not formatted [mount.go:173]
root@bench-01:~/zhoucheng/juicefs_source# ls abd.db
abd.db
```

**What you expected to happen**:
should not create db file when mount failed with a non-exist db file. 
maybe for sqlite3 protocol, we can first check if the db file exist, if not exist, we do not try to connect to it.

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**

**Environment**:
- JuiceFS version (use `juicefs --version`) or Hadoop Java SDK version:
- Cloud provider or hardware configuration running JuiceFS:
- OS (e.g `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Object storage (cloud provider and region, or self maintained):
- Metadata engine info (version, cloud provider managed or self maintained):
- Network connectivity (JuiceFS to metadata engine, JuiceFS to object storage):
- Others:

**Comment by bigkun** [comment]
`sudo juicefs format sqlite3://abd.db myjfs2` first!
