### ISSUE TITLE
Failed to sync large files into Azure Blob Storage, ErrorCode=RequestBodyTooLarge

### ISSUE THREAD

**Issue by DeanThompson** [juicedata/juicefs#1947]
**What happened**:

Using `juicefs sync` to copy files from AWS S3 to Azure Blob Storage, got error when the files are too large (not sure of the exact threshold). The smaller files work well.

From what I saw, files larger than 3GB failed, while ~200MB succeeded.

Error message:

```
Time:2022-05-02T17:55:58.7465947Z, RequestInitiated=Mon, 02 May 2022 17:55:57 GMT, RequestId=809d1e23-201e-0005-5f4d-5e36b1000000, API Version=2017-04-17, QueryParameterName=, QueryParameterValue=
2022/05/03 01:56:04.853836 juicefs[404967] <ERROR>: Failed to copy 0002_part_00.parquet: storage: service returned error: StatusCode=413, ErrorCode=RequestBodyTooLarge, ErrorMessage=The request body is too large and exceeds the maximum permissible limit.
```

**Comment by solracsf** [comment]
Ref: https://docs.microsoft.com/en-us/troubleshoot/azure/general/request-body-large

**Comment by davies** [comment]
We are using [azure-sdk-for-go](https://github.com/Azure/azure-sdk-for-go)/storage/ , which does not support block blob (similar to multipart upload), and is deprecating, we should switch to [github.com/Azure/azure-sdk-for-go/sdk/storage/azblob](https://github.com/Azure/azure-sdk-for-go/tree/main/sdk/storage/azblob) instead.
