### ISSUE TITLE
Error mounting encrypted JuiceFS filesystem

### ISSUE THREAD

**Issue by helix-loop** [juicedata/juicefs#1981]
**What happened**:
Mounting encrypted JuiceFS filesystem does not work and shows 

`<FATAL>: object storage: load private key: passphrase is required to private key [mount.go:271]`

(Passphrase is set via environment variable `export JFS_RSA_PASSPHRASE=the-passwd-for-rsa`)

**What you expected to happen**:
Filesystem is mounted successfully

**How to reproduce it (as minimally and precisely as possible)**:
Create encrypted filesystem with private key and passphrase. Load environment variable with `export JFS_RSA_PASSPHRASE=the-passwd-for-rsa` and try to mount the filesystem with all other required parameters

**Anything else we need to know?**
-

**Environment**:
- JuiceFS version (use `juicefs --version`) or Hadoop Java SDK version: 1.0.0-beta2
- Cloud provider or hardware configuration running JuiceFS: -
- OS (e.g `cat /etc/os-release`): Debian 11 (Bullseye)
- Kernel (e.g. `uname -a`): 5.15.25
- Object storage (cloud provider and region, or self maintained): self maintained
- Metadata engine info (version, cloud provider managed or self maintained): PostgreSQL 13
- Network connectivity (JuiceFS to metadata engine, JuiceFS to object storage): 1 GBit/s
- Others: -

**Comment by helix-loop** [comment]
Using JuiceFS version 1.0.0-beta3 results in the following error:
`<FATAL>: object storage: passphrase is required to private key, please try again after setting the 'JFS_RSA_PASSPHRASE' environment variable [mount.go:287]`

**Comment by zhijian-pro** [comment]
I haven't reproduced your problem, you can follow my steps to see if it works.
```bash
# JuiceFS version 1.0.0-beta3

# in the same session terminal
$ export JFS_RSA_PASSPHRASE=passphrase
$ openssl genrsa -out my-priv-key.pem -aes256 2048  #Enter "passphrase" twice
$ juicefs format --encrypt-rsa-key my-priv-key.pem "sqlite3://my-jfs.db" test1
$ juicefs mount -d "sqlite3://my-jfs.db" /tmp/test1
```
You will see a log similar to the following.
<img width="2551" alt="image" src="https://user-images.githubusercontent.com/31313340/167525347-d52b764d-b053-40ba-9a65-6c4ae20b786a.png">

**Comment by davies** [comment]
Cannot reprodoce
