### ISSUE TITLE
Hope support overlayfs upper layer on juicefs

### ISSUE THREAD

**Issue by wuyongzhi** [juicedata/juicefs#1989]
when i create overlay fs with juicefs as upper layer, i can not create overlay fs, it got a error:

the command:
```
# mount -t overlay o1 -o lowerdir=jfs/exercises/001,upperdir=jfs/user/001,workdir=workspaces/001/work workspaces/001/merged
```

output:
```
mount: /opt/workspaces/001/merged: wrong fs type, bad option, bad superblock on o1, missing codepage or helper program, or other error
```

**What would you like to be added**:
create overlay fs with juicefs as upper layer, 

**Why is this needed**:

**Comment by davies** [comment]
Based on: https://www.kernel.org/doc/html/latest/filesystems/overlayfs.html
```
The upper filesystem will normally be writable and if it is it must support the creation of trusted.* and/or user.* extended attributes, and must provide valid d_type in readdir responses
```
You need to mount JuiceFS with `--enable-xattr` to use it as upper layer.
