### ISSUE TITLE
Speed up path resolving using Lua script

### ISSUE THREAD

**Issue by davies** [juicedata/juicefs#199]
The Hadoop SDK and S3 gateway are heavy dependent on path resolving (lookup the inode for a path step by step), which is slow if there are many level of directories.

This could be speed up using Lua script to resolve the path in Redis (also check the permissions).

This is similar to the recursive Lookup with permission checking.

**Comment by suzaku** [comment]
I'm interested in this issue. Could you please show me the current related implementation?

**Comment by davies** [comment]
@suzaku The current implementation is here: https://github.com/juicedata/juicefs/blob/main/pkg/fs/fs.go#L532

**Comment by suzaku** [comment]
In the `fs` layer, we are not sure whether the underlying `meta` is Redis based. How can we introduce this optimization without breaking the encapsulation?

**Comment by suzaku** [comment]
How about modifying the `Meta` interface and introduce something like `LookupPath`?

**Comment by davies** [comment]
> How about modifying the `Meta` interface and introduce something like `LookupPath`?

Yes, we can add a `Resolve(Context, parent Inode, path string, inode *Ino, attr *Attr) Errno`

**Comment by suzaku** [comment]
The downside of this design is that we no longer have a default implementation of `fs.Lookup` that only depends on `meta.Lookup`.

We can keep the original implementation if we can somehow tell if `Resolve` is supported.

**Comment by davies** [comment]
fs.Lookup() can call meta.Resolve() first, then fallback to meta.Lookup() if it's not supported.

**Comment by davies** [comment]
Resolve() can return syscall.ENOTSUP
