### ISSUE TITLE
TestSQLiteClient failed

### ISSUE THREAD

**Issue by sanwan** [juicedata/juicefs#2004]
=== RUN   TestSQLiteClient
2022/05/11 09:38:49.209549 juicefs[23313] <ERROR>: error: no such table: jfs_node
goroutine 2184 [running]:
runtime/debug.Stack()
	/home/travis/.gimme/versions/go1.17.linux.amd64/src/runtime/debug/stack.go:24 +0x65
github.com/juicedata/juicefs/pkg/meta.errno({0x15ac260, 0xc001b00cc0})
	/home/travis/gopath/src/github.com/juicedata/juicefs/pkg/meta/utils.go:92 +0x117
github.com/juicedata/juicefs/pkg/meta.(*dbMeta).doGetAttr(0xc000b64e00, {0xc003d50000, 0x21e1780}, 0x1, 0xc0000bb5b8)
	/home/travis/gopath/src/github.com/juicedata/juicefs/pkg/meta/sql.go:673 +0xf9
github.com/juicedata/juicefs/pkg/meta.(*baseMeta).GetAttr.func1()
	/home/travis/gopath/src/github.com/juicedata/juicefs/pkg/meta/base.go:563 +0x4f
github.com/juicedata/juicefs/pkg/utils.WithTimeout.func1()
	/home/travis/gopath/src/github.com/juicedata/juicefs/pkg/utils/utils.go:70 +0x2f
created by github.com/juicedata/juicefs/pkg/utils.WithTimeout
	/home/travis/gopath/src/github.com/juicedata/juicefs/pkg/utils/utils.go:69 +0xe5 [utils.go:92]
2022/05/11 09:38:49.287974 juicefs[23313] <INFO>: create session 1 OK [base.go:186]
    redis_test.go:527: chunks: [{0 100 0 100} {0 0 0 50} {1 100 50 50}]
2022/05/11 09:38:49.541561 juicefs[23313] <INFO>: close session 1: %!s(<nil>) [base.go:243]
--- FAIL: TestSQLiteClient (0.33s)

Details may refer to  https://app.travis-ci.com/github/juicedata/juicefs/builds/250501613#L1764 .

**Comment by SandyXSD** [comment]
Not reproduced for a long time.
