### ISSUE TITLE
error message not clear.

### ISSUE THREAD

**Issue by zhoucheng361** [juicedata/juicefs#2008]
**What happened**:
```
runner@fv-az198-826:~/work/test-ci/test-ci$ ./juicefs format --storage minio --bucket http://localhost:9000 --access-key juicedata --secret-key juicedata sqlite3://abc.db myjfs
2022/05/12 07:48:25.805377 juicefs[9400] <INFO>: Meta address: sqlite3://abc.db [interface.go:383]
2022/05/12 07:48:25.806092 juicefs[9400] <FATAL>: object storage: no bucket name provided in http://localhost:9000: %!s(<nil>) [format.go:377]
```

**What you expected to happen**:

"%!s(<nil>)" is not readable.

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**

**Environment**:
- JuiceFS version (use `juicefs --version`) or Hadoop Java SDK version:
- Cloud provider or hardware configuration running JuiceFS:
- OS (e.g `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Object storage (cloud provider and region, or self maintained):
- Metadata engine info (version, cloud provider managed or self maintained):
- Network connectivity (JuiceFS to metadata engine, JuiceFS to object storage):
- Others:

**Comment by SandyXSD** [comment]
It's because we use "%s" as `fmt verbs` in logging, while the real value is an error.
