### ISSUE TITLE
juicefs panic after running for few days

### ISSUE THREAD

**Issue by penglaixy99** [juicedata/juicefs#2033]
**What happened**:
juicefs panic  afer running for 20 days and we have met this issue twices.
**What you expected to happen**:
juicefs will run for a long time without any panic
**How to reproduce it (as minimally and precisely as possible)**:
Running juicefs on a VM for a few days
**Anything else we need to know?**
We use tikv as our metadata service and juicefs version is 1.0.0-beta1 and tikv version is 2.0.0-RC
**Environment**:
- JuiceFS version  1.0.0-beta1
- Cloud provider or hardware configuration running JuiceFS:  VM (  not  baremetal machine )
-  centos-rhel-7.3.1611
- Kernel 3.10.0-514.el7.x86_64
- Object storage KS3
- Metadata  TIKV 2.0.0-RC
- Network connectivity (JuiceFS to metadata engine, JuiceFS to object storage): TCP

Panic log:

panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x220 pc=0xe2ba55]

goroutine 4160279 [running]:
google.golang.org/grpc.(*ClientConn).GetState(...)
        /root/workspace/pkg/mod/google.golang.org/grpc@v1.27.1/clientconn.go:521
github.com/tikv/client-go/v2/internal/client.(*RPCClient).SendRequest(0xc0006f9000, 0x30bdf90, 0xc0006fb3c0, 0xc0007dc0d8, 0x13, 0xc001cb37c0, 0x6fc23ac00, 0x0, 0x0, 0x0)
        /root/workspace/pkg/mod/github.com/tikv/client-go/v2@v2.0.0-rc/internal/client/client.go:410 +0x275
github.com/tikv/client-go/v2/internal/client.reqCollapse.SendRequest(0x3099cd0, 0xc0006f9000, 0x30bdf90, 0xc0006fb3c0, 0xc0007dc0d8, 0x13, 0xc001cb37c0, 0x6fc23ac00, 0x2a63640, 0x49a5201, ...)
        /root/workspace/pkg/mod/github.com/tikv/client-go/v2@v2.0.0-rc/internal/client/client_collapse.go:74 +0x12a
github.com/tikv/client-go/v2/tikv.(*KVStore).updateSafeTS.func1(0x3099cf8, 0xc0009606f0, 0xc0000c78c0, 0x30bdf90, 0xc0006fb3c0, 0xc0030e94a0, 0x6, 0xc0007dc0d8, 0x13)
        /root/workspace/pkg/mod/github.com/tikv/client-go/v2@v2.0.0-rc/tikv/kv.go:562 +0x165
created by github.com/tikv/client-go/v2/tikv.(*KVStore).updateSafeTS
        /root/workspace/pkg/mod/github.com/tikv/client-go/v2@v2.0.0-rc/tikv/kv.go:560 +0x145

**Comment by SandyXSD** [comment]
Related TiKV client-go issue: https://github.com/tikv/client-go/issues/505

**Comment by davies** [comment]
This is a bug in tikv client, we will wait for the fix from upstream.
