### ISSUE TITLE
It is strange that  the amount of entries is larger than the amount of keys when I dump the meta data.

### ISSUE THREAD

**Issue by sanwan** [juicedata/juicefs#2039]
What happened:
The amount of entries is larger than the amount of keys when I dump the meta data.
![image](https://user-images.githubusercontent.com/1523269/168977064-ef081879-b848-4370-aff5-2f61cb9a623d.png)

What you expected to happen:
The amount of entries is smaller than the amount of keys when I dump the meta data.
How to reproduce it (as minimally and precisely as possible):
Remove some files during dumping meta data.
Anything else we need to know?
I use redis cluster as my metadata service and juicefs version is 1.0.0-dev+2022-05-12.3e8ba749 
Environment:

JuiceFS version 1.0.0-dev+2022-05-12.3e8ba749
Cloud provider or hardware configuration running JuiceFS: VM ( not baremetal machine )
Ubuntu 20.04.3 LTS

**Comment by davies** [comment]
This is expected when you dump the meta data and remove files in the same time.
