### ISSUE TITLE
Show the internal information for a file or directory

### ISSUE THREAD

**Issue by davies** [juicedata/juicefs#205]
We can provide a tool to inspect the internal details of a file or directory:

```
$ ./juicefs info /jfs/syslog
/jfs/syslog:
 inodes: 	280
  directories: 	2
  files: 	278
 chunks: 	278
 length: 	654645174
 size: 		655237120

```

**Comment by 201341** [comment]
hi，I will try this, please assign it to me.

**Comment by davies** [comment]
@201341  `juicefs rmr` could be an example to follow.

**Comment by 201341** [comment]
one question about the implement is whether i can get the info through redis or just through the os library? If using the os library, the performance isn't good when there are millions files in the directory.

**Comment by davies** [comment]
I think we only need the information for current directory or a file, so performance will not be a problem. The os library will not give us the internal information, so we have to look into Redis, or call a RPC to do that (similar to `juicefs rmr`) .
