### ISSUE TITLE
sync lost file

### ISSUE THREAD

**Issue by 583373805** [juicedata/juicefs#2088]
**What happened**: 
juicefs sync two object storage(like ceph s3)，if network problem or server is not response, some files will sync fail, but no error info

**How to reproduce it (as minimally and precisely as possible)**:
example: after start juicefs sync, restart server(e.g: ceph rgw)

here is i found may problem code:
**after list success, if err is caused by network err or server not response，return nil is OK？**
![image](https://user-images.githubusercontent.com/29896516/169963914-f45983bb-ba89-4439-a07b-1b946935aaae.png)

**Comment by SandyXSD** [comment]
We probably have to check the specific error type here to see if it's an ENOENT or not.
