### ISSUE TITLE
rm failed because "error: database is locked"

### ISSUE THREAD

**Issue by sanwan** [juicedata/juicefs#2094]
**What happened**:
https://github.com/juicedata/juicefs/runs/6584156766?check_suite_focus=true
![image](https://user-images.githubusercontent.com/1523269/170168996-b8b1406b-d39c-4833-89a1-08969252ad9d.png)

2022/05/25 01:59:30.805812 juicefs[7692] <WARNING>: backup metadata skipped because of too many inodes: 4001188 1h0m0s; you mayease `--backup-meta` to enable it again [backup.go:57]
2022/05/25 01:59:47.033648 juicefs[7692] <WARNING>: Already tried 50 times, returning: database is locked [sql.go:636]
2022/05/25 01:59:47.034812 juicefs[7692] <ERROR>: error: database is locked
goroutine 4028390 [running]:
runtime/debug.Stack()
        /opt/hostedtoolcache/go/1.17.10/x64/src/runtime/debug/stack.go:24 +0x65
github.com/juicedata/juicefs/pkg/meta.errno({0x3029000, 0xc0088a3520})
        /home/runner/work/juicefs/juicefs/pkg/meta/utils.go:92 +0xc5
github.com/juicedata/juicefs/pkg/meta.(*dbMeta).doRmdir(0xc0008aba40, {0x7fab5b681090, 0xc0083c52c0}, 0x133de3f, {0xc0157502a8,)
        /home/runner/work/juicefs/juicefs/pkg/meta/sql.go:1400 +0x145
github.com/juicedata/juicefs/pkg/meta.(*baseMeta).Rmdir(0xc0008aba40, {0x7fab5b681090, 0xc0083c52c0}, 0x133de3f, {0xc0157502a8,)
        /home/runner/work/juicefs/juicefs/pkg/meta/base.go:722 +0x213
github.com/juicedata/juicefs/pkg/meta.emptyEntry({0x30e45d0, 0xc0008aba40}, {0x7fab5b681090, 0xc0083c52c0}, 0x4b5ebe0, {0xc0157, 0x4}, 0x24c0d00, 0xc00a9a8618)
        /home/runner/work/juicefs/juicefs/pkg/meta/utils.go:268 +0xa3
github.com/juicedata/juicefs/pkg/meta.emptyDir({0x30e45d0, 0xc0008aba40}, {0x7fab5b681090, 0xc0083c52c0}, 0x133de3f, 0xc0003204
        /home/runner/work/juicefs/juicefs/pkg/meta/utils.go:251 +0x3f2
github.com/juicedata/juicefs/pkg/meta.emptyEntry({0x30e45d0, 0xc0008aba40}, {0x7fab5b681090, 0xc0083c52c0}, 0x4b5ebe0, {0xc0157, 0x4}, 0x24c0d00, 0xc00a9a8590)
        /home/runner/work/juicefs/juicefs/pkg/meta/utils.go:266 +0x5c
github.com/juicedata/juicefs/pkg/meta.emptyDir({0x30e45d0, 0xc0008aba40}, {0x7fab5b681090, 0xc0083c52c0}, 0x133de3e, 0xc0003204
        /home/runner/work/juicefs/juicefs/pkg/meta/utils.go:251 +0x3f2
github.com/juicedata/juicefs/pkg/meta.emptyEntry({0x30e45d0, 0xc0008aba40}, {0x7fab5b681090, 0xc0083c52c0}, 0x4b5ebe0, {0xc0157, 0x4}, 0x24c0d00, 0xc00a9a8508)
        /home/runner/work/juicefs/juicefs/pkg/meta/utils.go:266 +0x5c
github.com/juicedata/juicefs/pkg/meta.emptyDir({0x30e45d0, 0xc0008aba40}, {0x7fab5b681090, 0xc0083c52c0}, 0x133de3d, 0xc0003204
        /home/runner/work/juicefs/juicefs/pkg/meta/utils.go:251 +0x3f2
github.com/juicedata/juicefs/pkg/meta.emptyEntry({0x30e45d0, 0xc0008aba40}, {0x7fab5b681090, 0xc0083c52c0}, 0x4b5ebe0, {0xc014d, 0x4}, 0x24c0d00, 0xc00a9a8480)
        /home/runner/work/juicefs/juicefs/pkg/meta/utils.go:266 +0x5c
github.com/juicedata/juicefs/pkg/meta.emptyDir({0x30e45d0, 0xc0008aba40}, {0x7fab5b681090, 0xc0083c52c0}, 0x133de3c, 0xc0003204
        /home/runner/work/juicefs/juicefs/pkg/meta/utils.go:251 +0x3f2
github.com/juicedata/juicefs/pkg/meta.emptyEntry({0x30e45d0, 0xc0008aba40}, {0x7fab5b681090, 0xc0083c52c0}, 0x4b5ebe0, {0xc014d, 0x4}, 0x24c0d00, 0xc00a9a83f8)
        /home/runner/work/juicefs/juicefs/pkg/meta/utils.go:266 +0x5c
github.com/juicedata/juicefs/pkg/meta.emptyDir({0x30e45d0, 0xc0008aba40}, {0x7fab5b681090, 0xc0083c52c0}, 0x133de3b, 0xc0003204
        /home/runner/work/juicefs/juicefs/pkg/meta/utils.go:251 +0x3f2
**What you expected to happen**:
I can delete the directory.
**How to reproduce it (as minimally and precisely as possible)**:
Follow the github action.

**Comment by davies** [comment]
fixed by #2102
