### ISSUE TITLE
juicefs rmr failed

### ISSUE THREAD

**Issue by sanwan** [juicedata/juicefs#2098]
**What happened**:
**juicefs rmr dir** 
2022/05/25 16:46:14.432761 juicefs[623777] <WARNING>: Already tried 50 times, returning: redis: transaction failed [redis.go:789]
2022/05/25 16:46:14.432885 juicefs[623777] <ERROR>: error: redis: transaction failed
goroutine 20506531 [running]:
runtime/debug.Stack()
        /usr/local/go/src/runtime/debug/stack.go:24 +0x65
github.com/juicedata/juicefs/pkg/meta.errno({0x3051d80, 0x3046240})
        /root/sanwan/juicefs/pkg/meta/utils.go:92 +0xc5
github.com/juicedata/juicefs/pkg/meta.(*redisMeta).doRmdir(0xc00024c500, {0x7f46c42cafb0?, 0xc0508da3c0}, 0x7fffffff10000011, {0xc05ab4c078, 0x16})
        /root/sanwan/juicefs/pkg/meta/redis.go:1389 +0x345
github.com/juicedata/juicefs/pkg/meta.(*baseMeta).Rmdir(0xc00024c500, {0x7f46c42cafb0, 0xc0508da3c0}, 0x7fffffff10000011, {0xc05ab4c078, 0x16})
        /root/sanwan/juicefs/pkg/meta/base.go:710 +0x213
github.com/juicedata/juicefs/pkg/vfs.(*VFS).Rmdir(0xc000151a40, {0x3078b40?, 0xc0508da3c0}, 0x7fffffff10000011, {0xc05ab4c078, 0x16})
        /root/sanwan/juicefs/pkg/vfs/vfs.go:200 +0x157
github.com/juicedata/juicefs/pkg/fuse.(*fileSystem).Rmdir(0xc000592180, 0xc0003edf40?, 0xc000b3fa58, {0xc05ab4c078, 0x16})
        /root/sanwan/juicefs/pkg/fuse/fuse.go:144 +0xad
github.com/hanwen/go-fuse/v2/fuse.doRmdir(0xc000b3f8c0?, 0xc000b3f8c0)
        /root/go/pkg/mod/github.com/juicedata/go-fuse/v2@v2.1.1-0.20210926080226-cfe1ec802a7f/fuse/opcode.go:361 +0x4a
github.com/hanwen/go-fuse/v2/fuse.(*Server).handleRequest(0xc00004d080, 0xc000b3f8c0)
        /root/go/pkg/mod/github.com/juicedata/go-fuse/v2@v2.1.1-0.20210926080226-cfe1ec802a7f/fuse/server.go:483 +0x1f3
github.com/hanwen/go-fuse/v2/fuse.(*Server).loop(0xc00004d080, 0x80?)
        /root/go/pkg/mod/github.com/juicedata/go-fuse/v2@v2.1.1-0.20210926080226-cfe1ec802a7f/fuse/server.go:456 +0x108
created by github.com/hanwen/go-fuse/v2/fuse.(*Server).readRequest
        /root/go/pkg/mod/github.com/juicedata/go-fuse/v2@v2.1.1-0.20210926080226-cfe1ec802a7f/fuse/server.go:323 +0x52b [utils.go:92]
2022/05/25 16:46:14.432934 juicefs[623777] <INFO>: slow operation: rmdir (9223372032828243985,20176063-20176066-aaa2): input/output error <23.126581> [accesslog.go:65]
**What you expected to happen**:
rmr should not fail
**How to reproduce it (as minimally and precisely as possible)**:
The directory has 400 children directory and 400w files.
Use juicefs rmr to delete the directory.

**Comment by davies** [comment]
Fixed by #2102
