### ISSUE TITLE
Design a JuiceFS's storage API protocol (different from S3 API) for users to implement their own backend

### ISSUE THREAD

**Issue by aofei** [juicedata/juicefs#21]
The storage layer of this project is based on object storage, which is great (I'm a big fan of this kind of usage). But it shouldn't be limited to AWS S3 or any other cloud service providers' products. It should also support users to implement and use their own custom storage backends by following a **simplified** (compared to S3 API) API protocol that belongs to JuiceFS.

**Comment by davies** [comment]
The API and implementations is current hold in juicesync, see https://github.com/juicedata/juicesync/blob/master/object/object_storage.go#L45

Currently, JuiceFS only use part of interface in  object.ObjectStorage, Get, Put and Delete should be enough for JuiceFS.

**Comment by davies** [comment]
I think we can put the interface here.
