### ISSUE TITLE
Copying a directory with 100000 empty files is very slow

### ISSUE THREAD

**Issue by zhijian-pro** [juicedata/juicefs#2178]
## reproduction steps
```
$ juicefs  format redis://localhost:6379/1  test1 
$ juicefs  mount     "redis://localhost:6379/1"  /tmp/t1 -d
$ mkdir /tmp/t1/createfile
$ cd /tmp/t1/createfile
# create 100000 empty files
# you can load this json file https://zhijian-dev.oss-cn-hangzhou.aliyuncs.com/test10w.json

$ time cp -r /tmp/t1/createfile /tmp/t1/createfile2
  cp -r createfile createfile2  2.57s user 56.47s system 8% cpu 11:23.81 total
```

**Comment by davies** [comment]
I tried this in my mac, it finished in 4.3 minutes, 
```
time cp -r ~/jfs/createfile/ ~/jfs/t3

real	4m21.729s
user	0m1.681s
sys	0m24.506s
```

The `juicefs profile` reports 4xx files/seconds, and 45% time spent in lookup. 

So it look normal here. You redis could be slow (flush every second?)

**Comment by zhijian-pro** [comment]
<img width="1269" alt="image" src="https://user-images.githubusercontent.com/31313340/172355647-ca832747-7b34-46b2-a741-69b0b6bd6f4e.png">
It's because my redis is too slow.
