### ISSUE TITLE
Remove Usage Tracking

### ISSUE THREAD

**Issue by aofei** [juicedata/juicefs#22]
For commercial products, tracking user data may be an understandable and acceptable thing. But for an open source software... well, I think this will become a very controversial behavior (even if you just collects seemingly harmless data).  I don't think people would want the JuiceFS process they run to send any data to endpoints that aren't part of their project.

Therefore, please consider removing any “tracking” behavior. ❤️

**Comment by davies** [comment]
@aofei Very good point. You can disable it with a command line argument.

So we'd like to keep it for now, to better understand how the community is using it.
