### ISSUE TITLE
out of memory when juicefs rmr on big dirs

### ISSUE THREAD

**Issue by zhoucheng361** [juicedata/juicefs#2211]
**What happened**:
when use juicefs rmr to remove several directories, each directory hav 500k files, it will OOM. juicefs process will cost 16.5G memory. 

refer to the heap in the attachment

**What you expected to happen**:
rmr should not cost much memory and [should](url) not OOM。

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**

**Environment**:
- JuiceFS version (use `juicefs --version`) or Hadoop Java SDK version:
- Cloud provider or hardware configuration running JuiceFS:
- OS (e.g `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Object storage (cloud provider and region, or self maintained):
- Metadata engine info (version, cloud provider managed or self maintained):
- Network connectivity (JuiceFS to metadata engine, JuiceFS to object storage):
- Other
[heap.zip](https://github.com/juicedata/juicefs/files/8889565/heap.zip)
s:

**Comment by davies** [comment]
Fixed by #2214
