### ISSUE TITLE
Suggest to optimize function "reorderOptions"

### ISSUE THREAD

**Issue by showjason** [juicedata/juicefs#2216]
Hi community, maybe [newArgs](https://github.com/juicedata/juicefs/blob/6d0e682b3aa5896276d95b24cd53c00b324385c5/cmd/main.go#L169) in function `reorderOptions` can be optimized, it should be declared by build-in function `make` and specify the length and capacity to reduce number of times of memory allocations。
If you also agree with me, I'd like to commit a PR :)

**Comment by davies** [comment]
The newArgs is only called once and this optimization have tiny benefits, I think we should not waste the time to optimize it.
