### ISSUE TITLE
[meta] [cleanupdeletedslice]Slice with chunkid equal to 0 should not be set slicekey and should not be deleted

### ISSUE THREAD

**Issue by penglaixy99** [juicedata/juicefs#2228]
func (m *kvMeta) doCleanupDelayedSlices(edge int64, limit int) (int, error) {
	.........
			for _, s := range ss {                                                                         ------------》 there may be slice which chunk is 0    
                                                                                                  //  added begin
                                if s.Chunkid == 0 {                    
                                       rs = append(rs, 0)
                                       continue
                                 }
                                                                                                //  added end                                        

				rs = append(rs, tx.incrBy(m.sliceKey(s.Chunkid, s.Size), -1))
			}
			tx.dels(key)
			return nil
		}); err != nil {
			logger.Warnf("Cleanup delayed slices %s: %s", key, err)
			continue
		}
		for i, s := range ss {
			if rs[i] < 0 {
				m.deleteSlice(s.Chunkid, s.Size)
				count++
			}
		}
		if count >= limit {
			break
		}
	}
	return count, nil
}

**Comment by SandyXSD** [comment]
Maybe it's better to ignore zero chunks when adding to the delayed list.

**Comment by penglaixy99** [comment]
@SandyXSD can't agree more.
