### ISSUE TITLE
fail to insert some tables into clickhouse

### ISSUE THREAD

**Issue by sanwan** [juicedata/juicefs#2230]
**What happened**:
The err log is :
Code: 76. DB::Exception: Received from localhost:9000. DB::ErrnoException. DB::ErrnoException: Cannot open file /data/jfs/store/369/369b25e4-92c5-4d83-a8bf-b2687850135f/tmp_insert_1997_41_41_0/primary.idx, errno: 4, strerror: Interrupted system call. (CANNOT_OPEN_FILE)
(query: INSERT INTO lineorder FORMAT CSV)

The juicefslog is :
2022/06/14 14:45:50.172753 juicefs[10061] <WARNING>: unexpected error for lookup: ERR user_script:4: ENOENT script: 8526c6498467f67f44755c8ba7dcdf7ea60, on @user_script:4. [redis.go:604]
2022/06/14 14:51:20.914874 juicefs[10061] <WARNING>: backup metadata failed: redis: nil [backup.go:71]
2022/06/14 15:51:41.647323 juicefs[10061] <WARNING>: backup metadata failed: redis: nil [backup.go:71]
2022/06/14 16:51:45.443258 juicefs[10061] <WARNING>: backup metadata failed: redis: nil [backup.go:71]
2022/06/14 16:58:18.486904 juicefs[10061] <INFO>: slow operation: write (142702,131072,2097152): OK <15.427945> [accesslog.go:6
2022/06/14 16:58:18.490362 juicefs[10061] <INFO>: slow operation: write (142780,131072,2490368): OK <16.662031> [accesslog.go:6
2022/06/14 16:58:18.490531 juicefs[10061] <INFO>: slow operation: write (142890,131072,1048576): OK <16.543164> [accesslog.go:6
2022/06/14 16:58:18.490812 juicefs[10061] <INFO>: slow operation: write (143025,144,0): OK <15.334842> [accesslog.go:65]
2022/06/14 16:58:18.491125 juicefs[10061] <INFO>: slow operation: write (143029,4096,0): OK <14.939281> [accesslog.go:65]
2022/06/14 16:58:18.541092 juicefs[10061] <INFO>: slow operation: write (142658,131072,4194304): OK <16.631873> [accesslog.go:6
2022/06/14 16:58:18.556340 juicefs[10061] <INFO>: slow operation: write (142633,131072,3276800): OK <15.530643> [accesslog.go:6
2022/06/14 16:58:18.571568 juicefs[10061] <INFO>: slow operation: write (143020,131072,1572864): OK <15.546056> [accesslog.go:6
2022/06/14 16:58:18.571738 juicefs[10061] <INFO>: slow operation: write (142762,131072,2097152): OK <15.449037> [accesslog.go:6

I manually do the insert opeation and the action failed again.

**What you expected to happen**:
Data was inserted successfully.
**How to reproduce it (as minimally and precisely as possible)**:
Follow the github action https://github.com/juicedata/juicefs/runs/6882779832?check_suite_focus=true .
**Anything else we need to know?**
No
**Environment**:
- JuiceFS version (use `juicefs --version`) or Hadoop Java SDK version:
release-1.0-rc1

**Comment by SandyXSD** [comment]
Possible cause: CH process consumes a lot of CPU (160%+), while the action host has only 2 cores. It makes juicefs slow to write data. Reducing the threads of CH process or size of test tables may help.

**Comment by SandyXSD** [comment]
Maybe fixed by #2324 , need confirmation

**Comment by SandyXSD** [comment]
Not reproduced for more than 2 weeks.
