### ISSUE TITLE
occurred a DataBase syntax error when run "juicefs format"

### ISSUE THREAD

**Issue by ifunjoke** [juicedata/juicefs#2237]
**What happened**:
juicefs[16466] <FATAL>: Load metadata: Error 1105: syntax error at position 23 near 'READ' [format.go:402]

**What you expected to happen**:
 Volume is formatted successful
**How to reproduce it (as minimally and precisely as possible)**:
juicefs format  mysql://username:HIDDENPASSWORD@(HIDDEN_DB_NAME.ap-northeast-2.psdb.cloud)/sqldb?tls=true mysql
**Anything else we need to know?**
PlanetScale Paas Database (MySQL branch v8.0.23)
**Environment**:
- JuiceFS version (use `juicefs --version`) or Hadoop Java SDK version:juicefs version 1.0.0-rc1+2022-06-15.0c63cd8
- Cloud provider or hardware configuration running JuiceFS: Alibaba cloud LightHouse 1Core 2G
- OS (e.g `cat /etc/os-release`):Debian GNU/Linux 9 (stretch)
- Kernel (e.g. `uname -a`):Linux iZuf64sbw5awdeew7d95bdZ 4.9.0-9-amd64  SMP Debian 4.9.168-1 (2019-04-12) x86_64 GNU/Linux
- Object storage (cloud provider and region, or self maintained): northeast(JP)
- Metadata engine info (version, cloud provider managed or self maintained): MySQL v8.0.23
- Network connectivity (JuiceFS to metadata engine, JuiceFS to object storage):HIDDEN_DB_NAME.ap-northeast-2.psdb.cloud
- Others: None

**Comment by davies** [comment]
@ifunjoke It looks like PlanetScale PaaS Database (MySQL branch v8.0.23) does not support read-only transaction, it's a feature MySQL support, can you report this to PlanetScale?

**Comment by davies** [comment]
related issue: https://github.com/vitessio/vitess/issues/3637
