### ISSUE TITLE
ltp failed

### ISSUE THREAD

**Issue by sanwan** [juicedata/juicefs#2276]
**What happened**:
<<<test_start>>>
tag=mkdir09 stime=1655452461
cmdline="mkdir09"
contacts=""
analysis=exit
<<<test_output>>>
mkdir09     1  TFAIL  :  mkdir09.c:412: MKDIR ./X.2.0, errno = 4; Wrong error detected.
mkdir09     0  TWARN  :  tst_brk__: Invalid Type: 4. Using TBROK
mkdir09     1  TBROK  :  mkdir09.c:217: 	Child{127544} exited status = 100
**What you expected to happen**:
ltp pass
**How to reproduce it (as minimally and precisely as possible)**:
Follow the action https://github.com/juicedata/juicefs/runs/6932047496?check_suite_focus=true .
**Anything else we need to know?**
No
**Environment**:
- JuiceFS version (use `juicefs --version`) or Hadoop Java SDK version:
The version is d6e18fe .

**Comment by SandyXSD** [comment]
This failure can't be reproduced, and all other runs recently have passed.
Will put it to a lower priority.

**Comment by sanwan** [comment]
The ltp test has failed three times recently as follow https://github.com/juicedata/juicefs/actions/runs/2558030511  https://github.com/juicedata/juicefs/actions/runs/2558030511  https://github.com/juicedata/juicefs/actions/runs/2544975337 .
