### ISSUE TITLE
failed to create fs on oos

### ISSUE THREAD

**Issue by enlindashuaibi** [juicedata/juicefs#2277]
**What happened**:
i can't create fs on oos 
**What you expected to happen**:
i can create fs on oos 
**How to reproduce it (as minimally and precisely as possible)**:
juicefs format --storage oos 
    --bucket https://cyn.oos-hz.ctyunapi.cn \
    --access-key xxxxxx \
    --secret-key xxxxxxx \
    redis://:Tianshu123456@172.16.0.164:6379/1 \
    myjfs
**Anything else we need to know?**

**Environment**:
- JuiceFS version (use `juicefs --version`) or Hadoop Java SDK version: juicefs version 1.0.0-beta3+2022-05-05.0fb9155
- Cloud provider or hardware configuration running JuiceFS:
- OS (e.g `cat /etc/os-release`): Centos 7
- Kernel (e.g. `uname -a`): Linux ecs-df87 3.10.0-514.el7.x86_64 #1 SMP Tue Nov 22 16:42:41 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux
- Object storage (cloud provider and region, or self maintained): oos
- Metadata engine info (version, cloud provider managed or self maintained): redis:6
- Network connectivity (JuiceFS to metadata engine, JuiceFS to object storage):
- Others:

**Comment by enlindashuaibi** [comment]
> What is the error message?

 <FATAL>: Storage oos://cyn/myjfs/ is not configured correctly: Failed to create bucket oos://cyn/myjfs/: please create bucket cyn manually, previous error: InvalidArgument: 
	status code: 400, request id: b250b13d30184014, host id:  [format.go:415]

**Comment by enlindashuaibi** [comment]
![image](https://user-images.githubusercontent.com/56947765/174697621-a5dff3ee-74b8-4a19-9c6e-e7dbb834e082.png)
![image](https://user-images.githubusercontent.com/56947765/174697774-f2a731db-6ede-4b4a-87ee-b0359f8da3b9.png)
my ak sk is right, it seem like bucket url is not  true

**Comment by enlindashuaibi** [comment]
when i use cyn.oss-hz,ctyunapi.cn it return 400 error 
![image](https://user-images.githubusercontent.com/56947765/174698044-e7836616-cd3b-4a69-a484-521b4fe835d9.png)

**Comment by enlindashuaibi** [comment]
我已经检查过了 ak/sk地区都是正确的，我看你测试用的oss-cn.ctyunapi.cn,是属于对象存储网络，但我的oos-hz.ctyunapi.cn和oos-hz.ctyunapi.cn请求地址应该不一样 我可以把我的AK/SK发给你测试下

**Comment by enlindashuaibi** [comment]
我新开了一个和你同个区域的对象存储来新建文件系统，可以成功。
![image](https://user-images.githubusercontent.com/56947765/174707867-360951d7-a1a3-4e83-88a6-006304586d0f.png)
希望后续可以看下以下地区要怎么处理
![image](https://user-images.githubusercontent.com/56947765/174707971-1225a361-5f13-4109-bf4e-b70871634b1f.png)

**Comment by enlindashuaibi** [comment]
对象存储（经典版） 开通在杭州节点，创建文件系统失败，后来又开通了上海2节点使用oos-cn.ctyunapi.cn,创建文件系统成功

**Comment by zhijian-pro** [comment]
After my test, the endpoints in all areas are `oos-cn.ctyunapi.cn`.

**Comment by zhijian-pro** [comment]
You can send me your WeChat account by djx@juicedata.io , and I can give you a remote demonstration.

**Comment by enlindashuaibi** [comment]
> You can send me your WeChat account by [djx@juicedata.io](mailto:djx@juicedata.io) , and I can give you a remote demonstration.

i have send you email with my wechat  account

**Comment by zhijian-pro** [comment]
Conclusion: for oos, the endpoints in different regions are `oos-cn.ctyunapi.cn`.
