### ISSUE TITLE
[cmd]in fsck command file, key is not setted corrrect 

### ISSUE THREAD

**Issue by penglaixy99** [juicedata/juicefs#2279]
for inode, ss := range slices {
		for _, s := range ss {
			n := (s.Size - 1) / uint32(chunkConf.BlockSize)
			for i := uint32(0); i <= n; i++ {
				sz := chunkConf.BlockSize
				if i == n {
					sz = int(s.Size) - int(i)*chunkConf.BlockSize
				}
				Key := fmt.Sprintf("%d_%d_%d", s.Chunkid, i, sz)
				if _, ok := blocks[key]; !ok {

                                      /*
                                            Add a new objKey,  Modified two lines below
                                       */
                                       objKey :=  fmt.Sprintf("%v/%v/%v_%v_%v",  s.Chunkid/1000/1000, s.Chunkid/1000,  s.Chunkid, i, sz) 
					if _, err := blob.Head(objKey); err != nil {

						if _, ok := brokens[inode]; !ok {
							if ps := meta.GetPaths(m, meta.Background, inode); len(ps) > 0 {
								brokens[inode] = ps[0]
							} else {
								brokens[inode] = fmt.Sprintf("inode:%d", inode)
							}
						}
						logger.Errorf("can't find block %s for file %s: %s", key, brokens[inode], err)
						lostDSpin.IncrInt64(int64(sz))
					}
				}
			}
			sliceCBar.Increment()
			sliceBSpin.IncrInt64(int64(s.Size))
		}
	}

**Comment by SandyXSD** [comment]
Yes, the object key is not correct for blob.
