### ISSUE TITLE
meta multiple requests

### ISSUE THREAD

**Issue by lidaohang** [juicedata/juicefs#2310]
client:
fio --name=jfs-test --directory=/jfs/ -ioengine=libaio --rw=read --bs=1m --size=1g --numjobs=1 --direct=1 --group_reporting

juicefs: 
![image](https://user-images.githubusercontent.com/4077643/175521051-2456125d-eef0-440c-ad40-daa3613b9bb0.png)

log:
![image](https://user-images.githubusercontent.com/4077643/175521099-12bf754a-bb7c-496a-8901-bbac8a4873a7.png)

**Comment by SandyXSD** [comment]
`Read` is called for each block in the chunk. It's okay since the result is cached in the openfiles.
