### ISSUE TITLE
Support Unix Domain sockets for Metadata

### ISSUE THREAD

**Issue by solracsf** [juicedata/juicefs#2313]
**What would you like to be added**:

When JuiceFS is running on standalone mode, it can be helpful to connect to metadata server trough UNIX sockets instead of TCP, at least for supported ones like (not limited to) Redis, MySQL/MariaDB. Something like:

```
mysql://unix:/run/mysqld/mysql.sock
redis://unix:/run/redis/redis.sock
```

This can be helpful in cases where servers are configured to listen on UNIX sockets only.

**Comment by davies** [comment]
TCP is portable (same address from everywhere), but unix socket is only accessible from same host, so I'd suggest that using localhost rather than UNIX socket.

**Comment by solracsf** [comment]
Sure it is, but this is not always possible in very constrained environnements where only UNIX Domain sockets are available. :(

**Comment by davies** [comment]
Why do we need this setting `skip-networking`? try to understand the use case.

**Comment by solracsf** [comment]
Systems where each nanosecond matters, like high performance financial systems where all services must communicate under UNIX sockets (apply to Redis too) to avoid the TCP overhead. JuiceFS still a good fit here because of `--writeback` and `--upload-delay` options where cache lives 100% in RAM.

**Comment by osevan** [comment]
Nice feature big thx
