### ISSUE TITLE
POSIX shared lock test from LLNL/simul fails

### ISSUE THREAD

**Issue by dianarg** [juicedata/juicefs#2323]
**What happened**:
File lock test fails with "No such file or directory".  Potentially a race condition?

**What you expected to happen**:
Test passes

**How to reproduce it (as minimally and precisely as possible)**:
- Download and build simul test from https://github.com/LLNL/simul (simple `make`)
- Run the shared lock test only with a large number of ranks:
```
mpirun -np 64 /path/to/simul -i 20 -N 2 -d /dir/under/test
```
- Output:
```
Simul is running with 64 process(es)
11:20:03: Set iteration 0
11:20:03: Running test #20(iter 0): fcntl locking, shared mode.
stale file found
11:20:03: Process 0(us01odc-1601-1-pbm014): FAILED in simul_fcntl_lock, fcntl unlock failed: No such file or directory
application called MPI_Abort(MPI_COMM_WORLD, 1) - process 0
```

**Anything else we need to know?**
Seems to pass when directory under test is a regular NFS filesystem
Relevant source code from simul can be seen here: https://github.com/LLNL/simul/blob/master/simul.c#L929-L1036

**Environment**:
- JuiceFS version (use `juicefs --version`) or Hadoop Java SDK version:  1.0.0-beta3+2022-05-05.0fb915555d
- Cloud provider or hardware configuration running JuiceFS: Intel Xeon Gold 6248 server, 1.5T memory
- OS (e.g `cat /etc/os-release`): CentOS 7
- Kernel (e.g. `uname -a`): Linux  3.10.0-1160.31.1.el7.x86_64
- Object storage (cloud provider and region, or self maintained): self maintained
- Metadata engine info (version, cloud provider managed or self maintained): self maintained
- Network connectivity (JuiceFS to metadata engine, JuiceFS to object storage): all on same node
- Others:

**Comment by dianarg** [comment]
Can anyone from the JuiceFS team point me at some alternative tests for the other POSIX features which are not covered by pjdfstest?

**Comment by SandyXSD** [comment]
We also test POSIX with:
- https://github.com/billziss-gh/secfs.test.git
- https://github.com/gofrs/flock.git
- https://github.com/linux-test-project/ltp

See [Makefile](https://github.com/juicedata/juicefs/blob/main/fstests/Makefile#L36-L43) and [LTP](https://juicefs.com/docs/community/posix_compatibility/#ltp).

**Comment by dianarg** [comment]
Thanks @SandyXSD, I confirmed the test is passing with the latest JuiceFS code.
