### ISSUE TITLE
tpcds failed

### ISSUE THREAD

**Issue by sanwan** [juicedata/juicefs#2339]
**What happened**:
tpcds failed
https://github.com/juicedata/juicefs/runs/7222488656?check_suite_focus=true
**What you expected to happen**:
tpcds passed
**How to reproduce it (as minimally and precisely as possible)**:
Follow the action.
**Anything else we need to know?**
No.

**Comment by tangyoupeng** [comment]
make it twice to avoid possible random spark executor killed failure
