### ISSUE TITLE
Hope support overlayfs upper layer on juicefs

### ISSUE THREAD

**Issue by davies** [juicedata/juicefs#2365]
### Discussed in https://github.com/juicedata/juicefs/discussions/2114

<div type='discussions-op-text'>

<sup>Originally posted by **wuyongzhi** May 10, 2022</sup>

when i create overlay fs with juicefs as upper layer, i can not create overlay fs, it got a error:

the command:
```
# mount -t overlay o1 -o lowerdir=jfs/exercises/001,upperdir=jfs/user/001,workdir=workspaces/001/work workspaces/001/merged
```

output:
```
mount: /opt/workspaces/001/merged: wrong fs type, bad option, bad superblock on o1, missing codepage or helper program, or other error
```

**What would you like to be added**:
create overlay fs with juicefs as upper layer, 

**Why is this needed**:

</div>

**Comment by SandyXSD** [comment]
Generally FUSE and network filesystems are not allowed as upper layer for overlayfs, see: https://github.com/torvalds/linux/blob/v5.4/fs/overlayfs/super.c#L754-L759 and: https://github.com/torvalds/linux/blob/v5.4/fs/overlayfs/util.c#L105.
FUSE dentry has `DCACHE_OP_REVALIDATE` flag set as it implements `d_revalidate`:
https://github.com/torvalds/linux/blob/v5.4/fs/fuse/dir.c#L301
