### ISSUE TITLE
Typo on the main page of the English version of JuiceFS

### ISSUE THREAD

**Issue by Cjcrew** [juicedata/juicefs#2369]
Hello, I couldn't find a repo of the project website so I assume it's ok for me to put this here.

As the title says just spotted a simple typo on https://juicefs.com/en/ , instead of **POSIX** its **POSXI**

![image](https://user-images.githubusercontent.com/1587015/179275758-f725070a-80cb-405e-8c21-6fcefb84c8e9.png)

**Comment by davies** [comment]
Fixed, thanks!
