### ISSUE TITLE
disallow access from root

### ISSUE THREAD

**Issue by davies** [juicedata/juicefs#2419]
### Discussed in https://github.com/juicedata/juicefs/discussions/2405

<div type='discussions-op-text'>

<sup>Originally posted by **Abssenta** July 26, 2022</sup>
Hi.

The problem I am facing with JuiceFS is that the mount point is writable by root by default. We normally avoid this for security reasons.  In normal nfs sharing, it should suffice to use root_squash in the export options. However, I don't think JuiceFS has that feature. Are there any options for mounting juicefs without root write permissions?

Thanks in advance.</div>

**Comment by SandyXSD** [comment]
Possible solution:
Add `root-squash` client option, and if enabled, map root user (uid 0) to an anonymous user (say, 65534) in fuse or meta package.

**Comment by SandyXSD** [comment]
From [exports man page](https://linux.die.net/man/5/exports):
```
root_squash
Map requests from uid/gid 0 to the anonymous uid/gid. Note that this does not apply to any other uids or gids that might be equally sensitive, such as user bin or group staff.
no_root_squash
Turn off root squashing. This option is mainly useful for diskless clients.
all_squash
Map all uids and gids to the anonymous user. Useful for NFS-exported public FTP directories, news spool directories, etc. The opposite option is no_all_squash, which is the default setting.
anonuid and anongid
These options explicitly set the uid and gid of the anonymous account. This option is primarily useful for PC/NFS clients, where you might want all requests appear to be from one user.
```
