### ISSUE TITLE
mysqlsmalltable test failed

### ISSUE THREAD

**Issue by sanwan** [juicedata/juicefs#2425]
**What happened**:
The mysqlsmalltable test failed .
**What you expected to happen**:
The mysqlsmalltable test passed .
**How to reproduce it (as minimally and precisely as possible)**:
Follow the action https://github.com/juicedata/juicefs/runs/7457515030?check_suite_focus=true .
**Anything else we need to know?**
No .

**Comment by sanwan** [comment]
The action https://github.com/juicedata/juicefs/runs/7309807324?check_suite_focus=true has some same err log as
 
Dropping table 'sbtest1'...
Dropping table 'sbtest2'...
Dropping table 'sbtest3'...
Dropping table 'sbtest4'...
Dropping table 'sbtest5'...
Dropping table 'sbtest6'...
Dropping table 'sbtest7'...
FATAL: mysql_drv_query() returned error 2013 (Lost connection to MySQL server during query) for query 'DROP TABLE IF EXISTS sbtest7'
FATAL: `cleanup' function failed: /usr/share/sysbench/oltp_common.lua:392: SQL error, errno = 2013, state = 'HY000': Lost connection to MySQL server during query

**Comment by zhijian-pro** [comment]
done by #3557
