### ISSUE TITLE
When all redis sentinels  failed,the mounted juicefs clients still can write files. 

### ISSUE THREAD

**Issue by sanwan** [juicedata/juicefs#2464]
**What would you like to be added**:
When all redis sentinels  failed, the mounted juicefs clients cannot wirte files.
**Why is this needed**:
This leads to produce  dirty data .
**Now the juicefs.log shows some errors as follows**

redis: 2022/08/04 16:11:58 sentinel.go:514: sentinel: GetMasterAddrByName master="mymaster" failed: dial tcp 127.0.0.1:46379: connect: connection refused
redis: 2022/08/04 16:12:13 sentinel.go:514: sentinel: GetMasterAddrByName master="mymaster" failed: dial tcp 127.0.0.1:26379: connect: connection refused
redis: 2022/08/04 16:12:28 sentinel.go:514: sentinel: GetMasterAddrByName master="mymaster" failed: dial tcp 127.0.0.1:36379: connect: connection refused
redis: 2022/08/04 16:12:51 sentinel.go:514: sentinel: GetMasterAddrByName master="mymaster" failed: dial tcp 127.0.0.1:46379: connect: connection refused
redis: 2022/08/04 16:12:59 sentinel.go:514: sentinel: GetMasterAddrByName master="mymaster" failed: dial tcp 127.0.0.1:26379: connect: connection refused
redis: 2022/08/04 16:13:12 sentinel.go:514: sentinel: GetMasterAddrByName master="mymaster" failed: dial tcp 127.0.0.1:36379: connect: connection refused
2022/08/04 16:13:12.806185 juicefs[95617] <ERROR>: error: redis: all sentinels specified in configuration are unreachable
goroutine 29320 [running]:
runtime/debug.Stack()
        /usr/local/go/src/runtime/debug/stack.go:24 +0x65
github.com/juicedata/juicefs/pkg/meta.errno({0x3033180, 0xc0073661d0})
        /home/pu/code/juicefs/pkg/meta/utils.go:104 +0xc5
github.com/juicedata/juicefs/pkg/meta.(*redisMeta).SetAttr(0xc0005a04b0, {0x30cd2a8, 0xc00bccf040}, 0x1070, 0x20, 0x40, 0xc007cbb540)
        /home/pu/code/juicefs/pkg/meta/redis.go:985 +0x2ac
github.com/juicedata/juicefs/pkg/vfs.(*VFS).SetAttr(0xc0009ac000, {0x30cd968, 0xc00bccf040}, 0x1070, 0x20, 0x18, 0x0, 0x0, 0x0, 0x0, ...)
        /home/pu/code/juicefs/pkg/vfs/vfs_unix.go:181 +0x349
github.com/juicedata/juicefs/pkg/fuse.(*fileSystem).SetAttr(0xc0002b5440, 0x21d7b8e, 0xc0019801b0, 0xc000817e48)
        /home/pu/code/juicefs/pkg/fuse/fuse.go:114 +0x10e
github.com/hanwen/go-fuse/v2/fuse.doSetattr(0xc000817d40, 0xc000817d40)
        /home/pu/go/pkg/mod/github.com/juicedata/go-fuse/v2@v2.1.1-0.20220720062817-183cb227b353/fuse/opcode.go:195 +0x55
github.com/hanwen/go-fuse/v2/fuse.(*Server).handleRequest(0xc0004cfb80, 0xc000817d40)
        /home/pu/go/pkg/mod/github.com/juicedata/go-fuse/v2@v2.1.1-0.20220720062817-183cb227b353/fuse/server.go:483 +0x1f3
github.com/hanwen/go-fuse/v2/fuse.(*Server).loop(0xc0004cfb80, 0x30)
        /home/pu/go/pkg/mod/github.com/juicedata/go-fuse/v2@v2.1.1-0.20220720062817-183cb227b353/fuse/server.go:456 +0x110
created by github.com/hanwen/go-fuse/v2/fuse.(*Server).readRequest
        /home/pu/go/pkg/mod/github.com/juicedata/go-fuse/v2@v2.1.1-0.20220720062817-183cb227b353/fuse/server.go:323 +0x534 [utils.go:104]
2022/08/04 16:13:12.810255 juicefs[95617] <INFO>: slow operation: setattr (4208,0x20,[mtime=1631595852]): input/output error <75.551253> [accesslog.go:65]

**Comment by zhijian-pro** [comment]
You should focus on the live status of the master rather than the sentinel.

**Comment by davies** [comment]
write() only write the data into buffers, it's OK that meta service is not available, the following close or fsync will fail with EIO (similar to the failed setattr)
