### ISSUE TITLE
ltp syscall middle test failed 

### ISSUE THREAD

**Issue by sanwan** [juicedata/juicefs#2471]
**What happened**:
https://github.com/juicedata/juicefs/runs/7347698805?check_suite_focus=true

<<<test_start>>>
tag=msync04 stime=1657831727
cmdline="msync04"
contacts=""
analysis=exit
<<<test_output>>>
tst_device.c:88: TINFO: Found free device 3 '/dev/loop3'
tst_supported_fs_types.c:89: TINFO: Kernel supports ext2
tst_supported_fs_types.c:51: TINFO: mkfs.ext2 does exist
tst_supported_fs_types.c:89: TINFO: Kernel supports ext3
tst_supported_fs_types.c:51: TINFO: mkfs.ext3 does exist
tst_supported_fs_types.c:89: TINFO: Kernel supports ext4
tst_supported_fs_types.c:51: TINFO: mkfs.ext4 does exist
tst_supported_fs_types.c:89: TINFO: Kernel supports xfs
tst_supported_fs_types.c:51: TINFO: mkfs.xfs does exist
tst_supported_fs_types.c:89: TINFO: Kernel supports btrfs
tst_supported_fs_types.c:51: TINFO: mkfs.btrfs does exist
tst_supported_fs_types.c:89: TINFO: Kernel supports vfat
tst_supported_fs_types.c:51: TINFO: mkfs.vfat does exist
tst_supported_fs_types.c:115: TINFO: Filesystem exfat is not supported
tst_supported_fs_types.c:119: TINFO: FUSE does support ntfs
tst_supported_fs_types.c:51: TINFO: mkfs.ntfs does exist
tst_supported_fs_types.c:147: TINFO: Skipping tmpfs as requested by the test
tst_test.c:1431: TINFO: Testing on ext2
tst_test.c:932: TINFO: Formatting /dev/loop3 with ext2 opts='' extra opts=''
mke2fs 1.45.5 (07-Jan-2020)
tst_test.c:1363: TINFO: Timeout per run is 0h 05m 00s
msync04.c:72: TPASS: msync() working correctly
tst_test.c:1431: TINFO: Testing on ext3
tst_test.c:932: TINFO: Formatting /dev/loop3 with ext3 opts='' extra opts=''
mke2fs 1.45.5 (07-Jan-2020)
tst_test.c:1363: TINFO: Timeout per run is 0h 05m 00s
msync04.c:72: TPASS: msync() working correctly
tst_test.c:1431: TINFO: Testing on ext4
tst_test.c:932: TINFO: Formatting /dev/loop3 with ext4 opts='' extra opts=''
mke2fs 1.45.5 (07-Jan-2020)
tst_test.c:1363: TINFO: Timeout per run is 0h 05m 00s
msync04.c:72: TPASS: msync() working correctly
tst_test.c:1431: TINFO: Testing on xfs
tst_test.c:932: TINFO: Formatting /dev/loop3 with xfs opts='' extra opts=''
tst_test.c:1363: TINFO: Timeout per run is 0h 05m 00s
msync04.c:59: TFAIL: Expected dirty bit to be set after writing to mmap()-ed area
tst_test.c:1431: TINFO: Testing on btrfs
tst_test.c:932: TINFO: Formatting /dev/loop3 with btrfs opts='' extra opts=''
tst_test.c:1363: TINFO: Timeout per run is 0h 05m 00s
msync04.c:72: TPASS: msync() working correctly
tst_test.c:1431: TINFO: Testing on vfat
tst_test.c:932: TINFO: Formatting /dev/loop3 with vfat opts='' extra opts=''
tst_test.c:1363: TINFO: Timeout per run is 0h 05m 00s
msync04.c:72: TPASS: msync() working correctly
tst_test.c:1431: TINFO: Testing on ntfs
tst_test.c:932: TINFO: Formatting /dev/loop3 with ntfs opts='' extra opts=''
The partition start sector was not specified for /dev/loop3 and it could not be obtained automatically.  It has been set to 0.
The number of sectors per track was not specified for /dev/loop3 and it could not be obtained automatically.  It has been set to 0.
The number of heads was not specified for /dev/loop3 and it could not be obtained automatically.  It has been set to 0.
To boot from a device, Windows needs the 'partition start sector', the 'sectors per track' and the 'number of heads' to be set.
Windows will not be able to boot from this device.
tst_test.c:946: TINFO: Trying FUSE...
tst_test.c:1363: TINFO: Timeout per run is 0h 05m 00s
msync04.c:72: TPASS: msync() working correctly

Summary:
passed   6
failed   1
broken   0
skipped  0
warnings 0
**What you expected to happen**:
The case passed .
**How to reproduce it (as minimally and precisely as possible)**:
Follow the action.
**Anything else we need to know?**
No.

**Comment by SandyXSD** [comment]
Not reproduced for a long time, and no error logs.
