### ISSUE TITLE
juicefs panic  when decompress data from S3

### ISSUE THREAD

**Issue by penglaixy99** [juicedata/juicefs#2495]
fatal error: unexpected signal during runtime execution
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x1cfcff8]

runtime stack:
runtime.throw({0x22d77d5, 0x441b76})
	/usr/local/go/src/runtime/panic.go:1198 +0x71
runtime.sigpanic()
	/usr/local/go/src/runtime/signal_unix.go:719 +0x396

goroutine 293287389 [syscall]:
runtime.cgocall(0x1cf8900, 0xc0038a7bb8)
	/usr/local/go/src/runtime/cgocall.go:156 +0x5c fp=0xc0038a7b90 sp=0xc0038a7b58 pc=0x41371c
github.com/hungys/go-lz4._Cfunc_LZ4_decompress_safe(0x0, 0xc012f1e000, 0x0, 0x400000)
	_cgo_gotypes.go:103 +0x4c fp=0xc0038a7bb8 sp=0xc0038a7b90 pc=0x14aa26c
github.com/hungys/go-lz4.DecompressSafe({0xc01751e000, 0x843f97, 0xc000146dd0}, {0xc012f1e000, 0xc00226e5a0, 0x0})
	/root/workspace/pkg/mod/github.com/hungys/go-lz4@v0.0.0-20170805124057-19ff7f07f099/lz4.go:73 +0x47 fp=0xc0038a7bf0 sp=0xc0038a7bb8 pc=0x14aa487
github.com/juicedata/juicefs/pkg/compress.LZ4.Decompress(...)
	/mnt/cephfs-admin/hanjiang/juicedata-server/pkg/compress/compress.go:121
github.com/juicedata/juicefs/pkg/compress.(*LZ4).Decompress(0x405e8f0, {0xc012f1e000, 0x402c4e0, 0xc0b154be895aa8c3}, {0xc01751e000, 0x402c4e0, 0x41d567})
	<autogenerated>:1 +0x5a fp=0xc0038a7c30 sp=0xc0038a7bf0 pc=0x14aafba
github.com/juicedata/juicefs/pkg/chunk.(*cachedStore).load(0xc000880d80, {0xc006e10120, 0x20}, 0xc001ff0f80, 0x1, 0x0)
	/mnt/cephfs-admin/hanjiang/juicedata-server/pkg/chunk/cached_store.go:734 +0xb96 fp=0xc0038a7f48 sp=0xc0038a7c30 pc=0x14b1196
github.com/juicedata/juicefs/pkg/chunk.(*rChunk).ReadAt.func1.1()
	/mnt/cephfs-admin/hanjiang/juicedata-server/pkg/chunk/cached_store.go:246 +0x9b fp=0xc0038a7fb0 sp=0xc0038a7f48 pc=0x14acd7b
github.com/juicedata/juicefs/pkg/utils.WithTimeout.func1()
	/mnt/cephfs-admin/hanjiang/juicedata-server/pkg/utils/utils.go:68 +0x2f fp=0xc0038a7fe0 sp=0xc0038a7fb0 pc=0x77658f
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:1581 +0x1 fp=0xc0038a7fe8 sp=0xc0038a7fe0 pc=0x479fc1
created by github.com/juicedata/juicefs/pkg/utils.WithTimeout
	/mnt/cephfs-admin/hanjiang/juicedata-server/pkg/utils/utils.go:67 +0xe5

**What happened**:

juicefs panic 

**What you expected to happen**:
data is compressed and read correctly

**How to reproduce it (as minimally and precisely as possible)**:
Sorry , I can not predict when it will panic. We have put 300TB in a bucket, and it panic when runnning after a few days. 

**Anything else we need to know?**

**Environment**:
- JuiceFS version (use `juicefs --version`) or Hadoop Java SDK version:  v1.0.0-beta3 (we added some code on this branch , but we do not modify any read/write process)
- Cloud provider or hardware configuration running JuiceFS:  bare metal ,CPU 64, 256GB
- OS (e.g `cat /etc/os-release`): centos 7
- Kernel (e.g. `uname -a`): 3.10.0-693.el7.x86_64 
- Object storage (cloud provider and region, or self maintained): ks3
- Metadata engine info (version, cloud provider managed or self maintained):tikv
- Network connectivity (JuiceFS to metadata engine, JuiceFS to object storage): TCP/IP
- Others:

**Comment by penglaixy99** [comment]
github.com/hungys/go-lz4._Cfunc_LZ4_decompress_safe(0x0, 0xc012f1e000, 0x0, 0x400000)      parameter became 0x0  ---> nil

github.com/hungys/go-lz4.DecompressSafe({0xc01751e000, 0x843f97, 0xc000146dd0}, {0xc012f1e000, 0xc00226e5a0, 0x0}  ---> not nil

github.com/juicedata/juicefs/pkg/compress.(*LZ4).Decompress(0x405e8f0, {0xc012f1e000, 0x402c4e0, 0xc0b154be895aa8c3}, {0xc01751e000, 0x402c4e0, 0x41d567})  --> not nil

I  think page is release   in some strange manner !

**Comment by penglaixy99** [comment]
I think the problem may be related to cgo  functions invoking and defer usage.

**Comment by davies** [comment]
This is caused by a failed Get from KS3, which returned 0 bytes, will fix it soon.
