### ISSUE TITLE
duplicated content in docs

### ISSUE THREAD

**Issue by timfeirg** [juicedata/juicefs#2504]
**What happened**:

some content are duplicated in the docs, like [the fstab part that I'm planning to work on](https://github.com/juicedata/juicefs/pull/2462):

<img width="689" alt="image" src="https://user-images.githubusercontent.com/4319104/184072189-32d6e5d9-5ac4-4e12-af4f-4e60f9068db0.png">

**What you expected to happen**:

knowledge should appear in the docs once and only once

**How to reproduce it (as minimally and precisely as possible)**:

look for "fstab" in the following pages:

* https://juicefs.com/docs/community/clouds/aliyun
* https://juicefs.com/docs/community/mount_juicefs_at_boot_time
...

**Comment by davies** [comment]
The docs are optimized for reader, not writer, so it normal to have duplicated content.
