### ISSUE TITLE
Prevent volume from being mounted multiple times at once

### ISSUE THREAD

**Issue by angristan** [juicedata/juicefs#251]
It looks like running `mount` multiple times will not yield any error. Although only the first `mount` will work, the other ones will keep running.

**What happened**:

```
root@jiuuce:~# ./juicefs mount -d localhost /mnt/
2021/03/15 16:55:50.148351 juicefs[2565] <INFO>: Meta address: redis://localhost
2021/03/15 16:55:50.151559 juicefs[2565] <WARNING>: AOF is not enabled, you may lose data if Redis is not shutdown properly.
2021/03/15 16:55:50.152511 juicefs[2565] <INFO>: Data use scw://juicetest/stonks/
2021/03/15 16:55:50.152974 juicefs[2565] <INFO>: Cache: /var/jfsCache/82f9475f-021d-4523-bfe4-9ce86a43d0d8 capacity: 1024 MB
2021/03/15 16:55:50.203680 juicefs[2565] <INFO>: OK, stonks is ready at /mnt/
root@jiuuce:~# ./juicefs mount -d localhost /mnt/
2021/03/15 16:55:51.080845 juicefs[2590] <INFO>: Meta address: redis://localhost
2021/03/15 16:55:51.083639 juicefs[2590] <WARNING>: AOF is not enabled, you may lose data if Redis is not shutdown properly.
2021/03/15 16:55:51.085350 juicefs[2590] <INFO>: Data use scw://juicetest/stonks/
2021/03/15 16:55:51.085683 juicefs[2590] <INFO>: Cache: /var/jfsCache/82f9475f-021d-4523-bfe4-9ce86a43d0d8 capacity: 1024 MB
2021/03/15 16:55:51.151515 juicefs[2590] <INFO>: OK, stonks is ready at /mnt/
root@jiuuce:~# ./juicefs mount -d localhost /mnt/
2021/03/15 16:55:51.953118 juicefs[2615] <INFO>: Meta address: redis://localhost
2021/03/15 16:55:51.959177 juicefs[2615] <WARNING>: AOF is not enabled, you may lose data if Redis is not shutdown properly.
2021/03/15 16:55:51.959994 juicefs[2615] <INFO>: Data use scw://juicetest/stonks/
2021/03/15 16:55:51.960515 juicefs[2615] <INFO>: Cache: /var/jfsCache/82f9475f-021d-4523-bfe4-9ce86a43d0d8 capacity: 1024 MB
2021/03/15 16:55:52.018893 juicefs[2615] <INFO>: OK, stonks is ready at /mnt/
```

```
root@jiuuce:~# ps faux | grep juicefs
root      2561  0.0  0.0   3084   824 pts/1    S+   16:55   0:00  |       \_ grep juicefs
root      2480  0.5  2.8 1361660 58956 ?       S<l  16:54   0:00 ./juicefs mount -d localhost /mnt/
root      2507  1.0  2.8 1435392 59036 ?       S<l  16:54   0:00 ./juicefs mount -d localhost /mnt/
root      2529  0.9  2.8 1288184 57384 ?       S<l  16:54   0:00 ./juicefs mount -d localhost /mnt/
```

```
Mar 15 16:54:53 jiuuce ./juicefs[2480]: juicefs[2480] <INFO>: Mounting volume stonks at /mnt/ ...
Mar 15 16:54:53 jiuuce ./juicefs[2465]: juicefs[2465] <INFO>: OK, stonks is ready at /mnt/
Mar 15 16:54:54 jiuuce ./juicefs[2491]: juicefs[2491] <INFO>: OK, stonks is ready at /mnt/
Mar 15 16:54:54 jiuuce ./juicefs[2507]: juicefs[2507] <INFO>: Mounting volume stonks at /mnt/ ...
Mar 15 16:54:54 jiuuce ./juicefs[2507]: juicefs[2507] <ERROR>: listen and serve for metrics: listen tcp :9567: bind: address already in use
Mar 15 16:54:55 jiuuce ./juicefs[2515]: juicefs[2515] <INFO>: OK, stonks is ready at /mnt/
Mar 15 16:54:55 jiuuce ./juicefs[2529]: juicefs[2529] <INFO>: Mounting volume stonks at /mnt/ ...
Mar 15 16:54:55 jiuuce ./juicefs[2529]: juicefs[2529] <ERROR>: listen and serve for metrics: listen tcp :9567: bind: address already in use
```

```
root@jiuuce:~# df -h
Filesystem      Size  Used Avail Use% Mounted on
udev            989M     0  989M   0% /dev
tmpfs           200M  5.4M  195M   3% /run
/dev/vda1        19G  838M   17G   5% /
tmpfs           997M     0  997M   0% /dev/shm
tmpfs           5.0M     0  5.0M   0% /run/lock
tmpfs           997M     0  997M   0% /sys/fs/cgroup
/dev/vda15      124M  262K  124M   1% /boot/efi
tmpfs           200M     0  200M   0% /run/user/0
JuiceFS:stonks  1.0P  257M  1.0P   1% /mnt
```

**What you expected to happen**:

I would expect an error like: `Error: volume is already mounted`.

Maybe some kind of lock system using a redis key would be useful?

**Environment**:
- JuiceFS version: `juicefs version 0.11.0-27 (2021-03-15 ddd4fda)`

**Comment by davies** [comment]
This is actually a feature rather than a bug, all the file system work like this, this could be used to upgrade JuiceFS without interrupting applications.

After it mounted, the latest process will provide service to new operations. The old ones can continue to service requests from open files. For example, the later mount will not interrupt existing `cat /jfs/.accesslog`.

**Comment by angristan** [comment]
Interesting, thanks! So if I mount a volume and run `cat /jfs/.accesslog`, then mount the volume again, I will still use the first instance of juicefs? However if I cancel the `cat` command and run it again, I will use the last instance of juicefs ?

How does it handle things like compacting slices? For example I'm reading a file on the first instance and it decides to compact slices, and then very quickly stop reading the file, mount the volume a second time and write to the file trough the second instance of juicefs while the first one is still compacting slices?

**Comment by davies** [comment]
@angristan 

> Interesting, thanks! So if I mount a volume and run `cat /jfs/.accesslog`, then mount the volume again, I will still use the first instance of juicefs? However if I cancel the `cat` command and run it again, I will use the last instance of juicefs ?

Yes.

> How does it handle things like compacting slices? For example I'm reading a file on the first instance and it decides to compact slices, and then very quickly stop reading the file, mount the volume a second time and write to the file through the second instance of juicefs while the first one is still compacting slices?

The compacting will NOT change the result of a file, the readers always see same data before and after compacting.  The two instances mounted at same mount point work the same as they are mounted in different machines. When on instance is compacting a file (replace existing slices with new one), another instance can write to file (add new slice at the end of chunk). These slices will be merged together during reading.

**Comment by angristan** [comment]
It makes sense now! Thanks for the explanation 👍
