### ISSUE TITLE
Can't format a volume in centos7

### ISSUE THREAD

**Issue by GuojieLin** [juicedata/juicefs#2513]
**What happened**:
centos7上面无法创建文件系统
```
[root@localhost data]# juicefs format --storage redis --bucket redis://10.60.45.246/0 redis://10.60.45.246/0 jfs
2022/08/12 14:16:48.977872 juicefs[1826] <INFO>: Meta address: redis://10.60.45.246/0 [interface.go:400]
2022/08/12 14:16:48.979160 juicefs[1826] <WARNING>: AOF is not enabled, you may lose data if Redis is not shutdown properly. [info.go:83]
2022/08/12 14:16:48.979404 juicefs[1826] <INFO>: Ping redis: 96.391µs [redis.go:2871]
2022/08/12 14:16:48.979846 juicefs[1826] <INFO>: Data use redis://10.60.45.246:6379/jfs/ [format.go:437]
2022/08/12 14:17:00.984420 juicefs[1826] <FATAL>: Storage redis://10.60.45.246:6379/jfs/ is not configured correctly: Failed to put: ERR wrong number of arguments for 'auth' command [format.go:440]
```
**What you expected to happen**:
可以成功创建
**How to reproduce it (as minimally and precisely as possible)**:
在centos7上面使用1.0.0和1.0.0-rc2都测试过 ，当使用redis作为元数据和对象存储时，元数据可以成功连接，数据存储连接redis会报错。
redis5.0.14和redis 7.0.4试过都不行，应该不是redis版本的问题。在window10上面使用1.0.0-rc2版本，同样的命令就可以创建成功。
下面是windows10的命令
```

C:\Users\Dm_ca\Downloads\juicefs-1.0.0-rc2-windows-amd64>juicefs format -storage redis --bucket redis://10.60.45.246/0 redis://10.60.45.246/0 jfs
2022/08/12 14:18:09.741434 juicefs[34432] <[1;34mINFO[0m>: Meta address: redis://10.60.45.246/0 [interface.go:400]
2022/08/12 14:18:09.844457 juicefs[34432] <[1;33mWARNING[0m>: AOF is not enabled, you may lose data if Redis is not shutdown properly. [info.go:83]
2022/08/12 14:18:09.852240 juicefs[34432] <[1;34mINFO[0m>: Ping redis: 6.9349ms [redis.go:2871]
2022/08/12 14:18:09.885110 juicefs[34432] <[1;34mINFO[0m>: Data use redis://10.60.45.246:6379/jfs/ [format.go:437]
2022/08/12 14:18:10.025406 juicefs[34432] <[1;34mINFO[0m>: Volume is formatted as {
  "Name": "jfs",
  "UUID": "84818aeb-828f-4c88-a167-016d22b8fc22",
  "Storage": "redis",
  "Bucket": "redis://10.60.45.246/0",
  "BlockSize": 4096,
  "Compression": "none",
  "TrashDays": 1,
  "MetaVersion": 1
} [format.go:474]
```
**Anything else we need to know?**

**Environment**::

- JuiceFS version (use `juicefs --version`) or Hadoop Java SDK version:  `juicefs version 1.0.0+2022-08-08.cf0c269`、`juicefs version 1.0.0-rc2+2022-06-24.fc6b120`
- Cloud provider or hardware configuration running JuiceFS:
- OS (e.g `cat /etc/os-release`): `CentOS Linux 7`
- Kernel (e.g. `uname -a`): `Linux localhost.localdomain 3.10.0-1127.el7.x86_64 #1 SMP Tue Mar 31 23:36:51 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux`
- Object storage (cloud provider and region, or self maintained): redis
- Metadata engine info (version, cloud provider managed or self maintained):redis
- Network connectivity (JuiceFS to metadata engine, JuiceFS to object storage): 
使用redis-cli在本机连接
```
[root@localhost data]# /data/redis-5.0.14/src/redis-cli
127.0.0.1:6379> ping
PONG
```
- Others:

**Comment by zhijian-pro** [comment]
Redis does not support user names before version 6.0, so you can't set ACCESS_KEY when it is an object store, you may have set the `ACCESS_KEY` environment variable to cause Such an error is reported.
