### ISSUE TITLE
Bad performance when using NFS over JuiceFS

### ISSUE THREAD

**Issue by huntersman** [juicedata/juicefs#2538]
**What happened**:
Bad performance when using NFS over JuiceFS 
**What you expected to happen**:
Good performance when using NFS over JuiceFS
**How to reproduce it (as minimally and precisely as possible)**:
I have two servers, one for JuiceFS and NFS server, one for NFS client.

1. create file system on JuiceFS and NFS server
```bash
juicefs format \
    --storage s3 \
    --bucket http://xxxxxxx/test \
    --access-key myAK \
    --secret-key mySK \
    redis://:password@myredis:6379/6 \
    myjfs
```
2. mount file system on JuiceFS and NFS server
```bash
nohup juicefs mount redis://:password@myredis:6379/6 /mnt/jfs &
```
3. use fio test the performance of JuiceFS 
`fio --name=sequential-write --directory=/mnt/jfs --rw=write --refill_buffers --bs=4M --size=4G --end_fsync=1`
```bash
sequential-write: (g=0): rw=write, bs=(R) 4096KiB-4096KiB, (W) 4096KiB-4096KiB, (T) 4096KiB-4096KiB, ioengine=psync, iodepth=1
fio-3.7
Starting 1 process
sequential-write: Laying out IO file (1 file / 4096MiB)
Jobs: 1 (f=1): [F(1)][100.0%][r=0KiB/s,w=0KiB/s][r=0,w=0 IOPS][eta 00m:00s]
sequential-write: (groupid=0, jobs=1): err= 0: pid=35054: Tue Aug 16 11:00:19 2022
  write: IOPS=25, BW=102MiB/s (107MB/s)(4096MiB/40248msec)
    clat (msec): min=4, max=282, avg=34.38, stdev=43.77
     lat (msec): min=4, max=282, avg=34.38, stdev=43.77
    clat percentiles (msec):
     |  1.00th=[    6],  5.00th=[    6], 10.00th=[    7], 20.00th=[    8],
     | 30.00th=[    8], 40.00th=[    8], 50.00th=[   17], 60.00th=[   21],
     | 70.00th=[   39], 80.00th=[   61], 90.00th=[   91], 95.00th=[  124],
     | 99.00th=[  215], 99.50th=[  220], 99.90th=[  279], 99.95th=[  284],
     | 99.99th=[  284]
   bw (  KiB/s): min=49053, max=385024, per=100.00%, avg=112111.28, stdev=44623.32, samples=74
   iops        : min=   11, max=   94, avg=27.24, stdev=10.93, samples=74
  lat (msec)   : 10=49.71%, 20=10.16%, 50=17.58%, 100=14.45%, 250=7.81%
  lat (msec)   : 500=0.29%
  cpu          : usr=5.55%, sys=9.98%, ctx=32789, majf=0, minf=1609
  IO depths    : 1=100.1%, 2=0.0%, 4=0.0%, 8=0.0%, 16=0.0%, 32=0.0%, >=64=0.0%
     submit    : 0=0.0%, 4=100.0%, 8=0.0%, 16=0.0%, 32=0.0%, 64=0.0%, >=64=0.0%
     complete  : 0=0.0%, 4=100.0%, 8=0.0%, 16=0.0%, 32=0.0%, 64=0.0%, >=64=0.0%
     issued rwts: total=0,1024,0,1 short=0,0,0,0 dropped=0,0,0,0
     latency   : target=0, window=0, percentile=100.00%, depth=1

Run status group 0 (all jobs):
  WRITE: bw=102MiB/s (107MB/s), 102MiB/s-102MiB/s (107MB/s-107MB/s), io=4096MiB (4295MB), run=40248-40248msec
```
4. use NFS on the folder
```bash
yum -y install nfs-utils rpcbind
vi /etc/exports
/mnt/jfs *(rw,insecure,sync,no_subtree_check,no_root_squash,fsid=0)
service rpcbind start
service nfs start
```
5. mount the folder on the NFS client server
```bash
yum -y install nfs-utils 
mkdir /mnt/share
mount -t nfs -o vers=3 myNFS:/mnt/jfs /mnt/share
```
6. use fio test the performance of NFS client folder
`fio --name=sequential-write --directory=/mnt/share --rw=write --refill_buffers --bs=4M --size=4G --end_fsync=1`
```bash
sequential-write: (g=0): rw=write, bs=(R) 4096KiB-4096KiB, (W) 4096KiB-4096KiB, (T) 4096KiB-4096KiB, ioengine=psync, iodepth=1
fio-3.7
Starting 1 process
sequential-write: Laying out IO file (1 file / 4096MiB)
Jobs: 1 (f=1): [F(1)][-.-%][r=0KiB/s,w=0KiB/s][r=0,w=0 IOPS][eta 00m:00s]
sequential-write: (groupid=0, jobs=1): err= 0: pid=17918: Wed Aug 17 09:29:44 2022
  write: IOPS=1, BW=5074KiB/s (5196kB/s)(4096MiB/826603msec)
    clat (usec): min=1511, max=3880, avg=1560.46, stdev=157.29
     lat (usec): min=1512, max=3881, avg=1560.68, stdev=157.35
    clat percentiles (usec):
     |  1.00th=[ 1516],  5.00th=[ 1516], 10.00th=[ 1532], 20.00th=[ 1532],
     | 30.00th=[ 1532], 40.00th=[ 1532], 50.00th=[ 1532], 60.00th=[ 1532],
     | 70.00th=[ 1549], 80.00th=[ 1549], 90.00th=[ 1549], 95.00th=[ 1598],
     | 99.00th=[ 2114], 99.50th=[ 2376], 99.90th=[ 3884], 99.95th=[ 3884],
     | 99.99th=[ 3884]
   bw (  MiB/s): min= 1632, max= 1784, per=100.00%, avg=1745.11, stdev=75.43, samples=4
   iops        : min=  408, max=  446, avg=436.25, stdev=18.84, samples=4
  lat (msec)   : 2=98.14%, 4=1.86%
  cpu          : usr=0.11%, sys=0.47%, ctx=179546, majf=0, minf=574
  IO depths    : 1=100.1%, 2=0.0%, 4=0.0%, 8=0.0%, 16=0.0%, 32=0.0%, >=64=0.0%
     submit    : 0=0.0%, 4=100.0%, 8=0.0%, 16=0.0%, 32=0.0%, 64=0.0%, >=64=0.0%
     complete  : 0=0.0%, 4=100.0%, 8=0.0%, 16=0.0%, 32=0.0%, 64=0.0%, >=64=0.0%
     issued rwts: total=0,1024,0,1 short=0,0,0,0 dropped=0,0,0,0
     latency   : target=0, window=0, percentile=100.00%, depth=1

Run status group 0 (all jobs):
  WRITE: bw=5074KiB/s (5196kB/s), 5074KiB/s-5074KiB/s (5196kB/s-5196kB/s), io=4096MiB (4295MB), run=826603-826603msec
```

**Anything else we need to know?**
I try to use NFS on a normal folder and the performance is good.
NFS server
```bash
mkdir /mnt/notjfs
vi /etc/exports
/mnt/notjfs *(rw,insecure,sync,no_subtree_check,no_root_squash)
```
NFS client
```bash
mount -t nfs -o vers=3 myNFS:/mnt/notjfs /mnt/notjfs
```
Test performance
`fio --name=sequential-write --directory=/mnt/notjfs --rw=write --refill_buffers --bs=4M --size=1G --end_fsync=1`
```bash
sequential-write: (g=0): rw=write, bs=(R) 4096KiB-4096KiB, (W) 4096KiB-4096KiB, (T) 4096KiB-4096KiB, ioengine=psync, iodepth=1
fio-3.7
Starting 1 process
sequential-write: Laying out IO file (1 file / 1024MiB)
Jobs: 1 (f=1): [F(1)][-.-%][r=0KiB/s,w=0KiB/s][r=0,w=0 IOPS][eta 00m:00s]
sequential-write: (groupid=0, jobs=1): err= 0: pid=16617: Wed Aug 17 13:59:03 2022
  write: IOPS=26, BW=105MiB/s (110MB/s)(1024MiB/9774msec)
    clat (usec): min=1524, max=3703, avg=1599.04, stdev=203.34
     lat (usec): min=1524, max=3705, avg=1599.23, stdev=203.42
    clat percentiles (usec):
     |  1.00th=[ 1532],  5.00th=[ 1532], 10.00th=[ 1532], 20.00th=[ 1532],
     | 30.00th=[ 1532], 40.00th=[ 1532], 50.00th=[ 1549], 60.00th=[ 1549],
     | 70.00th=[ 1565], 80.00th=[ 1598], 90.00th=[ 1680], 95.00th=[ 1827],
     | 99.00th=[ 2704], 99.50th=[ 2966], 99.90th=[ 3720], 99.95th=[ 3720],
     | 99.99th=[ 3720]
   bw (  MiB/s): min= 1704, max= 1704, per=100.00%, avg=1704.00, stdev= 0.00, samples=1
   iops        : min=  426, max=  426, avg=426.00, stdev= 0.00, samples=1
  lat (msec)   : 2=97.27%, 4=2.73%
  cpu          : usr=2.09%, sys=8.22%, ctx=19401, majf=0, minf=38
  IO depths    : 1=100.4%, 2=0.0%, 4=0.0%, 8=0.0%, 16=0.0%, 32=0.0%, >=64=0.0%
     submit    : 0=0.0%, 4=100.0%, 8=0.0%, 16=0.0%, 32=0.0%, 64=0.0%, >=64=0.0%
     complete  : 0=0.0%, 4=100.0%, 8=0.0%, 16=0.0%, 32=0.0%, 64=0.0%, >=64=0.0%
     issued rwts: total=0,256,0,1 short=0,0,0,0 dropped=0,0,0,0
     latency   : target=0, window=0, percentile=100.00%, depth=1

Run status group 0 (all jobs):
  WRITE: bw=105MiB/s (110MB/s), 105MiB/s-105MiB/s (110MB/s-110MB/s), io=1024MiB (1074MB), run=9774-9774msec
```

**Environment**:
- JuiceFS version (use `juicefs --version`) or Hadoop Java SDK version: juicefs version 1.0.0-rc3+2022-07-14.d1fe59d
- OS (e.g `cat /etc/os-release`): CentOS 7
- Kernel (e.g. `uname -a`): Linux master 3.10.0-1160.71.1.el7.x86_64
- Object storage (cloud provider and region, or self maintained): self maintained
- Metadata engine info (version, cloud provider managed or self maintained): redis 7.0.4, self maintained
- Network connectivity (JuiceFS to metadata engine, JuiceFS to object storage): I think Network connectivity is no problem.

Thanks a lot!

**Comment by solracsf** [comment]
What happens if you mont JuiceFS with `--writeback` option?
As JuiceFS is a distributed filesystem, why don't you simply mount it on every client instead of add NFS overhead?

**Comment by huntersman** [comment]
> What happens if you mont JuiceFS with `--writeback` option? As JuiceFS is a distributed filesystem, why don't you simply mount it on every client instead of add NFS overhead?

Thank you for your reply. 
I remount it with
`nohup juicefs mount --writeback redis://:password@myRedis:6379/6 /mnt/jfs &`
And test it with fio again
`fio --name=sequential-write --directory=/mnt/share --rw=write --refill_buffers --bs=4M --size=1G --end_fsync=1`
```bash
WRITE: bw=5560KiB/s (5693kB/s), 5560KiB/s-5560KiB/s (5693kB/s-5693kB/s), io=1024MiB (1074MB), run=188605-188605msec
```
It performs a little better but still not expected.

And the reason why I try to use NFS over JuiceFS is I find NFS in the architecture picture.
![image](https://user-images.githubusercontent.com/38181977/185070183-8e4db41b-cb9a-4c13-a5bb-5b40022a7f3f.png)

**Comment by SandyXSD** [comment]
This is a knows issue on CentOS 7 with 3.10 kernel. What happen here are
- 4M block is split to 1M each by NFS client
- NFS server will do `open->write->fsync->close` for every write from NFS client
- JuiceFS commits the data block to object storage whenever `fsync` or `close` is called (this means changing NFS exports option from `sync` to `async` won't help much)
- As a result, there are a lot of objects <= 1M uploaded, and JuiceFS will try to compact them to big ones, which harms the performance as well

Upgrading the kernel should help. AFAWK, kernel 5.4.0 (Ubuntu 20) with `async` NFS server can achieve good performance in this scenario, because it removes the `open / close` steps. On the other hand, you may use [`juicefs stats`](https://juicefs.com/docs/community/performance_evaluation_guide#performance-observation-and-analysis-tools) command to see more details about internal information.

**Comment by huntersman** [comment]
> This is a knows issue on CentOS 7 with 3.10 kernel. What happen here are
> 
> * 4M block is split to 1M each by NFS client
> * NFS server will do `open->write->fsync->close` for every write from NFS client
> * JuiceFS commits the data block to object storage whenever `fsync` or `close` is called (this means changing NFS exports option from `sync` to `async` won't help much)
> * As a result, there are a lot of objects <= 1M uploaded, and JuiceFS will try to compact them to big ones, which harms the performance as well
> 
> Upgrading the kernel should help. AFAWK, kernel 5.4.0 (Ubuntu 20) with `async` NFS server can achieve good performance in this scenario, because it removes the `open / close` steps. On the other hand, you may use [`juicefs stats`](https://juicefs.com/docs/community/performance_evaluation_guide#performance-observation-and-analysis-tools) command to see more details about internal information.

I'm so grateful, it works!
