### ISSUE TITLE
TestInfo 、TestFUSE and TestMySQLClient  failed

### ISSUE THREAD

**Issue by sanwan** [juicedata/juicefs#2539]
**What happened**:
Three test cases failed .
**What you expected to happen**:
All test cases passed .
**How to reproduce it (as minimally and precisely as possible)**:
Follow the actions https://github.com/juicedata/juicefs/runs/7871034723?check_suite_focus=true(TestFUSE) 、https://github.com/juicedata/juicefs/runs/7871311634?check_suite_focus=true(TestMySQLClient ) 
 and https://github.com/juicedata/juicefs/runs/7870743494?check_suite_focus=true (TestInfo).
**Anything else we need to know?**
No .

**Comment by SandyXSD** [comment]
Not reproduced for a long time.
