### ISSUE TITLE
juicefs crash when sync 

### ISSUE THREAD

**Issue by zhoucheng361** [juicedata/juicefs#2541]
**What happened**:
chengdeMacBook-Pro:scripts chengzhou$ ./juicefs sync --dirs /Users/chengzhou/Documents/juicefs2/pkg/ juicesync_dir/ --exclude ?
2022/08/17 16:00:47.516335 juicefs[58902] <INFO>: Syncing from file:///Users/chengzhou/Documents/juicefs2/pkg/ to file:///Users/chengzhou/Documents/juicefs2/.github/scripts/juicesync_dir/ [sync.go:619]
panic: match [ with chunk: syntax error in pattern

goroutine 107 [running]:
github.com/juicedata/juicefs/pkg/sync.matchKey({0xc000121ab8, 0x1, 0x0}, {0xc00005a312, 0x0})
	/Users/chengzhou/Documents/juicefs2/pkg/sync/sync.go:808 +0x365
github.com/juicedata/juicefs/pkg/sync.filter.func1()
	/Users/chengzhou/Documents/juicefs2/pkg/sync/sync.go:766 +0xb8
created by github.com/juicedata/juicefs/pkg/sync.filter
	/Users/chengzhou/Documents/juicefs2/pkg/sync/sync.go:761 +0xcf

**What you expected to happen**:
should not crash

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**

**Environment**:
- JuiceFS version (use `juicefs --version`) or Hadoop Java SDK version:
- Cloud provider or hardware configuration running JuiceFS:
- OS (e.g `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Object storage (cloud provider and region, or self maintained):
- Metadata engine info (version, cloud provider managed or self maintained):
- Network connectivity (JuiceFS to metadata engine, JuiceFS to object storage):
- Others:

**Comment by zhijian-pro** [comment]
use `./juicefs sync --dirs /Users/chengzhou/Documents/juicefs2/pkg/ juicesync_dir/ --exclude \?` 
or `./juicefs sync --dirs /Users/chengzhou/Documents/juicefs2/pkg/ juicesync_dir/ --exclude '?'`

**Comment by zhijian-pro** [comment]
It is not necessary to print stack information here.
