### ISSUE TITLE
Introduction video is not accessible

### ISSUE THREAD

**Issue by 117503445** [juicedata/juicefs#2566]
**What happened**:

I tried to watch the youtube intro [video](https://www.youtube.com/watch?v=8RdZoBG-D6Y) in the README, but the video won't play because it's a private video.

![屏幕截图 2022-08-21 235904](https://user-images.githubusercontent.com/21152034/185799881-621c4305-fe48-4299-b02a-92f9dd4e67ad.png)

**What you expected to happen**:

I can watch the video normally.

**Comment by timfeirg** [comment]
closed by https://github.com/juicedata/juicefs/pull/2568
