### ISSUE TITLE
Unimplemented opcode POLL

### ISSUE THREAD

**Issue by solracsf** [juicedata/juicefs#2590]
On `aarch64` architecture, I get this when I mount the filesystem:

```
...
<INFO>: OK, juicefs is ready at /mnt/juicefs
juicefs[83018]: Unimplemented opcode POLL
```
System is `Ubuntu 22.04.1` with Kernel `5.15.0-46-generic`

Mounting the same filesystem on a `x86_64` system doesn't output this line.

**Comment by qingyunha** [comment]
https://github.com/juicedata/juicefs/issues/2428

**Comment by solracsf** [comment]
If it is supported since 5.14, why does it trigger here, on 5.15?
https://github.com/juicedata/juicefs/issues/2428#issuecomment-1200663433

**Comment by SandyXSD** [comment]
`FALLOC_FL_ZERO_RANGE` is supported since v5.14, not `POLL`

**Comment by davies** [comment]
This log tells that JuiceFS does NOT implement POLL yet, it's OK, maybe we can hide this one.

**Comment by SandyXSD** [comment]
This log does provide meaningful information, and will only be printed for at most once. So we'll just leave it.
