### ISSUE TITLE
integration test for ioctl (immutable and appendonly)

### ISSUE THREAD

**Issue by davies** [juicedata/juicefs#2619]
We should have end-to-end test for it, may also enable those in ltp test suites.

**Comment by qingyunha** [comment]
This is a [testcase ](https://github.com/linux-test-project/ltp/blob/master/testcases/kernel/syscalls/setxattr/setxattr03.c)  -`setxattr(2) to immutable and append-only files should get EPERM`. But we forgot to check these flags in setxattr and setattr.
