### ISSUE TITLE
Support lseek to skip holes in sparse fille

### ISSUE THREAD

**Issue by davies** [juicedata/juicefs#2637]
https://github.com/torvalds/linux/commit/0b5da8db145bfd44266ac964a2636a0cf8d7c286

similar issue in glusterfs: https://bugzilla.redhat.com/show_bug.cgi?id=1220173

**Comment by Hexilee** [comment]
The `SEEK_HOLE` and `SEEK_DATA` flags should be supported by #3898. However, the GNU utils won't call `lseek` to scan source file until we return smaller `nblocks` than `size/blocksize` in `getattr`, `lookup`, `open` and `readdirplus`.  (refer to https://github.com/coreutils/coreutils/blob/master/src/copy.c#L1144)

To record the accurate data length (file size without holes), we have to store hole list in meta engine like the slice list, which costs too much resources. So we decided not to implement this feature currently.
