### ISSUE TITLE
Using sqlite3, thousands of "database is locked" warnings in logs

### ISSUE THREAD

**Issue by solracsf** [juicedata/juicefs#2645]
### Discussed in https://github.com/juicedata/juicefs/discussions/2615

<div type='discussions-op-text'>

<sup>Originally posted by **solracsf** August 28, 2022</sup>
When using Litestream, there are some parameters that can be optimized : https://litestream.io/tips/

Is there any way to pass PRAGMA parameters? Could this be an enhancement?

This would avoid lines like:

```
juicefs[634272] <WARNING>: Transaction succeeded after 3 tries (3.671605ms), inodes: [1], last error: database is locked [sql.go:654]
```
</div>

See https://github.com/mattn/go-sqlite3/blob/master/README.md#connection-string
If this is already possible, document it.

**Comment by solracsf** [comment]
I've tested a mount with

`sqlite3://juicefs.db?_journal_mode=WAL&_busy_timeout=5000&_synchronous=NORMAL`

and it seem to work flawlessly.

**Comment by solracsf** [comment]
Let me add this here that could help for a better handling of these:
https://github.com/mattn/go-sqlite3/issues/632#issuecomment-450585303

**Comment by davies** [comment]
Can you add `-q` to ignore these warning?

**Comment by solracsf** [comment]
Why hide them instead of avoid them? 🥴

**Comment by oguzhane** [comment]
@solracsf have you sorted out this issue ? If so, how ?

**Comment by solracsf** [comment]
Not using sqlite anymore sorry
