### ISSUE TITLE
add cache for download in unittest.

### ISSUE THREAD

**Issue by zhoucheng361** [juicedata/juicefs#2648]
**What would you like to be added**:

**Why is this needed**:

**Comment by zhijian-pro** [comment]
Don't miss hdfs
https://github.com/juicedata/juicefs/blob/bdc4178dacb725a0f61dfeda0fbf3a3ef1619ff6/travis-setup-hdfs.sh#L23

**Comment by zhijian-pro** [comment]
<img width="993" alt="image" src="https://user-images.githubusercontent.com/31313340/187621261-149797c8-2c2b-4a9c-b0c4-9f0cc716f189.png">
<img width="2191" alt="image" src="https://user-images.githubusercontent.com/31313340/187621426-d65cc178-4ea8-47dc-8afc-d418a00b74e5.png">

Maybe there's no need to optimize, it's already very fast.

**Comment by davies** [comment]
Fixed by https://github.com/juicedata/juicefs/pull/2630 ?
