### ISSUE TITLE
ltpsyscall sync01 and fanotify15 failed

### ISSUE THREAD

**Issue by sanwan** [juicedata/juicefs#2669]
**What happened**:
The cases of sync01  and fanotify15 failed.
**What you expected to happen**:
The cases passed.
**How to reproduce it (as minimally and precisely as possible)**:
Follow the actions https://github.com/juicedata/juicefs/runs/8171934207?check_suite_focus=true (sync01) and https://github.com/juicedata/juicefs/runs/8079423200?check_suite_focus=true(fanotify15) .
**Anything else we need to know?**
No .

**Comment by SandyXSD** [comment]
```
tst_test.c:1431: TINFO: Testing on ext2
tst_test.c:932: TINFO: Formatting /dev/loop3 with ext2 opts='' extra opts=''
mke2fs 1.45.5 (07-Jan-2020)
Error: The action has timed out.
```
Probably the same issue as #2414

**Comment by SandyXSD** [comment]
Duplicated
