### ISSUE TITLE
There is a lot of metadata accessing the cache file system when JuiceFS is idle

### ISSUE THREAD

**Issue by wutz** [juicedata/juicefs#2688]
**What happened**:

There is a lot of metadata (getattr) accessing the cache file system when JuiceFS is idle

**What you expected to happen**:

The cache file system also has no I/O access when JuiceFS is idle

**How to reproduce it (as minimally and precisely as possible)**:

1. Use shared network file system as juicefs cache-dir
2. Mount juicefs on multiple nodes
3. Do some write or read data
4. Wait juicefs idle

**Anything else we need to know?**

1. We use a shared network filesystem (Lustre) as juicefs cache-dir with writeback enabled
2. Mount juicefs on almost 40 nodes
3. JuiceFS idle stats (usage 40% CPU)

```
---------usage--------- ----------fuse--------- -------------meta------------ -blockcache ---------------------object--------------------
 cpu   mem   buf  cache| ops   lat   read write| ops   lat   txn   lat  retry| read write| get  get_c  lat   put  put_c  lat  del_c  lat
 0.0%  182M    0     0 |   0     0     0     0 |   0     0     0     0     0 |   0     0 |   0     0     0     0     0     0     0     0
42.6%  182M    0     0 |  11  3.74     0     0 |   3  2.61     0     0     0 |   0     0 |   0     0     0     0     0     0     0     0
42.5%  182M    0     0 |  10  0.49     0     0 |   0     0     0     0     0 |   0     0 |   0     0     0     0     0     0     0     0
43.1%  182M    0     0 |  11  0.62     0     0 |   1  1.98     0     0     0 |   0     0 |   0     0     0     0     0     0     0     0
42.1%  182M    0     0 |  10  0.48     0     0 |   0     0     0     0     0 |   0     0 |   0     0     0     0     0     0     0     0
43.2%  182M    0     0 |  11  0.66     0     0 |   2  2.94     0     0     0 |   0     0 |   0     0     0     0     0     0     0     0
43.8%  182M    0     0 |  10  0.49     0     0 |   0     0     2  5.30     0 |   0     0 |   0     0     0     0     0     0     0     0
41.7%  182M    0     0 |  11  0.62     0     0 |   1  2.14     0     0     0 |   0     0 |   0     0     0     0     0     0     0     0
```

4. JuiceFS idle `strace -f -p <pid>` output

```
[pid 281073] newfstatat(AT_FDCWD, "/HOME/jfs/cache/d5fb3b63-2886-4e99-a0c3-02da286c66d1/raw/chunks/0/702/702800_0_118620",  <unfinished ...>
[pid 280971] nanosleep({tv_sec=0, tv_nsec=20000}, NULL) = 0
[pid 280971] futex(0x4c2f6b8, FUTEX_WAIT_PRIVATE, 0, {tv_sec=0, tv_nsec=79181964} <unfinished ...>
[pid 281073] <... newfstatat resumed>{st_mode=S_IFREG|0600, st_size=118620, ...}, AT_SYMLINK_NOFOLLOW) = 0
[pid 281073] futex(0x4c2f6b8, FUTEX_WAKE_PRIVATE, 1) = 1
[pid 280971] <... futex resumed>)       = 0
[pid 281073] newfstatat(AT_FDCWD, "/HOME/jfs/cache/d5fb3b63-2886-4e99-a0c3-02da286c66d1/raw/chunks/0/702/702801_0_76284",  <unfinished ...>
[pid 280971] nanosleep({tv_sec=0, tv_nsec=20000}, NULL) = 0
[pid 280971] futex(0x4c2f6b8, FUTEX_WAIT_PRIVATE, 0, {tv_sec=0, tv_nsec=78284141} <unfinished ...>
[pid 281073] <... newfstatat resumed>{st_mode=S_IFREG|0600, st_size=76284, ...}, AT_SYMLINK_NOFOLLOW) = 0
[pid 281073] futex(0x4c2f6b8, FUTEX_WAKE_PRIVATE, 1) = 1
[pid 280971] <... futex resumed>)       = 0
[pid 281073] newfstatat(AT_FDCWD, "/HOME/jfs/cache/d5fb3b63-2886-4e99-a0c3-02da286c66d1/raw/chunks/0/702/702802_0_101891",  <unfinished ...>
[pid 280971] nanosleep({tv_sec=0, tv_nsec=20000}, NULL) = 0
[pid 280971] futex(0x4c2f6b8, FUTEX_WAIT_PRIVATE, 0, {tv_sec=0, tv_nsec=77334217} <unfinished ...>
[pid 281073] <... newfstatat resumed>{st_mode=S_IFREG|0600, st_size=101891, ...}, AT_SYMLINK_NOFOLLOW) = 0
[pid 281073] futex(0x4c2f6b8, FUTEX_WAKE_PRIVATE, 1) = 1
[pid 280971] <... futex resumed>)       = 0
[pid 281073] newfstatat(AT_FDCWD, "/HOME/jfs/cache/d5fb3b63-2886-4e99-a0c3-02da286c66d1/raw/chunks/0/702/702803_0_11977",  <unfinished ...>
[pid 280971] nanosleep({tv_sec=0, tv_nsec=20000}, NULL) = 0
[pid 280971] futex(0x4c2f6b8, FUTEX_WAIT_PRIVATE, 0, {tv_sec=0, tv_nsec=76487289} <unfinished ...>
[pid 281073] <... newfstatat resumed>{st_mode=S_IFREG|0600, st_size=11977, ...}, AT_SYMLINK_NOFOLLOW) = 0
[pid 281073] futex(0x4c2f6b8, FUTEX_WAKE_PRIVATE, 1) = 1
[pid 280971] <... futex resumed>)       = 0
```

**Environment**:
- JuiceFS version (use `juicefs --version`) or Hadoop Java SDK version: juicefs version 1.0.0+2022-08-08.cf0c269
- Cloud provider or hardware configuration running JuiceFS: 128Cores CPU, 512G Mem 
- OS (e.g `cat /etc/os-release`): CentOS Linux 7
- Kernel (e.g. `uname -a`): 3.10.0-1160.25.1.el7_lustre.x86_64
- Object storage (cloud provider and region, or self maintained): Ceph RGW
- Metadata engine info (version, cloud provider managed or self maintained): TiKV
- Network connectivity (JuiceFS to metadata engine, JuiceFS to object storage): 25Gbps ETH
- Others:

**Comment by solracsf** [comment]
I agree; load on a MySQL with idle (but mounted, of course) file system is insane.

**Comment by davies** [comment]
@wutz JuiceFS scans cached blocks in every 5 minutes, because the cache-dir is expected to be a local disk, we will make that configurable and reduce the default frequency (once in a hour).

@solracsf The one you said is different, can you create another PR for it?

**Comment by wutz** [comment]
What is the purpose of scanning cache-dir? Is it possible to configure to allow only one client to scan? In addition, will the scan read each file size, because accessing the size in Lustre is very expensive, and Lustre may not be suitable for shared cache.

**Comment by davies** [comment]
In general, It's not recommended to use a shared disk for cache.

Without scanning, the client can't use the blocks created by other client, because of the in-memory index of cached blocks.

**Comment by wutz** [comment]
Will juicefs scan it regularly when using local cache-dir?

**Comment by SandyXSD** [comment]
Yes, and it's expected to be cheap when on a local disk.
