### ISSUE TITLE
 Fetch all metadata from DB: Error 1054: Unknown column 'id' in 'field list' [main.go:31]

### ISSUE THREAD

**Issue by zhoucheng361** [juicedata/juicefs#2717]
**What happened**:

chengdeMacBook-Pro:scripts chengzhou$ ./juicefs-1.0.0-beta1 format mysql://root:root@\(127.0.0.1\)/test test-volume --block-size 1 --compress lz4 --shards 0 --storage minio --capacity 0 --inodes 1048576 --trash-days 0 --bucket http://localhost:9000/test-bucket --access-key minioadmin --secret-key minioadmin --debug
2022/09/10 12:12:23.277279 juicefs[31526] <INFO>: Meta address: mysql://root@(127.0.0.1)/test
[xorm] [info]  2022/09/10 12:12:23.277536 PING DATABASE mysql
2022/09/10 12:12:23.281378 juicefs[31526] <WARNING>: The latency to database is too high: 3.852224ms
2022/09/10 12:12:23.281574 juicefs[31526] <DEBUG>: Creating minio storage at endpoint http://localhost:9000/test-bucket
2022/09/10 12:12:23.281725 juicefs[31526] <INFO>: Data use minio://localhost:9000/test-bucket/test-volume/
2022/09/10 12:12:23.484646 juicefs[31526] <INFO>: Volume is formatted as {Name:test-volume UUID:44ce4f18-f653-4520-8da5-e9e59b121118 Storage:minio Bucket:http://localhost:9000/test-bucket AccessKey:minioadmin SecretKey:removed BlockSize:64 Compression:lz4 Shards:0 Partitions:0 Capacity:0 Inodes:1048576 EncryptKey: TrashDays:0}
chengdeMacBook-Pro:scripts chengzhou$ ./juicefs-1.1.0-dev dump mysql://root:root@\(127.0.0.1\)/test dump.json --debug
2022/09/10 12:13:00.009102 juicefs[31536] <INFO>: Meta address: mysql://root:****@(127.0.0.1)/test [interface.go:402]
[xorm] [info]  2022/09/10 12:13:00.013110 PING DATABASE mysql
2022/09/10 12:13:00.019658 juicefs[31536] <WARNING>: The latency to database is too high: 7.232269ms [sql.go:203]
2022/09/10 12:13:00.029276 juicefs[31536] <FATAL>: Fetch all metadata from DB: Error 1054: Unknown column 'id' in 'field list' [main.go:31]

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**
https://github.com/juicedata/juicefs/runs/8281855468?check_suite_focus=true

**Environment**:
- JuiceFS version (use `juicefs --version`) or Hadoop Java SDK version:
- Cloud provider or hardware configuration running JuiceFS:
- OS (e.g `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Object storage (cloud provider and region, or self maintained):
- Metadata engine info (version, cloud provider managed or self maintained):
- Network connectivity (JuiceFS to metadata engine, JuiceFS to object storage):
- Others:

**Comment by SandyXSD** [comment]
It's expected since `dump` is supposed to be a read-only operation.
You have to mount the volume with `juicefs-1.1.0-dev` once to make later `dump` work.
