### ISSUE TITLE
FATAL should be in red color

### ISSUE THREAD

**Issue by zhoucheng361** [juicedata/juicefs#2722]
**What happened**:
FATAL is not in red color. 

<img width="1440" alt="image" src="https://user-images.githubusercontent.com/100545994/189476670-c0f216d6-b020-44cd-91f3-667876b1076f.png">

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**

**Environment**:
- JuiceFS version (use `juicefs --version`) or Hadoop Java SDK version:
- Cloud provider or hardware configuration running JuiceFS:
- OS (e.g `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Object storage (cloud provider and region, or self maintained):
- Metadata engine info (version, cloud provider managed or self maintained):
- Network connectivity (JuiceFS to metadata engine, JuiceFS to object storage):
- Others:

**Comment by qingyunha** [comment]
The log at the beginning and at the end both have no color seems use a lower version juicefs (0.17.1?).

**Comment by zhoucheng361** [comment]
> The log at the beginning and at the end both have no color seems use a lower version juicefs (0.17.1?).

you are right!
