### ISSUE TITLE
Another process is using this Badger database. error: resource temporarily unavailable

### ISSUE THREAD

**Issue by zhoucheng361** [juicedata/juicefs#2727]
**What happened**:

chengdeMacBook-Pro:scripts chengzhou$ ./test7.sh 
Removed `myminio/test-bucket` successfully.
2022/09/12 12:29:02.246578 juicefs[20978] <INFO>: Meta address: badger://badger-47d932eaf26a4e958a1a472dfb2aeeca [interface.go:402]
2022/09/12 12:29:02.281237 badger[20978] <INFO>: All 0 tables opened in 0s [logger.go:46]
2022/09/12 12:29:02.292085 badger[20978] <INFO>: Discard stats nextEmptySlot: 0 [logger.go:46]
2022/09/12 12:29:02.292208 badger[20978] <INFO>: Set nextTxnTs to 0 [logger.go:46]
2022/09/12 12:29:02.292880 juicefs[20978] <DEBUG>: Creating minio storage at endpoint http://localhost:9000/test-bucket [object_storage.go:154]
2022/09/12 12:29:02.293042 juicefs[20978] <INFO>: Data use minio://localhost:9000/test-bucket/test-volume/ [format.go:435]
2022/09/12 12:29:02.458383 juicefs[20978] <DEBUG>: Iterating objects from minio://localhost:9000/test-bucket/test-volume/ start "" [sync.go:78]
2022/09/12 12:29:02.458510 juicefs[20978] <DEBUG>: Listing objects from minio://localhost:9000/test-bucket/test-volume/ marker "" [sync.go:117]
2022/09/12 12:29:02.468634 juicefs[20978] <DEBUG>: Found 0 object from minio://localhost:9000/test-bucket/test-volume/ in 10.264174ms [sync.go:123]
2022/09/12 12:29:02.493972 juicefs[20978] <INFO>: Volume is formatted as {
  "Name": "test-volume",
  "UUID": "fc14e922-4f9d-4ad1-82b3-951f4fc84fb4",
  "Storage": "minio",
  "Bucket": "http://localhost:9000/test-bucket",
  "AccessKey": "minioadmin",
  "SecretKey": "removed",
  "BlockSize": 512,
  "Compression": "lz4",
  "Shards": 1,
  "HashPrefix": true,
  "Capacity": 201863462912,
  "Inodes": 1048576,
  "KeyEncrypted": true,
  "TrashDays": 782,
  "MetaVersion": 1
} [format.go:472]
2022/09/12 12:29:02.558150 juicefs[20983] <INFO>: Meta address: badger://badger-47d932eaf26a4e958a1a472dfb2aeeca [interface.go:402]
2022/09/12 12:29:02.570595 badger[20983] <INFO>: All 0 tables opened in 0s [logger.go:46]
2022/09/12 12:29:02.580172 badger[20983] <INFO>: Discard stats nextEmptySlot: 0 [logger.go:46]
2022/09/12 12:29:02.580249 badger[20983] <INFO>: Set nextTxnTs to 1 [logger.go:46]
2022/09/12 12:29:02.581943 juicefs[20983] <WARNING>: delayed upload only work in writeback mode [mount.go:413]
2022/09/12 12:29:02.582058 juicefs[20983] <DEBUG>: Creating minio storage at endpoint http://localhost:9000/test-bucket [object_storage.go:154]
2022/09/12 12:29:02.582441 juicefs[20983] <INFO>: Data use minio://localhost:9000/test-bucket/test-volume/ [mount.go:422]
2022/09/12 12:29:02.582951 badger[20983] <INFO>: Lifetime L0 stalled for: 0s [logger.go:46]
2022/09/12 12:29:02.591858 badger[20983] <INFO>: 
Level 0 [ ]: NumTables: 01. Size: 677 B of 0 B. Score: 0.00->0.00 StaleData: 0 B Target FileSize: 64 MiB
Level 1 [ ]: NumTables: 00. Size: 0 B of 10 MiB. Score: 0.00->0.00 StaleData: 0 B Target FileSize: 2.0 MiB
Level 2 [ ]: NumTables: 00. Size: 0 B of 10 MiB. Score: 0.00->0.00 StaleData: 0 B Target FileSize: 2.0 MiB
Level 3 [ ]: NumTables: 00. Size: 0 B of 10 MiB. Score: 0.00->0.00 StaleData: 0 B Target FileSize: 2.0 MiB
Level 4 [ ]: NumTables: 00. Size: 0 B of 10 MiB. Score: 0.00->0.00 StaleData: 0 B Target FileSize: 2.0 MiB
Level 5 [ ]: NumTables: 00. Size: 0 B of 10 MiB. Score: 0.00->0.00 StaleData: 0 B Target FileSize: 2.0 MiB
Level 6 [B]: NumTables: 00. Size: 0 B of 10 MiB. Score: 0.00->0.00 StaleData: 0 B Target FileSize: 2.0 MiB
Level Done [logger.go:46]
2022/09/12 12:29:03.105335 juicefs[20983] <INFO>: OK, test-volume is ready at /tmp/sync-test/ [mount_unix.go:45]
status
2022/09/12 12:29:03.192670 juicefs[21001] <INFO>: Meta address: badger://badger-47d932eaf26a4e958a1a472dfb2aeeca [interface.go:402]
2022/09/12 12:29:03.193044 juicefs[21001] <FATAL>: Meta badger://badger-47d932eaf26a4e958a1a472dfb2aeeca is not available: connect to addr badger-47d932eaf26a4e958a1a472dfb2aeeca: Cannot acquire directory lock on "badger-47d932eaf26a4e958a1a472dfb2aeeca".  Another process is using this Badger database. error: resource temporarily unavailable [interface.go:409]

chengdeMacBook-Pro:scripts chengzhou$ cat test7.sh 
umount /tmp/sync-test
rm -rf badger-47d932eaf26a4e958a1a472dfb2aeeca
mc rb myminio/test-bucket --force
set -e 

./juicefs-1.0.0 format badger://badger-47d932eaf26a4e958a1a472dfb2aeeca test-volume --block-size 775 --compress lz4 --shards 1 --storage minio --hash-prefix --capacity 188 --inodes 1048576 --trash-days 782 --no-update --bucket http://localhost:9000/test-bucket --access-key minioadmin --secret-key minioadmin --debug
./juicefs-1.0.0 mount -d badger://badger-47d932eaf26a4e958a1a472dfb2aeeca /tmp/sync-test/ --no-syslog --log ~/.juicefs/juicefs.log --attr-cache 1 --entry-cache 1 --dir-entry-cache 1 --get-timeout 30 --put-timeout 31 --io-retries 6 --max-uploads 2 --max-deletes 2 --buffer-size 100 --upload-limit 0 --download-limit 0 --prefetch 1 --upload-delay 2 --cache-dir ~/.juicefs/cache1 --cache-size 0 --free-space-ratio 0.10000000000000002 --backup-meta 300 --heartbeat 6 --read-only --open-cache 1 --metrics 127.0.0.1:9567 --consul 127.0.0.1:8500 --no-usage-report --debug
echo status
./juicefs-1.0.0 status badger://badger-47d932eaf26a4e958a1a472dfb2aeeca

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**

**Environment**:
- JuiceFS version (use `juicefs --version`) or Hadoop Java SDK version:
- Cloud provider or hardware configuration running JuiceFS:
- OS (e.g `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Object storage (cloud provider and region, or self maintained):
- Metadata engine info (version, cloud provider managed or self maintained):
- Network connectivity (JuiceFS to metadata engine, JuiceFS to object storage):
- Others:

**Comment by SandyXSD** [comment]
It's a limitation of Badger, which only allows at most one connection.
