### ISSUE TITLE
ltp utime03 failed

### ISSUE THREAD

**Issue by sanwan** [juicedata/juicefs#2735]
**What happened**:
<<<test_start>>>
tag=utime03 stime=166[29294](https://github.com/juicedata/juicefs/actions/runs/3033251477/jobs/4881352459#step:10:29295)34
cmdline="utime03"
contacts=""
analysis=exit
<<<test_output>>>
tst_device.c:88: TINFO: Found free device 3 '/dev/loop3'
tst_supported_fs_types.c:89: TINFO: Kernel supports ext2
tst_supported_fs_types.c:51: TINFO: mkfs.ext2 does exist
tst_supported_fs_types.c:89: TINFO: Kernel supports ext3
tst_supported_fs_types.c:51: TINFO: mkfs.ext3 does exist
tst_supported_fs_types.c:89: TINFO: Kernel supports ext4
tst_supported_fs_types.c:51: TINFO: mkfs.ext4 does exist
tst_supported_fs_types.c:89: TINFO: Kernel supports xfs
tst_supported_fs_types.c:51: TINFO: mkfs.xfs does exist
tst_supported_fs_types.c:89: TINFO: Kernel supports btrfs
tst_supported_fs_types.c:51: TINFO: mkfs.btrfs does exist
tst_supported_fs_types.c:147: TINFO: Skipping vfat as requested by the test
tst_supported_fs_types.c:147: TINFO: Skipping exfat as requested by the test
tst_supported_fs_types.c:119: TINFO: FUSE does support ntfs
tst_supported_fs_types.c:51: TINFO: mkfs.ntfs does exist
tst_supported_fs_types.c:89: TINFO: Kernel supports tmpfs
tst_supported_fs_types.c:38: TINFO: mkfs is not needed for tmpfs
tst_test.c:1431: TINFO: Testing on ext2
tst_test.c:932: TINFO: Formatting /dev/loop3 with ext2 opts='' extra opts=''
mke2fs 1.45.5 (07-Jan-2020)
tst_test.c:1363: TINFO: Timeout per run is 0h 05m 00s
utime03.c:76: TPASS: utime(TEMP_FILE, NULL) passed
tst_test.c:1431: TINFO: Testing on ext3
tst_test.c:932: TINFO: Formatting /dev/loop3 with ext3 opts='' extra opts=''
mke2fs 1.45.5 (07-Jan-2020)
tst_test.c:1363: TINFO: Timeout per run is 0h 05m 00s
utime03.c:76: TPASS: utime(TEMP_FILE, NULL) passed
tst_test.c:1431: TINFO: Testing on ext4
tst_test.c:932: TINFO: Formatting /dev/loop3 with ext4 opts='' extra opts=''
mke2fs 1.45.5 (07-Jan-2020)
tst_test.c:1363: TINFO: Timeout per run is 0h 05m 00s
utime03.c:76: TPASS: utime(TEMP_FILE, NULL) passed
tst_test.c:1431: TINFO: Testing on xfs
tst_test.c:932: TINFO: Formatting /dev/loop3 with xfs opts='' extra opts=''
tst_test.c:1363: TINFO: Timeout per run is 0h 05m 00s
utime03.c:76: TPASS: utime(TEMP_FILE, NULL) passed
tst_test.c:1431: TINFO: Testing on btrfs
tst_test.c:932: TINFO: Formatting /dev/loop3 with btrfs opts='' extra opts=''
tst_test.c:1363: TINFO: Timeout per run is 0h 05m 00s
utime03.c:76: TPASS: utime(TEMP_FILE, NULL) passed
tst_test.c:1431: TINFO: Testing on ntfs
tst_test.c:932: TINFO: Formatting /dev/loop3 with ntfs opts='' extra opts=''
The partition start sector was not specified for /dev/loop3 and it could not be obtained automatically.  It has been set to 0.
The number of sectors per track was not specified for /dev/loop3 and it could not be obtained automatically.  It has been set to 0.
The number of heads was not specified for /dev/loop3 and it could not be obtained automatically.  It has been set to 0.
To boot from a device, Windows needs the 'partition start sector', the 'sectors per track' and the 'number of heads' to be set.
Windows will not be able to boot from this device.
tst_test.c:946: TINFO: Trying FUSE...
tst_test.c:1363: TINFO: Timeout per run is 0h 05m 00s
utime03.c:76: TPASS: utime(TEMP_FILE, NULL) passed
utime03.c:82: TFAIL: utime() did not set expected atime
utime03.c:85: TFAIL: utime() did not set expected mtime
tst_test.c:1431: TINFO: Testing on tmpfs
tst_test.c:932: TINFO: Skipping mkfs for TMPFS filesystem
tst_test.c:913: TINFO: Limiting tmpfs size to 32MB
tst_test.c:1363: TINFO: Timeout per run is 0h 05m 00s
utime03.c:76: TPASS: utime(TEMP_FILE, NULL) passed

Summary:
passed   7
failed   2
broken   0
skipped  0
warnings 0
<<<execution_status>>>
initiation_status="ok"
duration=33 termination_type=exited termination_id=1 corefile=no
cutime=11 cstime=90
<<<test_end>>>
**What you expected to happen**:
The case passed .
**How to reproduce it (as minimally and precisely as possible)**:
Follow the action https://github.com/juicedata/juicefs/actions/runs/3033251477/jobs/4881352459 .
**Anything else we need to know?**
No .

**Comment by SandyXSD** [comment]
Duplicated with #2415
