### ISSUE TITLE
 Read message: 0 EOF when warmup

### ISSUE THREAD

**Issue by zhoucheng361** [juicedata/juicefs#2739]
**What happened**:
chengdeMacBook-Pro:scripts chengzhou$ cat test_warmup.sh 
mysql -uroot -proot -h localhost -P 3306 -e "drop database if exists test; create database test;"
mc rb myminio/test-bucket --force
set -e
./juicefs-1.0.0-beta1 format mysql://root:root@\(127.0.0.1\)/test test-volume --block-size 28904 --compress lz4 --shards 0 --storage minio --capacity 23 --inodes 1092875 --trash-days 8716 --no-update --bucket http://localhost:9000/test-bucket --access-key minioadmin --secret-key minioadmin --debug
./juicefs-1.1.0-dev mount -d mysql://root:root@\(127.0.0.1\)/test /tmp/sync-test/ --no-syslog --log /Users/chengzhou/.juicefs/juicefs.log --attr-cache 3 --entry-cache 5 --dir-entry-cache 10 --get-timeout 53 --put-timeout 34 --io-retries 5 --max-uploads 62 --max-deletes 1 --buffer-size 965 --upload-limit 517 --download-limit 787 --prefetch 84 --upload-delay 0 --cache-dir /Users/chengzhou/.juicefs/cache1 --cache-size 944916 --free-space-ratio 0.5 --backup-meta 1000 --heartbeat 5 --no-bgjob --open-cache 1 --metrics 127.0.0.1:9568 --no-usage-report --debug
./juicefs-1.0.0-beta1 warmup --threads 100 /tmp/sync-test/file.list --debug

chengdeMacBook-Pro:scripts chengzhou$ ./test_warmup.sh 
mysql: [Warning] Using a password on the command line interface can be insecure.
Removed `myminio/test-bucket` successfully.
2022/09/13 20:40:31.638598 juicefs[17679] <INFO>: Meta address: mysql://root@(127.0.0.1)/test
[xorm] [info]  2022/09/13 20:40:31.638913 PING DATABASE mysql
2022/09/13 20:40:31.645131 juicefs[17679] <WARNING>: The latency to database is too high: 6.235892ms
2022/09/13 20:40:31.645944 juicefs[17679] <DEBUG>: Creating minio storage at endpoint http://localhost:9000/test-bucket
2022/09/13 20:40:31.646043 juicefs[17679] <INFO>: Data use minio://localhost:9000/test-bucket/test-volume/
2022/09/13 20:40:31.919640 juicefs[17679] <INFO>: Volume is formatted as {Name:test-volume UUID:11e9fd24-3d43-4e3b-8b25-adc4b566b948 Storage:minio Bucket:http://localhost:9000/test-bucket AccessKey:minioadmin SecretKey:removed BlockSize:16384 Compression:lz4 Shards:0 Partitions:0 Capacity:24696061952 Inodes:1092875 EncryptKey: TrashDays:8716}
2022/09/13 20:40:31.982721 juicefs[17680] <INFO>: Meta address: mysql://root:****@(127.0.0.1)/test [interface.go:411]
[xorm] [info]  2022/09/13 20:40:31.983089 PING DATABASE mysql
2022/09/13 20:40:31.989595 juicefs[17680] <WARNING>: The latency to database is too high: 6.518202ms [sql.go:216]
2022/09/13 20:40:31.992139 juicefs[17680] <DEBUG>: Creating minio storage at endpoint http://localhost:9000/test-bucket [object_storage.go:154]
2022/09/13 20:40:31.992328 juicefs[17680] <INFO>: Data use minio://localhost:9000/test-bucket/test-volume/ [mount.go:518]
2022/09/13 20:40:31.992828 juicefs[17680] <INFO>: Disk cache (/Users/chengzhou/.juicefs/cache1/11e9fd24-3d43-4e3b-8b25-adc4b566b948/): capacity (944916 MB), free ratio (50%), max pending pages (12) [disk_cache.go:100]
2022/09/13 20:40:31.992942 juicefs[17680] <DEBUG>: Scan /Users/chengzhou/.juicefs/cache1/11e9fd24-3d43-4e3b-8b25-adc4b566b948/rawstaging to find staging blocks [disk_cache.go:546]
2022/09/13 20:40:31.992934 juicefs[17680] <DEBUG>: Scan /Users/chengzhou/.juicefs/cache1/11e9fd24-3d43-4e3b-8b25-adc4b566b948/raw to find cached blocks [disk_cache.go:503]
2022/09/13 20:40:31.993022 juicefs[17680] <DEBUG>: Found 0 cached blocks (0 bytes) in /Users/chengzhou/.juicefs/cache1/11e9fd24-3d43-4e3b-8b25-adc4b566b948/ with 115.688µs [disk_cache.go:531]
2022/09/13 20:40:32.496016 juicefs[17680] <INFO>: OK, test-volume is ready at /tmp/sync-test/ [mount_unix.go:45]
2022/09/13 20:40:32.728348 juicefs[17694] <FATAL>: Read message: 0 EOF

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**

**Environment**:
- JuiceFS version (use `juicefs --version`) or Hadoop Java SDK version:
- Cloud provider or hardware configuration running JuiceFS:
- OS (e.g `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Object storage (cloud provider and region, or self maintained):
- Metadata engine info (version, cloud provider managed or self maintained):
- Network connectivity (JuiceFS to metadata engine, JuiceFS to object storage):
- Others:

**Comment by davies** [comment]
This is expected, old client can't work with a mount point with new version.
