### ISSUE TITLE
session list is empty when status with 0.17.1

### ISSUE THREAD

**Issue by zhoucheng361** [juicedata/juicefs#2740]
**What happened**:

chengdeMacBook-Pro:scripts chengzhou$ cat test_session.sh 
umount /tmp/sync-test
redis-cli flushall
mc rb myminio/test-bucket --force

set -e
./juicefs-0.17.1 format redis://localhost/1 test-volume --block-size 27650 --compress lz4 --shards 1 --storage minio --capacity 1 --inodes 919928833 --force --no-update --bucket http://localhost:9000/test-bucket --access-key minioadmin --secret-key minioadmin --debug
./juicefs-1.1.0-dev mount -d redis://localhost/1 /tmp/sync-test/ --no-syslog --log ~/.juicefs/juicefs.log --attr-cache 1 --entry-cache 4 --dir-entry-cache 8 --get-timeout 41 --put-timeout 49 --io-retries 10 --max-uploads 1 --max-deletes 36 --buffer-size 352 --upload-limit 565 --download-limit 391 --prefetch 34 --writeback --upload-delay 0 --cache-dir ~/.juicefs/cache1 --cache-size 330757 --free-space-ratio 0.10000000000000002 --backup-meta 705 --heartbeat 11 --open-cache 1 --metrics 127.0.0.1:9567 --no-usage-report --debug
./juicefs-1.1.0-dev status redis://localhost/1 
./juicefs-0.17.1 status redis://localhost/1 

chengdeMacBook-Pro:scripts chengzhou$ ./test_session.sh 
OK
Removed `myminio/test-bucket` successfully.
2022/09/13 21:49:06.147683 juicefs[18473] <INFO>: Meta address: redis://localhost/1
2022/09/13 21:49:06.152556 juicefs[18473] <WARNING>: AOF is not enabled, you may lose data if Redis is not shutdown properly.
2022/09/13 21:49:06.152809 juicefs[18473] <INFO>: Ping redis: 152.891µs
2022/09/13 21:49:06.154177 juicefs[18473] <DEBUG>: Creating minio storage at endpoint http://localhost:9000/test-bucket
2022/09/13 21:49:06.154444 juicefs[18473] <INFO>: Data use minio://localhost:9000/test-bucket/test-volume/
2022/09/13 21:49:06.293411 juicefs[18473] <INFO>: Volume is formatted as {Name:test-volume UUID:db7afac0-76bd-437c-9e50-d37249bb1106 Storage:minio Bucket:http://localhost:9000/test-bucket AccessKey:minioadmin SecretKey:removed BlockSize:16384 Compression:lz4 Shards:1 Partitions:0 Capacity:1073741824 Inodes:919928833 EncryptKey:}
2022/09/13 21:49:06.371507 juicefs[18474] <INFO>: Meta address: redis://localhost/1 [interface.go:411]
2022/09/13 21:49:06.374327 juicefs[18474] <WARNING>: AOF is not enabled, you may lose data if Redis is not shutdown properly. [info.go:83]
2022/09/13 21:49:06.374492 juicefs[18474] <INFO>: Ping redis: 91.342µs [redis.go:2932]
2022/09/13 21:49:06.375046 juicefs[18474] <DEBUG>: Creating minio storage at endpoint http://localhost:9000/test-bucket [object_storage.go:154]
2022/09/13 21:49:06.375206 juicefs[18474] <INFO>: Data use minio://localhost:9000/test-bucket/test-volume/ [mount.go:518]
2022/09/13 21:49:06.375643 juicefs[18474] <INFO>: Disk cache (/Users/chengzhou/.juicefs/cache1/db7afac0-76bd-437c-9e50-d37249bb1106/): capacity (330757 MB), free ratio (10%), max pending pages (4) [disk_cache.go:100]
2022/09/13 21:49:06.375765 juicefs[18474] <DEBUG>: Scan /Users/chengzhou/.juicefs/cache1/db7afac0-76bd-437c-9e50-d37249bb1106/raw to find cached blocks [disk_cache.go:503]
2022/09/13 21:49:06.375823 juicefs[18474] <DEBUG>: Found 0 cached blocks (0 bytes) in /Users/chengzhou/.juicefs/cache1/db7afac0-76bd-437c-9e50-d37249bb1106/ with 90.335µs [disk_cache.go:531]
2022/09/13 21:49:06.375772 juicefs[18474] <DEBUG>: Scan /Users/chengzhou/.juicefs/cache1/db7afac0-76bd-437c-9e50-d37249bb1106/rawstaging to find staging blocks [disk_cache.go:546]
2022/09/13 21:49:06.879198 juicefs[18474] <INFO>: OK, test-volume is ready at /tmp/sync-test/ [mount_unix.go:45]
2022/09/13 21:49:06.947961 juicefs[18488] <INFO>: Meta address: redis://localhost/1 [interface.go:411]
2022/09/13 21:49:06.952479 juicefs[18488] <WARNING>: AOF is not enabled, you may lose data if Redis is not shutdown properly. [info.go:83]
2022/09/13 21:49:06.952699 juicefs[18488] <INFO>: Ping redis: 131.117µs [redis.go:2932]
{
  "Setting": {
    "Name": "test-volume",
    "UUID": "db7afac0-76bd-437c-9e50-d37249bb1106",
    "Storage": "minio",
    "Bucket": "http://localhost:9000/test-bucket",
    "AccessKey": "minioadmin",
    "SecretKey": "removed",
    "BlockSize": 16384,
    "Compression": "lz4",
    "Shards": 1,
    "Capacity": 1073741824,
    "Inodes": 919928833
  },
  "Sessions": [
    {
      "Sid": 1,
      "Expire": "2022-09-13T21:50:01+08:00",
      "Version": "1.1.0-dev+2022-09-13.ec9d8004",
      "HostName": "chengdeMacBook-Pro.local",
      "MountPoint": "/tmp/sync-test",
      "ProcessID": 18482
    }
  ]
}
2022/09/13 21:49:07.011008 juicefs[18492] <INFO>: Meta address: redis://localhost/1
2022/09/13 21:49:07.014642 juicefs[18492] <WARNING>: AOF is not enabled, you may lose data if Redis is not shutdown properly.
2022/09/13 21:49:07.014772 juicefs[18492] <INFO>: Ping redis: 89.007µs
{
  "Setting": {
    "Name": "test-volume",
    "UUID": "db7afac0-76bd-437c-9e50-d37249bb1106",
    "Storage": "minio",
    "Bucket": "http://localhost:9000/test-bucket",
    "AccessKey": "minioadmin",
    "SecretKey": "removed",
    "BlockSize": 16384,
    "Compression": "lz4",
    "Shards": 1,
    "Partitions": 0,
    "Capacity": 1073741824,
    "Inodes": 919928833
  },
  "Sessions": []
}

**What you expected to happen**:
Sessions should not be empty when status with 0.17.1

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**

**Environment**:
- JuiceFS version (use `juicefs --version`) or Hadoop Java SDK version:
- Cloud provider or hardware configuration running JuiceFS:
- OS (e.g `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Object storage (cloud provider and region, or self maintained):
- Metadata engine info (version, cloud provider managed or self maintained):
- Network connectivity (JuiceFS to metadata engine, JuiceFS to object storage):
- Others:

**Comment by davies** [comment]
this is expected, old client can't see new session.
