### ISSUE TITLE
mac: mount again after mount doesn't work

### ISSUE THREAD

**Issue by zhoucheng361** [juicedata/juicefs#2755]
**What happened**:

chengdeMacBook-Pro:scripts chengzhou$ cat ./test_fsck2.sh 
umount /tmp/sync-test
echo "delall --yes" |tcli -pd localhost:2379
mc rb myminio/test-bucket --force
set -e

./juicefs-1.0.0-rc1 format redis://localhost/1 test-volume --block-size 1637 --compress lz4 --shards 0 --storage minio --capacity 211 --inodes 1051137 --trash-days 8228 --force --bucket http://localhost:9000/test-bucket --access-key minioadmin --secret-key minioadmin --debug
./juicefs-1.0.0-rc1 mount -d redis://localhost/1 /tmp/sync-test/ --log ~/.juicefs/juicefs.log -o debug,allow_other,writeback_cache --enable-xattr --attr-cache 5 --entry-cache 2 --dir-entry-cache 5 --get-timeout 39 --put-timeout 45 --io-retries 10 --max-uploads 55 --max-deletes 64 --buffer-size 480 --upload-limit 347 --download-limit 280 --prefetch 1 --upload-delay 2 --cache-dir ~/.juicefs/cache1 --cache-size 388039 --free-space-ratio 0.5 --backup-meta 553 --heartbeat 7 --read-only --open-cache 59 --metrics 127.0.0.1:9567 --no-usage-report --debug
./juicefs-1.0.0-rc1 mount -d redis://localhost/1 /tmp/sync-test/ --log ~/.juicefs/juicefs.log -o writeback_cache,debug --attr-cache 5 --entry-cache 8 --dir-entry-cache 4 --get-timeout 50 --put-timeout 39 --io-retries 15 --max-uploads 96 --max-deletes 32 --buffer-size 406 --upload-limit 849 --download-limit 646 --prefetch 59 --writeback --upload-delay 0 --cache-dir ~/.juicefs/cache1 --cache-size 1 --free-space-ratio 0.3774125676432615 --backup-meta 698 --heartbeat 10 --no-bgjob --open-cache 63 --metrics 127.0.0.1:9567 --no-usage-report --debug
echo abc>/tmp/sync-test/abc.info

chengdeMacBook-Pro:scripts chengzhou$ ./test_fsck2.sh 
Removed `myminio/test-bucket` successfully.
2022/09/14 16:47:28.863350 juicefs[54754] <INFO>: Meta address: redis://localhost/1 [interface.go:397]
2022/09/14 16:47:28.867507 juicefs[54754] <WARNING>: AOF is not enabled, you may lose data if Redis is not shutdown properly. [info.go:83]
2022/09/14 16:47:28.867708 juicefs[54754] <INFO>: Ping redis: 111.393µs [redis.go:2869]
2022/09/14 16:47:28.868110 juicefs[54754] <DEBUG>: Creating minio storage at endpoint http://localhost:9000/test-bucket [object_storage.go:154]
2022/09/14 16:47:28.868274 juicefs[54754] <INFO>: Data use minio://localhost:9000/test-bucket/test-volume/ [format.go:420]
2022/09/14 16:47:29.016824 juicefs[54754] <WARNING>: Existing volume will be overwrited: {Name:test-volume UUID:44bb207c-da77-4567-963d-2277b2c7cfdc Storage:minio Bucket:http://localhost:9000/test-bucket AccessKey:minioadmin SecretKey:removed BlockSize:1024 Compression:lz4 Shards:0 HashPrefix:true Capacity:226559524864 Inodes:1051137 EncryptKey: KeyEncrypted:true TrashDays:8228 MetaVersion:1 MinClientVersion: MaxClientVersion:} [config.go:69]
2022/09/14 16:47:29.017227 juicefs[54754] <INFO>: Volume is formatted as {Name:test-volume UUID:44bb207c-da77-4567-963d-2277b2c7cfdc Storage:minio Bucket:http://localhost:9000/test-bucket AccessKey:minioadmin SecretKey:removed BlockSize:1024 Compression:lz4 Shards:0 HashPrefix:true Capacity:226559524864 Inodes:1051137 EncryptKey: KeyEncrypted:true TrashDays:8228 MetaVersion:1 MinClientVersion: MaxClientVersion:} [format.go:458]
2022/09/14 16:47:29.093914 juicefs[54759] <INFO>: Meta address: redis://localhost/1 [interface.go:397]
2022/09/14 16:47:29.098699 juicefs[54759] <WARNING>: AOF is not enabled, you may lose data if Redis is not shutdown properly. [info.go:83]
2022/09/14 16:47:29.098878 juicefs[54759] <INFO>: Ping redis: 108.11µs [redis.go:2869]
2022/09/14 16:47:29.099526 juicefs[54759] <WARNING>: delayed upload only work in writeback mode [mount.go:411]
2022/09/14 16:47:29.099600 juicefs[54759] <DEBUG>: Creating minio storage at endpoint http://localhost:9000/test-bucket [object_storage.go:154]
2022/09/14 16:47:29.099845 juicefs[54759] <INFO>: Data use minio://localhost:9000/test-bucket/test-volume/ [mount.go:420]
2022/09/14 16:47:29.100082 juicefs[54759] <INFO>: Disk cache (/Users/chengzhou/.juicefs/cache1/44bb207c-da77-4567-963d-2277b2c7cfdc/): capacity (388039 MB), free ratio (50%), max pending pages (96) [disk_cache.go:90]
2022/09/14 16:47:29.100223 juicefs[54759] <DEBUG>: Scan /Users/chengzhou/.juicefs/cache1/44bb207c-da77-4567-963d-2277b2c7cfdc/rawstaging to find staging blocks [disk_cache.go:519]
2022/09/14 16:47:29.100233 juicefs[54759] <DEBUG>: Scan /Users/chengzhou/.juicefs/cache1/44bb207c-da77-4567-963d-2277b2c7cfdc/raw to find cached blocks [disk_cache.go:478]
2022/09/14 16:47:29.100305 juicefs[54759] <DEBUG>: Found 0 cached blocks (0 bytes) in /Users/chengzhou/.juicefs/cache1/44bb207c-da77-4567-963d-2277b2c7cfdc/ with 123.268µs [disk_cache.go:506]
2022/09/14 16:47:29.603053 juicefs[54759] <INFO>: OK, test-volume is ready at /tmp/sync-test/ [mount_unix.go:45]
2022/09/14 16:47:29.678117 juicefs[54776] <WARNING>: /tmp/sync-test/ is already mounted by juicefs, maybe you should umount it first. [mount.go:275]
2022/09/14 16:47:29.678355 juicefs[54776] <INFO>: Meta address: redis://localhost/1 [interface.go:397]
2022/09/14 16:47:29.683005 juicefs[54776] <WARNING>: AOF is not enabled, you may lose data if Redis is not shutdown properly. [info.go:83]
2022/09/14 16:47:29.683301 juicefs[54776] <INFO>: Ping redis: 182.579µs [redis.go:2869]
2022/09/14 16:47:29.684343 juicefs[54776] <DEBUG>: Creating minio storage at endpoint http://localhost:9000/test-bucket [object_storage.go:154]
2022/09/14 16:47:29.684617 juicefs[54776] <INFO>: Data use minio://localhost:9000/test-bucket/test-volume/ [mount.go:420]
2022/09/14 16:47:29.684804 juicefs[54776] <INFO>: Disk cache (/Users/chengzhou/.juicefs/cache1/44bb207c-da77-4567-963d-2277b2c7cfdc/): capacity (1 MB), free ratio (37%), max pending pages (81) [disk_cache.go:90]
2022/09/14 16:47:29.685025 juicefs[54776] <DEBUG>: Scan /Users/chengzhou/.juicefs/cache1/44bb207c-da77-4567-963d-2277b2c7cfdc/raw to find cached blocks [disk_cache.go:478]
2022/09/14 16:47:29.685106 juicefs[54776] <DEBUG>: Found 0 cached blocks (0 bytes) in /Users/chengzhou/.juicefs/cache1/44bb207c-da77-4567-963d-2277b2c7cfdc/ with 154.848µs [disk_cache.go:506]
2022/09/14 16:47:29.685091 juicefs[54776] <DEBUG>: Scan /Users/chengzhou/.juicefs/cache1/44bb207c-da77-4567-963d-2277b2c7cfdc/rawstaging to find staging blocks [disk_cache.go:519]
2022/09/14 16:47:30.189452 juicefs[54776] <INFO>: OK, test-volume is ready at /tmp/sync-test/ [mount_unix.go:45]
./test_fsck2.sh: line 9: /tmp/sync-test/abc.info: Read-only file system

chengdeMacBook-Pro:scripts chengzhou$ tail -f ~/.juicefs/juicefs.log 
2022/09/14 16:43:58.207860 juicefs[54698] <DEBUG>: Creating minio storage at endpoint http://localhost:9000/test-bucket [object_storage.go:154]
2022/09/14 16:43:58.208203 juicefs[54698] <INFO>: Data use minio://localhost:9000/test-bucket/test-volume/ [mount.go:420]
2022/09/14 16:43:58.208409 juicefs[54698] <INFO>: Disk cache (/Users/chengzhou/.juicefs/cache1/5adad976-db8a-4f2f-b622-2e401d98c4ff/): capacity (1 MB), free ratio (37%), max pending pages (81) [disk_cache.go:90]
2022/09/14 16:43:58.208551 juicefs[54698] <DEBUG>: Scan /Users/chengzhou/.juicefs/cache1/5adad976-db8a-4f2f-b622-2e401d98c4ff/raw to find cached blocks [disk_cache.go:478]
2022/09/14 16:43:58.208583 juicefs[54698] <DEBUG>: Scan /Users/chengzhou/.juicefs/cache1/5adad976-db8a-4f2f-b622-2e401d98c4ff/rawstaging to find staging blocks [disk_cache.go:519]
2022/09/14 16:43:58.208675 juicefs[54698] <DEBUG>: Found 0 cached blocks (0 bytes) in /Users/chengzhou/.juicefs/cache1/5adad976-db8a-4f2f-b622-2e401d98c4ff/ with 145.653µs [disk_cache.go:506]
2022/09/14 16:43:58.215371 juicefs[54698] <INFO>: Create session 1 OK with version: 1.0.0-rc1+2022-06-15.0c63cd8 [base.go:209]
2022/09/14 16:43:58.216256 juicefs[54698] <ERROR>: listen on 127.0.0.1:9567 failed: listen tcp 127.0.0.1:9567: bind: address already in use [mount.go:142]
2022/09/14 16:43:58.216415 juicefs[54698] <INFO>: Mounting volume test-volume at /tmp/sync-test ... [mount_unix.go:181]
2022/09/14 16:43:58.216493 juicefs[54698] <WARNING>: setpriority: permission denied [fuse.go:419]
2022-09-14 16:43:58.228911 I | rx 33: STATFS n1 
2022-09-14 16:43:58.230503 I | tx 33:     OK, {blocks (55312384,55312384)/55312384 files 1051137/1051137 bs4096 nl255 frs4096}
2022-09-14 16:43:58.236315 I | rx 26: STATFS n1 
2022-09-14 16:43:58.237777 I | tx 26:     OK, {blocks (55312384,55312384)/55312384 files 1051137/1051137 bs4096 nl255 frs4096}
2022-09-14 16:43:58.504722 I | rx 2: LOOKUP n1 ["abc.info"] 9b
2022-09-14 16:43:58.505807 I | tx 2:     2=no such file or directory, {n0 g0 tE=0s tA=0s {M00 SZ=0 L=0 0:0 0 0:0 A 0.000000 M 0.000000 C 0.000000}}
2022-09-14 16:43:58.505998 I | rx 14: CREATE n1 {0100644 [RDWR,CREAT,EXCL]} ["abc.info"] 9b
2022-09-14 16:43:58.506113 I | tx 14:     30=read-only file system, {n0 g0 {M00 SZ=0 L=0 0:0 0 0:0 A 0.000000 M 0.000000 C 0.000000} &{0 0 0}}
**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**

**Environment**:
- JuiceFS version (use `juicefs --version`) or Hadoop Java SDK version:
- Cloud provider or hardware configuration running JuiceFS:
- OS (e.g `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Object storage (cloud provider and region, or self maintained):
- Metadata engine info (version, cloud provider managed or self maintained):
- Network connectivity (JuiceFS to metadata engine, JuiceFS to object storage):
- Others:

**Comment by SandyXSD** [comment]
It looks like we can't mount again on Mac. Maybe it's a limitation of macFUSE, but I'm not sure, and will set this with low priority.

**Comment by SandyXSD** [comment]
Mount again with the same juicefs on the same mount point is also disabled on Linux by #2979
