### ISSUE TITLE
StorjDCS compatibility and their `ListObjects` implementation

### ISSUE THREAD

**Issue by solracsf** [juicedata/juicefs#2764]
**What happened**:

[Docs states a compatibility with StorjDCS](https://juicefs.com/docs/community/how_to_setup_object_storage/#storj-dcs) but there is, at least, a problem with [their `ListObjects` implementation](https://github.com/storj/gateway-st/blob/main/docs/s3-compatibility.md#listobjects) API.

It can be verified with `juicefs objbench` command, it will output:
`<ERROR>: The keys are out of order: marker "", last "96" current "12" [sync.go:132]`

This will, at least, impact `fsck` or `gc` commands as they both call `ListObjects`.

**How to reproduce it (as minimally and precisely as possible)**:
Create a free StorjDCS account and run `juicefs objbench` on it.

---
See also https://github.com/juicedata/juicefs/issues/1655

**Comment by SandyXSD** [comment]
Also #1755.
We'd better update the doc.
