### ISSUE TITLE
It's possible to create new entry under a removed directory

### ISSUE THREAD

**Issue by SandyXSD** [juicedata/juicefs#2774]
**What happened**:
Client A: rmdir /jfs/test (succeed since test is an empty directory, and it's moved to trash)
Client B: touch /jfs/test/a (usually it will fail, but if the entry cache says `/jfs/test` exits, this op will succeed because we only check s the existence of the attribute of `/jfs/test`, which is true)

**What you expected to happen**:
Touch on Client B failed.

**Environment**:
- JuiceFS version (use `juicefs --version`) or Hadoop Java SDK version: v1.0.0

**Comment by tangyoupeng** [comment]
#3737
