### ISSUE TITLE
Use jfs too much disk usage in k8s and obs

### ISSUE THREAD

**Issue by eudore** [juicedata/juicefs#2777]
**What happened**:
Deploying three copies of Kafka runs for 8 hours, creating 89G jfsCache and 120G obs files, and the k8s cluster fluctuates several times.

Enter the container kafka-0 /kafka directory space is 1.1G
Server node3 /var/jfsCache space is 89G
Server node4 /var/jfsCache space is 32G
obs used space is 120.91 GB
3pv volume pod consumes 5-8G of memory, see jfs-memory for memory usage
09:00-16:00 prometheus oom twice, the monitoring graph data is lost for two segments.
There is a continuous increase in the cpu of the business container. In the cpu diagram, the green line continues to increase, and then a new copy of the yellow line is manually added. After the load balancer removes the green line, it returns to zero, and the sending container restarts around 14:30.

logs and images: [jfs-disk 20220916.zip](https://github.com/juicedata/juicefs/files/9582710/jfs-disk.20220916.zip)

**Environment**:
- JuiceFS version (use `juicefs --version`) or Hadoop Java SDK version:
        jfs is deleted
        image: juicedata/juicefs-csi-driver:v0.17.0
        image: quay.io/k8scsi/csi-provisioner:v1.6.0
        image: quay.io/k8scsi/livenessprobe:v1.1.0
        image: juicedata/juicefs-csi-driver:v0.17.0
        image: quay.io/k8scsi/csi-node-driver-registrar:v2.1.0
        image: quay.io/k8scsi/livenessprobe:v1.1.0

- Cloud provider or hardware configuration running JuiceFS:
  16vCPUs | 64GiB |  huawei cloud c6.4xlarge.4
- OS (e.g `cat /etc/os-release`):
   centos7 
- Kernel (e.g. `uname -a`):
  Linux n3.prod.kailinesb.com 3.10.0-1160.49.1.el7.x86_64 1 SMP Tue Nov 30 15:51:32 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
- Object storage (cloud provider and region, or self maintained):
  huawei cloud obs
- Metadata engine info (version, cloud provider managed or self maintained):
  mysql5.7
- K8s version
 Server Version: version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.1", GitCommit:"86ec240af8cbd1b60bcc4c03c20da9b98005b92e", GitTreeState:"clean", BuildDate:"2021-12-16T11:34:54Z", GoVersion:"go1.17.5", Compiler:"gc", Platform:"linux/amd64"}

**Comment by SandyXSD** [comment]
You'd better disable trash if your application does a lot of deletion or overwriting.
See: https://juicefs.com/docs/community/security/trash/#cautions

**Comment by eudore** [comment]
updated format options is `trash-days=0`, retry running kafka.

**Comment by SandyXSD** [comment]
@eudore Hello, is there any update?

**Comment by eudore** [comment]
Cleaned up obs recycling files yesterday; re-deployed pvc today for three hours.
Everything is normal at present, and jfsCache is also recycled normally, thank you.
