### ISSUE TITLE
Storj+Windows+MySQL的环境下，执行遇到报错。

### ISSUE THREAD

**Issue by jetwong88** [juicedata/juicefs#2779]
执行命令：
juicefs format --storage jetstorj --bucket https://xxxxx.storjshare.io --access-key xxxxxxxxxxxxxxxxxxxxxxxx --secret-key xxxxxxxxxxxxxxxxxxxxxxxx  mysql://xxxxx:xxxxxxxxx@(xxxxxxxxx:xxxx)/xxxxxx jetstorj

返回提示：
 <INFO>: Meta address: mysql://xxxxx:****@(xxxxxxxxxxxx:xxxxx)/xxxxxx [interface.go:402]
 <WARNING>: The latency to database is too high: 54.4312ms [sql.go:203]

错误提示：<FATAL>: object storage: invalid storage: jetstorj [format.go:433]

提示无效存储的错误，有点摸不清楚问题在哪。

**Comment by SandyXSD** [comment]
You need to use `s3` storage type for Storj.
https://juicefs.com/docs/zh/community/how_to_setup_object_storage#storj-dcs
