### ISSUE TITLE
MinIO Gateway deprecation

### ISSUE THREAD

**Issue by JonMerlevede** [juicedata/juicefs#2784]
[JuiceFS S3 Gateway](https://juicefs.com/docs/community/s3_gateway/) is based on MinIO Gateway, which is, unfortunately [deprecated](https://blog.min.io/deprecation-of-the-minio-gateway/). No new MinIO Gateway versions will be released. Forking is encouraged but the GNU AGPL v3 license is required.

**What would you like to be added**: A roadmap for JuiceFS S3 Gateway.

**Why is this needed**: Deprecation of the component MinIO Gateway.

**Comment by davies** [comment]
@JonMerlevede We are using a forked MinIO before license change, and we will continue to maintain this fork for security and bug fix.

**Comment by JonMerlevede** [comment]
That's great news, thanks for clearing that up for me!
