### ISSUE TITLE
How to mount the local data storage of multiple nodes for a jfs client？

### ISSUE THREAD

**Issue by felixYyu** [juicedata/juicefs#2787]
1. JuiceFS client node：192.168.202.146
2. data storage
local storage node1：192.168.202.138（data001/data002/data003/data004/data005/data006）
local storage node2：192.168.202.139（data001/data002/data003/data004/data005/data006）
local storage node3：192.168.202.140（data001/data002/data003/data004/data005/data006）
local storage node4：192.168.202.141（data001/data002/data003/data004/data005/data006）
3.metadata
redis://192.168.209.131:6379/1

How to mount node1/node2/node3/node4 local storage（data001/data002/data003/data004/data005/data006）？

**Comment by SandyXSD** [comment]
You have to build distributed object storage on these disks, and then use the object storage as the data backend of JuiceFS.
MinIO should be a simple choice to start, see: https://juicefs.com/docs/community/how_to_setup_object_storage/#minio

**Comment by felixYyu** [comment]
Thanks@SandyXSD, I will to try.  other JuiceFS client node whether HA is required, how to ?

**Comment by SandyXSD** [comment]
No, HA is not required for clients. Any node that is able to access:
1. metadata, i,e, the Redis server
2. data, i,e, the MinIO service

can act as a JuiceFS client, and the client is stateless.

**Comment by felixYyu** [comment]
Thanks, I understand and close this issue.
