### ISSUE TITLE
load big directory failure with foundationdb

### ISSUE THREAD

**Issue by zhoucheng361** [juicedata/juicefs#2803]
**What happened**:

root@bench-01:~# juicefs1/juicefs load fdb:///etc/foundationdb/fdb.cluster?prefix=jfs META_7M_EMPTY_FILE.json
2022/09/26 18:55:59.386426 juicefs[1354863] <INFO>: Meta address: fdb:///etc/foundationdb/fdb.cluster?prefix=jfs [interface.go:411]
2022/09/26 18:55:59.402748 juicefs[1354863] <INFO>: Loading from file ... [dump.go:312]
Loaded entries count: 5000000 / 7000004 [===========================================>------------------]  71 % 2m11s

when the directory has 7000000 entries, the load progress blocked on 5000000 entries.

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**

**Environment**:
- JuiceFS version (use `juicefs --version`) or Hadoop Java SDK version:
- Cloud provider or hardware configuration running JuiceFS:
- OS (e.g `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Object storage (cloud provider and region, or self maintained):
- Metadata engine info (version, cloud provider managed or self maintained):
- Network connectivity (JuiceFS to metadata engine, JuiceFS to object storage):
- Others:

**Comment by SandyXSD** [comment]
The memory engine has a default limit of 1GiB. You have to increase it to a higher value by setting `storage_memory` in the `/etc/foundationdb/foundationdb.conf`.
See: https://apple.github.io/foundationdb/administration.html?highlight=storage_memory

**Comment by penglaixy99** [comment]
I use tikv to store metadata, I have written 20  million files in a single directory， and   ls command has stuck for 40 min.  Is there some option to configure for tikv ?

**Comment by SandyXSD** [comment]
> I use tikv to store metadata, I have written 20 million files in a single directory， and ls command has stuck for 40 min. Is there some option to configure for tikv ?

refer to: #2831
