### ISSUE TITLE
Big directory when using tikv as metadata engine 

### ISSUE THREAD

**Issue by penglaixy99** [juicedata/juicefs#2831]
**What happened**:
I have written 20 million files in a single directory.
ls command has stuck for 40 min, and the memory used has increased from 71MB to 10GB, but  soon  decreased slowly , and finally to 4.5GB.  But the ls command has no result. 

**What you expected to happen**:
ls command output normally.

**How to reproduce it (as minimally and precisely as possible)**:
write 2000 0000 files in a single direcotry.

**Anything else we need to know?**
When ls command is executing, 8 clients are stilling writing files to the directory.

**Environment**:
- JuiceFS version (use `juicefs --version`) or Hadoop Java SDK version: 1.0.0
- Cloud provider or hardware configuration running JuiceFS:
- OS (e.g `cat /etc/os-release`):  centos 7.4
- Kernel (e.g. `uname -a`): 
- Object storage (cloud provider and region, or self maintained):  ks3
- Metadata engine info (version, cloud provider managed or self maintained): tikv 2.0.1
- Network connectivity (JuiceFS to metadata engine, JuiceFS to object storage):
- Others:

**Comment by SandyXSD** [comment]
Could you get the juicefs.log and part of the [access log](https://juicefs.com/docs/community/fault_diagnosis_and_analysis/#access-log) when running the `ls` command?

**Comment by penglaixy99** [comment]
LOG :
slow operation: readdir (8302,4096,0): OK (18402593) <128.107549> [accesslog.go:65]    

entries number is correct. 

But ls command is stuck.  I will retry the command and set the fuse debug on.

**Comment by SandyXSD** [comment]
The first `readdir` will retrieve all entries (20m) and cache them for the following `readdir`s, so it's normal that it takes a bit long like 2 mins.
Usually the access log should be more useful in such case.

**Comment by penglaixy99** [comment]
I have a  retry.

11:44:27  juicefs begin to load entries from tikv.
2022/10/08 11:44:27 rx 27: READDIRPLUS n8302 {Fh 2 [0 +4096)  L 0 DIRECTORY,NONBLOCK,0x8000}



11:46:53   all entries are cached.
2022/10/08 11:46:53.347175 vivo_juicefs[2680] <INFO>: slow operation: readdir (8302,4096,0): OK (18593782) <145.730275> [accesslog.go:65]


then all entries are filled to the kernel fuse.

2022/10/08 11:46:53 rx 93: READDIRPLUS n8302 {Fh 2 [24 +4096)  L 0 DIRECTORY,NONBLOCK,0x8000}
2022/10/08 11:46:53 rx 95: READDIRPLUS n8302 {Fh 2 [48 +4096)  L 0 DIRECTORY,NONBLOCK,0x8000}
2022/10/08 11:46:53 rx 97: READDIRPLUS n8302 {Fh 2 [72 +4096)  L 0 NONBLOCK,DIRECTORY,0x8000}
2022/10/08 11:46:53 rx 99: READDIRPLUS n8302 {Fh 2 [96 +4096)  L 0 DIRECTORY,NONBLOCK,0x8000}
2022/10/08 11:46:53 rx 101: READDIRPLUS n8302 {Fh 2 [120 +4096)  L 0 DIRECTORY,NONBLOCK,0x8000}
2022/10/08 11:46:53 rx 103: READDIRPLUS n8302 {Fh 2 [144 +4096)  L 0 DIRECTORY,NONBLOCK,0x8000}
2022/10/08 11:46:53 rx 105: READDIRPLUS n8302 {Fh 2 [168 +4096)  L 0 DIRECTORY,NONBLOCK,0x8000}
2022/10/08 11:46:53 rx 107: READDIRPLUS n8302 {Fh 2 [192 +4096)  L 0 DIRECTORY,NONBLOCK,0x8000}
.........
2022/10/08 12:07:21 rx 4198510: READDIRPLUS n8302 {Fh 2 [18593520 +4096)  L 0 DIRECTORY,NONBLOCK,0x8000}
2022/10/08 12:07:21 rx 4198512: READDIRPLUS n8302 {Fh 2 [18593544 +4096)  L 0 DIRECTORY,NONBLOCK,0x8000}
2022/10/08 12:07:21 rx 4198514: READDIRPLUS n8302 {Fh 2 [18593568 +4096)  L 0 DIRECTORY,NONBLOCK,0x8000}
2022/10/08 12:07:21 rx 4198516: READDIRPLUS n8302 {Fh 2 [18593592 +4096)  L 0 DIRECTORY,NONBLOCK,0x8000}
2022/10/08 12:07:21 rx 4198518: READDIRPLUS n8302 {Fh 2 [18593616 +4096)  L 0 DIRECTORY,NONBLOCK,0x8000}
2022/10/08 12:07:21 rx 4198520: READDIRPLUS n8302 {Fh 2 [18593640 +4096)  L 0 NONBLOCK,DIRECTORY,0x8000}
2022/10/08 12:07:21 rx 4198522: READDIRPLUS n8302 {Fh 2 [18593664 +4096)  L 0 DIRECTORY,NONBLOCK,0x8000}
2022/10/08 12:07:21 rx 4198524: READDIRPLUS n8302 {Fh 2 [18593688 +4096)  L 0 NONBLOCK,DIRECTORY,0x8000}
2022/10/08 12:07:21 rx 4198526: READDIRPLUS n8302 {Fh 2 [18593712 +4096)  L 0 DIRECTORY,NONBLOCK,0x8000}
2022/10/08 12:07:21 rx 4198528: READDIRPLUS n8302 {Fh 2 [18593736 +4096)  L 0 DIRECTORY,NONBLOCK,0x8000}
2022/10/08 12:07:21 rx 4198530: READDIRPLUS n8302 {Fh 2 [18593760 +4096)  L 0 NONBLOCK,DIRECTORY,0x8000}
2022/10/08 12:07:21 rx 4198532: READDIRPLUS n8302 {Fh 2 [18593782 +4096)  L 0 DIRECTORY,NONBLOCK,0x8000}

**Comment by SandyXSD** [comment]
It's hard coded in kernel to use only 1 page for each `readdir` request, so it seems to be expected taking that long time to transfer all the entries.

**Comment by penglaixy99** [comment]
Thanks， Sandy!  BTW, Close the issue !
