### ISSUE TITLE
Incorrect permissions of created folders when creating FSDataOutputStream in non-exist folders with Hadoop SDK 1.0

### ISSUE THREAD

**Issue by cmmp6** [juicedata/juicefs#2832]
**What happened**:
We use Hadoop SDK 1.0 to write some bytes into JuiceFS file(jfs://jfs-test/tmp/jfs/hellojfs) with JuiceFS umask configured as 022 and HDFS umask configured as 077. Parent path(jfs://jfs-test/tmp/jfs) of file doesn't exist. After writing and flushing, the file and parent folders are created. Permissions of file(jfs://jfs-test/tmp/jfs/hellojfs) is 644 and permissions of parent path(jfs://jfs-test/tmp/jfs) is 700.

**What you expected to happen**:
Permissions of parent path(jfs://jfs-test/tmp/jfs) is 755. Same as the permissions using HDFS mkdir API.

**How to reproduce it (as minimally and precisely as possible)**:
`...`
`Configuration hadoopConf = new Configuration();`
`hadoopConf.addResource(new File("core-site.xml").toURI().toURL());`
`hadoopConf.addResource(new File("hdfs-site.xml").toURI().toURL());`
`FileSystem fs = FileSystem.get(new URI("jfs://jfs-test"), hadoopConf);`
`Path p = new Path("jfs://jfs-redis-test/tmp/jfs/hellojfs");`
`FSDataOutputStream out = fs.create(p, true);`
`out.write("hello juicefs".getBytes());`
`out.flush();`
`...`

**Anything else we need to know?**
The reason is input permission of mkdir function being applied hadoop umask when creating FSDataOutputStream.
![image](https://user-images.githubusercontent.com/11750215/194702077-78634f24-dbb9-4aa9-be58-02248e28e5b4.png)

**Environment**:
- JuiceFS version (use `juicefs --version`) or Hadoop Java SDK version:
Hadoop Java SDK 1.0

- Cloud provider or hardware configuration running JuiceFS:
MAC Pro M1

- OS (e.g `cat /etc/os-release`):
Mac OS 12.4

- Kernel (e.g. `uname -a`):
Darwin mingdeMacBook-Pro.local 21.5.0 Darwin Kernel Version 21.5.0: Tue Apr 26 21:08:37 PDT 2022; root:xnu-8020.121.3~4/RELEASE_ARM64_T6000 arm64

- Object storage (cloud provider and region, or self maintained):
Baidu Cloud Object Storage

- Metadata engine info (version, cloud provider managed or self maintained):
Baidu Cloud Redis

**Comment by tangyoupeng** [comment]
fixed by #2833

**Comment by tangyoupeng** [comment]
@cmmp6 When HDFS create a file which parent does not exist, the new created parent dir will inherit the last exist parent dir, it will not apply the configured umask, did you expect this?

**Comment by tangyoupeng** [comment]
Currently, JuiceFS's implemention is use 0777 apply umask which is different with HDFS

**Comment by cmmp6** [comment]
> Currently, JuiceFS's implemention is use 0777 apply umask which is different with HDFS

This is what I expect, 0777 & ^${juicefs.umask}. I think #2833 already fixed this issue.
