### ISSUE TITLE
fatal error: sync :unlock of unlocked mutex

### ISSUE THREAD

**Issue by JesseDPC** [juicedata/juicefs#2873]
<img width="1280" alt="fb130d09bf974607a8da3d0aaf1e921" src="https://user-images.githubusercontent.com/68317718/196367207-8a8436ab-5a01-46ea-9e7b-358b55515fdb.png">

**Comment by zhijian-pro** [comment]
What is the version? Please provide more information to help us reproduce this problem.

**Comment by JesseDPC** [comment]
> 版本是什么？请提供更多信息以帮助我们重现此问题。

juicefs v1.0.0+2022-08-08

**Comment by SandyXSD** [comment]
It's caused by corrupt value in Redis.
We should return EIO for this Read instead of panic.
