### ISSUE TITLE
windows git clone repo to juicefs "Permission denied"

### ISSUE THREAD

**Issue by orestonce** [juicedata/juicefs#2894]
**What happened**:
Cannot clone git repo to an windows juicefs directory "F:/" .

**What you expected to happen**:
clone success.

**How to reproduce it (as minimally and precisely as possible)**:

1. juicefs.exe mount sqlite3://D:/jfs/meta.db F:
2.
````
git.exe clone --progress -v "D:\dev\go-projects\FastestBilibiliDownloader" "F:\FastestBilibiliDownloader"
//juicefs/disk1/FASTESTBILIBILIDOWNLOADER/.git/: Permission denied
Cloning into 'F:\FastestBilibiliDownloader'...

git  脛顺谩(脥枚1) (688 ms @ 2022/10/22 18:09:40)
````
**Anything else we need to know?**
![1](https://user-images.githubusercontent.com/6974828/197334062-6a9cf4fe-acc9-4b27-951c-9315902963e1.PNG)

**Environment**:
- JuiceFS version (use `juicefs --version`) or Hadoop Java SDK version: juicefs version 1.1.0-dev+2022-10-21.3955fd44
- Cloud provider or hardware configuration running JuiceFS:
- OS (e.g `cat /etc/os-release`): windows 10
- Object storage (cloud provider and region, or self maintained): 
````
juicefs.exe config sqlite3://D:/jfs/meta.db
2022/10/22 18:23:50.056489 juicefs[36176] <INFO>: Meta address: sqlite3://D:/jfs/meta.db [interface.go:411]
{
  "Name": "disk1",
  "UUID": "c9992261-4fe2-4b72-a5d0-e2f49dfc32c9",
  "Storage": "file",
  "Bucket": "D:\\jfs\\data/",
  "BlockSize": 4096,
  "Compression": "none",
  "EncryptAlgo": "aes256gcm-rsa",
  "TrashDays": 1,
  "MetaVersion": 1
}
````
- Network connectivity (JuiceFS to metadata engine, JuiceFS to object storage): sqlite3

**Comment by zhijian-pro** [comment]
This is a known problem. https://github.com/juicedata/juicefs/issues/1505 
We will try to fix it. Thanks!

**Comment by SandyXSD** [comment]
duplicated with #1505
