### ISSUE TITLE
Support Restoring Archived S3 Objects

### ISSUE THREAD

**Issue by jashandeep-sohi** [juicedata/juicefs#2898]
**What would you like to be added**: 

Add a way to automatically restore objects in S3 Intelligent-Tiering Archive tier.

Perhaps, it's as simple as issuing a `RestoreObject` API call if a `GetObject` returns a response indicating the object is in `DEEP_ARCHIVE_ACCESS` access tier. Perhaps not?

**Why is this needed**:

S3 intelligent tiering has an optional tier, `DEEP_ARCHIVE_ACCESS`, that offers drastic savings for objects that are rarely accessed (>180 days). The only catch is that objects must be asynchronously restored back to Frequent Access Tier, before they can be accessed again. And it may take up to 12 hours for that to complete.

Granted, not everyone would be willing to wait that long, but having this *optional* feature would save significant costs for those that can. I'd find it especially useful for archival type volumes that rarely get any traffic, but need to store petabytes of data for compliance/historical purposes.

**Comment by davies** [comment]
JuiceFS can't wait 12 hours to read an object, it will timeout and return IOError before that.

we may need archive/restore command to do this, which will be a broader change.

**Comment by jashandeep-sohi** [comment]
Yeah, I wouldn't expect it to wait for the object to become ready either. Perhaps an error at the filesystem level. How does the IOError bubble up to the fuse/filesystem layer? Could it return something like `EAGAIN` for file operations until underlying the objects are available, leaving it up to the user to retry?

Even an administrate command that could do this would be enough for my use-case, but this is very specific to S3 so not sure how that would fit in with the CLI. Maybe a more generic command that just dumps what objects belong to a give file-path, and then I can just pipe that into another script that does the restore.

**Comment by davies** [comment]
The `juicefs info` command could dump all the objects that used for given file.
