### ISSUE TITLE
use iceberg via s3a can't access juicefs s3 gateway 

### ISSUE THREAD

**Issue by ming12713** [juicedata/juicefs#2904]
hi
we use iceberg in Spark with hive catalog acesses juicefs not support list metadata directory, output errors as bellow
![image](https://user-images.githubusercontent.com/5196113/197740641-776e3870-7e7d-4fcc-bc58-d8fd35f9691e.png)

no errors on s3 gateway console 
![image](https://user-images.githubusercontent.com/5196113/197742734-e7e3c77e-75d1-448d-af35-eafc747901f3.png)

try to use hadoop s3a mode access  juice s3 gateway, still can't display meta diretory
`hadoop s3a list`
![image](https://user-images.githubusercontent.com/5196113/197742906-64267a04-87f7-4bc8-9b02-d55fa96422df.png)

use minio client can  list full files in meta directory
![Screenshot from 2022-10-25 17-55-05](https://user-images.githubusercontent.com/5196113/197743392-7c4f7e2c-9087-4cff-9b3c-ace1d4d09cda.png)

**Comment by tangyoupeng** [comment]
We don't suggest to use jfs s3 gateway with iceberg .
You can use java sdk with iceberg to access juicefs.  Refer to https://juicefs.com/docs/zh/community/hadoop_java_sdk

**Comment by ming12713** [comment]
> We don't suggest to use jfs s3 gateway with iceberg . You can use java sdk with iceberg to access juicefs. Refer to https://juicefs.com/docs/zh/community/hadoop_java_sdk

thx, does the sdk support iceberg use hive/hdfs cataglog ? 
By the way, are there any best practice  for iceberg on juicefs?

**Comment by ming12713** [comment]
> We don't suggest to use jfs s3 gateway with iceberg . You can use java sdk with iceberg to access juicefs. Refer to https://juicefs.com/docs/zh/community/hadoop_java_sdk

if i use hive catalog ,that mean i need configure hive warehouse on juicefs first,   right ?

**Comment by tangyoupeng** [comment]
Yes, you my need to configure hive and spark 

> > We don't suggest to use jfs s3 gateway with iceberg . You can use java sdk with iceberg to access juicefs. Refer to https://juicefs.com/docs/zh/community/hadoop_java_sdk
> 
> if i use hive catalog ,that mean i need configure hive warehouse on juicefs first, right ?

**Comment by ming12713** [comment]
> Yes, you may need to configure hive and spark
> 
> > > We don't suggest to use jfs s3 gateway with iceberg . You can use java sdk with iceberg to access juicefs. Refer to https://juicefs.com/docs/zh/community/hadoop_java_sdk
> > 
> > 
> > if i use hive catalog ,that mean i need configure hive warehouse on juicefs first, right ?



> Yes, you may need to configure hive and spark
> 
> > > We don't suggest to use jfs s3 gateway with iceberg . You can use java sdk with iceberg to access juicefs. Refer to https://juicefs.com/docs/zh/community/hadoop_java_sdk
> > 
> > 
> > if i use hive catalog ,that mean i need configure hive warehouse on juicefs first, right ?

i will go play with sdk, thanks

**Comment by tangyoupeng** [comment]
@ming12713 How do you create the warehouse dir? Through jfs:// or s3a:// or fuse?

**Comment by ming12713** [comment]
> @ming12713 How do you create the warehouse dir? Through jfs:// or s3a:// or fuse?

 use s3a create warehouse dir

**Comment by 1241407808** [comment]
does juicefs s3 gateway support s3a? 
i meet same problem in flink using juicefs s3 gateway as backend stored filesystem.

flink return the following error:
```
2023-06-08 08:59:10,514 WARN  org.apache.hadoop.fs.s3a.S3ABlockOutputStream                [] - Application invoked the Syncable API against stream writing to flink-recovery/flink-s3-20230607-7/blob/job_f29902218942ba7958ced729d65df190/blob_p-2e39076f7544bce058cc6bcb7c1e92503b1cb887-03f7d6eae33b485c9ce3d486f593dd62. This is unsupported

 2023-06-08 08:59:10,524 WARN  com.amazonaws.services.s3.internal.Mimetypes                 [] - Unable to find 'mime.types' file in classpath
```

**Comment by tangyoupeng** [comment]
This is a warning caused by S3ABlockOutputStream to call hflush or hsync.

**Comment by 1241407808** [comment]
Thx . This's the issue of hadoop .
https://hadoop.apache.org/docs/stable/hadoop-aws/tools/hadoop-aws/troubleshooting_s3a.html
```
The application has tried to call either the Syncable.hsync() or Syncable.hflush() methods on an S3A output stream. This has been rejected because the connector isn’t saving any data at all. The Syncable API, especially the hsync() call, are critical for applications such as HBase to safely persist data.
```
