### ISSUE TITLE
Using MINIO as engine and Redis as metadata store, it fails to use correct region on mount

### ISSUE THREAD

**Issue by haakonnessjoen** [juicedata/juicefs#2974]
**What happened**:
Formatted the storage by first setting MINIO_REGION="eu-north-1" in the terminal. It successfully initialized the storage as long as I specified that environment variable correct.

But when I tried to mount the same volume, it falls back to the default "us-east-1", so no write operations work.

**What you expected to happen**:
I expected the mount operation to either read the region from the environment variable, or better yet from the metadata store.

**How to reproduce it (as minimally and precisely as possible)**:
```
# First set up a minio storage with "eu-north-1" as the region
# after that, run:
juicefs format --storage minio --bucket http://127.0.0.1:9000/juicefs1 --access-key minioacceskey --secret-key minio-secretkey redis://127.0.0.1:6379/1 myjuicefs
sudo juicefs mount redis://127.0.0.1:6379/1 /mnt/juicefs
touch /mnt/juicefs/testfile
```

**Environment**:
- juicefs version 1.0.2+2022-10-13.514ef03
- local minio storage
- Ubuntu linux
- Redis 4.0.14

**Comment by zhijian-pro** [comment]
If you use environment variables when `format`, make sure you can still read the same environment variables when `mount`.

**Comment by haakonnessjoen** [comment]
I have made sure of that, but it does not seem to do it. Or maybe "sudo" clears them before running juicefs? I was pretty sure sudo keeps most of exported env variables?

**Comment by omesser** [comment]
sudo does not preserve the caller terminal's environment variables by default.
You can preserve all (well, most) or some specific env vars by using:
```sh
       -E, --preserve-env
                   Indicates to the security policy that the user wishes to
                   preserve their existing environment variables.  The security
                   policy may return an error if the user does not have
                   permission to preserve the environment.

       --preserve-env=list
                   Indicates to the security policy that the user wishes to add
                   the comma-separated list of environment variables to those
                   preserved from the user's environment.  The security policy
                   may return an error if the user does not have permission to
                   preserve the environment.  This option may be specified
                   multiple times.
```

**Comment by haakonnessjoen** [comment]
Thanks! Seems like it helped!

**Comment by haakonnessjoen** [comment]
Maybe it would be better to change the examples to `sudo --preserve-env=MINIO_REGION` in that case.
