### ISSUE TITLE
spring 应用引用juice hadoop jar，打成可执行jar部署异常

### ISSUE THREAD

**Issue by malin177** [juicedata/juicefs#2982]
**What happened**:
当spring boot应用使用可执行jar部署时，访问jfs文件系统报错：
异常发生原因：
JuiceFileSystemImpl.java > 535行 jarPath获取为null，导致542行空指针

**What you expected to happen**:
可以正常解析嵌套jar内容

**Environment**:
jfs：1.0.0-rc3版本

**Comment by tangyoupeng** [comment]
we've fixed the problem in the last release version

**Comment by tangyoupeng** [comment]
Please try the last version. Feel free to reopen this issue if the exception still exist.
