### ISSUE TITLE
The purpose of slice struct design

### ISSUE THREAD

**Issue by SongHuaxiong** [juicedata/juicefs#2985]
I want to know what is the purpose of designing the slice structure, the difference between "slice" and "Slice", why not write chunk/block directly. I have never used the golang before.
thank you.

**Comment by Hexilee** [comment]
Hi, the `slice` structure of juicefs metadata is irrelevant with the `slice` of `array` in golang, so I believe you can understand my following explanation even if you have never used golang.

juicefs stores data on object-based storage, which has lower IOPS and higher latency than disk-based storage, so we must have a bigger block size (like 32MB or 64MB) than local filesystem (just like many other distributed filesystems) to ensure high-performance in sequential write cases. 

However, in random write cases, big block size cause terrible write amplification (assume that you write 4KB data randomly with 64MB block size, there are 16K times write amplification). So, we design the slice struct, which allow you to write and upload data in any size, then the slices will be asynchronously compact into chunks in batches.

**Comment by SongHuaxiong** [comment]
Hi,Hexilee.
I don’t know if I’m right. The first time I modify a chunk data is on slice-A, and the second time I modify on slice-B. The final result will integrate A and B. If B covers part of A, B can only start to modify after the A'modification is completed?

**Comment by Hexilee** [comment]
Once the slice-A is created in meta engine, the A'modification is completed. If you read the target chunk before A is compacted into it, juicefs will merge chunk with all uncompacted slices and return the merged chunk.

**Comment by Hexilee** [comment]
You are welcome!
