### ISSUE TITLE
Flaky test: TestMarsharl

### ISSUE THREAD

**Issue by Hexilee** [juicedata/juicefs#3020]
```log
=== RUN   TestMarsharl
    object_storage_test.go:619: PUT failed: create /.hello.tmp.679478056050146678: addBlock call failed with ERROR_APPLICATION (java.io.IOException)
--- FAIL: TestMarsharl (0.01s)
```

https://github.com/juicedata/juicefs/actions/runs/3538221106/jobs/5938870538 also refer to https://github.com/juicedata/juicefs/issues/2576

**Comment by zhijian-pro** [comment]
The hdfs datanode is not ready. 
We should use the `hdfs put` command to ensure that hdfs is ready before run unit tests.
