### ISSUE TITLE
error parsing oracle endpoint

### ISSUE THREAD

**Issue by neocxf** [juicedata/juicefs#3073]
**What happened**: 
can't format oracle object storage as storage backend

![image](https://user-images.githubusercontent.com/12878595/207233906-e857bdba-b1c5-489c-b304-908a218909e4.png)

**What you expected to happen**:
 formating work correctly on oracle object storage

**How to reproduce it (as minimally and precisely as possible)**:
```shell
juicefs format \
    --storage s3 \
    --bucket https://test-bucket.testns.compat.objectstorage.test-region.oraclecloud.com \
    --access-key testak\
    --secret-key testsk \
    tikv://localhost:2379/myjfs     myjfs
```

**Anything else we need to know?**

**Environment**:
- JuiceFS version (use `juicefs --version`) or Hadoop Java SDK version:  juicefs version 1.1.0-dev+2022-11-22.84b45417
- Cloud provider or hardware configuration running JuiceFS: oracle
- OS (e.g `cat /etc/os-release`):  Oracle Linux Server 8.7
- Kernel (e.g. `uname -a`):  5.4.17-2136.313.6.el8uek.x86_64 #2 SMP Thu Oct 20 14:30:48 PDT 2022 x86_64 x86_64 x86_64 GNU/Linux 
- Object storage (cloud provider and region, or self maintained):  oracle
- Metadata engine info (version, cloud provider managed or self maintained): tikv
- Network connectivity (JuiceFS to metadata engine, JuiceFS to object storage):   JuiceFS to object storage
- Others:

**Comment by zhijian-pro** [comment]
close by #3075
