### ISSUE TITLE
error sync jfs to s3

### ISSUE THREAD

**Issue by neocxf** [juicedata/juicefs#3106]
**What happened**:
![image](https://user-images.githubusercontent.com/12878595/208609842-45f5408b-24c7-483d-8d53-1f88194aad5e.png)

**What you expected to happen**:
sync the jfs data to s3 successfully

**How to reproduce it (as minimally and precisely as possible)**:
`juicefs sync ~/mystor/ s3://ak:sk@juicefs-chen.s3.cn-northwest-1.amazonaws.com/images/`

**Anything else we need to know?**

**Environment**:
- JuiceFS version (use `juicefs --version`) or Hadoop Java SDK version: **juicefs version 1.0.2+2022-10-13.514ef03**
- Cloud provider or hardware configuration running JuiceFS:  **aws**
- OS (e.g `cat /etc/os-release`):
```text
NAME="Ubuntu"
VERSION="20.04.5 LTS (Focal Fossa)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 20.04.5 LTS"
VERSION_ID="20.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=focal
UBUNTU_CODENAME=focal
```
- Kernel (e.g. `uname -a`):
```text
Linux ip-172-18-127-77 5.15.0-1026-aws #30~20.04.2-Ubuntu SMP Fri Nov 25 14:53:22 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
```
- Object storage (cloud provider and region, or self maintained): **s3**
- Metadata engine info (version, cloud provider managed or self maintained): **tikv**
- Network connectivity (JuiceFS to metadata engine, JuiceFS to object storage):
- Others:

**Comment by zhijian-pro** [comment]
Whether the `.config` file is likely to be modified during command execution ?

**Comment by zhijian-pro** [comment]
`~/mystor/` is juicefs mountpoint ?

**Comment by zhijian-pro** [comment]
This is the expected behavior. 
When the length of the 'config' file is calculated but the contents are not read, the contents of the file are modified, causing the http 'Content-Length' to be different from the actual body length, so an error is reported.
We recommend that when sync is used, no changes are made between the source and target ends.
