### ISSUE TITLE
uploadlimit and downloadlimit don't work

### ISSUE THREAD

**Issue by cat0dog** [juicedata/juicefs#3116]
**What happened**:
uploadlimit and downloadlimit is not working

![image](https://user-images.githubusercontent.com/51560192/209088660-0e952a33-b07a-42b8-8e30-8b3ce0f522ba.png)
![image](https://user-images.githubusercontent.com/51560192/209088740-0f13c0cf-2069-45e1-a4e6-59b8d5dffab0.png)
![6d9abd8757ff8deefd59ab17a8866c3](https://user-images.githubusercontent.com/51560192/209088840-cccf91ac-4892-482c-afb2-87c0d09dacab.png)

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**

**Environment**:
- JuiceFS version (use `juicefs --version`) or Hadoop Java SDK version:
- Cloud provider or hardware configuration running JuiceFS:
- OS (e.g `cat /etc/os-release`): 

![image](https://user-images.githubusercontent.com/51560192/209089019-54450cbd-f64c-470c-acff-264c0e93d375.png)

- Kernel (e.g. `uname -a`):
- Object storage (cloud provider and region, or self maintained):
- Metadata engine info (version, cloud provider managed or self maintained):
- Network connectivity (JuiceFS to metadata engine, JuiceFS to object storage):
- Others:

**Comment by zhijian-pro** [comment]
That's not much different from the norm. That's ok.

**Comment by davies** [comment]
@cat0dog upload-limit and download-limit are used to limit the bandwidth to object storage, can you use `dstat` or similar tools to check the network bandwidth?

**Comment by cat0dog** [comment]
In my test, juicefs works with redis and local disk. Upload limit 1MB/s, node network bandwith 1GB/s. upload bandwith works like ‘\’ . In the early stages, the speed is very fast, while in the later stages, the speed drops to well below the limit 
![image](https://user-images.githubusercontent.com/51560192/209898674-dcf6627f-78ab-4645-a5b8-881e32b36b2a.png)

At the same time, upload a 800MB file failed with upload limit 1MB/s
![f5521e8c4974dd778712a54725c83eb](https://user-images.githubusercontent.com/51560192/209898975-9145d213-86f6-47c3-8654-de53a5ab7460.png)

**Comment by zhijian-pro** [comment]
As for the problem of speed limiting, we have confirmed again that there is no problem. 
Because of the slow speed limit, fuse's flush api failed to flush the data in memory to the object store within 5 minutes and timed out, so there was an error when copying the 800M file.
