### ISSUE TITLE
storage webdav double encoding uri in func newWebDAV 

### ISSUE THREAD

**Issue by DEvmIb** [juicedata/juicefs#3123]
endpoint got encoded elsewhere and gowebdav.NewClient would double encode the endpoint url. i can't find where endpoint gets first encoded sorry, so i post only bug report.

**Comment by zhijian-pro** [comment]
Provide an example of an endpoint format that can reproduce this problem.

**Comment by DEvmIb** [comment]
storage: webdav
bucket:  http://example.com/sub/sub space/
endpoint : http://example.com/sub/sub%20space/
NewClient: http://example.com/sub/sub%2520space/

**Comment by zhijian-pro** [comment]
Sorry, I didn't reproduce it. Can you provide an example of the format command？

**Comment by zhijian-pro** [comment]
Unable to reproduce, temporarily closed
