### ISSUE TITLE
juicefs sync with https_proxy

### ISSUE THREAD

**Issue by fxmumu** [juicedata/juicefs#3136]
**What happened**:
with https_proxy, juicefs sync from aliyun oss to local.
when I give a wrong schema, it works.
when I give a right schema, it doesn't work.
![3](https://user-images.githubusercontent.com/3285890/209929256-0ed660ff-ee48-43f4-8397-84063760b2fa.png)
**What you expected to happen**:
juicefs sync work with http_proxy/https_proxy
**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**

**Environment**:
- JuiceFS version (use `juicefs --version`) or Hadoop Java SDK version:
- Cloud provider or hardware configuration running JuiceFS:
- OS (e.g `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Object storage (cloud provider and region, or self maintained):
- Metadata engine info (version, cloud provider managed or self maintained):
- Network connectivity (JuiceFS to metadata engine, JuiceFS to object storage):
- Others:

**Comment by zhijian-pro** [comment]
The obs implements https_proxy , but the oss is not yet implemented.

**Comment by fxmumu** [comment]
> 

ok, got it. and is there a plan for oss http_proxy?

**Comment by fxmumu** [comment]
> The obs implements https_proxy , but the oss is not yet implemented.


ok, got it. and is there a plan for oss http_proxy?

**Comment by zhijian-pro** [comment]
We will be supporting this feature in the near future.

**Comment by zhijian-pro** [comment]
Can you use the [oss_support_http_proxy](https://github.com/juicedata/juicefs/tree/oss_support_http_proxy) branch to test it ?

**Comment by fxmumu** [comment]
> Can you use the [oss_support_http_proxy](https://github.com/juicedata/juicefs/tree/oss_support_http_proxy) branch to test it ?

OK, I will test the feat, Thx.
