### ISSUE TITLE
when invoking InvalidateChunk we should use 0xFFFFFFFF all the way

### ISSUE THREAD

**Issue by penglaixy99** [juicedata/juicefs#3169]
**What happened**:

in file base.go and tikv.go  when invoking invalidatachunk , we use 0xFFFFFFFE to invalid chunk cache.

file base.go

func (m *baseMeta) Link(ctx Context, inode, parent Ino, name string, attr *Attr) syscall.Errno 

file  tikv.go

func (m *kvMeta) SetAttr(ctx Context, inode Ino, set uint16, sugidclearmode uint8, attr *Attr) syscall.Errno
func (m *kvMeta) doUnlink(ctx Context, parent Ino, name string) syscall.Errno
func (m *kvMeta) doRename(ctx Context, parentSrc Ino, nameSrc string, parentDst Ino, nameDst string, flags uint32, inode *Ino, attr *Attr) syscall.Errno

**What you expected to happen**:

always use 0xFFFFFFFF

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**

**Environment**:
- JuiceFS version (use `juicefs --version`) or Hadoop Java SDK version:
- Cloud provider or hardware configuration running JuiceFS:
- OS (e.g `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Object storage (cloud provider and region, or self maintained):
- Metadata engine info (version, cloud provider managed or self maintained):
- Network connectivity (JuiceFS to metadata engine, JuiceFS to object storage):
- Others:

**Comment by SandyXSD** [comment]
`0xFFFFFFFE` is a special index used to invalidate the attribute. Is there any real issue you encountered?

**Comment by penglaixy99** [comment]
file  openfile.go
func (o *openfiles) InvalidateChunk(ino Ino, indx uint32) {
	o.Lock()
	defer o.Unlock()
	of, ok := o.files[ino]
	if ok {
		if indx == 0xFFFFFFFF {                                            ---------> but we use  0xFFFFFFFF  in function InvalidateChunk
			of.chunks = make(map[uint32][]Slice)
		} else {
			delete(of.chunks, indx)
		}
		of.lastCheck = time.Unix(0, 0)
	}
}

**Comment by penglaixy99** [comment]
we do not encounterd any issue, we find this issue  when reviewing code

**Comment by SandyXSD** [comment]
`0xFFFFFFFF` is used to invalidate both chunk & attribute caches, while `0xFFFFFFFE` is used to invalidate only the attribute cache (i.e, `of.lastCheck = time.Unix(0, 0)`).

**Comment by penglaixy99** [comment]
Thks, I  understand now.

**Comment by davies** [comment]
this will be improved by https://github.com/juicedata/juicefs/pull/3172
