### ISSUE TITLE
Customized build configuration option

### ISSUE THREAD

**Issue by cayolblake** [juicedata/juicefs#318]
**What would you like to be added**:
Have an option to customize the build configuration to include only specific parts as required.

**Why is this needed**:

1. Have a smaller generated binary instead of the usual 60 MB one.
2. Smaller binary means faster loading.
3. Only-what's-needed generated binary.

**Comment by davies** [comment]
We can have some options to exclude some features, and have the full featured binary by default.

For example, we can `--tags nogcs` to exclude support for GCS.

**Comment by cayolblake** [comment]
Yeah that would be perfect and a nice addition imho :)
