### ISSUE TITLE
Session information is not recreated after network failure recovery

### ISSUE THREAD

**Issue by CodeRusher** [juicedata/juicefs#3183]
**What happened**:
We injected a 5 minute network failure at a certain node. After the fault is restored, the exception below will always be reported
```
2023/01/13 15:06:57.651702 juicefs[3896811] <ERROR>: update session: no session found matching sid: 969 [sql.go:1904]
```
the sid=969 has been cleared in meta-store, but the mount client has not recreated the session.

**What you expected to happen**:
mount client can recreated the session information after Network failure recovery 

**How to reproduce it (as minimally and precisely as possible)**:
injected a 5 minute network failure to meta-store

**Anything else we need to know?**

**Environment**:
- JuiceFS version (use `juicefs --version`) or Hadoop Java SDK version: juicefs version 1.0.3+2022-12-27.e4bf15a
- Cloud provider or hardware configuration running JuiceFS:
- OS (e.g `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Object storage (cloud provider and region, or self maintained):
- Metadata engine info (version, cloud provider managed or self maintained):
- Network connectivity (JuiceFS to metadata engine, JuiceFS to object storage):
- Others:

**Comment by SandyXSD** [comment]
The session will be recreated for sql with #3190, just like that in redis/tkv.
