### ISSUE TITLE
sync command, limit can't be -1 

### ISSUE THREAD

**Issue by SandyXSD** [juicedata/juicefs#3186]
root@bench-01:~# 4.9.0/cmd/mount/mount sync --help
--limit value limit the number of objects that will be processed (default: -1)

but limit -1 will cause fatal:
4.9.0/cmd/mount/mount sync .github/ /jfs/.github/ --threads 11 --perms --dry --delete-dst --exclude *.py --include *.yml --links --limit -1 --bwlimit 61 --no-https
: subprocess run error: 2023/01/13 15:12:33.565604 juicefs[103117] : limit should not be less than 0 [config.go:51]

**Comment by SandyXSD** [comment]
We need a more clear description about the limit values (-1 vs. 0 vs. positive).

**Comment by davies** [comment]
change fatal to warn should be enough
