### ISSUE TITLE
开源版如何做到apache v2开源协议的

### ISSUE THREAD

**Issue by daodol** [juicedata/juicefs#3201]
这个项目依赖了minio gateway,minio gateway采用了agplv3协议与apache协议似乎冲突？

**Comment by SandyXSD** [comment]
JuiceFS depends on an early version of MinIO gateway, which uses Apache License 2.0. See: https://github.com/juicedata/minio/blob/master/LICENSE

**Comment by daodol** [comment]
ok,thank you for your answer
