### ISSUE TITLE
Does Community Edition have a plan to support kerberos user authentication ？

### ISSUE THREAD

**Issue by ft2898** [juicedata/juicefs#3215]
目前社区版的用户认证使用的是 linux 本地用户认证，会导致只要拥有了任意一客户端的管理员权限，就拥有了juicefs文件系统最高权限，这对于海量数据而言是非常不安全的。文档中有描述 “JuiceFS 不会校验 Kerberos 用户的合法性，但是可以使用通过 Kerberos 认证的用户名” ，这种做法对于数据安全性基本没有保障

**Comment by tangyoupeng** [comment]
Because JuiceFS CE does not has a meta which is used to verify the ST(client request from KDC) sent from the client. So now there is not a proper way to support kerberos.
