### ISSUE TITLE
sync stop illegal character code

### ISSUE THREAD

**Issue by onkevin** [juicedata/juicefs#3216]
**What happened**:
I use juicefs sync OSS to COS，some Bucket had complete,but one bucket fault.
This is error report:

2023/02/06 17:27:14.562011 juicefs[58073] <INFO>: Syncing from oss://storage-private/ to cos://storage-private-12345/ [sync.go:619]
2023/02/06 17:27:40.774668 juicefs[58073] <WARNING>: Fail to list: XML syntax error on line 3574: illegal character code U+001F, retry again [sync.go:156]
2023/02/06 17:27:41.090834 juicefs[58073] <WARNING>: Fail to list: XML syntax error on line 3574: illegal character code U+001F, retry again [sync.go:156]
2023/02/06 17:27:41.419623 juicefs[58073] <WARNING>: Fail to list: XML syntax error on line 3574: illegal character code U+001F, retry again [sync.go:156]
2023/02/06 17:27:41.785279 juicefs[58073] <ERROR>: Fail to list after c/attachment/temp/1650560322584433827/word.docx: XML syntax error on line 3574: illegal character code U+001F [sync.go:166]
2023/02/06 17:27:41.785303 juicefs[58073] <ERROR>: Listing failed, stop syncing, waiting for pending ones [sync.go:682]
2023/02/06 17:27:41.785966 juicefs[58073] <INFO>: Found: 102985, copied: 0 (0 B), checked: 0 B, deleted: 0, skipped: 102985, failed: 0 [sync.go:892]
**How to reproduce it (as minimally and precisely as possible)**:

/opt/juicefs-1.0.3 sync --bwlimit 6048 --threads 30 oss://AK1:SK1@storage-private.oss-cn-beijing-internal.aliyuncs.com cos://AK1:SK2@storage-private-12345.cos.ap-beijing.myqcloud.com
**Anything else we need to know?**

**Environment**:
./juicefs-1.0.3 -V
juicefs version 1.0.3+2022-12-27.e4bf15a
[root@120-28 opt]#  uname -a
Linux 120-28 3.10.0-1127.el7.x86_64 #1 SMP Tue Mar 31 23:36:51 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
[root@120-28 opt]# cat /etc/os-release
NAME="CentOS Linux"
VERSION="7 (Core)"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="7"
PRETTY_NAME="CentOS Linux 7 (Core)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:centos:centos:7"
HOME_URL="https://www.centos.org/"
BUG_REPORT_URL="https://bugs.centos.org/"

CENTOS_MANTISBT_PROJECT="CentOS-7"
CENTOS_MANTISBT_PROJECT_VERSION="7"
REDHAT_SUPPORT_PRODUCT="centos"
REDHAT_SUPPORT_PRODUCT_VERSION="7"

**Comment by zhijian-pro** [comment]
We will add the `encodeing-type` parameter to each listobject request of the object store if it supports.
