### ISSUE TITLE
Minio region parameter

### ISSUE THREAD

**Issue by toomyem** [juicedata/juicefs#3245]
**What would you like to be added**:
New parameter to `juicefs format` command allowing to pass minio region name.

**Why is this needed**:
Currently minio region can only by passed via env variable MINIO_REGION. This make immpossible to pass this info using Nomad's volume specification.

**Comment by zhijian-pro** [comment]
Does the nomads not support environment variables? 
We think it is easier and more flexible to transfer region information by environment variables.

**Comment by toomyem** [comment]
I don't see any way to define env variables in [volume specification](https://www.nomadproject.io/docs/commands/volume/register#volume-specification) file.

**Comment by davies** [comment]
Maybe we cound pass it as url query, for example:  minio://ip:port/bucket?region=myregion
