### ISSUE TITLE
unit test failure not captured by CI

### ISSUE THREAD

**Issue by zhoucheng361** [juicedata/juicefs#3253]
**What happened**:
go test ./pkg/usage/... -v -count=1 -cover -timeout=5m -coverpkg=./pkg/usage/... -coverprofile=mutest-cov.out
![image](https://user-images.githubusercontent.com/100545994/220005920-1536f4b9-b80e-43bc-80ea-201c6dc936b7.png)

**What you expected to happen**:

- [x] 1. fix the test
- [ ] 2. check why the test failure is not captured by CI.

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**

**Environment**:
- JuiceFS version (use `juicefs --version`) or Hadoop Java SDK version:
- Cloud provider or hardware configuration running JuiceFS:
- OS (e.g `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Object storage (cloud provider and region, or self maintained):
- Metadata engine info (version, cloud provider managed or self maintained):
- Network connectivity (JuiceFS to metadata engine, JuiceFS to object storage):
- Others:

**Comment by SandyXSD** [comment]
May be related to #3252

**Comment by zhijian-pro** [comment]
Cannot reproduce panic but the test result is success.
