### ISSUE TITLE
juicefs access to internal / external url for same object storage

### ISSUE THREAD

**Issue by dbpaul** [juicedata/juicefs#3267]
Several object storage providers have two ways of accessing their storage, an internal url and an external one.
internal.provider.com
external.provider.com
both pointing to the same object storage.

If a juicefs filesystem is created with the internal url, how is it possible to access it for a client with the external one? The url is stored in the database, so i guess changing it would be possible, but how to enable access for both, internal and sxternal url?

**Comment by SandyXSD** [comment]
You can change the url temporarily with the `--bucket` option of `juicefs mount`.

**Comment by SandyXSD** [comment]
Closing this issue since it's idle for more than one month. Feel free to reopen it if you have any more question.
