### ISSUE TITLE
Allow ("s", "m", "h") suffix for `--backup-meta` option

### ISSUE THREAD

**Issue by solracsf** [juicedata/juicefs#3284]
Actually, `--backup-meta` accepts only seconds, like 7200 for 2h.
Like other options (ex.: `--upload-delay`) accept ("s", "m", "h") suffix, so '2h' instead of '7200'.

**Comment by A-Stupid-Sun** [comment]
hi @solracsf  I'm new here, I see the source code

> `BackupMeta: duration(c.String("backup-meta")),` which  in func getChunkConf(cmd/mount.go)

has implemented this feature as `upload-delay`  which in func getVfsConf(cmd/mount.go)

> `UploadDelay:  duration(c.String("upload-delay")),`

Could you give me more details about this feature ?

**Comment by solracsf** [comment]
`--backup-meta` accepts only seconds (int) like '7200'
Like `--upload-delay` command, it should also accept ("s", "m", "h") suffix, so '2h' instead of '7200'

**Comment by SandyXSD** [comment]
It does accept suffix, and uses `seconds` as the default unit. So both `2h` and `7200` are acceptable, and mean the same thing.

**Comment by solracsf** [comment]
Oh..so it's just not correctly documented :\

**Comment by SandyXSD** [comment]
The usage of suffixes is not mentioned because we found that most users are used to the "number of seconds" way.
