### ISSUE TITLE
Add information about the IP address of the system where the "mount" process is running to the session information

### ISSUE THREAD

**Issue by CodeRusher** [juicedata/juicefs#3295]
**What would you like to be added**:
在session信息中，新增字段：mount进程所在的系统ip地址

**Why is this needed**:
有了ip地址信息，可以做服务发现的一些工作，如自动发现mount进程的 metric endpoints列表

**Comment by davies** [comment]
目前已经有 hostname, 是否足够用来做服务发现？

**Comment by CodeRusher** [comment]
在我们的环境，只有hostname是不够的，部分不能够解析（或者说hostname是未管控的），反而ip是统一分配的

**Comment by CodeRusher** [comment]
> 

在我们的环境，只有hostname是不够的，部分不能够解析（或者说hostname是未管控的），反而ip是统一分配的
