### ISSUE TITLE
Report input/output error when start a rand write io test

### ISSUE THREAD

**Issue by wutz** [juicedata/juicefs#33]
**What happened**:

fio report:

```
big-file-multi-write: (groupid=0, jobs=1): err= 5 (file:io_u.c:1756, func=io_u error, error=Input/output error): pid=15850: Tue Jan 12 18:03:50 2021
```

juicefs report:

```
2021/01/12 18:03:25.169256 juicefs[6976] <WARNING>: compact 27806 0 with 20 slices: message 1001 is not supported
2021/01/12 18:03:25.216898 juicefs[6976] <WARNING>: compact 27806 1 with 20 slices: message 1001 is not supported
2021/01/12 18:03:25.379931 juicefs[6976] <ERROR>: error: redis: transaction failed
2021/01/12 18:03:25.380029 juicefs[6976] <WARNING>: write inode:27806 error: input/output error
2021/01/12 18:03:25.380042 juicefs[6976] <ERROR>: write inode:27806 indx:1  input/output error
```

**What you expected to happen**:

fio and juicefs have no error report.

**How to reproduce it (as minimally and precisely as possible)**:

Start a rand write on juicefs:

```
 fio --name=big-file-multi-write  --rw=randwrite --refill_buffers --bs=4k --size=100M --numjobs=1 --end_fsync=1
```

**Anything else we need to know?**:

**Environment**:
- JuiceFS version (use `./juicefs --version`): juicefs version 0.9.1 (2021-01-10T16:31:23Z 1b9f6f4)
- Cloud provider or hardware configuration running JuiceFS: Aliyun, 8core, 16GiB mem
- OS (e.g: `cat /etc/os-release`): Ubuntu 18.04.3
- Kernel (e.g. `uname -a`): 4.15.0-66-generic
- Object storage (cloud provider and region): Aliyun OSS
- Redis info (version, cloud provider managed or self maintained): Aliyun RDS Redis 5.x
- Network connectivity (JuiceFS to Redis, JuiceFS to object storage): Aliyun VPC
- Others:

**Comment by davies** [comment]
@wutz Thanks, we are working on it.

**Comment by davies** [comment]
@wutz What's the kind of Redis are you using?  There are multiple choice in Aliyun.

**Comment by wutz** [comment]
Aliyun RDS Redis 5.x

I also try dockerhub redis:6, it’s same issue

**Comment by davies** [comment]
I can reproduce the issue, working on it.

**Comment by wutz** [comment]
@davies  Thanks for you working. I have trying the master version with no error report, but random write iops is down from 15k to 200 compared to ossfs.

If i increase test size from 100M to 1G, fio report the error:

```
fio: io_u error on file big-file-multi-write.0.0: Input/output error: write offset=529514496, buflen=4096
fio: pid=14098, err=5/file:io_u.c:1756, func=io_u error, error=Input/output error
```

**Comment by davies** [comment]
I will

**Comment by davies** [comment]
@wutz It should be fixed, can you double check?

**Comment by wutz** [comment]
@davies It's working fine now.
