### ISSUE TITLE
Concurrently deleting a massive directory content turns the whole filesystem inaccessible

### ISSUE THREAD

**Issue by cayolblake** [juicedata/juicefs#332]
**What happened**:
```
$ rm -rf go/pkg/mod/github.com/

rm: cannot remove 'go/pkg/mod/github.com/!data!dog/zstd@v1.4.5/LICENSE': Permission denied
rm: cannot remove 'go/pkg/mod/github.com/!data!dog/zstd@v1.4.5/README.md': Permission denied
rm: cannot remove 'go/pkg/mod/github.com/!data!dog/zstd@v1.4.5/ZSTD_LICENSE': Permission denied
rm: cannot remove 'go/pkg/mod/github.com/!data!dog/zstd@v1.4.5/bitstream.h': Permission denied
rm: cannot remove 'go/pkg/mod/github.com/!data!dog/zstd@v1.4.5/compiler.h': Permission denied
rm: cannot remove 'go/pkg/mod/github.com/!data!dog/zstd@v1.4.5/cover.c': Permission denied

... truncated ...
```

**What you expected to happen**:
Dir to be recursively removed.

**Environment**:
- JuiceFS version (use `./juicefs --version`) or Hadoop Java SDK version: `juicefs version 0.12.1-10 (2021-04-21 dadf18e)`
- OS (e.g: `cat /etc/os-release`): `Fedora 33`
- Kernel (e.g. `uname -a`): `5.11.14-200.fc33.x86_64`
- Object storage (cloud provider and region): `DigitalOcean/S3`
- Redis info (version, cloud provider managed or self maintained): `Redis server v=6.2.2 sha=00000000:0 malloc=jemalloc-5.1.0 bits=64 build=c8cbd75df80c9803`
- Network connectivity (JuiceFS to Redis, JuiceFS to object storage): `Single machine setup`

**Comment by davies** [comment]
@cayolblake I can't reproduce this issue:

```bash
root@localhost:/jfs/mod# ls github.com
alecthomas   cpuguy83    form3tech-oss   hungys         mattn                       pierrec     spaolacci
aliyun       !data!dog   go-asn1-ber     !i!b!m         matttproud                  pingcap     square
!arvintian   davecgh     gogo            imdario        miekg                       pkg         streadway
aws          davies      golang          jcmturner      minio                       prometheus  tencentyun
!azure       dchest      go-ldap         jmespath       mitchellh                   qiniu       tidwall
baidubce     deckarep    gomodule        josharian      modern-go                   rcrowley    tikv
bcicen       dgrijalva   google          json-iterator  montanaflynn                rjeczalik   tinylib
beevik       dgryski     googleapis      juicedata      mozillazg                   rs          upyun
beorn7       djherbis    go-redis        juju           nats-io                     russross    urfave
billziss-gh  dswarbrick  gorilla         klauspost      ncw                         ryanuber    valyala
ceph         dustin      go-sql-driver   kr             !net!ease-!object-!storage  satori      viki-org
cespare      eapache     grpc-ecosystem  ks3sdklib      nsqio                       secure-io   !vivid!cortex
cheggaaa     eclipse     hanwen          kurin          olivere                     shirou      wcharczuk
colinmarc    elazarl     hashicorp       lib            opentracing                 !shopify    willf
coredns      fatih       huandu          mailru         pengsrc                     shurcoo!l   xdg
coreos       felixge     huaweicloud     !masterminds   philhofer                   sirupsen    yunify
root@localhost:/jfs/mod# rm -rf github.com/
```

It looks like do you have permission to remove these files, rather than something related to `!`

**Comment by cayolblake** [comment]
Confirmed. There's a corruption in the mount point and I'll report in a different issue.

**Comment by cayolblake** [comment]
@davies 

It appears the problems is much bigger than expected.

I changed the title of the issue since I was able to track down what happened which is not a single file in the `juicefs` mount point is currently readable.
 
What I did was the following to reach the current state.

1. `$ cd dir_with_70k_files_and_dirs`
2. `$ for i in *; do rm -rf $i & done`
3. About a minute later I got a flood of errors saying `Transport endpoint is not connected`
4. The mount point was completely inaccessible.
5. Had to umount and remount the filesystem.
6.  Attempting to read any file regardless small or large blocks.
7. Creating any new file and attempting to read its content succeeds tho.
8. Attempted to create a new cache dir and remounted and attempted to read any file still fails.
9. Tried to `strace` cat'ing a file, it appears its blocking in the `read()` syscall.

That's all what happened. Not sure if I lost the content for good or not 🤔

**Comment by davies** [comment]
After looking at these together, there is what happpened:

1. When deleting many directories concurrently, the `juicefs` is killed by kernel (OOM), then you see `Transport endpoint is not connected`
2. When `writeback` is enabled, the blocks will written into the cache directory first. in the same time, the cache-size is set to 128MB, then some of the blocks can be read until it's uploaded into S3.
3. There could be lots of request to S3, especially after the deletions of many files, your S3 buckets may be flooded, and you see `fail to read chunkid 111036 (off:0, size:431, clen: 431): timeout after 1m0s`
4. After move the stagging blocks into current cache-dir and mount it again, all files become accessible.
5. After removing `--writeback`, the benchmark result looks reasonable, even still lower than the result from running in AWS.
