### ISSUE TITLE
The Java program encountered an error while copying files using JuiceFS to access HDFS and enabling Kerberos authentication

### ISSUE THREAD

**Issue by bruceangelliu** [juicedata/juicefs#3334]
**What happened**:
1.Java通过UserGroupInformation实现hdfs的kerberos认证，然后进行复制文件（调用FileUtil.copy()）是可以的；
2.用Juicefs挂载hdfs，直接向挂载目录写文件也是正常的，使用hdfs dfs -cp jfs://myjfs/a.txt jfs://myjfs/b.txt操作也是正常的；
3.Java程序引用juice-hadoop.jar，使用UserGroupInformation登录认证后，创建目录、改权限、移动都可以正常操作，就是复制、上传、下载需要拷贝流的就报错；
4.服务器下也是有/tmp/krb5cc_1009这种ccache文件；配置文件各项也都合适正确，且("hadoop.security.authentication"="kerberos")；

**What you expected to happen**:
1.Java程序报错日志：
2023/03/15 17:26:23.245442 juicefs[15841] <DEBUG>: PUT chunks/0/14/14003_0_3 (create /tenant-guangqi/chunks/0/14/.14003_0_3.tmp.8519068579405533917: no available namenodes: write tcp 10.1.3.25:39478->10.1.3.26:8020: write: broken pipe, 0.000s) [cached_store.go:347]
2023/03/15 17:26:23.245522 juicefs[15841] <WARNING>: Upload chunks/0/14/14003_0_3: create /tenant-guangqi/chunks/0/14/.14003_0_3.tmp.8519068579405533917: no available namenodes: write tcp 10.1.3.25:39478->10.1.3.26:8020: write: broken pipe (try 1) [cached_store.go:396]
2.NameNode服务报错日志：
2023-03-15 17:27:36,723 INFO  ipc.Server (Server.java:doRead(1256)) - Socket Reader #1 for port 8020: readAndProcess from client 10.1.3.25:39090 threw exception [org.apache.hadoop.security.AccessControlException: SIMPLE authentication is not enabled.  Available:[TOKEN, KERBEROS]]
org.apache.hadoop.security.AccessControlException: SIMPLE authentication is not enabled.  Available:[TOKEN, KERBEROS]
        at org.apache.hadoop.ipc.Server$Connection.initializeAuthContext(Server.java:2136)
        at org.apache.hadoop.ipc.Server$Connection.readAndProcess(Server.java:2085)
        at org.apache.hadoop.ipc.Server$Listener.doRead(Server.java:1249)
        at org.apache.hadoop.ipc.Server$Listener$Reader.doRunLoop(Server.java:1105)
        at org.apache.hadoop.ipc.Server$Listener$Reader.run(Server.java:1076)

**How to reproduce it (as minimally and precisely as possible)**:
1.搭建开启kerberos的hadoop环境；
2.使用JuiceFs挂载Hdfs；
3.使用Java程序通过JuiceFs操作Hdfs API，比如复制、上传、下载文件；

**Anything else we need to know?**

**Environment**:
- JuiceFS version (use `juicefs --version`) or Hadoop Java SDK version: 社区版JuiceFSv1.0.3，Hadoop-3.1.1，JDK8
- Cloud provider or hardware configuration running JuiceFS: Liunx服务器
- OS (e.g `cat /etc/os-release`): 
   NAME="CentOS Linux"
   VERSION="7 (Core)"
   ID="centos"
   ID_LIKE="rhel fedora"
   VERSION_ID="7"
   PRETTY_NAME="CentOS Linux 7 (Core)"
   ANSI_COLOR="0;31"
   CPE_NAME="cpe:/o:centos:centos:7"
- Kernel (e.g. `uname -a`): Linux slave1 3.10.0-957.el7.x86_64 #1 SMP Thu Nov 8 23:39:32 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
- Object storage (cloud provider and region, or self maintained):  self maintained
- Metadata engine info (version, cloud provider managed or self maintained): Mysql5.7 self maintained
- Network connectivity (JuiceFS to metadata engine, JuiceFS to object storage):
- Others:

**Comment by tangyoupeng** [comment]
Since hdfs dfs -cp jfs://myjfs/a.txt jfs://myjfs/b.txt works then your own jar should work. The command also use the hadoop java sdk.
Please check the hadoop conf is right?

**Comment by tangyoupeng** [comment]
Specify HADOOP_CONF_DIR env var add try it again. It works for me.
According to the namnode error message. It is obvious that the config was not configured right.

**Comment by bruceangelliu** [comment]
Previously, export HADOOP_CONF_DIR was set on each node in the cluster, and the Java program read the configuration files of core-site and hdfs-site, and I thought it would be OK, but I did not expect to need to set the export Hadoop_conf_dir in the JAVA program. Now it has been solved. Thank you!
