### ISSUE TITLE
Encrypted file system, files exported through metadata automatic backup cannot be restored

### ISSUE THREAD

**Issue by yuhr123** [juicedata/juicefs#3337]
**What happened**:

The metadata backup files that are automatically exported to the "meta" directory by the encrypted file system created according to [the documentation](https://juicefs.com/docs/community/security/encrypt/#enable-data-encryption-at-rest) cannot be restored through the "load" command.

![截屏2023-03-16 11 35 27](https://user-images.githubusercontent.com/3388604/225507414-f023c273-8475-4868-8e20-678a742608ca.png)

It should be noted that for encrypted file systems, the backup exported by manually executing the "dump" command can be used for restoration.

**What you expected to happen**:

The files automatically exported to the "meta" directory can be used for restoration of the encrypted file system.

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**

https://github.com/juicedata/juicefs/discussions/3141

**Environment**:
- JuiceFS version (use `juicefs --version`) or Hadoop Java SDK version:
- Cloud provider or hardware configuration running JuiceFS:
- OS (e.g `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Object storage (cloud provider and region, or self maintained):
- Metadata engine info (version, cloud provider managed or self maintained):
- Network connectivity (JuiceFS to metadata engine, JuiceFS to object storage):
- Others:

**Comment by zhijian-pro** [comment]
close by #3311
