### ISSUE TITLE
Flink+Hive batch is not working with juicefs

### ISSUE THREAD

**Issue by bronzels** [juicedata/juicefs#3341]
**What happened**:
Setup a hadoop system with HDFS replaced by juicefs.  Also a flink cluster is started based on hadoop cluster. Try to read hive table in flink sql-client.sh, always with error:
org.apache.flink.table.api.ValidationException: Could not find any factory for identifier 'hive' that implements 'org.apache.flink.table.planner.delegation.ParserFactory' in the classpath.

Same table can be read in hive command and also spark sql.  There are juicefs logs produced. Compare juicefs logs in flink and in hive/sparksql, no error in flink/juicefs, but only part of file op logs comparing to juicefs working with hive/sparksql.

With hive/juicefs version fixed, change hadoop version to 3.1.1/3.3.1/3.3.4, change flink to 1.14.0/1.14.6, 1.15.3/1.15.4, 1.16.1, all same error.

**What you expected to happen**:
Flink+Hive batch read/write working with juicefs

**How to reproduce it (as minimally and precisely as possible)**:
Just setup hadoop 3.3.4 / flink 1.15.4 based on juicefs, a hive 3.1.2 table with data.

**Anything else we need to know?**

**Environment**:
- JuiceFS version (use `juicefs --version`) or Hadoop Java SDK version:
1.02
- Cloud provider or hardware configuration running JuiceFS:
premier hardware
- OS (e.g `cat /etc/os-release`):
centos7, k8s 1.21
- Kernel (e.g. `uname -a`):
3.10.0-1160.80.1.el7.x86_64
- Object storage (cloud provider and region, or self maintained):
minio
- Metadata engine info (version, cloud provider managed or self maintained):
redis
- Network connectivity (JuiceFS to metadata engine, JuiceFS to object storage):
1000M ethernet
- Others:

**Comment by tangyoupeng** [comment]
org.apache.flink.table.api.ValidationException: Could not find any factory for identifier 'hive' that implements 'org.apache.flink.table.planner.delegation.ParserFactory' in the classpath.

This is a problem of integration of hive and flink. 

You can refer to: https://nightlies.apache.org/flink/flink-docs-release-1.15/docs/connectors/table/hive/overview/ 

It works for me after  follow this doc
