### ISSUE TITLE
setting bucket policy is not supported through minio gateway juicefs

### ISSUE THREAD

**Issue by crushCoin** [juicedata/juicefs#3375]
**What happened**:
API: PutBucketPolicy(bucket=67a21de05095d0fca39dc3f4d5f7bde074c252328a4c152b0d1ca4a082559d73, object=5e76d207cf4ab20866fdc03c83e8a0f4e8f458e880777956ec0bae4e9f23f6c5)
Time: 03:01:13 UTC 03/24/2023
DeploymentID: e384e517-74a7-48fc-a2e6-9afdae1507b0
RequestID: 174F3BBE1D6A69EB
RemoteHost: dcbf8706e69d7aac53fd791b49a56f30f8ca42d26922e0dd2abb8abb5ddd9030
Host: 192.168.1.156:9000
UserAgent: MinIO (Windows 10; amd64) minio-java/8.2.1
Error: cmd.NotImplemented
       4: cmd/gateway-unsupported.go:125:cmd.GatewayUnsupported.SetBucketPolicy()
       3: cmd/bucket-metadata-sys.go:92:cmd.(*BucketMetadataSys).Update()
       2: cmd/bucket-policy-handlers.go:106:cmd.objectAPIHandlers.PutBucketPolicyHandler()
       1: net/http/server.go:2084:http.HandlerFunc.ServeHTTP()

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**

**Environment**:
- JuiceFS version (use `juicefs --version`) or Hadoop Java SDK version:
- Cloud provider or hardware configuration running JuiceFS:
- OS (e.g `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Object storage (cloud provider and region, or self maintained):
- Metadata engine info (version, cloud provider managed or self maintained):
- Network connectivity (JuiceFS to metadata engine, JuiceFS to object storage):
- Others:

**Comment by zhijian-pro** [comment]
juicefs gateway does not support this feature, you can try our other version，ref https://juicefs.com/docs/community/s3_gateway/#use-a-full-featured-s3-gateway

**Comment by crushCoin** [comment]
> juicefs gateway does not support this feature, you can try our other version，ref https://juicefs.com/docs/community/s3_gateway/#use-a-full-featured-s3-gateway

the same error.

I want to achieve anonymous access to files uploaded from Juicefs to Minio through the URL by setting bucket access policies, without logging in

**Comment by zhijian-pro** [comment]
anonymous access can try this setting
https://juicefs.com/docs/community/how_to_setup_object_storage/#amazon-s3:~:text=If%20the%20S3%20bucket%20has%20public%20access%20(anonymous%20access%20is%20supported)%2C%20please%20set%20%2D%2Daccess%2Dkey%20to%20anonymous.

**Comment by zhijian-pro** [comment]
> > juicefs gateway does not support this feature, you can try our other version，ref https://juicefs.com/docs/community/s3_gateway/#use-a-full-featured-s3-gateway
> 
> the same error.
> 
> I want to achieve anonymous access to files uploaded from Juicefs to Minio through the URL by setting bucket access policies, without logging in

I think minio disabled this feature on s3gateway

**Comment by davies** [comment]
@crushCoin The WebDAV can provide anonymous access via HTTP, does that work with you?

**Comment by zhijian-pro** [comment]
done by #4030
