### ISSUE TITLE
Add Scoop or Chocolatey manifest for Windows

### ISSUE THREAD

**Issue by wizpresso-steve-cy-fan** [juicedata/juicefs#3406]
**What would you like to be added**:

It would be so much better if I can `scoop install juicefs` or `cinst juicefs`

**Why is this needed**:

Convenience and reproducible

**Comment by yuhr123** [comment]
Hello @wizpresso-steve-cy-fan , JuiceFS has been added to [Scoop](https://scoop.sh/) main repo, feel free to try:

```powershell
scoop update
scoop install juicefs
```
