### ISSUE TITLE
fluid+juicefs The display directory is read-only

### ISSUE THREAD

**Issue by xiashengjie** [juicedata/juicefs#3475]
### Discussed in https://github.com/juicedata/juicefs/discussions/3474

<div type='discussions-op-text'>

<sup>Originally posted by **xiashengjie** April 13, 2023</sup>
Use the following configuration file
### dataset.yaml
apiVersion: data.fluid.io/v1alpha1
kind: Dataset
metadata:
  name: jfsdemo
spec:
  mounts:
    - name: minio
      mountPoint: "juicefs:///demo"
      options:
        bucket: "http://192.168.103.129:9000/fluid"
        storage: "minio"
      encryptOptions:
        - name: metaurl
          valueFrom:
            secretKeyRef:
              name: jfs-secret
              key: metaurl
        - name: access-key
          valueFrom:
            secretKeyRef:
              name: jfs-secret
              key: access-key
        - name: secret-key
          valueFrom:
            secretKeyRef:
              name: jfs-secret
              key: secret-key

### runtime.yaml
apiVersion: data.fluid.io/v1alpha1
kind: JuiceFSRuntime
metadata:
  name: jfsdemo
spec:
  replicas: 1
  tieredstore:
    levels:
      - mediumtype: MEM
        path: /dev/shm
        quota: 40Gi
        low: "0.1"

### log
2023/04/13 04:37:56.318179 juicefs[6] <INFO>: Meta address: redis://192.168.103.140:6379/1 [interface.go:402]
2023/04/13 04:37:56.332463 juicefs[6] <INFO>: Ping redis: 979.547µs [redis.go:2878]
2023/04/13 04:37:56.336622 juicefs[6] <INFO>: Data use minio://192.168.103.129:9000/fluid/minio/ [format.go:435]
2023/04/13 04:37:56.375521 juicefs[6] <INFO>: Volume is formatted as {
  "Name": "minio",
  "UUID": "48b0ef8c-5040-415e-b228-96e4e9a2c708",
  "Storage": "minio",
  "Bucket": "http://192.168.103.129:9000/fluid",
  "AccessKey": "minioadmin",
  "SecretKey": "removed",
  "BlockSize": 4096,
  "Compression": "none",
  "KeyEncrypted": true,
  "TrashDays": 1,
  "MetaVersion": 1
} [format.go:472]
2023/04/13 04:37:56.648638 juicefs[22] <INFO>: Meta address: redis://192.168.103.140:6379/1 [interface.go:402]
2023/04/13 04:37:56.655804 juicefs[22] <INFO>: Ping redis: 855.124µs [redis.go:2878]
2023/04/13 04:37:56.657691 juicefs[22] <FATAL>: Meta redis://192.168.103.140:6379/1 is not available: lookup subdir demo: read-only file system [interface.go:409]

How can I solve this problem?</div>

**Comment by zwwhdls** [comment]
Hi @xiashengjie , dataset default accessModes is ReadOnlyMany. You can set accessMode to ReadWriteMany referring to https://github.com/fluid-cloudnative/fluid/blob/master/docs/zh/samples/data_accessmodes.md

**Comment by xiashengjie** [comment]
How can I fetch juicefs metrics when using juicefsruntime in fluid? Any examples?
@zwwhdls
