### ISSUE TITLE
Trino raises "End of file reached before reading fully" when reading parquet in JuiceFS

### ISSUE THREAD

**Issue by fzn0268** [juicedata/juicefs#3482]
**What happened**:
Trino often raises exceptions as quoted in title when reading parquet files, and Pread EOF records appears in access log accordingly. However the parquet files obtained from mounted folder are complete.

**What you expected to happen**:
Read fully and no exception on complete files like this.

**How to reproduce it (as minimally and precisely as possible)**:
Just query, it seems be unable to find a way to reproduce precisely.

**Anything else we need to know?**
Size of parquet files is about 10MB to 110MB.
Cannot find any juicefs log in log of trino.
Added some access logs to pread function in pkg/fs/fs.go, find that offset(some number Trino wants but less than file size) > File.info.Size()(always 4096) in EOF log lines, however OK lines appear previously.

**Environment**:
- JuiceFS version (use `juicefs --version`) or Hadoop Java SDK version: 1.0.4
- Cloud provider or hardware configuration running JuiceFS: HuaweiCloud
- OS (e.g `cat /etc/os-release`): EulerOS 2.0 (SP2)
- Kernel (e.g. `uname -a`): Linux 3.10.0 x86_64
- Object storage (cloud provider and region, or self maintained): HuaweiCloud OBS
- Metadata engine info (version, cloud provider managed or self maintained): PostgreSQL, HuaweiCloud RDS
- Network connectivity (JuiceFS to metadata engine, JuiceFS to object storage):
- Others:
[eof-log.zip](https://github.com/juicedata/juicefs/files/11247956/eof-log.zip)

**Comment by tangyoupeng** [comment]
Could you also add the accesslog file and the trino file to this issue

**Comment by tangyoupeng** [comment]
@fzn0268 Did you change the code or just use the juicefs-hadoop jar from github release. And what kind of meta engine did you use?

**Comment by fzn0268** [comment]
> @fzn0268 Did you change the code or just use the juicefs-hadoop jar from github release. And what kind of meta engine did you use?

just use the juicefs-hadoop jar from github release, only add some lines to print access log of eof pread, meta engine is postgresql.

**Comment by tangyoupeng** [comment]
Can you provide the juicefs conf in the core-site

**Comment by tangyoupeng** [comment]
Are you in our wechat group?

**Comment by davies** [comment]
It would be great if you can provide a way to reproduce this issue. 

My guess is the Attr is modified by other threads, can you print all the fields of Attr when it failed?

**Comment by fzn0268** [comment]
> Can you provide the juicefs conf in the core-site

sorry I forget to reply
`
<property>
<name>juicefs.dir-entry-cache</name>
<value>60</value>
</property>
<property>
<name>juicefs.backup-meta</name>
<value>0</value>
</property>
<property>
<name>juicefs.meta</name>
<value>postgres://user:pw@@x.x.x.x:x/juicefs</value>
</property>
<property>
<name>juicefs.attr-cache</name>
<value>60</value>
</property>
<property>
<name>juicefs.no-bgjob</name>
<value>true</value>
</property>
<property>
<name>fs.jfs.impl</name>
<value>io.juicefs.JuiceFileSystem</value>
</property>
<property>
<name>fs.AbstractFileSystem.jfs.impl</name>
<value>io.juicefs.JuiceFS</value>
</property>
<property>
<name>juicefs.cache-dir</name>
<value>/jfscache</value>
</property>
<property>
<name>juicefs.cache-full-block</name>
<value>true</value>
</property>
<property>
<name>juicefs.entry-cache</name>
<value>60</value>
</property>
<property>
<name>juicefs.cache-size</name>
<value>10240</value>
</property>
<property>
<name>juicefs.access-log</name>
<value>/tmp/juicefs.access.log</value>
</property>
<property>
<name>juicefs.open-cache</name>
<value>60</value>
</property>
`

**Comment by fzn0268** [comment]
> It would be great if you can provide a way to reproduce this issue.
> 
> My guess is the Attr is modified by other threads, can you print all the fields of Attr when it failed?

I add File.info.attr struct log using File.fs.log() in pread function when offset larger than f.info.Size(), is this enough?

**Comment by davies** [comment]
> > It would be great if you can provide a way to reproduce this issue.
> > My guess is the Attr is modified by other threads, can you print all the fields of Attr when it failed?
> 
> I add File.info.attr struct log using File.fs.log() in pread function when offset larger than f.info.Size(), is this enough?

yes

**Comment by tangyoupeng** [comment]
Can you try close dir-entry-cache, entry-cache, attr-cache, open-cache and see if the error still exists.

**Comment by fzn0268** [comment]
> > > It would be great if you can provide a way to reproduce this issue.
> > > My guess is the Attr is modified by other threads, can you print all the fields of Attr when it failed?
> > 
> > 
> > I add File.info.attr struct log using File.fs.log() in pread function when offset larger than f.info.Size(), is this enough?
> 
> yes

pread (/a/b/c/d/e.db/f/month=202208/day=9/part-00001-65217629-b31f-4229-ad9b-db812c4c6e93.c000.snappy.parquet,10016459,4096): (0,EOF) offset(4096) >= f.info.Size()(4096) Attr: &{Flags:0 Typ:2 Mode:511 Uid:0 Gid:0 Rdev:0 Atime:1671415951 Mtime:1676016154 Ctime:1676016154 Atimensec:872490000 Mtimensec:603499000 Ctimensec:603499000 Nlink:8 Length:4096 Parent:1 Full:true KeepCache:true}

this is the attr when it failed, indicates the length is only 4096, but in directory mounted by juicefsctl, the length of this file is 116937516, the table stores archive, so no other apps modify it.

**Comment by davies** [comment]
The attr logged is from another inode (a directory), so it could be overwrite of misused. 

Can you disable these cache ( dir-entry-cache, entry-cache, attr-cache, open-cache) one by one to find which one is related to the bug?

**Comment by fzn0268** [comment]
> > > > It would be great if you can provide a way to reproduce this issue.
> > > > My guess is the Attr is modified by other threads, can you print all the fields of Attr when it failed?
> > > 
> > > 
> > > I add File.info.attr struct log using File.fs.log() in pread function when offset larger than f.info.Size(), is this enough?
> > 
> > 
> > yes
> 
> pread (/a/b/c/d/e.db/f/month=202208/day=9/part-00001-65217629-b31f-4229-ad9b-db812c4c6e93.c000.snappy.parquet,10016459,4096): (0,EOF) offset(4096) >= f.info.Size()(4096) Attr: &{Flags:0 Typ:2 Mode:511 Uid:0 Gid:0 Rdev:0 Atime:1671415951 Mtime:1676016154 Ctime:1676016154 Atimensec:872490000 Mtimensec:603499000 Ctimensec:603499000 Nlink:8 Length:4096 Parent:1 Full:true KeepCache:true}
> 
> this is the attr when it failed, indicates the length is only 4096, but in directory mounted by juicefsctl, the length of this file is 116937516, the table stores archive, so no other apps modify it.

except for "End of file" exception, sometimes it raises "not found" exception
`
Caused by: java.io.FileNotFoundException: jfs://juicefs/a/b/c/d/e.db/f/month=202208/day=5/part-00000-65217629-b31f-4229-ad9b-db812c4c6e93.c000.snappy.parquet: not found
	at io.juicefs.JuiceFileSystemImpl.error(JuiceFileSystemImpl.java:196)
	at io.juicefs.JuiceFileSystemImpl.open(JuiceFileSystemImpl.java:974)
	at org.apache.hadoop.fs.FilterFileSystem.open(FilterFileSystem.java:164)
	at org.apache.hadoop.fs.PrestoFileSystemCache$FileSystemWrapper.open(PrestoFileSystemCache.java:325)
	at org.apache.hadoop.fs.FileSystem.open(FileSystem.java:899)
	at io.prestosql.plugin.hive.parquet.ParquetPageSourceFactory.createParquetPageSource(ParquetPageSourceFactory.java:160)
	... 21 more
`
I tried to set dir-entry-cache, entry-cache, attr-cache, open-cache all to 0 on over half nodes, "end of file" and "not found" exceptions appear on nodes from both halves.

**Comment by davies** [comment]
Is it possible that the file was read after close? You can grep the accesslog to verify that.

**Comment by fzn0268** [comment]
> Is it possible that the file was read after close? You can grep the accesslog to verify that.

I started query at 10:59, it raised  that "not found" exception, access log about the file:
`
2023.05.30 10:51:47.649872 [uid:2000,gid:10,pid:6769053] Pread (/a/b/c/d/e.db/f/month=202208/day=5/part-00000-65217629-b31f-4229-ad9b-db812c4c6e93.c000.snappy.parquet,9645451,33950842): (9645451,OK) <0.009996>
2023.05.30 10:51:47.655494 [uid:2000,gid:10,pid:6769053] Close (/a/b/c/d/e.db/f/month=202208/day=5/part-00000-65217629-b31f-4229-ad9b-db812c4c6e93.c000.snappy.parquet): OK <0.000004>
...... before query
2023.05.30 10:59:59.432703 [uid:2000,gid:10,pid:6769056] Open (/a/b/c/d/e.db/f/month=202208/day=5/part-00000-65217629-b31f-4229-ad9b-db812c4c6e93.c000.snappy.parquet,4): OK <0.589402>
...... no close log
2023.05.30 10:59:59.754723 [uid:2000,gid:10,pid:6769053] Open (/a/b/c/d/e.db/f/month=202208/day=5/part-00000-65217629-b31f-4229-ad9b-db812c4c6e93.c000.snappy.parquet,4): OK <0.788270>
2023.05.30 10:59:59.754880 [uid:2000,gid:10,pid:6769053] Pread (/a/b/c/d/e.db/f/month=202208/day=5/part-00000-65217629-b31f-4229-ad9b-db812c4c6e93.c000.snappy.parquet,8,117338793): (8,OK) <0.000112>
2023.05.30 10:59:59.754932 [uid:2000,gid:10,pid:6769053] Pread (/a/b/c/d/e.db/f/month=202208/day=5/part-00000-65217629-b31f-4229-ad9b-db812c4c6e93.c000.snappy.parquet,26762,117312031): (26762,OK) <0.000004>
2023.05.30 10:59:59.763713 [uid:2000,gid:10,pid:6769053] Pread (/a/b/c/d/e.db/f/month=202208/day=5/part-00000-65217629-b31f-4229-ad9b-db812c4c6e93.c000.snappy.parquet,4403336,101977019): (4403336,OK) <0.005857>
2023.05.30 10:59:59.767809 [uid:2000,gid:10,pid:6769053] Close (/a/b/c/d/e.db/f/month=202208/day=5/part-00000-65217629-b31f-4229-ad9b-db812c4c6e93.c000.snappy.parquet): OK <0.000003>
......
2023.05.30 11:00:00.014803 [uid:2000,gid:10,pid:6769419] Open (/a/b/c/d/e.db/f/month=202208/day=5/part-00000-65217629-b31f-4229-ad9b-db812c4c6e93.c000.snappy.parquet,4): OK <1.171445>
2023.05.30 11:00:00.015125 [uid:2000,gid:10,pid:6769419] Pread (/a/b/c/d/e.db/f/month=202208/day=5/part-00000-65217629-b31f-4229-ad9b-db812c4c6e93.c000.snappy.parquet,8,117338793): (8,OK) <0.000269>
2023.05.30 11:00:00.015181 [uid:2000,gid:10,pid:6769419] Pread (/a/b/c/d/e.db/f/month=202208/day=5/part-00000-65217629-b31f-4229-ad9b-db812c4c6e93.c000.snappy.parquet,26762,117312031): (26762,OK) <0.000006>
2023.05.30 11:00:00.016115 [uid:2000,gid:10,pid:6769419] Close (/a/b/c/d/e.db/f/month=202208/day=5/part-00000-65217629-b31f-4229-ad9b-db812c4c6e93.c000.snappy.parquet): OK <0.000003>
`
in presto query overview, the query elapsed about 900 ms, the log seems no read after close

**Comment by fzn0268** [comment]
> @fzn0268 can you try #3716 and post the access log here?

2023.05.30 21:45:21.886203 [uid:2000,gid:10,pid:24203061] Open (/wuling/user/hive/warehouse/sgmw_big_data2.db/user_event_parquet/dtmonth=202301/dtday=20/part-00009-a3d2c1ad-dabc-4b9b-84c9-42e6ff0a159d.c000.snappy.parquet,4): OK &{Flags:0 Typ:1 Mode:420 Uid:0 Gid:0 Rdev:0 Atime:1680771900 Mtime:1680771913 Ctime:1680772120 Atimensec:909847000 Mtimensec:787500000 Ctimensec:604942000 Nlink:1 Length:98333332 Parent:9939342 Full:true KeepCache:false} <1.178487>
2023.05.30 21:45:21.888661 [uid:2000,gid:10,pid:24203061] Pread (/wuling/user/hive/warehouse/sgmw_big_data2.db/user_event_parquet/dtmonth=202301/dtday=20/part-00009-a3d2c1ad-dabc-4b9b-84c9-42e6ff0a159d.c000.snappy.parquet,8,98333324): (8,OK) &{Flags:0 Typ:1 Mode:420 Uid:0 Gid:0 Rdev:0 Atime:1680771900 Mtime:1680771913 Ctime:1680772120 Atimensec:909847000 Mtimensec:787500000 Ctimensec:604942000 Nlink:1 Length:98333332 Parent:9939342 Full:true KeepCache:false} <0.002403>
2023.05.30 21:45:21.888712 [uid:2000,gid:10,pid:24203061] Pread (/wuling/user/hive/warehouse/sgmw_big_data2.db/user_event_parquet/dtmonth=202301/dtday=20/part-00009-a3d2c1ad-dabc-4b9b-84c9-42e6ff0a159d.c000.snappy.parquet,21540,98311784): (21540,OK) &{Flags:0 Typ:1 Mode:420 Uid:0 Gid:0 Rdev:0 Atime:1680771900 Mtime:1680771913 Ctime:1680772120 Atimensec:909847000 Mtimensec:787500000 Ctimensec:604942000 Nlink:1 Length:98333332 Parent:9939342 Full:true KeepCache:false} <0.000004>
2023.05.30 21:45:22.097953 [uid:2000,gid:10,pid:24203061] Pread (/wuling/user/hive/warehouse/sgmw_big_data2.db/user_event_parquet/dtmonth=202301/dtday=20/part-00009-a3d2c1ad-dabc-4b9b-84c9-42e6ff0a159d.c000.snappy.parquet,150929,11325525): (150929,OK) &{Flags:0 Typ:2 Mode:511 Uid:0 Gid:0 Rdev:0 Atime:1671415951 Mtime:1676016154 Ctime:1676016154 Atimensec:872490000 Mtimensec:603499000 Ctimensec:603499000 Nlink:8 Length:4096 Parent:1 Full:true KeepCache:false} <0.208384>
2023.05.30 21:45:22.098236 [uid:2000,gid:10,pid:24203061] pread (/wuling/user/hive/warehouse/sgmw_big_data2.db/user_event_parquet/dtmonth=202301/dtday=20/part-00009-a3d2c1ad-dabc-4b9b-84c9-42e6ff0a159d.c000.snappy.parquet,152517,45093471): (0,EOF) offset(45093471) >= f.info.Size()(4096) Attr: &{Flags:0 Typ:2 Mode:511 Uid:0 Gid:0 Rdev:0 Atime:1671415951 Mtime:1676016154 Ctime:1676016154 Atimensec:872490000 Mtimensec:603499000 Ctimensec:603499000 Nlink:8 Length:4096 Parent:1 Full:true KeepCache:false}
2023.05.30 21:45:22.098264 [uid:2000,gid:10,pid:24203061] Pread (/wuling/user/hive/warehouse/sgmw_big_data2.db/user_event_parquet/dtmonth=202301/dtday=20/part-00009-a3d2c1ad-dabc-4b9b-84c9-42e6ff0a159d.c000.snappy.parquet,152517,45093471): (0,EOF) &{Flags:0 Typ:2 Mode:511 Uid:0 Gid:0 Rdev:0 Atime:1671415951 Mtime:1676016154 Ctime:1676016154 Atimensec:872490000 Mtimensec:603499000 Ctimensec:603499000 Nlink:8 Length:4096 Parent:1 Full:true KeepCache:false} <0.000051>
2023.05.30 21:45:22.098397 [uid:2000,gid:10,pid:24203061] Close (/wuling/user/hive/warehouse/sgmw_big_data2.db/user_event_parquet/dtmonth=202301/dtday=20/part-00009-a3d2c1ad-dabc-4b9b-84c9-42e6ff0a159d.c000.snappy.parquet): OK &{Flags:0 Typ:2 Mode:511 Uid:0 Gid:0 Rdev:0 Atime:1671415951 Mtime:1676016154 Ctime:1676016154 Atimensec:872490000 Mtimensec:603499000 Ctimensec:603499000 Nlink:8 Length:4096 Parent:1 Full:true KeepCache:false} <0.000001>

**Comment by fzn0268** [comment]
> @fzn0268 can you try #3716 and post the access log here?

2023.05.30 21:45:21.886203 [uid:2000,gid:10,pid:24203061] Open (/a/b/c/d/e.db/f/month=202301/day=20/part-00009-a3d2c1ad-dabc-4b9b-84c9-42e6ff0a159d.c000.snappy.parquet,4): OK &{Flags:0 Typ:1 Mode:420 Uid:0 Gid:0 Rdev:0 Atime:1680771900 Mtime:1680771913 Ctime:1680772120 Atimensec:909847000 Mtimensec:787500000 Ctimensec:604942000 Nlink:1 Length:98333332 Parent:9939342 Full:true KeepCache:false} <1.178487>
2023.05.30 21:45:21.888661 [uid:2000,gid:10,pid:24203061] Pread (/a/b/c/d/e.db/f/month=202301/day=20/part-00009-a3d2c1ad-dabc-4b9b-84c9-42e6ff0a159d.c000.snappy.parquet,8,98333324): (8,OK) &{Flags:0 Typ:1 Mode:420 Uid:0 Gid:0 Rdev:0 Atime:1680771900 Mtime:1680771913 Ctime:1680772120 Atimensec:909847000 Mtimensec:787500000 Ctimensec:604942000 Nlink:1 Length:98333332 Parent:9939342 Full:true KeepCache:false} <0.002403>
2023.05.30 21:45:21.888712 [uid:2000,gid:10,pid:24203061] Pread (/a/b/c/d/e.db/f/month=202301/day=20/part-00009-a3d2c1ad-dabc-4b9b-84c9-42e6ff0a159d.c000.snappy.parquet,21540,98311784): (21540,OK) &{Flags:0 Typ:1 Mode:420 Uid:0 Gid:0 Rdev:0 Atime:1680771900 Mtime:1680771913 Ctime:1680772120 Atimensec:909847000 Mtimensec:787500000 Ctimensec:604942000 Nlink:1 Length:98333332 Parent:9939342 Full:true KeepCache:false} <0.000004>
2023.05.30 21:45:22.097953 [uid:2000,gid:10,pid:24203061] Pread (/a/b/c/d/e.db/f/month=202301/day=20/part-00009-a3d2c1ad-dabc-4b9b-84c9-42e6ff0a159d.c000.snappy.parquet,150929,11325525): (150929,OK) &{Flags:0 Typ:2 Mode:511 Uid:0 Gid:0 Rdev:0 Atime:1671415951 Mtime:1676016154 Ctime:1676016154 Atimensec:872490000 Mtimensec:603499000 Ctimensec:603499000 Nlink:8 Length:4096 Parent:1 Full:true KeepCache:false} <0.208384>
2023.05.30 21:45:22.098236 [uid:2000,gid:10,pid:24203061] pread (/a/b/c/d/e.db/f/month=202301/day=20/part-00009-a3d2c1ad-dabc-4b9b-84c9-42e6ff0a159d.c000.snappy.parquet,152517,45093471): (0,EOF) offset(45093471) >= f.info.Size()(4096) Attr: &{Flags:0 Typ:2 Mode:511 Uid:0 Gid:0 Rdev:0 Atime:1671415951 Mtime:1676016154 Ctime:1676016154 Atimensec:872490000 Mtimensec:603499000 Ctimensec:603499000 Nlink:8 Length:4096 Parent:1 Full:true KeepCache:false}
2023.05.30 21:45:22.098264 [uid:2000,gid:10,pid:24203061] Pread (/a/b/c/d/e.db/f/month=202301/day=20/part-00009-a3d2c1ad-dabc-4b9b-84c9-42e6ff0a159d.c000.snappy.parquet,152517,45093471): (0,EOF) &{Flags:0 Typ:2 Mode:511 Uid:0 Gid:0 Rdev:0 Atime:1671415951 Mtime:1676016154 Ctime:1676016154 Atimensec:872490000 Mtimensec:603499000 Ctimensec:603499000 Nlink:8 Length:4096 Parent:1 Full:true KeepCache:false} <0.000051>
2023.05.30 21:45:22.098397 [uid:2000,gid:10,pid:24203061] Close (/a/b/c/d/e.db/f/month=202301/day=20/part-00009-a3d2c1ad-dabc-4b9b-84c9-42e6ff0a159d.c000.snappy.parquet): OK &{Flags:0 Typ:2 Mode:511 Uid:0 Gid:0 Rdev:0 Atime:1671415951 Mtime:1676016154 Ctime:1676016154 Atimensec:872490000 Mtimensec:603499000 Ctimensec:603499000 Nlink:8 Length:4096 Parent:1 Full:true KeepCache:false} <0.000001>

**Comment by davies** [comment]
Can you change the %+v to %p in logging format? We want to know whether the attr is changed or the content of it is changed.

**Comment by fzn0268** [comment]
> Can you change the %+v to %p in logging format? We want to know whether the attr is changed or the content of it is changed.

2023.05.31 10:45:18.788587 [uid:2000,gid:10,pid:24627072] Open (/a/b/c/d/e.db/f/month=202212/day=1/part-00009-e5a19ae4-01c0-4b11-a7da-c3f450224ed7.c000.snappy.parquet,4): OK 0xc00352caa0 <0.337112>
2023.05.31 10:45:18.788955 [uid:2000,gid:10,pid:24627072] Pread (/a/b/c/d/e.db/f/month=202212/day=1/part-00009-e5a19ae4-01c0-4b11-a7da-c3f450224ed7.c000.snappy.parquet,8,96441277): (8,OK) 0xc00352caa0 <0.000319>
2023.05.31 10:45:18.789014 [uid:2000,gid:10,pid:24627072] Pread (/a/b/c/d/e.db/f/month=202212/day=1/part-00009-e5a19ae4-01c0-4b11-a7da-c3f450224ed7.c000.snappy.parquet,21273,96420004): (21273,OK) 0xc00352caa0 <0.000008>
2023.05.31 10:45:18.791469 [uid:2000,gid:10,pid:24627072] Pread (/a/b/c/d/e.db/f/month=202212/day=1/part-00009-e5a19ae4-01c0-4b11-a7da-c3f450224ed7.c000.snappy.parquet,136762,12092755): (136762,OK) 0xc00352caa0 <0.000979>
2023.05.31 10:45:18.792512 [uid:2000,gid:10,pid:24627072] Pread (/a/b/c/d/e.db/f/month=202212/day=1/part-00009-e5a19ae4-01c0-4b11-a7da-c3f450224ed7.c000.snappy.parquet,137499,45487434): (137499,OK) 0xc00352caa0 <0.000761>
2023.05.31 10:45:18.877248 [uid:2000,gid:10,pid:24627072] Pread (/a/b/c/d/e.db/f/month=202212/day=1/part-00009-e5a19ae4-01c0-4b11-a7da-c3f450224ed7.c000.snappy.parquet,475902,29451784): (475902,OK) 0xc00352caa0 <0.084227>
2023.05.31 10:45:19.035079 [uid:2000,gid:10,pid:24627072] Pread (/a/b/c/d/e.db/f/month=202212/day=1/part-00009-e5a19ae4-01c0-4b11-a7da-c3f450224ed7.c000.snappy.parquet,41079,33236576): (41079,OK) 0xc00352caa0 <0.157287>
2023.05.31 10:45:19.040229 [uid:2000,gid:10,pid:24627072] Pread (/a/b/c/d/e.db/f/month=202212/day=1/part-00009-e5a19ae4-01c0-4b11-a7da-c3f450224ed7.c000.snappy.parquet,136762,12092755): (136762,OK) 0xc00352caa0 <0.004835>
2023.05.31 10:45:19.058446 [uid:2000,gid:10,pid:24627072] Pread (/a/b/c/d/e.db/f/month=202212/day=1/part-00009-e5a19ae4-01c0-4b11-a7da-c3f450224ed7.c000.snappy.parquet,1065427,10647109): (1065427,OK) 0xc00352caa0 <0.003994>
2023.05.31 10:45:19.066598 [uid:2000,gid:10,pid:24627072] Pread (/a/b/c/d/e.db/f/month=202212/day=1/part-00009-e5a19ae4-01c0-4b11-a7da-c3f450224ed7.c000.snappy.parquet,494897,31112098): (494897,OK) 0xc00352caa0 <0.004156>
2023.05.31 10:45:19.069388 [uid:2000,gid:10,pid:24627072] Pread (/a/b/c/d/e.db/f/month=202212/day=1/part-00009-e5a19ae4-01c0-4b11-a7da-c3f450224ed7.c000.snappy.parquet,150773,33277655): (150773,OK) 0xc00352caa0 <0.000031>
2023.05.31 10:45:19.321343 [uid:2000,gid:10,pid:24627072] Pread (/a/b/c/d/e.db/f/month=202212/day=1/part-00009-e5a19ae4-01c0-4b11-a7da-c3f450224ed7.c000.snappy.parquet,473245,62775894): (0,EOF) 0xc00352caa0 <0.000119>
2023.05.31 10:45:19.321610 [uid:2000,gid:10,pid:24627072] Close (/a/b/c/d/e.db/f/month=202212/day=1/part-00009-e5a19ae4-01c0-4b11-a7da-c3f450224ed7.c000.snappy.parquet): OK 0xc00352caa0 <0.000001>

**Comment by davies** [comment]
Can you post the whole accesslog here? we need to find whether another thread is using the same attr.

**Comment by fzn0268** [comment]
[juicefs.access.log.gz](https://github.com/juicedata/juicefs/files/11608669/juicefs.access.log.gz)


> Can you post the whole accesslog here? we need to find whether another thread is using the same attr.

**Comment by davies** [comment]
When the attr is wrong, it's always the attribute of same directory /a (parent is 1, or another directory under /). Another strange things is that KeepCache should only be true for files, but it's true for directory (Type=2) in the logging.

I have add more logging in the PR (also the inode ), can you try again?

Is it possible the grant us access to your enviroment or tell us how to reproduce it?

**Comment by fzn0268** [comment]
> When the attr is wrong, it's always the attribute of same directory /a (parent is 1, or another directory under /). Another strange things is that KeepCache should only be true for files, but it's true for directory (Type=2) in the logging.
> 
> I have add more logging in the PR (also the inode ), can you try again?
> 
> Is it possible the grant us access to your enviroment or tell us how to reproduce it?

I added logging codes, will provide more log later.
May be not convenient to grant access :)
It does not always but frequently appears when query especially aggregate the partitions stored at juice fs on trino, has not appeared on spark.
PS: Our team created a cluster with 1 master(6c48g,sys100g,data200g) and 20 worker(4c32g,sys100g,data400g) nodes of Huawei Cloud MRS 2.1 with Trino v308(HWC doesnt provide MRS 2.1 now, I'm not sure if it can be reproduced using current version). Juice file system created with RDS PostgreSQL as meta engine and OBS as data store, we plan to use the cache ability of JFS to accelerate OBS and relieve pressure of limited HDFS capacity. The table is stored at HDFS partitioned by month and day, some earlier partitions moved to jfs.

**Comment by fzn0268** [comment]
more log
[juicefs.access.log.gz](https://github.com/juicedata/juicefs/files/11659197/juicefs.access.log.gz)

**Comment by davies** [comment]
@fzn0268 we found the root cause, could you verify the patch in #3766 ?

**Comment by SandyXSD** [comment]
Need user confirmation
