### ISSUE TITLE
Support `StorageClass` for object storage

### ISSUE THREAD

**Issue by SandyXSD** [juicedata/juicefs#3497]
https://docs.aws.amazon.com/AmazonS3/latest/dev/storage-class-intro.html

**Comment by jyialive** [comment]
Set the storage class of a file, or The file system supports storage class tiering ?

**Comment by solracsf** [comment]
How could `Glacier` be supported?

**Comment by zhijian-pro** [comment]
@solracsf  Storage types that need to be unfrozen before reading will not be supported.

**Comment by zhijian-pro** [comment]
@jyialive The volume level allows you to set a default storage class, and parameters are provided during mount to allow you to override the default storage class.
