### ISSUE TITLE
JuiceFS Mount Pod stuck in init state that 'Data use ceph://<pool_name>/<fs_name>/ [format.go:434]'

### ISSUE THREAD

**Issue by aquarion43** [juicedata/juicefs#3507]
**What happened:**
I deploy juicefs csi on k8s and use Ceph rados as object storage and redis as metadata engine.
And I create pvc and pod that pvc created successfully but pod cannnot attach volume.
The JuiceFS mount pod stuck in init state, and stuck in '<INFO>: Data use ceph://k8s_juicefs_ssd_c1/juicefs/ [format.go:434]'.

**What you expected to happen:**
JuiceFS mount pod should format volume and test pod can mount volume successfully.

**Environment:**
JuiceFS version: 1.0.4
Object storage : Ceph Rados 
Ceph version: 16.2.11
Metadata engine info : redis 6.2

**CSI Pod Status**
NAME                                                                                                                              READY   STATUS ESS GATES
juicefs-csi-controller-0                                                                                                      3/3     Running
juicefs-csi-controller-1                                                                                                      3/3     Running
juicefs-csi-node-85vrp                                                                                                      3/3     Running
juicefs-csi-node-8qngn                                                                                                     3/3     Running
juicefs-csi-node-cb95b                                                                                                      3/3     Running

**JuiceFS Mount Pod Status**
NAME                                                                                                                              READY   STATUS ESS GATES
juicefs-tste-s48-k8s2-ca-0003-pvc-2563a21b-3c33-47b1-a8cc-366055533b2c-raxeaj    0/1     Init:0/1

**Test Pod Status**
NAME                                                                                                                              READY   STATUS ESS GATES
test-juicefs-pod-1                                                                                                               0/1     ContainerCreating

**PVC Status**
NAME        STATUS   VOLUME                                     CAPACITY   ACCESS MODES   STORAGECLASS      AGE
jfs-pvc-1   Bound    pvc-2563a21b-3c33-47b1-a8cc-366055533b2c   1Gi        RWO            test-juicefs-sc   3h15m

**Log - juicefs-plugin Log**
2023-04-21T11:12:30.449482407+08:00 I0421 03:12:30.449374       7 main.go:90] Run CSI controller
2023-04-21T11:12:30.465894306+08:00 I0421 03:12:30.465840       7 driver.go:48] Driver: csi.juicefs.com version v0.19.0 commit 6d8dd58d888b27c08d53596a44162dff4a52d7ba date 2023-04-08T02:23:05Z
2023-04-21T11:12:30.466688685+08:00 I0421 03:12:30.466647       7 driver.go:113] Listening for connection on address: &net.UnixAddr{Name:"/var/lib/csi/sockets/pluginproxy/csi.sock", Net:"unix"}
2023-04-21T11:12:31.169766805+08:00 I0421 03:12:31.169728       7 mount_manager.go:100] Mount manager started.
2023-04-21T11:12:31.169831635+08:00 I0421 03:12:31.169818       7 leaderelection.go:248] attempting to acquire leader lease test-juicefs/mount.juicefs.com...
2023-04-21T11:12:49.559230028+08:00 I0421 03:12:49.559162       7 leaderelection.go:258] successfully acquired lease test-juicefs/mount.juicefs.com
2023-04-21T11:13:20.509265050+08:00 I0421 03:13:20.509189       7 controller.go:70] CreateVolume: Secrets contains keys [bucket configs metaurl name secret-key storage access-key]

**Log - JuiceFS Mount Pod Log**
2023-04-21T11:13:22.315944643+08:00 2023/04/21 03:13:22.315813 juicefs[7] <INFO>: Meta address: redis://172.18.65.171:6379/0 [interface.go:401]
2023-04-21T11:13:22.316640531+08:00 2023/04/21 03:13:22.316556 juicefs[7] <INFO>: redis 172.18.65.171:6379 is in cluster mode [redis.go:169]
2023-04-21T11:13:22.319436689+08:00 2023/04/21 03:13:22.319385 juicefs[7] <WARNING>: AOF is not enabled, you may lose data if Redis is not shutdown properly. [info.go:83]
2023-04-21T11:13:22.319959147+08:00 2023/04/21 03:13:22.319894 juicefs[7] <INFO>: Ping redis: 465.883 [redis.go:2904]
2023-04-21T11:13:22.329038431+08:00 2023/04/21 03:13:22.328991 juicefs[7] <INFO>: Data use ceph://k8s_juicefs_ssd_c1/juicefs/ [format.go:434]

**cph.conf file - /etc/ceph/ceph.conf**
[global]
        fsid = ddba3fba-1c8a-11ed-a0c2-ef8447aa2767
        mon_host = 100.111.9.52:6789

**Comment by zwwhdls** [comment]
Hi @aquarion43 , you need to add ceph.conf in mount pod, referring to https://juicefs.com/docs/zh/csi/guide/pv#mount-pod-extra-files

**Comment by aquarion43** [comment]
Hi @zwwhdls, yes, I get a shell to the running JuiceFS mount container, and check /etc/ceph/ceph.conf and /etc/ceph/ceph.client.admin.keyring files are exists.

**Check Files:**
kubectl -n test-juicefs exec -it $mount -c jfs-format -- bash

**/etc/ceph/ceph.conf**
root@juicefs-hostname-pvc-2563a21b-3c33-47b1-a8cc-36605:/workspace# cat /etc/ceph/ceph.conf
[global]
        fsid = ddba3fba-1c8a-11ed-a0c2-ef8447aa2767
        mon_host = 100.111.9.52:6789
**ceph.client.admin.keyring**
root@juicefs-hostname-pvc-2563a21b-3c33-47b1-a8cc-36605:/workspace# cat /etc/ceph/ceph.client.admin.keyring
[client.admin]
        key =Key
        
**Perform JuiceFS Format in Mount Counter**
root@juicefs-hostname-pvc-2563a21b-3c33-47b1-a8cc-36605:/workspace# juicefs format --storage=ceph --bucket=ceph://k8s_juicefs_ssd_c1 --access-key=ceph --secret-key="client.admin" ${metaurl} juicefs --trace -v
2023/04/21 09:28:51.704026 juicefs[424] <INFO>: Meta address: redis://172.18.65.171:6379/0 [interface.go:401]
2023/04/21 09:28:51.704724 juicefs[424] <INFO>: redis 172.18.65.171:6379 is in cluster mode [redis.go:169]
2023/04/21 09:28:51.707209 juicefs[424] <WARNING>: AOF is not enabled, you may lose data if Redis is not shutdown properly. [info.go:83]
2023/04/21 09:28:51.707619 juicefs[424] <INFO>: Ping redis: 351.661 [redis.go:2904]
2023/04/21 09:28:51.707983 juicefs[424] <DEBUG>: Creating ceph storage at endpoint ceph://k8s_juicefs_ssd_c1 [object_storage.go:154]
2023/04/21 09:28:51.716469 juicefs[424] <INFO>: Data use ceph://k8s_juicefs_ssd_c1/juicefs/ [format.go:434]

**Comment by aquarion43** [comment]
If I use the following format in ceph.conf. I will get 'server name not found' error and cannot connect to cluster.

**Log**
2023/04/21 11:54:49.763425 juicefs[49] <DEBUG>: maxprocs: Leaving GOMAXPROCS=80: CPU quota undefined [maxprocs.go:47]
2023/04/21 11:54:49.763597 juicefs[49] <INFO>: Meta address: redis://172.18.1.5:6379/1 [interface.go:492]
2023/04/21 11:54:49.764483 juicefs[49] <INFO>: redis 172.18.1.5:6379 is in cluster mode [redis.go:198]
2023/04/21 11:54:49.777404 juicefs[49] <WARNING>: AOF is not enabled, you may lose data if Redis is not shutdown properly. [info.go:84]
2023/04/21 11:54:49.778273 juicefs[49] <INFO>: Ping redis: 811.768 [redis.go:3475]
**2023/04/21 11:54:49.778628 juicefs[49] <DEBUG>: Creating ceph storage at endpoint ceph://k8s_juicsfs_ssd_c1 [object_storage.go:164]
server name not found: [v2:100.111.10.31:3300/0 (Name or service not known)
unable to parse addrs in '[v2:100.111.10.31:3300/0,v1:100.111.10.31:6789/0]'
2023/04/21 11:54:49.785746 juicefs[49] <FATAL>: object storage: Can't connect to cluster ceph: rados: ret=22, Invalid argument [format.go:439]**

**/etc/ceph/ceph.conf**
[global]
        fsid = 05e78f60-7a6a-11ec-ab86-e148b7e9f645
        mon_host = [v2:100.111.10.31:3300/0,v1:100.111.10.31:6789/0]

**Comment by zwwhdls** [comment]
Hi @aquarion43 , mon_host in ceph.conf can not be connected. Can you test the ceph.conf out of the mount pod ?

**Comment by aquarion43** [comment]
Hi @zwwhdls , thanks for your reply.
If I use **mon_host = [v2:100.111.10.31:3300/0,v1:100.111.10.31:6789/0]** in ceph.conf, mount pod can not be connected. 

When I use **mon_host = 100.111.9.52:6789** in ceph.conf, mount pod stuck in 'Data use ceph://k8s_juicefs_ssd_c1/juicefs/ [format.go:434]' without Ceph connection issue. 

Is there any issue with the format that caused this situation ?

**Situation 1 - Can't connect to cluster ceph**
**1.1 Mount Pod Log** 
2023/04/21 11:54:49.778628 juicefs[49] : Creating ceph storage at endpoint ceph://k8s_juicsfs_ssd_c1 [object_storage.go:164]
server name not found:[v2:100.111.10.31:3300/0 (Name or service not known)
unable to parse addrs in '[v2:100.111.10.31:3300/0,v1:100.111.10.31:6789/0]'**
**2023/04/21 11:54:49.785746 juicefs[49] : object storage: Can't connect to cluster ceph: rados: ret=22, Invalid argument [format.go:439]
**1.2 ceph.conf**
[global]
fsid = 05e78f60-7a6a-11ec-ab86-e148b7e9f645
mon_host = **[v2:100.111.10.31:3300/0,v1:100.111.10.31:6789/0]**

**Situation 2 - Mount Pod Stuck in 'Data use ceph://k8s_juicefs_ssd_c1/juicefs/ [format.go:434]'**
**2.1 Mount Pod Log**
2023/04/21 09:28:51.704026 juicefs[424] : Meta address: redis://172.18.65.171:6379/0 [interface.go:401]
2023/04/21 09:28:51.704724 juicefs[424] : redis 172.18.65.171:6379 is in cluster mode [redis.go:169]
2023/04/21 09:28:51.707209 juicefs[424] : AOF is not enabled, you may lose data if Redis is not shutdown properly. [info.go:83]
2023/04/21 09:28:51.707619 juicefs[424] : Ping redis: 351.661 [redis.go:2904]
2023/04/21 09:28:51.707983 juicefs[424] : Creating ceph storage at endpoint ceph://k8s_juicefs_ssd_c1 [object_storage.go:154]
2023/04/21 09:28:51.716469 juicefs[424] : Data use ceph://k8s_juicefs_ssd_c1/juicefs/ [format.go:434]
**2.2 ceph.conf**
[global]
fsid = ddba3fba-1c8a-11ed-a0c2-ef8447aa2767
mon_host = **100.111.9.52:6789**

**Comment by SandyXSD** [comment]
The next step is to do a simple test (PUT, GET, DELETE test objects) against the Ceph storage.
Could you try testing the Ceph cluster with the `rados` command directly to see if it works as expected?

**Comment by aquarion43** [comment]
Hi @SandyXSD, there is no rados command in mount pod.
May I ask if there are any steps that are missing or need to be supplemented?

**root@juicefs-host-pvc-38100d3f-26c5-4027-9a70-64345:/workspace# rados df
**bash: rados: command not found****
Mount Pod Image: juicedata/mount:ce-v1.0.4

**Comment by SandyXSD** [comment]
Maybe it's caused by the incompatibility between the go-ceph we used and the Ceph cluster. JuiceFS uses v0.4.0 to support Ceph Luminous, and it doesn't support Pacific as stated [here](https://github.com/ceph/go-ceph#supported-ceph-versions).

**Comment by aquarion43** [comment]
If it is possible to use JuiceFS with Ceph Pacific? And how to set it up?
Thank you.

**Comment by SandyXSD** [comment]
The main branch and release v1.1-beta1 upgrade the go-ceph to v0.18.0 in #3595, so they support Ceph Octopus, Pacific and Quincy.
