### ISSUE TITLE
COMMAND "juicefs sync --worker" ERROR SignatureDoesNotMatch

### ISSUE THREAD

**Issue by lixiaofengfeng** [juicedata/juicefs#3511]
**What happened**: 使用 juicefs sync 命令指定worker后报错
![image](https://user-images.githubusercontent.com/49725515/233819459-42f1e213-bb29-4768-9d91-66bd6704224f.png)

**What you expected to happen**: 正常完成指定目录的数据同步；类似命令在不指定worker时可以同步成功。

**How to reproduce it (as minimally and precisely as possible)**: 

**Anything else we need to know?**

**Environment**:
- JuiceFS version (use `juicefs --version`) or Hadoop Java SDK version: juicefs version 1.0.4+2023-04-06.f1c475d
- Cloud provider or hardware configuration running JuiceFS: 火山云
- OS (e.g `cat /etc/os-release`): ubuntu:22.04
- Kernel (e.g. `uname -a`): x86_64 GNU/Linux
- Object storage (cloud provider and region, or self maintained): 火山云-北京
- Metadata engine info (version, cloud provider managed or self maintained): 
- Network connectivity (JuiceFS to metadata engine, JuiceFS to object storage): 
- Others:

**Comment by davies** [comment]
应该是 worker 机器缺乏访问对象存储的 AK SK，是通过环境变量指定的吗？main 分支已经支持将 环境变量也传递给 worker, 可以试试主分支是否还有这个问题

**Comment by lixiaofengfeng** [comment]
> 

ak sk 是写在命令中的 ，传参的格式是s3://ak:sk@bucketName.endPoint/filePath

**Comment by lixiaofengfeng** [comment]
> 应该是 worker 机器缺乏访问对象存储的 AK SK，是通过环境变量指定的吗？main 分支已经支持将 环境变量也传递给 worker, 可以试试主分支是否还有这个问题

ak sk 是写在命令中的 ，传参的格式是s3://ak:[sk@bucketName.endPoint](mailto:sk@bucketName.endPoint)/filePath

**Comment by davies** [comment]
是不是 AK SK 中有特殊字符？

**Comment by lixiaofengfeng** [comment]
> 是不是 AK SK 中有特殊字符？

sk里面有 / = 符号，用了uri_encode

**Comment by davies** [comment]
找到问题，是 1.0.4 引入的 bug, 我们会先修复它，你改用 1.0.3 吧

**Comment by lixiaofengfeng** [comment]
> 找到问题，是 1.0.4 引入的 bug, 我们会先修复它，你改用 1.0.3 吧

好的，辛苦修复后回复一下
