### ISSUE TITLE
juicefs sync: privilege escalation in remote host

### ISSUE THREAD

**Issue by timfeirg** [juicedata/juicefs#3515]
when using ssh hosts, provided user might not necessarily have access to target path, but can gain access through privilege escalation.

juicefs sync should provide an option to perform this privilege escalation. but on the other hand, users might need to configure this separately for src and dst, maybe it's better to just incorporate this as a automatic check inside juicefs sync (when reading/writing files, check permission and automatically use sudo when needed)?

**Comment by zhijian-pro** [comment]
Sftp is based on the ssh protocol, so a user must be provided, and sftp operations are based on that user, so there is no way to do privileges. 
The only way to privilege is to have an executable program on the remote end, and then run that program with sudo in front of it, such as `rsync-path`.
