### ISSUE TITLE
there are some data races when run go test -race

### ISSUE THREAD

**Issue by pigletfly** [juicedata/juicefs#3523]
**What happened**:

there are some data races when run go test -race ./pkg/... on main branch

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**

**Environment**:
- JuiceFS version (use `juicefs --version`) or Hadoop Java SDK version: m
- Cloud provider or hardware configuration running JuiceFS:
- OS (e.g `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Object storage (cloud provider and region, or self maintained):
- Metadata engine info (version, cloud provider managed or self maintained):
- Network connectivity (JuiceFS to metadata engine, JuiceFS to object storage):
- Others:

**Comment by pigletfly** [comment]
the directories are pkg/chunk ,pkg/fs.

**Comment by SandyXSD** [comment]
The races found are caused by test code or acceptable, we'll just leave them intact.
