### ISSUE TITLE
CDH 5.14.0 hbase cannot start with juicefs 1.0.3

### ISSUE THREAD

**Issue by qiuxinyidian** [juicedata/juicefs#3533]
**What happened**:

if import juicefs-hadoop， hbase can not start sucefully
  
**What you expected to happen**:

hbase can restart sucessfully

**How to reproduce it (as minimally and precisely as possible)**:
change hdfs to juicefs 
**Anything else we need to know?**

**Environment**:
- JuiceFS version (use `juicefs --version`) or Hadoop Java SDK version: 1.0.3
- Cloud provider or hardware configuration running JuiceFS:
- OS (e.g `cat /etc/os-release`): CentOS Linux release 7.8.2003
- Kernel (e.g. `uname -a`):3.10.0-1127.el7.x86_64
- Object storage (cloud provider and region, or self maintained):
- Metadata engine info (version, cloud provider managed or self maintained): tikv
- Network connectivity (JuiceFS to metadata engine, JuiceFS to object storage):
- Others:

to restart hbase we need to mv 
/opt/cloudera/parcels/CDH/lib/hbase/lib/jruby-cloudera-1.0.0.jar  to other folder

if wantting to use hbase shell ，we need copy /opt/cloudera/parcels/CDH/lib/hbase/lib/jruby-cloudera-1.0.0.jar

**Comment by tangyoupeng** [comment]
It's a known issue, jruby also used jnr which is not compatible with JuiceFs used version. Only the hbase shell need jruby and hbase shell node did not use juicefs-hadoop.jar. Maybe you can use a gateway node to run hbase shell that did not install juicefs-hadoop.jar
