### ISSUE TITLE
juicefs adapt impala 

### ISSUE THREAD

**Issue by qiuxinyidian** [juicedata/juicefs#3535]
**What happened**:
impala cannot start with juicefs
 
**What you expected to happen**:
impala works normol with juicefs
**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**

**Environment**:
- JuiceFS version (use `juicefs --version`) or Hadoop Java SDK version:juicefs-1.0.3
- Cloud provider or hardware configuration running JuiceFS:
- OS (e.g `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Object storage (cloud provider and region, or self maintained):
- Metadata engine info (version, cloud provider managed or self maintained):
- Network connectivity (JuiceFS to metadata engine, JuiceFS to object storage):
- Others:

impala-shell -v -V
Impala Shell v2.11.0-cdh5.14.0 (d682065) built on Sat Jan  6 13:27:16 PST 2018

早上8点56:26.033分 INFO Currently configured default filesystem: JuiceFileSystem, fs.defaultF$ (jfs://juicefs/) is not supported.

  0x95adf9 impala::Status:;Status()
  0xba15f6 impala::Frontend::ValidateSettinas()0xbc8e88impala::ImpalaServer::ImpalaServer()
  0xbb502dImpaladMain()
  0x8e1f73main
  0x7f06c38b1555__libc_start_main0x929361(unknown)

can adapt impala upstream ?

**Comment by tangyoupeng** [comment]
Impala did not support jfs scheme. You can modify impala code to work with JuiceFs.

**Comment by simao-k** [comment]
@zhijian-pro When will Impala be compatible？
