### ISSUE TITLE
Implement event notification in s3gateway

### ISSUE THREAD

**Issue by zhijian-pro** [juicedata/juicefs#3537]
First evaluate the complexity of implementing the feature, and if it is easier we will do it.

**Comment by Hexilee** [comment]
It seems the s3-gateway of minio does not support notification and will never support as they [deprecated s3-gateway](https://blog.min.io/deprecation-of-the-minio-gateway/). Their latest [`ObjectLayer`](https://github.com/minio/minio/blob/master/cmd/object-api-interface.go#L184) removed methods about notification.
