### ISSUE TITLE
cannot sync pg data between two pc

### ISSUE THREAD

**Issue by ptrjeffrey** [juicedata/juicefs#3547]
**What happened**:
mount juicefs to sync postgres data between two linux pc.
one pc add data to table.nothing changed on another pc.
**What you expected to happen**:
data changes sync to another pc.
**How to reproduce it (as minimally and precisely as possible)**:
install pg via docker. mount pgdata dir to juicefs.
repeat this operation on another pc.
try to add data or delete data from one side.
**Anything else we need to know?**

**Environment**:
- JuiceFS version (use `juicefs --version`) or Hadoop Java SDK version:  juicefs v1.0.4
- Cloud provider or hardware configuration running JuiceFS: 4core 8G
- OS (e.g `cat /etc/os-release`): centos7
- Kernel (e.g. `uname -a`):  Linux localhost.localdomain 3.10.0-957.el7.x86_64 #1 SMP Thu Nov 8 23:39:32 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
- Object storage (cloud provider and region, or self maintained): self maintained minio
- Metadata engine info (version, cloud provider managed or self maintained): pg13 self maintained.
- Network connectivity (JuiceFS to metadata engine, JuiceFS to object storage): pg13 minio
- Others:

**Comment by zhijian-pro** [comment]
Juicefs sync is a data synchronization tool, but it does not include the ability to listen for file changes.
You need to make sure that postgres data changes fall onto the disk before manually executing juicefs sync.

**Comment by ptrjeffrey** [comment]
copy that.I need a block storage tool I think.
no worries,juicefs is great, it just does not fit this scene.
