### ISSUE TITLE
why updateDirQuota func use parent Inode but not p Inode in  updateParentStat

### ISSUE THREAD

**Issue by ddkddown** [juicedata/juicefs#3563]
for example:
if i use truncate cmd on a hardlink file, it will **checkquota** of the file's parent dirs and i can get these Inode by **getParents** func (these Inode maybe 402, 403.... nums >0 ),
then is this cmd success, it has to update quota,
as the hardlink file's parent Inode will always be 0
in **updateParentStat**, the program will execute these code
```
go func() {
			for p := range m.en.doGetParents(ctx, inode) {
				m.updateDirStat(ctx, p, length, space, 0)
				m.updateDirQuota(ctx, parent, space, 0)
			}
		}()
```

notice that parent is 0 , so in **updateDirQuotafunc** , it will only update m.dirQuotas[0], but not the true parent quota.
is this a bug or something else?

**Comment by SandyXSD** [comment]
Yes, it's a bug, the argument should be `p`.
