### ISSUE TITLE
Run benchmark in parallel

### ISSUE THREAD

**Issue by davies** [juicedata/juicefs#357]
`juicefs bench` run basic benchmark using single threads, which can be run in parallel to know  how it works under concurrent workload.

**Comment by suzaku** [comment]
Do you mean reading and writing blocks in parallel?

**Comment by Sandy4999** [comment]
@suzaku hi, are you still working on this?

**Comment by suzaku** [comment]
@Sandy4999 No, I'm not working on it recently.
