### ISSUE TITLE
Try to use Titan as the metadata store

### ISSUE THREAD

**Issue by davies** [juicedata/juicefs#358]
Titan [1] is built on top of TiKV and speak Redis protocol, which could be used as an drop-in replacement for Redis for bigger scale.

[1] https://github.com/distributedio/titan

**Comment by xiaogaozi** [comment]
Ref to #183

**Comment by Sandy4999** [comment]
Local test result: https://github.com/juicedata/juicefs/pull/386#issuecomment-835653339
