### ISSUE TITLE
juicefs config --storage option

### ISSUE THREAD

**Issue by ak2k** [juicedata/juicefs#3650]
**What would you like to be added**:

`juicefs config` doesn't currently seem to accept a `--storage` parameter. 

**Why is this needed**:

I would like to change the object storage provider (and have migrated my objects using `juicefs sync`). While I can specify `--bucket`, `--access-key`, and `--secret-key`, I can't fully change the backing storage config because I can't change the `--storage` config.

**Comment by zhijian-pro** [comment]
Good suggestion, we will support this feature in the near future, thanks for the feedback

**Comment by davies** [comment]
This is an option for mount to change to `storage`, which is safe.

**Comment by davies** [comment]
> Thank you for getting back to me. If I understand correctly, until this option is [released](https://github.com/juicedata/juicefs/milestone/8), it is safe for me to change the JSON in the metadata table jfs_setting manually by separately editing the storage key?

Yes
