### ISSUE TITLE
Redis Cluster support not working

### ISSUE THREAD

**Issue by tesinormed** [juicedata/juicefs#3651]
**What happened**:
I tried to import a metadata dump into a Redis Cluster, and got this output.
```
juicefs load "redis://:$REDISCLI_PASSWORD@transmission.server.5505.industries.internal:7379,engine.server.5505.industries.internal:7379,vacuole.server.5505.industries.internal:7379"
2023/05/22 01:41:56.869154 juicefs[1] <INFO>: Meta address: redis://:****@transmission.server.5505.industries.internal:7379,engine.server.5505.industries.internal:7379,vacuole.server.5505.industries.internal:7379 [interface.go:401]
2023/05/22 01:41:57.961383 juicefs[1] <WARNING>: parse info: got 4 elements in cluster info address, expected 2 or 3 [redis.go:2884]
2023/05/22 01:41:59.426984 juicefs[1] <FATAL>: got 4 elements in cluster info address, expected 2 or 3 [main.go:31]
```

**What you expected to happen**:
I expected the metadata import to work.

**How to reproduce it (as minimally and precisely as possible)**:
1. Export a JuiceFS instance's metadata.
2. Run `juicefs load "redis://<server1>:<port1>,<server2>:<port2>,<server3>:<port3>"`
3. Loading fails due to error in the "what happened" section.

**Anything else we need to know?**
[go-redis seems to use `redis://localhost:123?addr=localhost:1234&addr=localhost:12345` instead of JuiceFS's format](https://github.com/redis/go-redis/blob/840c25cb6f320501886a82a5e75f47b491e46fbe/cluster_test.go#L1484)

**Environment**:
- JuiceFS version (use `juicefs --version`) or Hadoop Java SDK version: 1.0.4+2023-04-06.f1c475d
- Cloud provider or hardware configuration running JuiceFS: Hetzner Cloud
- OS (e.g `cat /etc/os-release`):
```
NAME="Fedora Linux"
VERSION="38.20230430.3.1 (CoreOS)"
ID=fedora
VERSION_ID=38
VERSION_CODENAME=""
PLATFORM_ID="platform:f38"
PRETTY_NAME="Fedora CoreOS 38.20230430.3.1"
ANSI_COLOR="0;38;2;60;110;180"
LOGO=fedora-logo-icon
CPE_NAME="cpe:/o:fedoraproject:fedora:38"
HOME_URL="https://getfedora.org/coreos/"
DOCUMENTATION_URL="https://docs.fedoraproject.org/en-US/fedora-coreos/"
SUPPORT_URL="https://github.com/coreos/fedora-coreos-tracker/"
BUG_REPORT_URL="https://github.com/coreos/fedora-coreos-tracker/"
REDHAT_BUGZILLA_PRODUCT="Fedora"
REDHAT_BUGZILLA_PRODUCT_VERSION=38
REDHAT_SUPPORT_PRODUCT="Fedora"
REDHAT_SUPPORT_PRODUCT_VERSION=38
SUPPORT_END=2024-05-14
VARIANT="CoreOS"
VARIANT_ID=coreos
OSTREE_VERSION='38.20230430.3.1'
```
- Kernel (e.g. `uname -a`): 6.2.13-300.fc38.x86_64
- Object storage (cloud provider and region, or self maintained): MinIO (using `quay.io/minio/minio:RELEASE.2023-05-18T00-05-36Z`), self hosted
- Metadata engine info (version, cloud provider managed or self maintained): Redis Cluster (using `docker.io/redis:7.0.11-alpine`), self hosted
- Network connectivity (JuiceFS to metadata engine, JuiceFS to object storage): over WireGuard, Docker host network
- Others: JuiceFS's CLI is running in Docker, version 20.10.2

**Comment by zhijian-pro** [comment]
https://github.com/juicedata/juicefs/pull/3233
The Main branch supports redis 7.0, 1.0.4 does not, we will soon release 1.1.0-beta1, which will include this feature.

**Comment by davies** [comment]
Yes. If it's not doable, you can fork the 1.0 branch and add #3233 , build a patched version.
