### ISSUE TITLE
support additional object storage backends via rclone

### ISSUE THREAD

**Issue by ak2k** [juicedata/juicefs#3669]
**What would you like to be added**:

support for using [rclone](https://github.com/rclone/rclone/) to leverage rclone-supported [backends](https://rclone.org/overview/) for juicefs object storage

**Why is this needed**:

[rclone](https://github.com/rclone/rclone/) supports a great many backends already. Utilities like [restic](https://github.com/restic/restic/) [support using rclone's various backends](https://restic.readthedocs.io/en/latest/030_preparing_a_new_repo.html#other-services-via-rclone) in addition to supporting a number of object storage backends directly.

I think it would be great if these backends could be available for use as juicefs object storage.

More selfishly, I would love to be able to use Dropbox for object storage, though an rclone integration would seem to facilitate this and more.

**Implementation ideas**:

- It's not necessary to make rclone a library/dependency. Instead, the restic approach was [here](https://restic.net/blog/2018-04-01/rclone-backend/):
> It turned out that it is also possible to run an HTTP2 connection over stdin/stdout of a newly started process. We’ve implemented this in restic and rclone. Internally, restic runs rclone serve restic --stdio, and it will serve HTTP requests via HTTP2 on stdin/stdout

**Comment by footlooseboss** [comment]
last time I was here, webdav was officially supported storage, and `rclone serve webdav arbitraryremote:/bucketname` passed all tests when run from linux, but not darwin

has anything changed functionally?

**Comment by footlooseboss** [comment]
> @footlooseboss  Can you provide details?
[https://github.com/juicedata/juicefs/issues/1445#issuecomment-1050433377](details)

**Comment by zhijian-pro** [comment]
@ak2k At present juicefs already supports most of the mainstream object storage, these and rclone support object storage there is a big overlap, so I don't think this is a very important requirement, if you think there are other object storage is important but juicefs does not support, you can ask us the issue.
