### ISSUE TITLE
Can not browser files with non-root user through Minio console of the full-featured s3 gateway

### ISSUE THREAD

**Issue by gsoec** [juicedata/juicefs#3692]
**What happened**:
When login with non-root user that has `s3:*` permission, clicking the `Browser` button on a bucket doesn't show the browser page on Minio console.

**What you expected to happen**:
Can browser files like a root user.

**How to reproduce it (as minimally and precisely as possible)**:
```bash
# build the minio
git clone -b gateway git@github.com:juicedata/minio.git && cd minio
make build
# run juicefs with local postgresql-15.3 running
juicefs format "postgres://postgres:postgres@localhost:5432/postgres?sslmode=disable" mybucket
./minio  gateway  juicefs --multi-buckets --keep-etag  --console-address ':59001' "postgres://postgres:postgres@localhost:5432/postgres?sslmode=disable"
```
Login to Minio console with admin and create a new policy called `myuser`
```
{
    "Version": "2012-10-17",
    "Statement": [
        {
          "Action": ["admin:*"],
          "Effect": "Allow"
        },
        {
            "Effect": "Allow",
            "Action": [
                "s3:*"
            ],
            "Resource": [
                "arn:aws:s3:::${aws:username}"
            ]
        }
    ]
}
```
- Create a new non-root user `test-user` and assign the `myuser` policy above
- create a top level of directory `test-user` as buckets
- logout and login with `test-user`
- click `Browser` button on `test-user` bucket. Nothing happen

**Anything else we need to know?**

**Environment**:
- JuiceFS version (use `juicefs --version`) or Hadoop Java SDK version: 1.0.4+2023-04-06.f1c475d
- Cloud provider or hardware configuration running JuiceFS: local disk
- OS (e.g `cat /etc/os-release`): MacOS 12.4
- Kernel (e.g. `uname -a`): Darwin Kernel Version 21.5.0
- Object storage (cloud provider and region, or self maintained): local disk
- Metadata engine info (version, cloud provider managed or self maintained): running at docker image: postgres:15.3-alpine
- Network connectivity (JuiceFS to metadata engine, JuiceFS to object storage): localhost
- Others:
- Minio version : DEVELOPMENT.2023-04-06T06-42-53Z

**Comment by zhijian-pro** [comment]
Your Resource format is strange, `"arn:aws:s3:::*"` is ok
```
{
    "Version": "2012-10-17",
    "Statement": [
        {
          "Action": ["admin:*"],
          "Effect": "Allow"
        },
        {
            "Effect": "Allow",
            "Action": [
                "s3:*"
            ],
            "Resource": [
                "arn:aws:s3:::*"
            ]
        }
    ]
}
```

**Comment by gsoec** [comment]
Inspired by @zhijian-pro 

Manually replacing `${aws:username}` with `test-user` works properly.
It seems that the system does not substitute the `${aws:username}` variable properly when the gateway runs in `--multi-buckets` mode.
```
{
    "Version": "2012-10-17",
    "Statement": [
        {
          "Action": ["admin:*"],
          "Effect": "Allow"
        },
        {
            "Effect": "Allow",
            "Action": [
                "s3:*"
            ],
            "Resource": [
                "arn:aws:s3:::test-user"
            ]
        }
    ]
}
```

**Comment by zhijian-pro** [comment]
Does MinIO have documentation on their support for the `${aws:username}` syntax ?

**Comment by zhijian-pro** [comment]
It may be a bug that this syntax is not supported, it's not a serious problem.
Now that you've found a workaround, I'll close the issue.
