### ISSUE TITLE
touch: setting times of '/jfs2/test797': Input/output error

### ISSUE THREAD

**Issue by zhoucheng361** [juicedata/juicefs#3712]
**What happened**:
    ```
set -ex
    umount /jfs || true
    rm test.db -rf
    rm /var/jfs/myjfs -rf 
    ./juicefs format sqlite3://test.db myjfs 
    ./juicefs mount -d sqlite3://test.db /jfs --heartbeat 5
    mkdir -p /jfs/d
    ./juicefs quota set sqlite3://test.db --path /d --inodes 1000 --capacity 1
    sleep 6s
    ./juicefs dump sqlite3://test.db > dump.json
    rm -rf test2.db
    ./juicefs load sqlite3://test2.db dump.json
    ./juicefs mount sqlite3://test2.db /jfs2 -d --heartbeat 5
    dd if=/dev/zero of=/jfs2/d/test1 bs=1G count=1
    sleep 6s
    echo a | tee -a /jfs2/d/test1 2>error.log && echo "dd should fail on out of space" && exit 1 || true
    grep "Disk quota exceeded" error.log || (echo "grep failed" && exit 1)
    rm /jfs2/d/test1 -rf
    sleep 6s
    for i in {1..1000}; do
        touch /jfs2/test$i
    done
    sleep 6s
    touch /jfs2/test1001 2>error.log && echo "touch should fail on out of inodes" && exit 1 || true
    grep "Disk quota exceeded" error.log || (echo "grep failed" && exit 1)
    ./juicefs quota check sqlite3://test.db --path /d --strict
```

the script will give error: 
touch: setting times of '/jfs2/test797': Input/output error

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**
cat /var/log/juicefs.log

2023/05/30 11:42:48.969681 juicefs[3694626] <INFO>: Mounting volume myjfs at /jfs2 ... [mount_unix.go:267]
2023/05/30 11:42:50.899467 juicefs[3693285] <WARNING>: checking counter lastCleanupFiles: attempt to write a readonly database [base.go:915]
2023/05/30 11:42:53.505647 juicefs[3694626] <ERROR>: write inode:3 indx:16  disk quota exceeded [writer.go:213]
2023/05/30 11:43:01.144055 juicefs[3693285] <ERROR>: Refresh session 1: attempt to write a readonly database [base.go:541]
2023/05/30 11:43:01.147228 juicefs[3693285] <WARNING>: checking counter lastCleanupSessions: attempt to write a readonly database [base.go:578]
2023/05/30 11:43:01.147948 juicefs[3694626] <ERROR>: error: disk I/O error
goroutine 1 [running]:
runtime/debug.Stack()
	/usr/local/go/src/runtime/debug/stack.go:24 +0x65
github.com/juicedata/juicefs/pkg/meta.errno({0x3828120, 0xc006c31140})
	/root/juicefs1/pkg/meta/utils.go:122 +0xc5
github.com/juicedata/juicefs/pkg/meta.(*dbMeta).SetAttr(0xc000e1ddc0, {0x3854718, 0xc002239540}, 0x320, 0x1b0, 0x4a?, 0xc006b5d360)
	/root/juicefs1/pkg/meta/sql.go:887 +0x1ec
github.com/juicedata/juicefs/pkg/vfs.(*VFS).SetAttr(0xc000e491e0, {0x3854de0?, 0xc002239540}, 0x320, 0x1b0, 0x0, 0x0, 0x0, 0x0, 0x647570c5, ...)
	/root/juicefs1/pkg/vfs/vfs_unix.go:197 +0x527
github.com/juicedata/juicefs/pkg/fuse.(*fileSystem).SetAttr(0xc0009052c0, 0xc006d001b0?, 0xc006d001b0, 0xc00111e108)
	/root/juicefs1/pkg/fuse/fuse.go:111 +0x11d
github.com/hanwen/go-fuse/v2/fuse.doSetattr(0x269e3a6?, 0xc00111e000)
	/root/go/pkg/mod/github.com/juicedata/go-fuse/v2@v2.1.1-0.20230418090413-880e994b8a4c/fuse/opcode.go:197 +0x55
github.com/hanwen/go-fuse/v2/fuse.init.0.func1(0xc00111e000?, 0xc00111e000?)
	/root/go/pkg/mod/github.com/juicedata/go-fuse/v2@v2.1.1-0.20230418090413-880e994b8a4c/fuse/opcode.go:751 +0x54
github.com/hanwen/go-fuse/v2/fuse.(*Server).handleRequest(0xc000e9c000, 0xc00111e000)
	/root/go/pkg/mod/github.com/juicedata/go-fuse/v2@v2.1.1-0.20230418090413-880e994b8a4c/fuse/server.go:492 +0x1f3
github.com/hanwen/go-fuse/v2/fuse.(*Server).loop(0xc000e9c000, 0x0?)
	/root/go/pkg/mod/github.com/juicedata/go-fuse/v2@v2.1.1-0.20230418090413-880e994b8a4c/fuse/server.go:465 +0x108
github.com/hanwen/go-fuse/v2/fuse.(*Server).Serve(0xc000e9c000)
	/root/go/pkg/mod/github.com/juicedata/go-fuse/v2@v2.1.1-0.20230418090413-880e994b8a4c/fuse/server.go:387 +0x35
github.com/juicedata/juicefs/pkg/fuse.Serve(0xc000e491e0, {0x0, 0x0}, 0x0, 0x0)
	/root/juicefs1/pkg/fuse/fuse.go:492 +0x574
github.com/juicedata/juicefs/cmd.mount_main(0xc000e491e0, 0x3869ac8?)
	/root/juicefs1/cmd/mount_unix.go:268 +0x629
github.com/juicedata/juicefs/cmd.mount(0xc000d61900)
	/root/juicefs1/cmd/mount.go:653 +0xa45
github.com/urfave/cli/v2.(*Command).Run(0xc000b19b80, 0xc000d61900, {0xc000113140, 0x6, 0x6})
	/root/go/pkg/mod/github.com/juicedata/cli/v2@v2.25.4-0.20230526070816-8aff66437fa8/command.go:274 +0xa42
github.com/urfave/cli/v2.(*Command).Run(0xc000f7cb00, 0xc000d61180, {0xc000d4e180, 0x7, 0x8})
	/root/go/pkg/mod/github.com/juicedata/cli/v2@v2.25.4-0.20230526070816-8aff66437fa8/command.go:267 +0xc8a
github.com/urfave/cli/v2.(*App).RunContext(0xc000ac0000, {0x38401a0?, 0xc0000500b0}, {0xc000d4e180, 0x7, 0x8})
	/root/go/pkg/mod/github.com/juicedata/cli/v2@v2.25.4-0.20230526070816-8aff66437fa8/app.go:332 +0x605
github.com/urfave/cli/v2.(*App).Run(...)
	/root/go/pkg/mod/github.com/juicedata/cli/v2@v2.25.4-0.20230526070816-8aff66437fa8/app.go:309
github.com/juicedata/juicefs/cmd.Main({0xc0000fe000?, 0x7?, 0x7?})
	/root/juicefs1/cmd/main.go:94 +0x34ec
main.main()
	/root/juicefs1/main.go:29 +0x2e [utils.go:122]
2023/05/30 11:43:13.538539 juicefs[3693285] <ERROR>: Refresh session 1: attempt to write a readonly database [base.go:541]
2023/05/30 11:43:13.538950 juicefs[3693285] <WARNING>: checking counter lastCleanupSessions: attempt to write a readonly database [base.go:578]
2023/05/30 11:43:25.337944 juicefs[3693285] <ERROR>: Refresh session 1: attempt to write a readonly database [base.go:541]
2023/05/30 11:43:25.338373 juicefs[3693285] <WARNING>: checking counter lastCleanupSessions: attempt to write a readonly database [base.go:578]
2023/05/30 11:43:37.690850 juicefs[3693285] <ERROR>: Refresh session 1: attempt to write a readonly database [base.go:541]
2023/05/30 11:43:37.691284 juicefs[3693285] <WARNING>: checking counter lastCleanupSessions: attempt to write a readonly database [base.go:578]

**Environment**:
- JuiceFS version (use `juicefs --version`) or Hadoop Java SDK version:
- Cloud provider or hardware configuration running JuiceFS:
- OS (e.g `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Object storage (cloud provider and region, or self maintained):
- Metadata engine info (version, cloud provider managed or self maintained):
- Network connectivity (JuiceFS to metadata engine, JuiceFS to object storage):
- Others:

**Comment by Hexilee** [comment]
This script does not umount `/jfs2`，so repeated executions cause repeated mount. Finally, sustained sqlite3 db become readonly and return IO errors.
