### ISSUE TITLE
should redirect tikv error message to stderr.

### ISSUE THREAD

**Issue by zhoucheng361** [juicedata/juicefs#3727]
**What happened**:
tikv client will output error message to stdout, should redirect it to stderr.

<img width="1194" alt="image" src="https://github.com/juicedata/juicefs/assets/100545994/a69af98f-40b9-4772-b825-a3885752e970">

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**

**Environment**:
- JuiceFS version (use `juicefs --version`) or Hadoop Java SDK version:
- Cloud provider or hardware configuration running JuiceFS:
- OS (e.g `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Object storage (cloud provider and region, or self maintained):
- Metadata engine info (version, cloud provider managed or self maintained):
- Network connectivity (JuiceFS to metadata engine, JuiceFS to object storage):
- Others:

**Comment by SandyXSD** [comment]
We can only specify a file name or the logger will use stdout, see: https://github.com/pingcap/log/blob/v1.1.0/log.go#L45

**Comment by SandyXSD** [comment]
@zhoucheng361 with #3728 merged, you can add `--log-level error` to ignore warning logs
