### ISSUE TITLE
sync --check-all will fatal on symbolic file.

### ISSUE THREAD

**Issue by zhoucheng361** [juicedata/juicefs#3736]
**What happened**:

+ ./juicefs sync jfs_source/ /jfs/jfs_source/ --check-all
2023/06/02 10:31:37.428886 juicefs[3915533] <INFO>: Syncing from file:///root/juicefs1/jfs_source/ to file:///jfs/jfs_source/ [sync.go:1036]
2023/06/02 10:31:53.015962 juicefs[3915533] <ERROR>: Failed to check symlink_to_file in 5.00024526s: src get: open /root/juicefs1/jfs_source/symlink_to_file: no such file or directory [sync.go:325]
2023/06/02 10:31:53.016018 juicefs[3915533] <ERROR>: Failed to copy object symlink_to_file: src get: open /root/juicefs1/jfs_source/symlink_to_file: no such file or directory [sync.go:589]
Scanned objects: 805/805 [==============================================================]  51.6/s used: 15.587711032s
Pending objects: 0                             0.0/s       
 Copied objects: 803                           51.5/s      
 Copied objects: 106.7 MiB (111901584 Bytes)   6.8 MiB/s   
Checked objects: 106.7 MiB (111901584 Bytes)   6.8 MiB/s   
Deleted objects: 0                             0.0/s       
Skipped objects: 0                             0.0/s       
 Failed objects: 1                             0.1/s       
2023/06/02 10:31:53.016729 juicefs[3915533] <INFO>: Found: 805, copied: 803 (106.72 MiB), checked: 106.72 MiB, deleted: 0, skipped: 0, failed: 1 [sync.go:1064]
2023/06/02 10:31:53.016779 juicefs[3915533] <FATAL>: Failed to handle 1 objects [main.go:31]

root@bench-01:~/juicefs1# ls jfs_source/symlink_to_file -l
lrwxrwxrwx 1 root root 15 Jun  2 10:31 jfs_source/symlink_to_file -> jfs_source/file

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**

**Environment**:
- JuiceFS version (use `juicefs --version`) or Hadoop Java SDK version:
- Cloud provider or hardware configuration running JuiceFS:
- OS (e.g `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Object storage (cloud provider and region, or self maintained):
- Metadata engine info (version, cloud provider managed or self maintained):
- Network connectivity (JuiceFS to metadata engine, JuiceFS to object storage):
- Others:

**Comment by SandyXSD** [comment]
symlink_to_file should point to file, not jfs_source/file
