### ISSUE TITLE
file size not expected: 33M VS 22M

### ISSUE THREAD

**Issue by cnglen** [juicedata/juicefs#3774]
I use tensorboard to write log to juicefs mounted directory. 

The total size is expected, such as 33M, but the file size is only 22M. It seems that while writing data, if i read the file, some data will be discarded.

How to debug? Where is the 11M data?

$ls -lht
total **33M**
-rw-r--r-- 1 root root **22M** Jun  7 16:21 events.out.tfevents.1686124794.common-xx-024-chief-0.1.0.v2

total 33131
drwxr-xr-x 2 root root     4096 Jun  7 15:59 .
drwxr-xr-x 4 root root     4096 Jun  7 15:59 ..
-rw-r--r-- 1 root root 22584097 Jun  7 16:21 events.out.tfevents.1686124794.common-xx-024-chief-0.1.0.v2

**Comment by davies** [comment]
Can you post the result of `stat events.out.tfevents.1686124794.common-xx-024-chief-0.1.0.v2`?

**Comment by cnglen** [comment]
$ stat the_file
  Size: 22584097  	Blocks: 66245      IO Block: 65536  regular file
Device: 28h/40d	Inode: 1013902     Links: 1
Access: (0644/-rw-r--r--)  Uid: (    0/    root)   Gid: (    0/    root)
Access: 2023-06-07 15:59:54.753172295 +0800
Modify: 2023-06-07 16:21:04.329347110 +0800
Change: 2023-06-07 16:21:04.329347110 +0800
 Birth: -

**Comment by SandyXSD** [comment]
Is this issue occurs only on this file (that is being written and read at the same time)? How about the stats of normal files that are closed?

**Comment by SandyXSD** [comment]
There are two possible reasons:
1. if the file in CSI is still open for write, its size may not be flushed to the metadata engine, so A can't see it.
2. if A has metadata cache (by default 1 second), it may see old values.

**Comment by davies** [comment]
can not reproduce it, close it for now
