### ISSUE TITLE
Performance degradation in mongodb test 

### ISSUE THREAD

**Issue by zhoucheng361** [juicedata/juicefs#3791]
**What happened**:
Performance degradation of mongodb test after this commit: 
https://github.com/juicedata/juicefs/commit/df275f4a9b0aa86afcfd0218b3f0d1f2828788a3

https://github.com/juicedata/juicefs/actions/runs/5219571294

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**

**Environment**:
- JuiceFS version (use `juicefs --version`) or Hadoop Java SDK version:
- Cloud provider or hardware configuration running JuiceFS:
- OS (e.g `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Object storage (cloud provider and region, or self maintained):
- Metadata engine info (version, cloud provider managed or self maintained):
- Network connectivity (JuiceFS to metadata engine, JuiceFS to object storage):
- Others:

**Comment by davies** [comment]
fixed by #3810

**Comment by davies** [comment]
fixed by #3810
