### ISSUE TITLE
juicefs+cephrados cannot be deployed concurrently because of formating 

### ISSUE THREAD

**Issue by liujiangang01** [juicedata/juicefs#3808]
**What would you like to be added**:
when we format juicefs instance, we can specify ceph user and keyring string to complete it instead of configrure file specified path. If we  support command options instead of configure file, we can format like this: juicefs.ceph format --storage ceph --bucket ceph:<mon_host>/<pool_name> --access-key <ceph-user> --secret-key <ceph-user-key> <meta_url> <instance_name>，it will bring us great convenience
**Why is this needed**:
juicefs+cephrados cannot be deployed concurrently,  because the ceph.conf must locate under the path of  "/etc/ceph/" when we format or mount a juicefs instance. when we use juicefs as persistent storage in k8s cluster, k8s ops will be under great distress

**Comment by zwwhdls** [comment]
Hi @liujiangang01 , when you use juicefs PV in k8s, you can set ceph.conf as a secret and mount it as /etc/ceph/ceph.conf referring to https://juicefs.com/docs/csi/guide/pv/#mount-pod-extra-files . Hope this helps.

**Comment by liujiangang01** [comment]
Our k8s mount juicefs.ceph use host-mount-bind style which mount in physical machine and bind to path in docker instand of pod-mount style, so we hope the same format style compared to other backend (eg. oss, we donot need extra conf)

**Comment by SandyXSD** [comment]
The conf files are required by Ceph librados, as it will parse all options in the ceph.conf, not only the monitor address. Also it requires proper permission for the keyring file. One possible way to satisfy your needs is creating the Ceph files automatically with the arguments passed to JuiceFS, but generally that's not a good practice. Instead we recommend you using the CSI way.

Refs: https://pkg.go.dev/github.com/ceph/go-ceph@v0.18.0/rados#NewConnWithClusterAndUser

**Comment by liujiangang01** [comment]
As you mentioned, we now optimize juicefs.ceph format style by recode newCephpkg/,  acoording to pass mon_host and secret-key to juicefs.ceph, juicefs.ceph will generate temporary keyring file parsed from cmd options，now we can format like this: juicefs.ceph format --storage ceph --bucket ceph://<mon_host>/<ceph_pool> --access-key <ceph_user> --secret-key=<ceph_user_key> tikv://<pd_addr>/<ins_name> <ins_name>, donot need any ceph conf and keyring file, at the same time,  it is also compatible with the original usage 
![image](https://github.com/juicedata/juicefs/assets/12525667/984490de-81cf-4d4f-90c5-2d83ad8d8353)

**Comment by davies** [comment]
The config file is needed for Ceph client, the addresses of monitor and keys are not enough, so the question is how to manage it.

If you use the CSI driver in K8S, the config file can be provided as secrets.

If you use JuiceFS as hostPath, that means  the JuiceFS mount point by k8s ops, then the Ceph configuration should also manged by k8s ops.
