### ISSUE TITLE
quota功能报:no such file or directory

### ISSUE THREAD

**Issue by JesseDPC** [juicedata/juicefs#3812]
**What happened**:
<img width="1112" alt="1686799586110" src="https://github.com/juicedata/juicefs/assets/68317718/5582860b-eb44-4eb9-ba4c-a70b75dec079">

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**

**Environment**:
- JuiceFS version (use `juicefs --version`) or Hadoop Java SDK version:
- Cloud provider or hardware configuration running JuiceFS:
- OS (e.g `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Object storage (cloud provider and region, or self maintained):
- Metadata engine info (version, cloud provider managed or self maintained):
- Network connectivity (JuiceFS to metadata engine, JuiceFS to object storage):
- Others:

**Comment by SandyXSD** [comment]
Use the path within the JuiceFS volume, i.e, remove the `/opt/testdir` prefix for the `--path` option.
