### ISSUE TITLE
quota error:no such table: jfs_edge and <FATAL>: input/output error

### ISSUE THREAD

**Issue by qinguoyi** [juicedata/juicefs#3837]
**What happened**:

with 1.1.0-beta1 and sqlite3，when i run the quota cmd，quota error:no such table: jfs_edge and <FATAL>: input/output error
![image](https://github.com/juicedata/juicefs/assets/25760295/a9724f3a-5561-40ce-b708-7900d12068dc)

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**

**Environment**:
- JuiceFS version (use `juicefs --version`) or Hadoop Java SDK version:
- Cloud provider or hardware configuration running JuiceFS:
- OS (e.g `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Object storage (cloud provider and region, or self maintained):
- Metadata engine info (version, cloud provider managed or self maintained):
- Network connectivity (JuiceFS to metadata engine, JuiceFS to object storage):
- Others:

**Comment by qinguoyi** [comment]
before i quota the dir，format and mount is normal

**Comment by davies** [comment]
What't the steps to reproduce it?

**Comment by qinguoyi** [comment]
this is my machine: tencent cloud lighthouse + centos
these are my run steps:
> wget "https://github.com/juicedata/juicefs/releases/download/v1.1.0-beta1/juicefs-1.1.0-beta1-linux-amd64.tar.gz"
> tar -zxf 'juicefs-1.1.0-beta1-linux-amd64.tar.gz'
> sudo install juicefs /usr/bin
> juicefs format /home/lighthouse/quota sqlite3://myjuices.db myjfs
> juicefs mount sqlite3://myjuices.db quota/ -d
> cd /home/lighthouse/quota && mkdir 1
> juicefs quota set sqlite3://myjuices.db --path quota/1 --capacity 1

**Comment by qinguoyi** [comment]
> What't the steps to reproduce it?

i replace sqlite3 to redis，quota is normal

**Comment by qinguoyi** [comment]
> What't the steps to reproduce it?

this is my machine: tencent cloud lighthouse + centos
these are my run steps:

wget "https://github.com/juicedata/juicefs/releases/download/v1.1.0-beta1/juicefs-1.1.0-beta1-linux-amd64.tar.gz"
tar -zxf 'juicefs-1.1.0-beta1-linux-amd64.tar.gz'
sudo install juicefs /usr/bin
juicefs format  sqlite3://myjuices.db myjfs
juicefs mount sqlite3://myjuices.db /home/lighthouse/quota/ -d
cd /home/lighthouse/quota && mkdir 1
juicefs quota set sqlite3://myjuices.db --path quota/1 --capacity 1

**Comment by SandyXSD** [comment]
It looks like you `cd`ed to the mount point before setting quota, which makes the last command using the wrong `myjuices.db`. Please switch back to the directory where you ran the `format` command, or use absolute path after `sqlite3://` schema.

**Comment by qinguoyi** [comment]
> It looks like you `cd`ed to the mount point before setting quota, which makes the last command using the wrong `myjuices.db`. Please switch back to the directory where you ran the `format` command, or use absolute path after `sqlite3://` schema.

if switch back to the directory where you ran the format command,  quota will wrong with "no such file or directory" like this issuse #3812 ,must use the path within the JuiceFS volume.

maybe use absolute path after sqlite3:// schema is availabel, i try it .

**Comment by SandyXSD** [comment]
Try:
``` bash
wget "https://github.com/juicedata/juicefs/releases/download/v1.1.0-beta1/juicefs-1.1.0-beta1-linux-amd64.tar.gz"
tar -zxf 'juicefs-1.1.0-beta1-linux-amd64.tar.gz'
sudo install juicefs /usr/bin
juicefs format sqlite3://myjuices.db myjfs
juicefs mount sqlite3://myjuices.db /home/lighthouse/quota/ -d
# cd /home/lighthouse/quota && mkdir 1
mkdir /home/lighthouse/quota/1
# juicefs quota set sqlite3://myjuices.db --path 1 --capacity 1
juicefs quota set sqlite3://myjuices.db --path /1 --capacity 1
```

**Comment by qinguoyi** [comment]
> Try:
> 
> ```shell
> wget "https://github.com/juicedata/juicefs/releases/download/v1.1.0-beta1/juicefs-1.1.0-beta1-linux-amd64.tar.gz"
> tar -zxf 'juicefs-1.1.0-beta1-linux-amd64.tar.gz'
> sudo install juicefs /usr/bin
> juicefs format sqlite3://myjuices.db myjfs
> juicefs mount sqlite3://myjuices.db /home/lighthouse/quota/ -d
> # cd /home/lighthouse/quota && mkdir 1
> mkdir /home/lighthouse/quota/1
> # juicefs quota set sqlite3://myjuices.db --path 1 --capacity 1
> juicefs quota set sqlite3://myjuices.db --path /1 --capacity 1
> ```

it works. thks ^_^.
