### ISSUE TITLE
Feature request: support GlusterFS as object storage backend

### ISSUE THREAD

**Issue by FollieHiyuki** [juicedata/juicefs#3839]
**What would you like to be added**:

GlusterFS as a supported object storage option.

**Why is this needed**:

[GlusterFS](https://www.gluster.org/) is a distributed, scalable filesystem developed by Red Hat. As great as it is, it doesn't officially provide CSI driver for K8s or S3-compatible API gateway anymore. The recommended access methods are fuse mount, NFS, CIFS or SAMBA (https://docs.gluster.org/en/latest/Administrator-Guide/Setting-Up-Clients/).

**Comment by davies** [comment]
Actually, this sounds a good idea, GlusterFS could be a better option than MinIO (easy management and scaling out) and Ceph (easy management). JuiceFS can address the weakness of GlusterFS, no CSI/S3 gateway/Java SDK, poor performance on listing on large cluster.

There is a Go SDK for GlusterFS [1], we can give it a shot.

[1] https://github.com/gluster/gogfapi

**Comment by davies** [comment]
Since Ceph is an option, have you tried it (Ceph RADOS, no RBD) ?

**Comment by FollieHiyuki** [comment]
I haven't tried yet.

To be honest, if I go for Ceph, I'll probably stick with Rook on the K8s side, as it is what I'm already familiar with. I'd desire something else this time though (if possible), as Ceph can be complicated sometimes.

**Comment by davies** [comment]
@FollieHiyuki Gluster is supported by #3840 , please try the main branch, will be released in 1.1 beta2
