### ISSUE TITLE
JuiceFS does not work well with Samba

### ISSUE THREAD

**Issue by locoz666** [juicedata/juicefs#3844]
**What happened**:
我是在K8S中使用JuiceFS，文件存储选择使用Ceph RADOS，元数据引擎使用Redis，使用CSI动态挂载PVC。按照官方文档中的说法，我自己构建了基于我使用的CEPH版本的镜像，并替换了上去。
然后我进行了两项测试：
1、使用Ubuntu镜像挂载PVC，然后进入容器内用命令进行常规的文件操作和性能测试，看起来一切正常。
<img width="914" alt="image" src="https://github.com/juicedata/juicefs/assets/18413149/bf891125-1d92-4878-8208-48e87d743afe">
<img width="932" alt="image" src="https://github.com/juicedata/juicefs/assets/18413149/d22db3da-4575-4011-8d15-1017332c59a2">
2、使用Samba镜像挂载PVC，然后使用macOS和Windows设备，通过两个系统自带的SMB访问方式访问该Samba服务，但出现了各种异常现象，具体如下。

macOS下写入文件，报错，且JuiceFS上创建了一个空文件。
<img width="420" alt="image" src="https://github.com/juicedata/juicefs/assets/18413149/e1331cd6-9527-44df-b56b-0e9ac04fa77e">

macOS下删除文件，报错，且文件未被删除。
<img width="412" alt="image" src="https://github.com/juicedata/juicefs/assets/18413149/2652db7c-2912-4905-b1a0-5a21d1d30b7d">

macOS下覆盖同名文件，同样无法写入。
<img width="428" alt="image" src="https://github.com/juicedata/juicefs/assets/18413149/23797a95-f8a2-47e0-bfde-7a7526ea4016">

macOS下新建文件夹，正常。但如果在新建文件夹时修改了名称，会修改失败，并且创建出一个默认名称的文件夹。
<img width="341" alt="image" src="https://github.com/juicedata/juicefs/assets/18413149/164e9403-1ad4-4891-aae8-83efdb01b67d">

Windows下直接写入文件，正常。但覆盖文件或删除文件会同样报错。
<img width="746" alt="image" src="https://github.com/juicedata/juicefs/assets/18413149/31749238-a75e-4ca2-b282-4a59b95828db">
<img width="769" alt="image" src="https://github.com/juicedata/juicefs/assets/18413149/b8671258-52c5-4ce5-8e3c-233bf0299ede">

Windows下使用文本编辑器对文本文件进行编辑、保存操作，正常。
<img width="915" alt="image" src="https://github.com/juicedata/juicefs/assets/18413149/d652e34e-65cc-4a0c-8c7e-79f6c76f93e3">

在出现上述错误的同时，Samba有时会报一条`unix_convert: talloc_asprintf failed`的错误，但看起来不是所有操作都会出现。
<img width="698" alt="image" src="https://github.com/juicedata/juicefs/assets/18413149/44915ea1-a1a9-4ecd-b853-1b26d181ae4e">

在出现上述错误的同时，JuiceFS挂载目录下的`.accesslog`日志中，会出现`no such file or directory`相关报错。
<img width="1432" alt="image" src="https://github.com/juicedata/juicefs/assets/18413149/e48adad0-f0ce-4db9-aca1-e638e573f0ae">

**What you expected to happen**: 
正常使用Samba对文件进行交互。

**How to reproduce it (as minimally and precisely as possible)**: 
按照前述测试方式进行同样操作即可。

**Anything else we need to know?**
测试使用的Samba镜像为ghcr.io/crazy-max/samba:4.16.7，使用k8s-at-home的Helm Chart进行部署，做了如下配置。
<img width="796" alt="image" src="https://github.com/juicedata/juicefs/assets/18413149/e7a50b2e-a42c-4cc0-a2a5-90d72dcdae31">

**Environment**:
- JuiceFS version (use `juicefs --version`) or Hadoop Java SDK version: 1.0.4+2023-04-06.f1c475d9
- Cloud provider or hardware configuration running JuiceFS: 本地x86物理机组建的K8S集群，节点配置为双路Intel E5-2667 V4 + 128GB内存，资源充足
- OS (e.g `cat /etc/os-release`): Ubuntu 22.04.2 LTS
- Kernel (e.g. `uname -a`): 5.15.0-75-generic
- Object storage (cloud provider and region, or self maintained): 使用Rook部署在K8S集群内的Ceph，版本为17.2.6
- Metadata engine info (version, cloud provider managed or self maintained): 使用Helm部署在K8S集群内的Redis，使用的镜像为bitnami/redis:7.0.11-debian-11-r7
- Network connectivity (JuiceFS to metadata engine, JuiceFS to object storage): 均为直接通过K8S内部网络进行通信。K8S使用的网络组件为Cilium 1.13.4。
- Others:

**Comment by SandyXSD** [comment]
Try mount JuiceFS with `--enable-xattr` option, see: https://juicefs.com/docs/zh/csi/guide/pv/#dynamic-mount-options

**Comment by locoz666** [comment]
> Try mount JuiceFS with `--enable-xattr` option, see: https://juicefs.com/docs/zh/csi/guide/pv/#dynamic-mount-options

The method is effective, and now it's working properly!

**Comment by locoz666** [comment]
However, it seems that Samba still has some errors (even when I haven't done any operations), but it doesn't appear to have much impact on basic operations.

<img width="656" alt="image" src="https://github.com/juicedata/juicefs/assets/18413149/79e51d44-a02d-4f85-8d07-ad13209aaba9">

**Comment by SandyXSD** [comment]
Probably related to this [issue](https://bugzilla.samba.org/show_bug.cgi?id=15362), which is solved in Samba 4.18.3.

**Comment by locoz666** [comment]
> Probably related to this [issue](https://bugzilla.samba.org/show_bug.cgi?id=15362), which is solved in Samba 4.18.3.

Indeed, it was this issue that caused the problem. After updating, the error no longer occurred. Thank you for your reminder.
