### ISSUE TITLE
kvtxn interface should allow returning errors

### ISSUE THREAD

**Issue by zinal** [juicedata/juicefs#3849]
**What would you like to be added**:
The kvtxn interface should be extended to return errors, its implementations should return errors instead of panicing, and its users should handle those errors as required.

**Why is this needed**:
The existing kvtxn interface does not support returning errors from its methods.  This leads to the situation when all errors have to be handled with `panic(err)`, which is actually implemented for etcd, TiDB, FoundationDB variants.
In practice, for distributed databases, any call can lead to errors, and in many cases those errors need to be detected and handled (on transaction or higher level).

**Plans**:
I am planning to provide the enhanced version of the interface, and the enhanced code supporting it.

**Comment by zinal** [comment]
Added PR #3852 implementing the fix

**Comment by SandyXSD** [comment]
I don't think the fix is necessary. The panic will be recovered and converted to an error in the `client.txn` functions, so this works like a `try ... catch ...` block. Codes in `tkv.go` use `txn` method and will only see the errors.

**Comment by zinal** [comment]
> I don't think the fix is necessary. The panic will be recovered and converted to an error in the `client.txn` functions, so this works like a `try ... catch ...` block. Codes in `tkv.go` use `txn` method and will only see the errors.

Not being a Golang guru, I am still under the impression that panic()s should be really exceptional.
Temporary database availability errors, on the other hand, are quite typical, and do not have to be handled the same way as program logic failures.

On the other hand, this looks like a style-mostly change touching many lines of code, and I see the point in avoiding it.

**Comment by SandyXSD** [comment]
Yeah, so I would rather keep the style for now as long as there is no critical issue. Idiomatic Go code prefers using error, and we do use normal error handling in most of the code. However, I have to say to some degree it's too verbose, such as the [snippet here](https://github.com/juicedata/juicefs/blob/1e7b628196d36aa1a398f2f33814757c5d8355d6/pkg/meta/sql.go#L1417-L1462) in `sql.go`. Then I learned the idea from [foundationdb](https://github.com/apple/foundationdb/blob/92fc089eb0e7/bindings/go/src/fdb/transaction.go\#L115), and find it works okay as I expected.
