### ISSUE TITLE
background option for the juicefs gateway command

### ISSUE THREAD

**Issue by AllenXieSZ** [juicedata/juicefs#3865]
**What would you like to be added**:

when start S3 gateway service, the command does not have option background like juicefs mount. then if the gateway starting command terminal is terminated, the gateway service will stop.

I suggest we add an option background like juicefs mount 

**Why is this needed**:

to make the gateway service running in background and avoid interrupted by terminating session.

**Comment by zhijian-pro** [comment]
This problem can be solved by using the control character '&' that runs in the background.
