### ISSUE TITLE
flaky test of quota

### ISSUE THREAD

**Issue by zhoucheng361** [juicedata/juicefs#3885]
**What happened**:
https://github.com/juicedata/juicefs/actions/runs/5462157962/jobs/9941126787

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**

**Environment**:
- JuiceFS version (use `juicefs --version`) or Hadoop Java SDK version:
- Cloud provider or hardware configuration running JuiceFS:
- OS (e.g `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Object storage (cloud provider and region, or self maintained):
- Metadata engine info (version, cloud provider managed or self maintained):
- Network connectivity (JuiceFS to metadata engine, JuiceFS to object storage):
- Others:

**Comment by Hexilee** [comment]
It should be fixed by #3882
