### ISSUE TITLE
meta: record the blocks in the file attributes

### ISSUE THREAD

**Issue by Hexilee** [juicedata/juicefs#3924]
We implement `SEEK_HOLE` and `SEEK_DATA` in #3898, but core utils of Linux like [cp](https://github.com/coreutils/coreutils/blob/master/src/copy.c#L1137C9-L1137C9) need blocks to call `lseek`.

Refer to #2637

**Comment by davies** [comment]
it's too expensive to tell exactly the number of blocks, we can't do it.

**Comment by vicaya** [comment]
There is _no_ need to track _exactly_ the total number of blocks for every write. btrfs, xfs, and zfs all do wildly different things for `st_blocks` but maintain the canonical invariance of `st_blocks < st_size / 512` for sparse files. The only gotcha is that st_blocks should be > 0 (cf. the infamous gpfs bug) for non empty files.

It'd be a pity that juicefs cannot support sparse files, as the juicefs file format is inherently sparse friendly. A simple change that would greatly improve sparse file/utility compatibility would be detect the first sparse write in the `Write` function and set a IsSparse attribute and modify `attrToStat` to set `blocks = max(1, (size - 512) / 512)` for sparse file (`IsSparse` is true).
