### ISSUE TITLE
sync --links not working

### ISSUE THREAD

**Issue by ar45** [juicedata/juicefs#3934]
**What happened**:

Created a volume and synced directory tree using `juicefs sync --links  data/  /mnt/` and symlink was followed instead of copying the link.

**What you expected to happen**:

the symlink should be copied, and not the files / directories the link is pointing to.

**How to reproduce it (as minimally and precisely as possible)**:

```bash
# create volume
juicefs format sqlite3://test1.db test1
juicefs mount sqlite3://test1.db /mnt/
```

Create directory tree
```bash
mkdir -p data/dir{1,2}/sub{1,2}
touch  data/dir{1,2}/sub{1,2}/file.txt
ln -sT ../dir2 data/dir1/link-to-dir2
```

```bash
data/
├── dir1
│   ├── link-to-dir2 -> ../dir2
│   ├── sub1
│   │   └── file.txt
│   └── sub2
│       └── file.txt
└── dir2
    ├── sub1
    │   └── file.txt
    └── sub2
        └── file.txt
```

Sync the tree
```bash
juicefs sync --links -v  ./data/ /mnt/
```

> 2023/07/25 06:24:32.991438 juicefs[3676] <DEBUG>: maxprocs: Leaving GOMAXPROCS=16: CPU quota undefined [maxprocs.go:47]
2023/07/25 06:24:32.991637 juicefs[3676] <DEBUG>: Creating file storage at endpoint /root/data/ [object_storage.go:171]
2023/07/25 06:24:32.991669 juicefs[3676] <DEBUG>: Ensure directory /root/data/ [file.go:339]
2023/07/25 06:24:32.991753 juicefs[3676] <DEBUG>: Creating file storage at endpoint /mnt/ [object_storage.go:171]
2023/07/25 06:24:32.991774 juicefs[3676] <DEBUG>: Ensure directory /mnt/ [file.go:339]
2023/07/25 06:24:32.992282 juicefs[3676] <INFO>: Syncing from file:///root/data/ to file:///mnt/ [sync.go:1043]
2023/07/25 06:24:32.992304 juicefs[3676] <DEBUG>: maxResults: 1000, defaultPartSize: 5242880, maxBlock: 10485760 [sync.go:642]
2023/07/25 06:24:32.992317 juicefs[3676] <DEBUG>: Iterating objects from file:///root/data/ with prefix  start "" [sync.go:78]
2023/07/25 06:24:32.992342 juicefs[3676] <DEBUG>: Listing objects from file:///root/data/ marker "" [sync.go:107]
2023/07/25 06:24:32.992467 juicefs[3676] <DEBUG>: Iterating objects from file:///mnt/ with prefix  start "" [sync.go:78]
2023/07/25 06:24:32.992491 juicefs[3676] <DEBUG>: Listing objects from file:///mnt/ marker "" [sync.go:107]
2023/07/25 06:24:32.993361 juicefs[3676] <DEBUG>: Ignore directory  [sync.go:670]
2023/07/25 06:24:32.993377 juicefs[3676] <DEBUG>: Ignore directory dir1/ [sync.go:670]
2023/07/25 06:24:32.993387 juicefs[3676] <DEBUG>: Ignore directory dir1/link-to-dir2/ [sync.go:670]
2023/07/25 06:24:32.993396 juicefs[3676] <DEBUG>: Ignore directory dir1/link-to-dir2/sub1/ [sync.go:670]
2023/07/25 06:24:32.997861 juicefs[3676] <DEBUG>: Ignore directory dir1/link-to-dir2/sub2/ [sync.go:670]
2023/07/25 06:24:32.997893 juicefs[3676] <DEBUG>: Ignore directory dir1/sub1/ [sync.go:670]
2023/07/25 06:24:32.997905 juicefs[3676] <DEBUG>: Ignore directory dir1/sub2/ [sync.go:670]
2023/07/25 06:24:32.997965 juicefs[3676] <DEBUG>: Ignore directory dir2/ [sync.go:670]
2023/07/25 06:24:32.997994 juicefs[3676] <DEBUG>: Ignore directory dir2/sub1/ [sync.go:670]
2023/07/25 06:24:32.998008 juicefs[3676] <DEBUG>: Ignore directory dir2/sub2/ [sync.go:670]
2023/07/25 06:24:33.009703 juicefs[3676] <DEBUG>: Copied data of dir2/sub1/file.txt (0 bytes) in 11.678581ms [sync.go:496]
2023/07/25 06:24:33.019047 juicefs[3676] <DEBUG>: Copied data of dir2/sub2/file.txt (0 bytes) in 20.990363ms [sync.go:496]
2023/07/25 06:24:33.022896 juicefs[3676] <DEBUG>: Copied data of dir1/sub2/file.txt (0 bytes) in 24.866996ms [sync.go:496]
2023/07/25 06:24:33.026201 juicefs[3676] <DEBUG>: Copied data of dir1/sub1/file.txt (0 bytes) in 28.278249ms [sync.go:496]
2023/07/25 06:24:33.035203 juicefs[3676] <DEBUG>: Copied data of dir1/link-to-dir2/sub2/file.txt (0 bytes) in 37.232772ms [sync.go:496]
2023/07/25 06:24:33.036853 juicefs[3676] <DEBUG>: Copied data of dir1/link-to-dir2/sub1/file.txt (0 bytes) in 38.955005ms [sync.go:496]
2023/07/25 06:24:33.039419 juicefs[3676] <INFO>: Found: 6, skipped: 0, copied: 6 (0 B), failed: 0 [sync.go:1082]

```bash
root@ms199:~# tree /mnt/
/mnt/
├── dir1
│   ├── link-to-dir2
│   │   ├── sub1
│   │   │   └── file.txt
│   │   └── sub2
│   │       └── file.txt
│   ├── sub1
│   │   └── file.txt
│   └── sub2
│       └── file.txt
└── dir2
    ├── sub1
    │   └── file.txt
    └── sub2
        └── file.txt

10 directories, 6 files
```

**Anything else we need to know?**

**Environment**:
- JuiceFS version (use `juicefs --version`) or Hadoop Java SDK version:  juicefs version 1.1.0-dev+2023-07-24.c924609
- Cloud provider or hardware configuration running JuiceFS: 
- OS (e.g `cat /etc/os-release`): Debian GNU/Linux 12 (bookworm)
- Kernel (e.g. `uname -a`): Linux ms199 6.2.16-4-pve # 1 SMP PREEMPT_DYNAMIC PVE 6.2.16-4 (2023-07-07T04:22Z) x86_64 GNU/Linux
- Object storage (cloud provider and region, or self maintained): file
- Metadata engine info (version, cloud provider managed or self maintained):  sqlite3
- Network connectivity (JuiceFS to metadata engine, JuiceFS to object storage): N/A
- Others:

**Comment by zhijian-pro** [comment]
We will fix it.

**Comment by ar45** [comment]
Thanks @zhijian-pro 

Just noting here a few things to ensure is handled correctly as I ended up yesterday with a large invalid tree.

* If the destination file exists and is a directory, throw an error if it attempts to replace that directory with a symlink. 
* If using the `--delete-dst` option in combination with `--links` first remove, then delete the destination dir and replace with the symlink.

**Comment by ar45** [comment]
Another point, if syncing from jfs to another storage like s3 using --links currently it gives a message
```
<WARNING>: storage s3://*****.s3.amazonaws.com/path/ does not support symlink, ignore it [sync.go:340]
```
We should make sure not to copy the tree referenced by the symlink.

Would be nice if jfs can implement a custom object with an metadata similar to how s3fs using `x-amz-meta-mode`  
same concept can be applied to permissions https://github.com/s3fs-fuse/s3fs-fuse/blob/faec0d9d15dc0c0c48ed06e06d02b7471521d072/src/s3fs.cpp#L2002

**Comment by zhijian-pro** [comment]
> If the destination file exists and is a directory, throw an error if it attempts to replace that directory with a symlink.

This is expected behavior because deleting a directory directly is too risky. 
When such an error occurs, the user can manually delete the directory and run it again.

**Comment by ar45** [comment]
> @ar45
> 
> > If the destination file exists and is a directory, throw an error if it attempts to replace that directory with a symlink.
> 
> This is expected behavior because deleting a directory directly is too risky. When such an error occurs, the user can manually delete the directory and run it again.

If `—delete-dst` with `—links` together, the expected behavior would be to make the DST match exactly to SRC. It would be quite difficult to clean up the target manually otherwise.
