### ISSUE TITLE
Allow n >= 2 volumes to share the same metadata DB

### ISSUE THREAD

**Issue by enspritz** [juicedata/juicefs#3944]
**What would you like to be added**:

The ability for several JuiceFS volumes to share the same one metadata DB.

**Why is this needed**:

I just received a surprise when putting JuiceFS and its CSI driver through its paces, exactly the same as described in the summary of [juicefs-csi-driver issue 430](https://github.com/juicedata/juicefs-csi-driver/issues/430). In our use, storage is dynamically allocated, sometimes several times per day. If it's true that JuiceFS cannot share a metadata store for use with n >= 2 volumes, that means we need to create a new DB for every new allocation of a storage volume.

Well, this will be burdensome for devops. The entire point of an SDS is to automate away this kind of building and instantiating. We prefer to merely declare that we are carving out a volume from storage with the current deployment idioms (like k8s & a PV), and then have the components manifest that declaration into reality.

This, or please make it excruciatingly clear in the documentation that the metadata DB cannot be shared; it's the sole property of a single volume, and that if you want more volumes, you're gonna have to make more metadata DBs. Particularly in the project README.md plus the metadata document.

Thanks!

**Comment by zwwhdls** [comment]
Hi @enspritz , are you suggesting that you need inter-application data isolation? If so, you can achieve this by using a same juicefs volume. You can dynamically mount it using a storage class, and each application can request its own PVC(refer to https://juicefs.com/docs/csi/guide/pv/#dynamic-provisioning). The data between applications will be automatically isolated through subdirectories. This eliminates the need for creating a new volume each time.

**Comment by enspritz** [comment]
Hi @zwwhdls , yes that's right, inter-application data isolation. I understand what you are saying about effecting this using storage classes, thanks for pointing that out.

Even with application data isolated by subdirectories, I'm afraid this approach won't harmonize well with our backup/restore systems. Everything else here is operating under the assumption of one volume per deployment; this way, each commissioning and decommissioning is an atomic operation that operates on the most natural-sized idioms at each layer, in this case, one discrete JuiceFS/S3-backed volume + one discrete JuiceFS metadata DB for workload storage. This satisfies the security and compliance people, in particular.

It was the promise of POSIX file system compliance which I am investigating, and I have already confirmed that it functions much better than current SeaweedFS. But the metadata DB story is difficult to swallow at this time...
