### ISSUE TITLE
Minio mount size is wrong showing PB.

### ISSUE THREAD

**Issue by arm2arm** [juicedata/juicefs#3954]
after mounting minio backend the size is shown  wrongly.
df -h
JuiceFS:myjfs                           1.0P   65G  1.0P   1% /mnt/juice

 ./juicefs  --version 
juicefs version 1.0.4+2023-04-06.f1c475d

the size of the bucket is restricted to 5Ti

**Comment by solracsf** [comment]
See https://juicefs.com/docs/community/guide/quota/#file-system-quota
See https://juicefs.com/docs/community/guide/quota/#limit-total-capacity

**Comment by arm2arm** [comment]
It was a little bit confusing,  but reconfigure was fixing the issue , thank you
