### ISSUE TITLE
docs: bug in juicefs_vs_s3ql.md

### ISSUE THREAD

**Issue by yfdyh000** [juicedata/juicefs#3968]
**What happened**:
"S3QL was no longer maintained since November 9, 2022" in https://github.com/juicedata/juicefs/pull/3045/files.
https://github.com/s3ql/s3ql/commits/master?after=c02f4509c46fcb7f766fe54455b10c0c3bdb1014+174&branch=master

**What you expected to happen**:
https://github.com/s3ql/s3ql appear to be alive.

**Comment by davies** [comment]
S3QL was orphaned before [1] and active again, we have update the docs (#3973).

[1] https://github.com/s3ql/s3ql/commit/3046e99204b8ae27917b984259174545aa01aef0
