### ISSUE TITLE
ImagePullBackOff: Back-off pulling image "juicedata/mount:ce-v1.1.0-beta2"

### ISSUE THREAD

**Issue by GoodJeek** [juicedata/juicefs#4004]
**When i used the juicefs-csi-driver, due to the network problem, I coudln't download the image-'juicedata/mount:ce-v1.1.0-beta2' from the URL-“https://registry-1.docker.io/v2/”. 
In my practice, I deployed juicefs-csi-driver with kubectl.

How and where to edit the image and replace the default image with my private image?

Thanks in advance !**

**Comment by xpnuo** [comment]
I have the same problem, can you share how you did it?
