### ISSUE TITLE
[Bug]when objbench, an error show: failed to get object with the offset out of range, expect "", but got "", error: InvalidRange: The requested range is not satisfiable

### ISSUE THREAD

**Issue by diyism** [juicedata/juicefs#4009]
```
$ juicefs status "redis://100.65.34.34:6379/1"
2023/08/18 08:00:55.128588 juicefs[20713] <INFO>: Meta address: redis://100.65.34.34:6379/1 [interface.go:401]
2023/08/18 08:00:55.481120 juicefs[20713] <INFO>: Ping redis: 65.422403ms [redis.go:2904]
{
  "Setting": {
    "Name": "juicefs-icefall",
    "UUID": "f151c6f4-82e4-4b95-b0aa-f9a38af41368",
    "Storage": "minio",
    "Bucket": "http://100.65.34.34:9001/bucket1",
    "AccessKey": "minioadmin",
    "SecretKey": "removed",
    "BlockSize": 4096,
    "Compression": "none",
    "KeyEncrypted": true,
    "TrashDays": 1,
    "MetaVersion": 1
  },
  "Sessions": [
    {
      "Sid": 1,
      "Expire": "2023-08-18T08:01:55Z",
      "Version": "1.0.4+2023-04-06.f1c475d",
      "HostName": "8c48c60a86e3",
      "MountPoint": "/content/mnt-juicefs-icefall",
      "ProcessID": 8479
    }
  ]
}

$ juicefs objbench --verbose --storage minio http://100.65.34.34:9001/bucket1 --access-key minioadmin --secret-key minioadmin
2023/08/18 07:44:27.427107 juicefs[16656] <DEBUG>: Creating minio storage at endpoint http://100.65.34.34:9001/bucket1 [object_storage.go:154]
Start Functional Testing ...
2023/08/18 07:45:06.536658 juicefs[16656] <DEBUG>: failed to get object with the offset out of range, expect "", but got "", error: InvalidRange: The requested range is not satisfiable
	status code: 416, request id: 177C6A8B48779B55, host id: 7987905dee74cdeb212432486a178e511309594cee7cb75f892cd53e35f09ea4 [objbench.go:601]
```

It seems the redis is enough fast on 100.65.34.34 (I can see: "Ping redis: 65.422403ms [redis.go:2904]"),
But I can't figure out what's wrong with my minio on 100.65.34.34

**Comment by zhijian-pro** [comment]
What is the version of minio ?
Can you post the full output of objbench ?

**Comment by zhijian-pro** [comment]
This is a warning log and does not affect the normal use of juicefs.Juicefs does not use this feature.

**Comment by diyism** [comment]
Any other method to trace the bug ?

**Comment by zhijian-pro** [comment]
`objbench` is a full feature of test object storage, and some warning logs indicate that it does not quite meet the standards of object storage, but it does not affect the use of juicefs, because juicefs uses only a small subset of the common interfaces of object storage.

**Comment by diyism** [comment]
Sorry, my fault. I guess the problem lies with my proxy program.
It seems that my proxy only affects the main process of JuiceFS and does not apply to its child processes.

I've tested "HTTP_PROXY=127.0.0.1:8081 juicefs format ...", it failed,
So I'm using gg(https://github.com/mzz2017/gg),
this command can success: "gg juicefs format ...",

but this command failed: "gg juicefs mount ...",
it say "juicefs[142261] <INFO>: OK, juicefs-icefall is ready at /content/mnt-juicefs-icefall [mount_unix.go:45]", but after it, all the sub proccesses exited.

**Comment by zhijian-pro** [comment]
What's your mount command ? 
In addition, you can try `socks5 proxy` without `mount -d`.

**Comment by diyism** [comment]
Cool, by getting rid of "-d", the objbench works now:
```
nohup gg juicefs mount --enable-xattr "redis://100.65.34.34:6379/1" /content/mnt-juicefs-icefall >/dev/null 2>&1 &
gg --testnode=false juicefs objbench --storage minio http://100.65.34.34:9001/bucket1 --access-key minioadmin --secret-key minioadmin
```

Thanks.

I've closed this issue.
