### ISSUE TITLE
【compaction】file maybe encounter Input/output error when  compaction trigggerd in another client

### ISSUE THREAD

**Issue by penglaixy99** [juicedata/juicefs#4012]
**What happened**:
When file Z is opened and read in client A and at the same time client B do compaction with file Z, client A then read the file for a second time, client A will read with input/output error.

**What you expected to happen**:
client A will refresh the chunk cache and use the new chunk cache to read objects.

**How to reproduce it (as minimally and precisely as possible)**:

We add a button to control the slice compaction.
Trash recycle  is closed.
Client A is configured with cache size 0.
Client A  read a file Z (with a lot of small slices) and slice compaction button is not opened.

Client B read a the same file Z with the slice compaction button open. then Client B will compaciton the file Z.

Because  Client A has opened and read the file Z, chunk size will be cached.

drop cache with  echo 3 > /proc/sys/vm/drop_caches

then Client A read the file Z for a second time,  because mtime is not updated when compaction, chunk cache is considered to be valid , and use the old chunk slices. But these chunk silce is deleted.

**Anything else we need to know?**

**Environment**:
- JuiceFS version (use `juicefs --version`) or Hadoop Java SDK version: 1.0.0
- Cloud provider or hardware configuration running JuiceFS: not related
- OS (e.g `cat /etc/os-release`): not related
- Kernel (e.g. `uname -a`):not related
- Object storage (cloud provider and region, or self maintained):not related
- Metadata engine info (version, cloud provider managed or self maintained): TIKV
- Network connectivity (JuiceFS to metadata engine, JuiceFS to object storage):not related
- Others:
 not related

I have a plan , we compact a file ,update the mtime , so chunk sliced will be updated.

**Comment by SandyXSD** [comment]
In this case the cache for slices should be invalidated, and the read request should be retried, see: https://github.com/juicedata/juicefs/blob/v1.0.0/pkg/vfs/reader.go#L223

**Comment by penglaixy99** [comment]
Thanks.
