### ISSUE TITLE
【dentry cache】lots of lookup will request dentry info

### ISSUE THREAD

**Issue by penglaixy99** [juicedata/juicefs#4013]
**What would you like to be added**:
add dentry cache.

**Why is this needed**:
In AI Training Platform, lots of lookup meta request.  When we enabled open cache, only inode --> attr info is cached.

**Comment by SandyXSD** [comment]
Increasing `entry-cache` and/or `dir-entry-cache` may work, see: https://juicefs.com/docs/community/cache_management#kernel-metadata-cache.

**Comment by penglaixy99** [comment]
thanks.
