### ISSUE TITLE
Invalid meta driver: fdb

### ISSUE THREAD

**Issue by MrZsy** [juicedata/juicefs#4014]
juicefs format --storage minio --bucket http://127.0.0.1:1234/myjfs --access-key ***** --secret-key **** "fdb:///etc/foundationdb/fdb.cluster?prefix=test" pics 
2023/08/22 16:28:57.978605 juicefs[37419] <INFO>: Meta address: fdb:///etc/foundationdb/fdb.cluster?prefix=test [interface.go:494]
2023/08/22 16:28:57.978797 juicefs[37419] <FATAL>: Invalid meta driver: fdb [interface.go:497]

**Comment by SandyXSD** [comment]
You have to compile the binary supporting FoundationDB by yourself. Try `make juicefs.fdb`.

**Comment by SandyXSD** [comment]
Also a new PR is created to clarify the usage of fdb: https://github.com/juicedata/juicefs/pull/4016
