### ISSUE TITLE
The length of jfs_chunk slices is greater than 24

### ISSUE THREAD

**Issue by fengjiannan2010** [juicedata/juicefs#4015]
**What happened**:The length of jfs_chunk slices is greater than 24

**What you expected to happen**:I'm not sure if this is correct

**How to reproduce it (as minimally and precisely as possible)**:Use the V1.0.4 code to run in goland debug mode, and make a breakpoint in the Write method in sql.go

**Environment**: 
- JuiceFS version (use `juicefs --version`) :V1.0.4
- OS (e.g `cat /etc/os-release`):
PRETTY_NAME="Ubuntu 22.04.3 LTS"
NAME="Ubuntu"
VERSION_ID="22.04"
VERSION="22.04.3 LTS (Jammy Jellyfish)"
VERSION_CODENAME=jammy
ID=ubuntu
ID_LIKE=debian
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
UBUNTU_CODENAME=jammy
- Kernel (e.g. `uname -a`):
Linux netzon-base 6.2.0-26-generic #26~22.04.1-Ubuntu SMP PREEMPT_DYNAMIC Thu Jul 13 16:27:29 UTC 2 x86_64 x86_64 x86_64 GNU/Linux
- Metadata engine info (version, cloud provider managed or self maintained): PostgreSQL Version:(PostgreSQL) 15.3 (Debian 15.3-1.pgdg110+1)

![1692699273746](https://github.com/juicedata/juicefs/assets/24803533/b8895ca7-a4bf-4563-a25f-e7eadce984c9)

![36fde80a698a2cfa7f95ab67982371a](https://github.com/juicedata/juicefs/assets/24803533/35509734-269d-4d54-99a4-a74a1715f19c)

added log output as below：

![dc6b00a66b94e530f2b52ba071f29e1](https://github.com/juicedata/juicefs/assets/24803533/375236c9-4212-43f6-9256-df9bc69a53b6)

**Comment by SandyXSD** [comment]
A chunk may contain multiple slices, thus it's size being N * 24 bytes.

**Comment by SandyXSD** [comment]
From the [internals](https://juicefs.com/docs/community/internals/#sql-chunk) doc:
> Slices are an array of bytes, and each [Slice](https://juicefs.com/docs/community/internals/#chunk) corresponds to 24 bytes.
