### ISSUE TITLE
libjfs create、close file occur input/output error

### ISSUE THREAD

**Issue by anzuo09** [juicedata/juicefs#4048]
**What happened**:
We have a flink on k8s task ，it often got an input/output error，when libjfs create、close file。

![image](https://github.com/juicedata/juicefs/assets/106730199/a459b90c-fd00-4dc2-a973-09ef7eac518b)

![image](https://github.com/juicedata/juicefs/assets/106730199/16dbb2db-40c8-4a35-a60a-5baa9d59886b)

Flink task error
![image](https://github.com/juicedata/juicefs/assets/106730199/6d61d477-e080-4ef1-a94b-1e67105c1b63)

![image](https://github.com/juicedata/juicefs/assets/106730199/8a8766f4-a42a-4fae-8812-1424872068e3)

Error related to juicefs.access.log in k8s container
![image](https://github.com/juicedata/juicefs/assets/106730199/e3e7cafe-6c21-4664-a1ea-067f74fd1d5a)
**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**

**Environment**:
- JuiceFS version (use `juicefs --version`) or Hadoop Java SDK version:
    juicefs.version：1.1.0-beta1+2023-06-08.5ef17ba0
    juice-hadoop：1.0.4
- Cloud provider or hardware configuration running JuiceFS:
- OS (e.g `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Object storage (cloud provider and region, or self maintained):
- Metadata engine info (version, cloud provider managed or self maintained):
- Network connectivity (JuiceFS to metadata engine, JuiceFS to object storage):
- Others:

**Comment by tangyoupeng** [comment]
Close will make sure the data flush to object storage and it takes over 30 seconds. Object storage too slow or the bandwidth of  this machine was reached may cause this problem

**Comment by anzuo09** [comment]
> Close will make sure the data flush to object storage and it takes over 30 seconds. Object storage too slow or the bandwidth of this machine was reached may cause this problem

Yes ，this error occur when flink do checkpoint ,one operator has 3 parallelism ，two op finish within 20ms ，another op use 30s and throw an error。

**Comment by tangyoupeng** [comment]
But there is also `create` io exception. 
Can you provide more go log. It is printed to stderr

**Comment by anzuo09** [comment]
> But there is also `create` io exception. It usally caused by meta problem. Can you provide more go log. It is printed to stderr and may mixed with java log

I have been trying to find the go log, but I couldn't find it in the Flink task and access log.
Can you give me some advice?

**Comment by tangyoupeng** [comment]
Juicefs 1.1 version java sdk will print go log to java side, you can try reproduce the problem with it.

**Comment by anzuo09** [comment]
> Close will make sure the data flush to object storage and it takes over 30 seconds. Object storage too slow or the bandwidth of this machine was reached may cause this problem


That's great, we'll try it out

**Comment by anzuo09** [comment]
> Juicefs 1.1 version java sdk will print go log to java side, you can try reproduce the problem with it.

That's great, we'll try it out

**Comment by anzuo09** [comment]
> Juicefs 1.1 version java sdk will print go log to java side, you can try reproduce the problem with it.

Last Friday, we successfully upgraded Juicefs to version 1.1.0 release.
I checked the log this morning and found that there has only been one input/output error in the past 3 days
![image](https://github.com/juicedata/juicefs/assets/106730199/161201a4-b077-4b81-8b3d-aa0fb26a54b3)

In this CHK, we saw that Flink has been reconnecting pulsar (source operator)
Afterwards, IcebergStreamWriter reported this error while flushing
![image](https://github.com/juicedata/juicefs/assets/106730199/a64abc8a-7071-4ab7-a7e7-7b2cda1674dc)

The go log shows Redis timeout, which I cannot understand
![image](https://github.com/juicedata/juicefs/assets/106730199/08299328-07de-4743-8f92-9c2d6f2c53c8)



I feel that the error was caused by the failure of pulsar (which indeed occur), but I cannot understand how the  Flink source operator  affects the Flink sink operator , and caused the sink operator to report a redis timeout

**Comment by tangyoupeng** [comment]
can you check redis status when i/o timeout occurs

**Comment by anzuo09** [comment]
> can you check redis status when redis i/o timeout occurs


I checked Redis and it works very well.
Additionally, we would like to know how to increase the 30 second timeout time，we would be very grateful

**Comment by davies** [comment]
The timeout can be specified in meta-url, for example, `redis://myhost/1?read-timeout=1m`

**Comment by anzuo09** [comment]
Thank you. We have found that this issue can be resolved by turning off the metadata backup function of the Juicefs client. The main reason is that full backup can cause Redis overload, resulting in a series of close and create errors.
