### ISSUE TITLE
 attacher.MountDevice failed to create newCsiDriverClient: driver name csi.juicefs.com not found in the list of registered CSI drivers

### ISSUE THREAD

**Issue by fi-ecavc** [juicedata/juicefs#4053]
I have 3 cloud servers, built a 3-node k8s cluster with sealos, k8s:1.25.6 
and I only changed the default value in csi-driver: 
# The kubelet working directory, can be set using --root-dir when starting kubelet
#kubeletDir: /var/lib/kubelet
kubeletDir: /data/kubelet
# JuiceFS mount directory
#jfsMountDir: /var/lib/juicefs/volume
jfsMountDir: /data/juicefs/volume
# JuiceFS config directory
#jfsConfigDir: /var/lib/juicefs/config
jfsConfigDir: /data/juicefs/config, then the business application cannot be started, the driver does not exist, and it is normal to restore to the default value.

the app yaml:
apiVersion: v1
kind: Pod
metadata:
  name: juicefs-app
  namespace: "kube-system"
spec:
  nodeName: dev11
  hostAliases:
  - ip: "192.168.0.3"
    hostnames:
    - "sss.pigsty"
  containers:
  - args:
    - -c
    - while true; do echo $(date -u) >> /data/outtest.txt; sleep 5; done
    command:
    - /bin/sh
    #image: sealos.hub:5000/vcs:202309
    image: busybox
    name: app
    securityContext:
      runAsUser: 1000
      runAsGroup: 3000
      privileged: true
    volumeMounts:
    - mountPath: /data
      name: juicefs-pv
  volumes:
  - name: juicefs-pv
    persistentVolumeClaim:
      claimName: juicefs-pvc

csi node dev11 logs:
Defaulted container "juicefs-plugin" out of: juicefs-plugin, node-driver-registrar, liveness-probe
I0915 06:54:07.877400       7 main.go:94] Run CSI node
I0915 06:54:08.939210       7 node.go:168] Pod Reconciler Started
I0915 06:54:08.939235       7 driver.go:48] Driver: csi.juicefs.com version v0.22.0 commit f32024bb43e77cb834d5df26bf5b515f08debd67 date 2023-09-08T08:26:10Z
I0915 06:54:08.955132       7 driver.go:113] Listening for connection on address: &net.UnixAddr{Name:"/csi/csi.sock", Net:"unix"}

**Comment by zwwhdls** [comment]
duplicate with https://github.com/juicedata/juicefs-csi-driver/issues/751. closing.
