### ISSUE TITLE
Issue in using redis with TLS with juicefs-csi-driver component

### ISSUE THREAD

**Issue by subhranil05** [juicedata/juicefs#4092]
**What happened**:
Issue in using redis with TLS (rediss:// protocol) with juicefs-csi-driver component

**What you expected to happen**:
It should work as mTLS option is disabled in redis instance by setting tls-auth-client= no and TLS only enabled with a self signed cert

**How to reproduce it (as minimally and precisely as possible)**:
enabled redis tls and use rediss:// protocol in command args of juicefs

**Anything else we need to know?**
I'm using latest mount image --  ce-v1.0.5 where latest juicefs client is installed.
Following this doc https://juicefs.com/docs/community/databases_for_metadata/
not passing certs parameter as mTLS option is disbaled
getting error below

```
2023/10/12 07:16:32.038202 juicefs[1] <INFO>: Meta address: rediss://:****@redis-meta-master.juicefs-system.svc.cluster.local:6379/0 [interface.go:497]
2023/10/12 07:16:37.089927 juicefs[1] <WARNING>: parse info: x509: certificate signed by unknown authority [redis.go:3544]
2023/10/12 07:16:37.099110 juicefs[1] <FATAL>: Load metadata: x509: certificate signed by unknown authority [format.go:453]
```
We are using this same redis instance in other app with rediss:// protocol its working fine there
**Environment**:
- JuiceFS version (use `juicefs --version`) or Hadoop Java SDK version: mount image version  ce-v1.0.5 
- Cloud provider or hardware configuration running JuiceFS: azure
- OS (e.g `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Object storage (cloud provider and region, or self maintained):
- Metadata engine info (version, cloud provider managed or self maintained): redis
- Network connectivity (JuiceFS to metadata engine, JuiceFS to object storage):
- Others:

**Comment by subhranil05** [comment]
Is there any insecure-skip-verify option in juciefs for redis meta url?
As I'm using self signed cert.

**Comment by zhijian-pro** [comment]
> Is there any insecure-skip-verify option in juciefs for redis meta url? As I'm using self signed cert.

The redis meta url already supports the `insecure-skip-verify` parameter.
```
redis://127.0.0.1:6379/1?insecure-skip-verify=ture
```

**Comment by subhranil05** [comment]
@zhijian-pro Thanks much, It working now with parameter added.
I think it is added recently,  last time it was not supported parameter.
Can this parameter be added to the document refered here  please ?https://juicefs.com/docs/community/databases_for_metadata/

**Comment by zhijian-pro** [comment]
@subhranil05  Thanks for reminding us that we missed this parameter, we will improve the documentation.
