### ISSUE TITLE
JuiceFS doesn't seem to respect DNS TTL

### ISSUE THREAD

**Issue by solracsf** [juicedata/juicefs#4159]
I'm using `systemd-resolved` as the DNS provider on my system. It respects DNS TTL records.
My S3 provider URL is `s3.gra.io.cloud.ovh.net` TTL of this record is 1h (3600).

Yet, i get calls from the host where JuiceFS is installed on my upstream DNS server to this record at about once every 30 seconds (in average).

Using `dig`, I can see `systemd-resolved` has the record on the cache by TTL:

```
# dig +noall +answer s3.gra.io.cloud.ovh.net A @127.0.0.53
s3.gra.io.cloud.ovh.net.     3595    IN    A    141.95.161.76
```
All other DNS requests from this host seem to respect the DNS TTL of the respectives hostnames lookups, but not this one (coming from JuiceFS only).

**Comment by zhijian-pro** [comment]
This might help.
https://github.com/juicedata/juicefs/blob/acabf98f53b25f0f551650695606c4986bfa3cd0/pkg/object/restful.go#L37

**Comment by davies** [comment]
`dnscache` just call `net.LookupIP(address)` in every 1 minute, it should request DNS resolver in the same host (another DNS cache), the upstream should respect the DNS TTL.

Without `dnscache` here, you will see a DNS lookup request for every new S3 connection from JuiceFS.

**Comment by solracsf** [comment]
`for i in {1..1000}; do dig s3.gra.io.cloud.ovh.net &>/dev/null; done`

Whit this I can't see a single request upstream. So the local cache is correctly being hit. But requests from JuiceFS aren't, i can see them upstream (more than 1400 per day). Every other request from that host seem to respect the TTL.

**Comment by davies** [comment]
The released binary is using libmusl, can you build a JuiceFS from source code to verify it?

**Comment by solracsf** [comment]
I see what is hapenning here; systemd doesn't cache negative records. The host only has a A record, not AAAA, and JuiceFS is trying to get the AAAA record too. As it isn't cached locally, it goes upstream....

Closing.
