### ISSUE TITLE
<FATAL>: Error 1049 (42000): Unknown database 'test' [main.go:31]

### ISSUE THREAD

**Issue by zhoucheng361** [juicedata/juicefs#4161]
**What happened**:
https://github.com/juicedata/juicefs/actions/runs/6842570563/job/18604197271
2023/11/12 20:10:34.730586 juicefs[135644] <INFO>: Meta address: ***(127.0.0.1)/test [interface.go:498]
2023/11/12 20:10:34.735664 juicefs[135644] <INFO>: Data use minio://localhost:9000/testbucket/test-volume/(encrypted) [mount.go:625]
2023/11/12 20:10:34.735742 juicefs[135644] <WARNING>: delayed upload is disabled in non-writeback mode [cached_store.go:547]
2023/11/12 20:10:34.736144 juicefs[135644] <INFO>: Disk cache (/home/runner/.juicefs/cache2/3fbec8bf-7ae2-42f4-828d-0c678fc813d5/): capacity (851926 MB), free ratio (10%), max pending pages (10) [disk_cache.go:114]
2023/11/12 20:10:34.785655 juicefs[135644] <INFO>: Create session 1 OK with version: 1.2.0-dev+2023-11-09.5163180 [base.go:492]
2023/11/12 20:10:34.795293 juicefs[135644] <INFO>: Prometheus metrics listening on 127.0.0.1:9567 [mount.go:158]
2023/11/12 20:10:34.796127 juicefs[135644] <INFO>: Mounting volume test-volume at /tmp/sync-test ... [mount_unix.go:281]
2023/11/12 20:10:34.796197 juicefs[135644] <WARNING>: setpriority: permission denied [fuse.go:431]
Unimplemented opcode POLL
2023/11/12 20:04:36.670790 juicefs[124916] <FATAL>: Error 1049 (42000): Unknown database 'test' [main.go:31]
2023/11/12 20:09:28.018081 juicefs[133551] <FATAL>: failed to clean up sid 1 [main.go:31]
2023/11/12 20:09:52.791239 juicefs[134247] <FATAL>: Error 1049 (42000): Unknown database 'test' [main.go:31]

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**

**Environment**:
- JuiceFS version (use `juicefs --version`) or Hadoop Java SDK version:
- Cloud provider or hardware configuration running JuiceFS:
- OS (e.g `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Object storage (cloud provider and region, or self maintained):
- Metadata engine info (version, cloud provider managed or self maintained):
- Network connectivity (JuiceFS to metadata engine, JuiceFS to object storage):
- Others:

**Comment by SandyXSD** [comment]
Looks like the database `test` is deleted by another thread. Probably caused by `juicefs destroy --force`.
