### ISSUE TITLE
Consul metadata engine

### ISSUE THREAD

**Issue by unRob** [juicedata/juicefs#4166]
**What would you like to be added**: An adapter to store metadata using Hasicorp's [Consul](https://www.consul.io/).

**Why is this needed**: I already have Consul running in a distributed environment and would like to try out juicefs.

Started on [a branch](https://github.com/juicedata/juicefs/compare/main...unRob:juicefs:feature/consul-metadata?expand=1) but still figuring out how storage for metadata is supposed to work, (I'm re-reading [the internal docs](https://juicefs.com/docs/community/internals#metadata-structure) carefully). Currently stuck trying to get [`m.Create`](https://github.com/unRob/juicefs/blob/main/pkg/meta/base_test.go#L223) of `base_test` to not error with `operation not permitted` so I thought to ask before going any further. Would this metadata engine would be interesting to maintainers?

**Comment by davies** [comment]
Consul may be similar to etcd, so you can take pkg/meta/tkv_etcd.go as example. 

Since we don't have much experience on Consul, so we will not put much effort on it.
