### ISSUE TITLE
allow insecure-skip-verify for tikv

### ISSUE THREAD

**Issue by ghost** [juicedata/juicefs#4170]
**What happened**:

``tikv://<ip>:2079/aigc-shared?ca=/home/ca.crt&cert=/home/client.crt&key=/home/client.pem&insecure-skip-verify=1`` doesn't work and the errro message is 

``
:TRANSIENT_FAILURE: error:rpc error: code = Unavailable desc = connection error: desc = \"transport: authentication handshake failed: x509: certificate is valid for 127.0.0.1, 192.168.0.2, not <target ip>
``

**What you expected to happen**:

allow insecure-skip-verify for tikv

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**

**Environment**:
- JuiceFS version (use `juicefs --version`) or Hadoop Java SDK version: juicefs version 1.1.0+2023-09-04.08c4ae6
- Cloud provider or hardware configuration running JuiceFS: Linux
- OS (e.g `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Object storage (cloud provider and region, or self maintained):
- Metadata engine info (version, cloud provider managed or self maintained):
- Network connectivity (JuiceFS to metadata engine, JuiceFS to object storage):
- Others:

**Comment by zhijian-pro** [comment]
Tikv does not support `insecure-skip-verify`
