### ISSUE TITLE
Support local disk mode instead of network share mode of WinFSP 

### ISSUE THREAD

**Issue by ghost** [juicedata/juicefs#4173]
**What would you like to be added**:
Currently juicefs on windows runs with network share mode which makes a lot of software unable to detect the drive
https://github.com/winfsp/winfsp/issues/507

Please support local disk mode instead of network share mode of WinFSP 

**Why is this needed**:
https://github.com/winfsp/winfsp/issues/358

**Comment by SandyXSD** [comment]
New features for Windows client will be low priority.
