### ISSUE TITLE
support SeaweedFS as storage backend

### ISSUE THREAD

**Issue by ghost** [juicedata/juicefs#4177]
**What would you like to be added**:
support SeaweedFS as storage backend

**Why is this needed**:
SeaweedFS is very optimized for small files and it has a different protocal compared to s3.

**Comment by SandyXSD** [comment]
Any issue when you use it with the S3 protocol?

**Comment by davies** [comment]
It's very difficult to use SeaweedFS without the filer under current architecture, so we won't put it int he roadmap.
