### ISSUE TITLE
When using Fluid to dock with Juicefs, both the dataset and runtime are normal, but when creating a pod using this PVC, it cannot be mounted

### ISSUE THREAD

**Issue by feeyman** [juicedata/juicefs#4196]
**Hello, could you please help me take a look at this issue? The main information is as follows. I am not sure what additional information I need. Please provide some help. Thank you**

1、**What happened**:
```
Events:
  Type     Reason       Age                  From               Message
  ----     ------       ----                 ----               -------
  Normal   Scheduled    15m                  default-scheduler  Successfully assigned default/demo-app to k8s-02
  Warning  FailedMount  9m7s                 kubelet            Unable to attach or mount volumes: unmounted volumes=[demo], unattached volumes=[kube-api-access-dhscg demo]: timed out waiting for the condition
  Warning  FailedMount  2m16s (x5 over 13m)  kubelet            Unable to attach or mount volumes: unmounted volumes=[demo], unattached volumes=[demo kube-api-access-dhscg]: timed out waiting for the condition
  Warning  FailedMount  77s (x15 over 15m)   kubelet            MountVolume.MountDevice failed for volume "default-jfsdemo" : rpc error: code = Unknown desc = NodeStageVolume: can't get node k8s-02: Get "https:                 //apiserver.cluster.local:6443/api/v1/nodes/k8s-02": dial tcp: lookup apiserver.cluster.local on 10.96.0.10:53: no such host
[root@k8s-01 03Fluid]# kubectl logs demo-app
Error from server (BadRequest): container "demo" in pod "demo-app" is waiting to start: ContainerCreating
[root@k8s-01 03Fluid]#
```
![image](https://github.com/juicedata/juicefs/assets/24524775/8885a190-da1c-43ab-b77b-f9d2216f906f)

2、**What you expected to happen**:
The pvc mounted

3、**How to reproduce it (as minimally and precisely as possible)**:
jfs-secret.ymal
```
apiVersion: v1
kind: Secret
metadata:
  name: jfs-secret
type: Opaque
stringData:
  metaurl: redis://192.168.91.157:6379/11
  access-key: horeb
  secret-key: horeb
```
dataset.ymal
```
apiVersion: data.fluid.io/v1alpha1
kind: Dataset
metadata:
  name: jfsdemo
spec:
  mounts:
    - name: myjfs-1122
      mountPoint: "juicefs:///demo"
      encryptOptions:
        - name: metaurl
          valueFrom:
            secretKeyRef:
              name: jfs-secret
              key: metaurl
        - name: access-key
          valueFrom:
            secretKeyRef:
              name: jfs-secret
              key: access-key
        - name: secret-key
          valueFrom:
            secretKeyRef:
              name: jfs-secret
              key: secret-key
  accessModes:
    - ReadWriteMany
```
runtime.ymal
```
apiVersion: data.fluid.io/v1alpha1
kind: JuiceFSRuntime
metadata:
  name: jfsdemo  # 与 Dataset 同名
spec:
  replicas: 1
  tieredstore:
    levels:
      - mediumtype: SSD
        path: /data/jfscache
        quota: 500Mi
        low: "0.01"
        # volumeType: hostPath (default), emptyDir
  worker:
    options:
      "cache-size": "102400"
```
app.ymal
```
apiVersion: v1
kind: Pod
metadata:
  name: demo-app
spec:
  containers:
    - name: demo
      image: nginx
      volumeMounts:
        - mountPath: /data
          name: demo
  volumes:
    - name: demo
      persistentVolumeClaim:
        claimName: jfsdemo
```

4、**Anything else we need to know?**
![image](https://github.com/juicedata/juicefs/assets/24524775/957c7b1e-8770-45dd-9d91-7fb5e44a274c)

5、**Environment**:
```
NAME     STATUS   ROLES                  AGE    VERSION
k8s-01   Ready    control-plane,master   7d4h   v1.25.0
k8s-02   Ready    worker                 7d4h   v1.25.0
k8s-03   Ready    worker                 7d4h   v1.25.0

fluid version is   0.9.2
```

**Comment by zwwhdls** [comment]
Hi @feeyman , it's because Fluid CSI tried to get node name by connecting apiserver but it failed.

**Comment by TrafalgarZZZ** [comment]
@feeyman Hi, here is a similar issue that may do some help to your problem: https://github.com/fluid-cloudnative/fluid/issues/3417#issuecomment-1691532950.

To resolve it, try to [install Fluid with Fluid CSI Plugin setting in hostNetwork mode](https://github.com/fluid-cloudnative/fluid/blob/master/docs/zh/userguide/install.md#%E9%AB%98%E7%BA%A7%E9%85%8D%E7%BD%AE), for example: 
```
helm install fluid --set csi.config.hostNetwork=true fluid/fluid
```

**Comment by feeyman** [comment]
> Hi @feeyman , it's because Fluid CSI tried to get node name by connecting apiserver but it failed.



> Hi @feeyman , it's because Fluid CSI tried to get node name by connecting apiserver but it failed.

Okay, thank you for your reply.

**Comment by feeyman** [comment]
> @feeyman Hi, here is a similar issue that may do some help to your problem: [fluid-cloudnative/fluid#3417 (comment)](https://github.com/fluid-cloudnative/fluid/issues/3417#issuecomment-1691532950).
> 
> To resolve it, try to [install Fluid with Fluid CSI Plugin setting in hostNetwork mode](https://github.com/fluid-cloudnative/fluid/blob/master/docs/zh/userguide/install.md#%E9%AB%98%E7%BA%A7%E9%85%8D%E7%BD%AE), for example:
> 
> ```
> helm install fluid --set csi.config.hostNetwork=true fluid/fluid
> ```

Okay, thank you for your reply. I will refer to the link and make some modifications.

**Comment by feeyman** [comment]
> @feeyman Hi, here is a similar issue that may do some help to your problem: [fluid-cloudnative/fluid#3417 (comment)](https://github.com/fluid-cloudnative/fluid/issues/3417#issuecomment-1691532950).
> 
> To resolve it, try to [install Fluid with Fluid CSI Plugin setting in hostNetwork mode](https://github.com/fluid-cloudnative/fluid/blob/master/docs/zh/userguide/install.md#%E9%AB%98%E7%BA%A7%E9%85%8D%E7%BD%AE), for example:
> 
> ```
> helm install fluid --set csi.config.hostNetwork=true fluid/fluid
> ```

Hello, I have reinstalled Fluid and it is indeed possible to launch the app. However, after running for a period of time, the CSI plugin of Fluid has been in a crashing state. Do I need to make some settings for this?
![image](https://github.com/juicedata/juicefs/assets/24524775/546376b8-d98a-455a-b0e1-1886c08457b2)

**Comment by TrafalgarZZZ** [comment]
@feeyman Would u mind having a look at the log messages in Fluid CSI Plugin container? You can check it by:
```
kubectl logs csi-nodeplugin-fluid-4z6q4 -n fluid-system -c fluid-csi -p
```

**Comment by feeyman** [comment]
> @feeyman Would u mind having a look at the log messages in Fluid CSI Plugin container? You can check it by:
> 
> ```
> kubectl logs csi-nodeplugin-fluid-4z6q4 -n fluid-system -c plugins -p
> ```

**Hello, @TrafalgarZZZ according to the command you provided, the printing information is as follows, indicating that the address has been used. Could you please provide some suggestions? Thank you**
```
[root@k8s-01 03Fluid]# kubectl logs csi-nodeplugin-fluid-8q9sc -n fluid-system -c plugins -p
+ check_kubelet_rootdir_subfolder /var/lib/kubelet/pods
+ local dir=/var/lib/kubelet/pods
+ '[' '!' -d /var/lib/kubelet/pods ']'
+ check_kubelet_rootdir_subfolder /var/lib/kubelet/plugins
+ local dir=/var/lib/kubelet/plugins
+ '[' '!' -d /var/lib/kubelet/plugins ']'
+ rm -f /var/lib/kubelet/csi-plugins/fuse.csi.fluid.io/csi.sock
+ mkdir -p /var/lib/kubelet/csi-plugins/fuse.csi.fluid.io
+ fluid-csi start --nodeid=k8s-02 --endpoint=unix:///var/lib/kubelet/csi-plugins/fuse.csi.fluid.io/csi.sock --v=5 --feature-gates=FuseRecovery=false --prune-fs=fuse.alluxio-fuse,fuse.jindofs-fuse,fuse.juicefs,fuse.                           goosefs-fuse,ossfs,alifuse.aliyun-alinas-efc --prune-path=/runtime-mnt --pprof-addr=:6060
2023/11/24 17:39:49 BuildDate: 2023-09-18_08:46:57
2023/11/24 17:39:49 GitCommit: 02f70acc7eb6ee7b9aead54a15060b2b85197dc3
2023/11/24 17:39:49 GitTreeState: clean
2023/11/24 17:39:49 GoVersion: go1.18.10
2023/11/24 17:39:49 Compiler: gc
2023/11/24 17:39:49 Platform: linux/amd64
I1124 17:39:49.182635    8792 csi.go:135] Enabling pprof with address :6060
I1124 17:39:49.182682    8792 csi.go:147] Starting pprof HTTP server at :6060
E1124 17:39:49.183727    8792 csi.go:163] listen tcp :6060: bind: address already in useFailed to start debug HTTP server
panic: listen tcp :6060: bind: address already in use

goroutine 71 [running]:
github.com/fluid-cloudnative/fluid/cmd/csi/app.newPprofServer.func1()
        /go/src/github.com/fluid-cloudnative/fluid/cmd/csi/app/csi.go:164 +0x1f1
created by github.com/fluid-cloudnative/fluid/cmd/csi/app.newPprofServer
        /go/src/github.com/fluid-cloudnative/fluid/cmd/csi/app/csi.go:149 +0x3c9

```

**Comment by TrafalgarZZZ** [comment]
@feeyman Ah.. Seems when running in hostNetwork mode, CSI Plugin is requiring a port that conflicts with your existing port. Please try to setting it manually in the Fluid CSI Plugin's daemonset, For example:
```
kubectl edit -n fluid-system ds csi-nodeplugin-fluid
```
find the argument `--pprof-addr=:6060`, and then delete it. (or changing it to a different port). Pprof is for process profiling only, deleting it will have no negative effect on Fluid's functionality.
```diff
 - args:
        - --nodeid=$(NODE_ID)
        - --endpoint=$(CSI_ENDPOINT)
        - --v=5
        - --feature-gates=FuseRecovery=true
        - --prune-fs=fuse.alluxio-fuse,fuse.jindofs-fuse,fuse.juicefs,fuse.goosefs-fuse,ossfs
        - --prune-path=/runtime-mnt
-      - --pprof-addr=:6060
```

**Comment by feeyman** [comment]
> @feeyman Ah.. Seems when running in hostNetwork mode, CSI Plugin is requiring a port that conflicts with your existing port. Please try to setting it manually in the Fluid CSI Plugin's daemonset, For example:
> 
> ```
> kubectl edit -n fluid-system ds csi-nodeplugin-fluid
> ```
> 
> find the argument `--pprof-addr=:6060`, and then delete it. (or changing it to a different port). Pprof is for process profiling only, deleting it will have no negative effect on Fluid's functionality.
> 
> ```diff
>  - args:
>         - --nodeid=$(NODE_ID)
>         - --endpoint=$(CSI_ENDPOINT)
>         - --v=5
>         - --feature-gates=FuseRecovery=true
>         - --prune-fs=fuse.alluxio-fuse,fuse.jindofs-fuse,fuse.juicefs,fuse.goosefs-fuse,ossfs
>         - --prune-path=/runtime-mnt
> -      - --pprof-addr=:6060
> ```

@TrafalgarZZZ **Thank you very much for your reply. It has been resolved, but it is worth noting that the previous conflict was also caused by CSI occupying port 6060.**
