### ISSUE TITLE
Initial mount timeout should be configurable

### ISSUE THREAD

**Issue by nodakai** [juicedata/juicefs#4206]
https://github.com/juicedata/juicefs/blob/a612e0896e8a4e83e4ed77b2e3e3989ba6a860ae/cmd/mount_unix.go#L43

I've encountered an issue with YugabyteDB, a PostgreSQL-compatible distributed database. It generally works well but has a quirk: its system tables respond slowly without human optimization, _e.g._ https://github.com/yugabyte/yugabyte-db/issues/7745

Specifically, the 10-second timeout in JuiceFS is insufficient for XORM to retrieve table metadata from Yugabyte using [this complex query with multiple joins](https://github.com/go-xorm/xorm/blob/f39e5d9bfdb70c435f8649555f224c0fa4f51e54/dialect_postgres.go#L953). (I know XORM has moved to GiTea, but this part hasn't changed much)

I anticipate that YugabyteDB will perform adequately once it overcomes the initial table metadata retrieval hurdle. Could you introduce a new parameter or environment variable to extend the hard-coded 20 x 0.5s = 10s timeout, allowing for longer durations as needed?

**Comment by davies** [comment]
We could add an environment variable as a temporary workaround, which could be JFS_MOUNT_TIMEOUT=10.
