### ISSUE TITLE
juicefs support dynamic change log level to debug better

### ISSUE THREAD

**Issue by liujiangang01** [juicedata/juicefs#4211]
**What would you like to be added**:
Now, when we want to debug, we must restart juicefs process to specify log level, it will result in business interrupting,  I wish juicefs can change log level when running like cephfs

**Why is this needed**:
Now debug by changing log level will result in business interrupting

**Comment by davies** [comment]
Once we can restart juicefs gracefully without interrupting applications, we can change the logging level easily.

We will support graceful restart in 1.2 release.

**Comment by zhijian-pro** [comment]
done #4392
