### ISSUE TITLE
JuiceFS is very slow in windows

### ISSUE THREAD

**Issue by ztyandjw** [juicedata/juicefs#4231]
请教一个问题：
我们windows上的Unreal游戏引擎消费数据，通过juicefs来挂盘，挂的测试数据差不多40G，2000个目录，2w个文件（这个量仅仅是测试数据）。发现个非常奇怪的问题，我右键点击某个文件查看属性，也要十几秒响应，完全无法使用。挂上的盘进入其中某个目录也卡卡的感觉， 其中juicefs使用当前最新版，元数据redis，数据minio理论上都没有性能瓶颈。
我的问题是，是juicefs的windows支持当前就有这个问题，还是我的使用姿势不对。

**Comment by davies** [comment]
感觉应该是不正常的，需要看下juicefs 客户端的日志

**Comment by ztyandjw** [comment]
> 感觉应该是不正常的，需要看下juicefs 客户端的日志

您好：


![WXWorkCapture_17017415597682](https://github.com/juicedata/juicefs/assets/14125652/b4bcaf4a-0afb-4d39-81a0-86aae5ebeac9)
windows 控制台没有日志信息，windows上更详细日志该去哪里找

**Comment by ztyandjw** [comment]
我mount的时候加了--verbose，看着没error，debug日志如下：

![image](https://github.com/juicedata/juicefs/assets/14125652/2d56cfac-c2df-4f39-af3f-7917b370ee7b)

**Comment by SandyXSD** [comment]
这些 debug 日志是正常的，可以关掉 verbose，看看有没 warning 或 error 日志呢？

**Comment by ztyandjw** [comment]
> 这些 debug 日志是正常的，可以关掉 verbose，看看有没 warning 或 error 日志呢？

没有任何报错

**Comment by SandyXSD** [comment]
一般这种问题需要通过检查 accesslog 来确认，但这个功能在 windows 下支持的有限。
可以考虑借助 WSL 在 windows 中来使用 juicefs：https://juicefs.com/docs/zh/community/tutorials/juicefs_on_wsl/

**Comment by ztyandjw** [comment]
> 一般这种问题需要通过检查 accesslog 来确认，但这个功能在 windows 下支持的有限。 可以考虑借助 WSL 在 windows 中来使用 juicefs：https://juicefs.com/docs/zh/community/tutorials/juicefs_on_wsl/

你好，我试下wsl挂载，我们的场景类似于，将一个UE5引擎开发的游戏的整个目录不放在windows本地，包括游戏启动exe也是在juicefs中，这种场景你们觉得能支持么

**Comment by ztyandjw** [comment]
工作节点是虚拟机，虚拟化嵌套应该跑不了wsl 这个场景应该是无解了
