### ISSUE TITLE
mtime should be accurate to nanoseconds after sync

### ISSUE THREAD

**Issue by zhoucheng361** [juicedata/juicefs#4239]
**What happened**:
root@bench-01:~/juicefs# rm xxxx yyyy zzzz -rf && touch xxxx  && ./juicefs sync xxxx yyyy && cp -a  xxxx zzzz  && stat xxxx yyyy zzzz
2023/12/07 14:34:39.250032 juicefs[471227] <INFO>: Prometheus metrics listening on 127.0.0.1:9567 [mount.go:158]
2023/12/07 14:34:39.250385 juicefs[471227] <INFO>: Syncing from file:///root/juicefs/xxxx to file:///root/juicefs/yyyy [sync.go:1099]
Scanned objects: 1/1 [==============================================================]  974.2/s used: 1.033498ms
Skipped objects: 0                 0.0/s      
Pending objects: 0                 0.0/s      
 Copied objects: 1                 1230.5/s   
   Copied bytes: 0.0 b (0 Bytes)   0.0 b/s    
 Failed objects: 0                 0.0/s      
2023/12/07 14:34:39.251453 juicefs[471227] <INFO>: Found: 1, skipped: 0, copied: 1 (0 B), failed: 0 [sync.go:1138]
  File: xxxx
  Size: 0         	Blocks: 0          IO Block: 4096   regular empty file
Device: fc01h/64513d	Inode: 4325528     Links: 1
Access: (0644/-rw-r--r--)  Uid: (    0/    root)   Gid: (    0/    root)
Access: 2023-12-07 14:34:39.250585739 +0800
Modify: 2023-12-07 14:34:39.218585555 +0800
Change: 2023-12-07 14:34:39.218585555 +0800
 Birth: -
  File: yyyy
  Size: 0         	Blocks: 0          IO Block: 4096   regular empty file
Device: fc01h/64513d	Inode: 4325543     Links: 1
Access: (0644/-rw-r--r--)  Uid: (    0/    root)   Gid: (    0/    root)
Access: 2023-12-07 14:34:39.218586000 +0800
Modify: 2023-12-07 14:34:39.218586000 +0800
Change: 2023-12-07 14:34:39.246585717 +0800
 Birth: -
  File: zzzz
  Size: 0         	Blocks: 0          IO Block: 4096   regular empty file
Device: fc01h/64513d	Inode: 4325544     Links: 1
Access: (0644/-rw-r--r--)  Uid: (    0/    root)   Gid: (    0/    root)
Access: 2023-12-07 14:34:39.218585555 +0800
Modify: 2023-12-07 14:34:39.218585555 +0800
Change: 2023-12-07 14:34:39.250585739 +0800
 Birth: -

**What you expected to happen**:
mtime should be accurate to nanoseconds

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**

**Environment**:
- JuiceFS version (use `juicefs --version`) or Hadoop Java SDK version:
- Cloud provider or hardware configuration running JuiceFS:
- OS (e.g `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Object storage (cloud provider and region, or self maintained):
- Metadata engine info (version, cloud provider managed or self maintained):
- Network connectivity (JuiceFS to metadata engine, JuiceFS to object storage):
- Others:

**Comment by davies** [comment]
Most of the storage does not support mtime in nanosecond, so we may not fix it.
