### ISSUE TITLE
When using sync to synchronize files, the Tencent COS server will report an error "The XML you provided was not well-formed or did not validate against our published schema"

### ISSUE THREAD

**Issue by shezhangjun** [juicedata/juicefs#4251]
**What happened:**
When using sync to synchronize files, the Tencent COS server will report an error "The XML you provided was not well-formed or did not validate against our published schema"

How to reproduce it (as minimally and precisely as possible):
Synchronize a large file and specify a key between target objects greater than 200 strings

Anything else we need to know?
I consulted the engineers of Tencent Cloud service provider and the answer was that it was caused by an extra object key being passed in the encapsulated multi-part upload method.
https://github.com/juicedata/juicefs/blob/main/pkg/object/cos.go#L246
<img width="1244" alt="image" src="https://github.com/juicedata/juicefs/assets/50070809/2d7f7d87-e45b-443c-bd49-88bd87dd2736">

The following is the API document provided by Tencent Cloud:
https://www.tencentcloud.com/document/product/436/7742
<img width="1784" alt="image" src="https://github.com/juicedata/juicefs/assets/50070809/9e8cca76-2525-436a-8bc7-79114b416c9a">

**Comment by yujunz** [comment]
Some history discussion about similar issues in https://juicefs.slack.com/archives/C01HXAD7LDQ/p1691479108609459

> Does juicefs sync retry on errors by default?
> 2023/08/08 07:10:17.419533 juicefs[2] <ERROR>: Failed to copy data of 51354d2a-1c4d-11ec-920d-00044bf65ef2/frames.tar.gz in 17m27.316406572s: multipart: POST https://<endpoint>/<prefix>/ab51f28a-b9b5-45b8-bdf4-0ab6da2ceb0d/51354d2a-1c4d-11ec-920d-00044bf65ef2/frames.tar.gz?uploadId=1691477570771f61e58a6c7e0b37b0f8ff97db384257c066476a702f850650288b3ac9070a: 400 MalformedXML(Message: The XML you provided was not well-formed or did not validate against our published schema., RequestId: NjRkMWVhNTRfMzJlZDVlMGJfZDI3MV8xMjI1MTRjNA==, TraceId: OGVmYzZiMmQzYjA2OWNhODk0NTRkMTBiOWVmMDAxODc0OWRkZjk0ZDM1NmI1M2E2MTRlY2MzZDhmNmI5MWI1OTY4OGQ5OWY4YWFhNjAzOTkyNDJhZmQyOTk1YWVmOWFlZjBkMDIxYTM5ZWI1ODVlNWY4ZmE0NTkzOTRjOTc0YTg=) [sync.go:501]
> 2023/08/08 07:10:17.419607 juicefs[2] <ERROR>: Failed to copy object 51354d2a-1c4d-11ec-920d-00044bf65ef2/frames.tar.gz: multipart: POST https://<endpoint>/<prefix>/ab51f28a-b9b5-45b8-bdf4-0ab6da2ceb0d/51354d2a-1c4d-11ec-920d-00044bf65ef2/frames.tar.gz?uploadId=1691477570771f61e58a6c7e0b37b0f8ff97db384257c066476a702f850650288b3ac9070a: 400 MalformedXML(Message: The XML you provided was not well-formed or did not validate against our published schema., RequestId: NjRkMWVhNTRfMzJlZDVlMGJfZDI3MV8xMjI1MTRjNA==, TraceId: OGVmYzZiMmQzYjA2OWNhODk0NTRkMTBiOWVmMDAxODc0OWRkZjk0ZDM1NmI1M2E2MTRlY2MzZDhmNmI5MWI1OTY4OGQ5OWY4YWFhNjAzOTkyNDJhZmQyOTk1YWVmOWFlZjBkMDIxYTM5ZWI1ODVlNWY4ZmE0NTkzOTRjOTc0YTg=) [sync.go:587]

> timfeirg
> --io-retries is supported in juicefs enterprise edition

> timfeirg
> I didn't see the same option in juicefs CE, should be ported back from EE @zhijian

zhijian
@Yujun Zhang
>  Default retry three times, details can see copyData 

> https://github.com/juicedata/juicefs/blob/22866d31089935d21f09ca960368635f8cd6a3c3/pkg/sync/sync.go#L475-L501
> sync.go
> func copyData(src, dst object.ObjectStorage, key string, size int64) error {
>     start := time.Now()
>     var err error
>     if size < maxBlock {
>         err = try(3, func() error { return doCopySingle(src, dst, key, size) })
> Show more
> <https://github.com/juicedata/juicefs|juicedata/juicefs>juicedata/juicefs | Added by GitHub
> 
> Yujun Zhang
> - 根据报错信息，拷贝数据到cos的过程中使用到了分块上传，cos的分块上传有一个接口Complete Multipart Upload，client需要请求这个接口来实现完成整个分块上传，调用期间会传递一个xml类型的body（参考https://cloud.tencent.com/document/product/436/7742）
> - 后端同学反馈client在调用该接口时，并没有上传xml 类型的body
> 后端同学反馈，如果使用cos sdk进行的copy动作，这个xml body是会自动生成的，但看到client使用的JuiceFS的sdk，JuiceFS在请求这个接口时可能没有去组装xml，所以会出现错误。
> Feedback from service provider.
> 
> 
> zhijian
> juicefs 的 sdk 调用的是 cos 的 complete
> https://github.com/juicedata/juicefs/blob/66bdd057c62504eeb03af71a850cb45fdfcd9415/pkg/object/interface.go#L108
> interface.go
>     CompleteUpload(key string, uploadID string, parts []*Part) error
> <https://github.com/juicedata/juicefs|juicedata/juicefs>juicedata/juicefs | Added by GitHub
> 
> 
> zhijian
> 能提供一些复现的方法吗，我注意到这个分块上传持续了 17 分钟，是特别大的文件吗？
> 
> Yujun Zhang
> 是个偶发的现象，2k 对象里出现了一次，总共 1T 数据
> 
> zhijian
> 好的，如果复现了可以提一个 issue

**Comment by davies** [comment]
I don't think the extra field of `Key` is the root cause, it may help reduce the size of xml body to reduce the chance of failure?

The failure may come from retry of `CompleteMultipartUpload`, which lost the XML body.

**Comment by shezhangjun** [comment]
> I don't think the extra field of `Key` is the root cause, it may help reduce the size of xml body to reduce the chance of failure?
> 
> The failure may come from retry of `CompleteMultipartUpload`, which lost the XML body.

I consulted the engineers of Tencent Cloud service provider, and the answer I got was that they limit the body size to 2MB when parsing XML. If this size is exceeded, the request will be abandoned and an error will be reported.

**Comment by davies** [comment]
> > I don't think the extra field of `Key` is the root cause, it may help reduce the size of xml body to reduce the chance of failure?
> > The failure may come from retry of `CompleteMultipartUpload`, which lost the XML body.
> 
> I consulted the engineers of Tencent Cloud service provider, and the answer I got was that they limit the body size to 2MB when parsing XML. If this size is exceeded, the request will be abandoned and an error will be reported.

I see, we will fix that.

**Comment by shezhangjun** [comment]
> I see, we will fix that.

Thank you very much！
