### ISSUE TITLE
High memory usage (almost OOM) on dump with Badger

### ISSUE THREAD

**Issue by solracsf** [juicedata/juicefs#4252]
_From https://juicefs.slack.com/archives/C01HXAD7LDQ/p1702284763003769_

**What happened**:

When performing juicefs dump using Badger, the overall memory consumption is very high.

**What you expected to happen**:

Not consuming almost 80% of both RAM and SWAP on a low-end box. (4Gb RAM + 3Gb SWAP).
INodes used are 2.6M. Badger dir is 300M and produced dump file is 1Gb.

Prefer slower dump but lower memory usage.

**How to reproduce it (as minimally and precisely as possible)**:

`juicefs dump badger://"${BADGER}" "${DUMP_FILE}" --keep-secret-key`

**Anything else we need to know?**

**Environment**:
- JuiceFS version : `juicefs version 1.1.1+2023-11-28.437f4e6`
- OS:  `Ubuntu 22.04.3 LTS`
- Kernel: `5.15.0-91-generic`
- Metadata engine: `Badger`

**Comment by solracsf** [comment]
Hi @davies i'm still hitting OOM here with juicefs version 1.1.2.
Memory consumption grows beyond 5GiB and OOM is hit :(

**Comment by davies** [comment]
Do you mean v1.2 ? How to reproduce this behavior?

**Comment by solracsf** [comment]
No, 1.1.2
I'll give 1.2 a shot and report back

**Comment by solracsf** [comment]
All good with v1.2 and `--fast=false` 👍
