### ISSUE TITLE
Warnings when running latest build on macOS

### ISSUE THREAD

**Issue by yujunz** [juicedata/juicefs#4256]
**What happened**:
```
go run github.com/juicedata/juicefs --help
# github.com/shirou/gopsutil/disk
iostat_darwin.c:28:2: warning: 'IOMasterPort' is deprecated: first deprecated in macOS 12.0 [-Wdeprecated-declarations]
/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/System/Library/Frameworks/IOKit.framework/Headers/IOKitLib.h:143:1: note: 'IOMasterPort' has been explicitly marked deprecated here
# github.com/shirou/gopsutil/host
smc_darwin.c:75:41: warning: 'kIOMasterPortDefault' is deprecated: first deprecated in macOS 12.0 [-Wdeprecated-declarations]
/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/System/Library/Frameworks/IOKit.framework/Headers/IOKitLib.h:133:19: note: 'kIOMasterPortDefault' has been explicitly marked deprecated here
# github.com/rjeczalik/notify
cgo-gcc-prolog:217:2: warning: 'FSEventStreamScheduleWithRunLoop' is deprecated: first deprecated in macOS 13.0 - Use FSEventStreamSetDispatchQueue instead. [-Wdeprecated-declarations]
/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/System/Library/Frameworks/CoreServices.framework/Frameworks/FSEvents.framework/Headers/FSEvents.h:1153:1: note: 'FSEventStreamScheduleWithRunLoop' has been explicitly marked deprecated here
NAME:
   juicefs - A POSIX file system built on Redis and object storage.

USAGE:
   juicefs [global options] command [command options] [arguments...]

VERSION:
   1.2.0-dev+unknown
```
**What you expected to happen**:

No warning message

**How to reproduce it (as minimally and precisely as possible)**:

```
go run github.com/juicedata/juicefs --help
```
**Anything else we need to know?**

**Environment**:
- JuiceFS version: 1.2.0-dev+unknown
- Cloud provider or hardware configuration running JuiceFS: N/A
- OS (e.g `cat /etc/os-release`): macOS 14.1.1 (23B81)
- Kernel (e.g. `uname -a`): Darwin YZ-m 23.1.0 Darwin Kernel Version 23.1.0: Mon Oct  9 21:27:27 PDT 2023; root:xnu-10002.41.9~6/RELEASE_X86_64 x86_64
- Object storage (cloud provider and region, or self maintained): N/A
- Metadata engine info (version, cloud provider managed or self maintained): N/A
- Network connectivity (JuiceFS to metadata engine, JuiceFS to object storage): N/A
- Others: current HEAD `963d81ef`

**Comment by davies** [comment]
the warning come from gopsutil, a dependent of minio， which should be upgraded to fix the warning.
