### ISSUE TITLE
recorded error in fileWriter never reset

### ISSUE THREAD

**Issue by SandyXSD** [juicedata/juicefs#4261]
If a fileWriter ever encounters some error (say, EIO), it will record it and return this error for later write & flush. However, even with the error set, the fileWriter still tries to do the normal work first (and it may succeed after a while), which may pass to the application a false negative result.

**Comment by davies** [comment]
false negative is better than false positive. The EIO tell application that the file may be corrupt, and JuiceFS try its best to save the data.

Once all data are flushed, and the file handle is closed, app can access the file without problem.
