### ISSUE TITLE
sync tries https for sftp

### ISSUE THREAD

**Issue by bjo81** [juicedata/juicefs#4282]
```
root@host ~ # juicefs -v sync  sftp://user:pass@user.rsync.net/juicecloud b2://xxxx:yyy/cloudstorage
2023/12/19 14:57:30.030460 juicefs[672723] <DEBUG>: maxprocs: Leaving GOMAXPROCS=4: CPU quota undefined [maxprocs.go:47]
2023/12/19 14:57:30.031713 juicefs[672723] <DEBUG>: Creating sftp storage at endpoint https://user.rsync.net [object_storage.go:171]
2023/12/19 14:57:30.033716 juicefs[672723] <ERROR>: connect to https failed: dial tcp: lookup https: no such host [sftp.go:539]
2023/12/19 14:57:30.033841 juicefs[672723] <FATAL>: create sftp https://user.rsync.net: dial tcp: lookup https: no such host [main.go:31]
```

**Environment**:
- JuiceFS version (use `juicefs --version`) or Hadoop Java SDK version: 1.1.1
- Cloud provider or hardware configuration running JuiceFS: rsync.net / b2
- OS (e.g `cat /etc/os-release`): Arch Linux
- Kernel (e.g. `uname -a`): 6.1.68
- Object storage (cloud provider and region, or self maintained):
- Metadata engine info (version, cloud provider managed or self maintained): redis
- Network connectivity (JuiceFS to metadata engine, JuiceFS to object storage): local

**Comment by SandyXSD** [comment]
Yes, there's a bug parsing the uri. As a temporary workaround you may try:
`juicefs -v sync user:pass@user.rsync.net:/juicecloud b2://xxxx:yyy/cloudstorage`

**Comment by bjo81** [comment]
The workaround leads to another issue:
```
2023/12/20 15:41:04.883244 juicefs[1115587] <DEBUG>: Creating sftp storage at endpoint user.rsync.net/juicecloud [object_storage.go:171]
panic: runtime error: slice bounds out of range [:-1]
```

**Comment by SandyXSD** [comment]
We need a `:` before the slash `/`, i.e, `xxx:/juicecloud`.

**Comment by davies** [comment]
It's common to use relative path in SFTP, but URI does not support that, so JuiceFS does NOT support specify the SFTP address as URI, it should be in format  `[USER[:PASS]@]HOST[:PORT]:PATH`, the path could be absolute or relative.

**Comment by davies** [comment]
We will support it as URI, but you can't have relative path in it.
