### ISSUE TITLE
Support triggering compaction of all files under a given directory

### ISSUE THREAD

**Issue by SandyXSD** [juicedata/juicefs#4303]
**What would you like to be added**:
Support triggering compaction of all files under a given directory

**Why is this needed**:
An alternative light way of `gc --compact` for large clusters.

**Comment by jiefenghuang** [comment]
### requirements
- A new **user** compact command
- Support triggering compaction of all files under a given directory

### design
- what we have
  - meta.engine.compact(inode Ino, index uint32, force bool)

- what we should do
  - Iterate entries under specific path, get all set (inode, type, length)
  - For a file, calculate the chunk count based on its length. The chunk index ranges from 0 to (chunk count-1). Perform 'compact' operation on all chunks(maybe not exists).
    - chunkCount = (fileLength + chunkSize - 1) / chunkSize
    - Ensure that the 'compact' function behaves correctly for non-existent chunks.
    - For files with many chunk holes, performance is poor, but this scenario is infrequent. Currently, it is not being considered.
