### ISSUE TITLE
[Feature Request] built-in replicating juicefs metadata sqlitedb into s3

### ISSUE THREAD

**Issue by diyism** [juicedata/juicefs#4304]
Currently, I can real-time incrementally replicate the metadata sqlite3 database into my s3 server with Litestream(https://litestream.io/guides/s3/):

```
$ juicefs format --storage s3 --bucket https://my_s3_server.com/bucket1 sqlite3:///home/malcolm/juicefs_meta.sqlite my_juicefs
$ juicefs mount -d --enable-xattr sqlite3://juicefs_meta.sqlite ./my_juicefs
$ cat litestream.yml
dbs:
  - path: /home/malcolm/juicefs_meta.sqlite
    replicas:
      - name: mys3
        type: s3
        endpoint: http://my_s3_server.com/
        bucket: bucket1
        path:   juicefs_meta.sqlite
        access-key-id: ...
        secret-access-key: ...
$ nohup litestream replicate >/dev/null 2>&1 &
```

But it's not very convenient, so I think that we need a built-in version for this function, for example to add one parameter "meta-bucket":
`$ juicefs format --storage s3 --bucket https://my_s3_server.com/bucket1 --meta-bucket https://my_s3_server.com/bucket1 sqlite3:///home/malcolm/juicefs_meta.sqlite my_juicefs`

**Comment by SandyXSD** [comment]
It looks to be only feasible for sqlite, but not a general solution. We recommend using the [metadata backup](https://juicefs.com/docs/community/metadata_dump_load/#backup-automatically) feature to backup metadata in the object storage.

**Comment by diyism** [comment]
Great,it seems that I can backup metadata every 30 seconds for my folder which contains far less than 1 million files:
`juicefs mount -d --enable-xattr --backup-meta 30s sqlite3://juicefs_meta.sqlite ./my_juicefs`
Thanks.
