### ISSUE TITLE
TIKV go client panic

### ISSUE THREAD

**Issue by penglaixy99** [juicedata/juicefs#4305]
**What happened**:

go client panic 

panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x10 pc=0xaa1d6b]

goroutine 73220838 [running]:
google.golang.org/grpc.(*ClientConn).Close(0x0)
        /data/go/pkg/mod/google.golang.org/grpc@v1.45.0/clientconn.go:1059 +0x4b
github.com/tikv/client-go/v2/internal/client.(*connArray).Close(0xc018f58870)
        /data/go/pkg/mod/github.com/tikv/client-go/v2@v2.0.1/internal/client/client.go:238 +0x57
github.com/tikv/client-go/v2/internal/client.(*connArray).Init(0xc018f58870, {0xc001bf00a8, 0x14}, {{0x0, 0x0}, {0x0, 0x0}, {0x0, 0x0}, {0xc00087b820, ...}}, ...)
        /data/go/pkg/mod/github.com/tikv/client-go/v2@v2.0.1/internal/client/client.go:198 +0xea6
github.com/tikv/client-go/v2/internal/client.newConnArray(0x4, {0xc001bf00a8, 0x14}, {{0x0, 0x0}, {0x0, 0x0}, {0x0, 0x0}, {0xc00087b820, ...}}, ...)
        /data/go/pkg/mod/github.com/tikv/client-go/v2@v2.0.1/internal/client/client.go:128 +0x198
github.com/tikv/client-go/v2/internal/client.(*RPCClient).createConnArray(0xc0006d1000, {0xc001bf00a8, 0x14}, 0x14, {0x0, 0x0, 0x0})
        /data/go/pkg/mod/github.com/tikv/client-go/v2@v2.0.1/internal/client/client.go:320 +0x2e5
github.com/tikv/client-go/v2/internal/client.(*RPCClient).getConnArray(0xc0006d1000, {0xc001bf00a8, 0x14}, 0x68, {0x0, 0x0, 0x0})
        /data/go/pkg/mod/github.com/tikv/client-go/v2@v2.0.1/internal/client/client.go:295 +0x155
github.com/tikv/client-go/v2/internal/client.(*RPCClient).SendRequest(0xc0006d1000, {0x2772c70, 0xc00073e180}, {0xc001bf00a8, 0x14}, 0xc002e98140, 0x6fc23ac00)
        /data/go/pkg/mod/github.com/tikv/client-go/v2@v2.0.1/internal/client/client.go:381 +0x387
github.com/tikv/client-go/v2/internal/client.interceptedClient.SendRequest({{0x27413e0, 0xc0006d1000}}, {0x2772c70, 0xc00073e180}, {0xc001bf00a8, 0x14}, 0x7f4c2575a408, 0x6fc23ac00)
        /data/go/pkg/mod/github.com/tikv/client-go/v2@v2.0.1/internal/client/client_interceptor.go:42 +0x186
github.com/tikv/client-go/v2/internal/client.reqCollapse.SendRequest({{0x27431b8, 0xc000e80670}}, {0x2772c70, 0xc00073e180}, {0xc001bf00a8, 0x14}, 0x21e0f40, 0x101000000000001)
        /data/go/pkg/mod/github.com/tikv/client-go/v2@v2.0.1/internal/client/client_collapse.go:74 +0xd6
github.com/tikv/client-go/v2/tikv.(*KVStore).updateSafeTS.func1({0x2772c70, 0xc00073e180}, 0xc00fa6bfd0, 0x278049, {0xc001bf00a8, 0x14})
        /data/go/pkg/mod/github.com/tikv/client-go/v2@v2.0.1/tikv/kv.go:540 +0x195
created by github.com/tikv/client-go/v2/tikv.(*KVStore).updateSafeTS
        /data/go/pkg/mod/github.com/tikv/client-go/v2@v2.0.1/tikv/kv.go:538 +0x8c

**What you expected to happen**:

go client should not panic

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**

**Environment**:
- JuiceFS version (use `juicefs --version`) or Hadoop Java SDK version:
- Cloud provider or hardware configuration running JuiceFS:
- OS (e.g `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Object storage (cloud provider and region, or self maintained):
- Metadata engine info (version, cloud provider managed or self maintained):
- Network connectivity (JuiceFS to metadata engine, JuiceFS to object storage):
- Others:

**Comment by zhijian-pro** [comment]
Can you provide a screenshot of the command executed?

**Comment by SandyXSD** [comment]
It's a bug of tikv client-go@v2.0.1, and was fixed by #2947 .
Upgrading JuiceFS to v1.0.3+ should fix this issue.

**Comment by penglaixy99** [comment]
We have met this bug for several times. Thanks,
