### ISSUE TITLE
jfs write IO error( raft entry is too large)

### ISSUE THREAD

**Issue by lidaohang** [juicedata/juicefs#4311]
![image](https://github.com/juicedata/juicefs/assets/4077643/a22c28ba-0e1c-4a94-bf6f-8e564661127e)

[jfs_raft_entry_too_large.log](https://github.com/juicedata/juicefs/files/13837534/jfs_raft_entry_too_large.log)

**Comment by zhijian-pro** [comment]
https://asktug.com/t/topic/693938
This question may need to be addressed to the tikv community

**Comment by SandyXSD** [comment]
Fixed by limiting the number of slices in one chunk, see #4309, #4573.
