### ISSUE TITLE
CMD: Refactor Operating System-Specific Code in cmd

### ISSUE THREAD

**Issue by jiefenghuang** [juicedata/juicefs#4343]
**What would you like to be added**:
Refactor Operating System-Specific Code in cmd

**Why is this needed**:
Currently, many commands have conditional checks in the code to differentiate behavior based on the operating system.
To address this, let's introduce a new file called 'cmd_list' to classify the supported command sets for different operating systems.

**Comment by davies** [comment]
We can remove the check of OS, but do that in openController()
