### ISSUE TITLE
juicefs format fails with MinIO bucket

### ISSUE THREAD

**Issue by copecog** [juicedata/juicefs#4378]
**What happened**:
Following JuiceFS guide with default MinIO installation. Mounting an already formatted filesystem from last year continues to work, but creating a new one fails:
```
root@jfs-test1:~# juicefs format --storage minio --bucket "http://127.0.0.1:9000/jfstest1" --access-key ...  --secret-key ... "sqlite3://jfstest1" jfstest1
2024/01/24 15:25:21.321143 juicefs[1640] <INFO>: Meta address: sqlite3://jfstest1.db [interface.go:497]
2024/01/24 15:25:21.328980 juicefs[1640] <WARNING>: The latency to database is too high: 7.506719ms [sql.go:260]
2024/01/24 15:25:21.329855 juicefs[1640] <INFO>: Data use minio://127.0.0.1:9000/jfstest1/jfstest1/ [format.go:471]
2024/01/24 15:25:33.418740 juicefs[1640] <FATAL>: Storage minio://127.0.0.1:9000/jfstest1/jfstest1/ is not configured correctly: Failed to create bucket minio://127.0.0.1:9000/jfstest1/jfstest1/: SignatureDoesNotMatch: The request signature we calculated does not match the signature you provided. Check your key and signing method.
        status code: 403, request id: ..., host id: ..., previous error: SignatureDoesNotMatch: The request signature we calculated does not match the signature you provided. Check your key and signing method.
        status code: 403, request id: ..., host id: ... [format.go:474]
```

**What you expected to happen**:
The format to succeed.

**How to reproduce it (as minimally and precisely as possible)**:
Default Ubuntu 22.04 installation. Default MinIO installation from their repo. Default JuiceFS installation from juicefs ubuntu ppa.
Create RW user under MinIO, create Access Key, Create Bucket.

**Anything else we need to know?**

**Environment**:
- JuiceFS version (use `juicefs --version`) or Hadoop Java SDK version:
```
root@jfs-test1:~# juicefs --version
juicefs version 1.1.1+2023-11-28.437f4e6
```
- Cloud provider or hardware configuration running JuiceFS:
KVM in Proxmox VE, 16GB ram, host CPU Intel XEON E5-2640 v3, VirtIO Disk/NIC
- OS (e.g `cat /etc/os-release`):
```
root@jfs-test1:~# cat /etc/os-release 
PRETTY_NAME="Ubuntu 22.04.3 LTS"
NAME="Ubuntu"
VERSION_ID="22.04"
VERSION="22.04.3 LTS (Jammy Jellyfish)"
VERSION_CODENAME=jammy
ID=ubuntu
ID_LIKE=debian
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
UBUNTU_CODENAME=jammy
```
- Kernel (e.g. `uname -a`):
```
root@jfs-test1:~# uname -a
Linux jfs-test1 5.15.0-91-generic #101-Ubuntu SMP Tue Nov 14 13:30:08 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux
```
- Object storage (cloud provider and region, or self maintained):
MinIO https://dl.min.io/server/minio/release/linux-amd64/archive/minio_20240118225128.0.0_amd64.deb Single Disk Single Node install with admin creds and MINIO_OPTS="--console-address :9001" set under /etc/default/minio
- Metadata engine info (version, cloud provider managed or self maintained):
Testing with local MySQL and SQLite3, error under both of them.
- Network connectivity (JuiceFS to metadata engine, JuiceFS to object storage):
All localhost
- Others:

**Comment by jiefenghuang** [comment]
We can see from the log that there is a 'create bucket' error, which is a test to check if the storage is available during the initialization of JuiceFS. The 'SignatureDoesNotMatch' error could be due to either a secret key error or a user permission issue?

**Comment by zhijian-pro** [comment]
Can you use the `mc` tool to test whether ak sk is working properly?

**Comment by copecog** [comment]
> Can you use the `mc` tool to test whether ak sk is working properly?

Here is me using the same key pair:
```
root@jfs-test1:~# mc alias set localhost http://127.0.0.1:9000 KWHH9jdXy3h7iKNz4qiZ Y6fIJcCJVJTtPInL9prO804eWAKeS3w8JdT4znqY
Added `localhost` successfully.
root@jfs-test1:~# mc cp ./minio.deb localhost/jfstest1/minio.deb
/root/minio.deb:                               33.99 MiB / 33.99 MiB ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 157.12 MiB/s 0s
root@jfs-test1:~# 
```
The user has minio default policy for "readwrite"

**Comment by copecog** [comment]
Here is the `mc admin trace` (This is a test VM to figure out the source of this error so I don't need to actually redact any private information)

```
jfs-test1.xmission.com:9000 [REQUEST s3.PutBucket] [2024-01-24T18:02:17.633] [Client IP: [2607:fa18:0:35::231]]                                                                                                                                                     
jfs-test1.xmission.com:9000 PUT /jfstest1                                                                                         
jfs-test1.xmission.com:9000 Proto: HTTP/1.1                                                                                                                                                                                                                         
jfs-test1.xmission.com:9000 Host: jfs-test1.xmission.com:9000                                                                     
jfs-test1.xmission.com:9000 X-Amz-Content-Sha256: e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855                                                                                                                                                  
jfs-test1.xmission.com:9000 X-Amz-Date: 20240125T010217Z                                                                                                                                                                                                            
jfs-test1.xmission.com:9000 Authorization: AWS4-HMAC-SHA256 Credential=KWHH9jdXy3h7iKNz4qiZ/20240125/us-east-1/s3/aws4_request, SignedHeaders=host;x-amz-content-sha256;x-amz-date, Signature=c1744a700b3d983904dc2ca982690273cef6add3933cb018a063bba39f4bd7b6
jfs-test1.xmission.com:9000 Content-Length: 0                    
jfs-test1.xmission.com:9000 User-Agent: aws-sdk-go/1.44.262 (go1.18.5; linux; amd64)                                              
jfs-test1.xmission.com:9000                                      
jfs-test1.xmission.com:9000 [RESPONSE] [2024-01-24T18:02:17.633] [ Duration 151µs TTFB 138.759µs ↑ 77 B  ↓ 403 B ]                                                                                                                                                  
jfs-test1.xmission.com:9000 403 Forbidden                        
jfs-test1.xmission.com:9000 Accept-Ranges: bytes                 
jfs-test1.xmission.com:9000 Strict-Transport-Security: max-age=31536000; includeSubDomains                                        
jfs-test1.xmission.com:9000 X-Amz-Request-Id: 17AD716ADD192920                                                                    
jfs-test1.xmission.com:9000 Content-Length: 403                                                                                   
jfs-test1.xmission.com:9000 Content-Type: application/xml                                                                         
jfs-test1.xmission.com:9000 Server: MinIO                        
jfs-test1.xmission.com:9000 Vary: Origin,Accept-Encoding         
jfs-test1.xmission.com:9000 X-Amz-Id-2: dd9025bab4ad464b049177c95eb6ebf374d3b3fd1af9251148b658df7ac2e3e8                          
jfs-test1.xmission.com:9000 X-Content-Type-Options: nosniff                                                                       
jfs-test1.xmission.com:9000 X-Xss-Protection: 1; mode=block                                                                       
jfs-test1.xmission.com:9000 <?xml version="1.0" encoding="UTF-8"?>                                                                
<Error><Code>SignatureDoesNotMatch</Code><Message>The request signature we calculated does not match the signature you provided. Check your key and signing method.</Message><BucketName>jfstest1</BucketName><Resource>/jfstest1</Resource><RequestId>17AD716ADD192
920</RequestId><HostId>dd9025bab4ad464b049177c95eb6ebf374d3b3fd1af9251148b658df7ac2e3e8</HostId></Error>                          
jfs-test1.xmission.com:9000                                      
```

**Comment by zhijian-pro** [comment]
I didn't reproduce the problem, but once I entered the sk incorrectly I got the same error as you, so I doubt that the sk is correct and being sk correctly into `juicefs`

<img width="2559" alt="image" src="https://github.com/juicedata/juicefs/assets/31313340/924c1561-0465-48b7-ac06-7e88ffaaace2">

**Comment by copecog** [comment]
> I didn't reproduce the problem, but once I entered the sk incorrectly I got the same error as you, so I doubt that the sk is correct and being sk correctly into `juicefs`
> <img alt="image" width="2000" src="https://private-user-images.githubusercontent.com/31313340/299874843-924c1561-0465-48b7-ac06-7e88ffaaace2.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDYzOTA0MjQsIm5iZiI6MTcwNjM5MDEyNCwicGF0aCI6Ii8zMTMxMzM0MC8yOTk4NzQ4NDMtOTI0YzE1NjEtMDQ2NS00OGI3LWFjMDYtN2U4OGZmYWFhY2UyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTI3VDIxMTUyNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTYwMDg1OGViNDg3OGMzNTZkMzJhY2M5MGNkODZiNDgyZjRkMzVhYjUwNWQ4ODMyMTZmZjhkY2I3NzIwMzA4OTAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.zUAeorzhFxSAG0EG5Aj06_CZCX2FX_P43LMsSQosN5A">

Okay, thank you for looking at this for me! I see this right now across a bunch of different minio installs (on ubuntu 22.04) when trying to format. I must be doing some repetitively that is messing up the authorization (I've been around long enough to know that's a thing).

**Comment by copecog** [comment]
I figured it out. It fails when there are dashes "-" in the bucket name.
