### ISSUE TITLE
clang compile error with juicefs filesystem

### ISSUE THREAD

**Issue by robotslacker** [juicedata/juicefs#4399]
**What happened**:
Try setup a build system with juicefs.
The clang build works fine when fs is ext4, nfs. but failed with juicefs.
Build command:
/usr/local/llvm/bin/clang++ -v --target=x86_64-linux-gnu \
    --sysroot=/home/jenkins/build/src/pontus/cmake/linux/../../contrib/sysroot/linux-x86_64/x86_64-linux-gnu/libc  \
	--gcc-toolchain=/home/jenkins/build/src/pontus/cmake/linux/../../contrib/sysroot/linux-x86_64 \
	-std=c++20 -fdiagnostics-color=always -fsized-deallocation  -pipe -mssse3 -msse4.1 -msse4.2 \
	-mpclmul -mpopcnt -fasynchronous-unwind-tables -ffile-prefix-map=/home/jenkins/build/src/pontus=. \
	-falign-functions=32 -mbranches-within-32B-boundaries -Wno-error=reserved-identifier \
	-Wno-error=suggest-destructor-override -fdiagnostics-absolute-paths -fstrict-vtable-pointers \
	-fexperimental-new-pass-manager -w -O3 -DNDEBUG  \
	--gcc-toolchain=/home/jenkins/build/src/pontus/cmake/linux/../../contrib/sysroot/linux-x86_64 \
	--ld-path=/usr/bin/ld.gold -rdynamic -no-pie -Wl,-no-pie    \
	-Xlinker --no-undefined contrib/protobuf-cmake/CMakeFiles/protoc.dir/__/protobuf/src/google/protobuf/compiler/main.cc.o  \
	-o contrib/protobuf-cmake/protoc  contrib/protobuf-cmake/lib_libprotoc.a  contrib/protobuf-cmake/lib_libprotobuf.a  \
	-lpthread  contrib/zlib-ng-cmake/lib_zlib.a  -Wl,--start-group  base/glibc-compatibility/libglibc-compatibility.a  \
	base/glibc-compatibility/memcpy/libmemcpy.a  contrib/libcxx-cmake/libcxx.a  contrib/libcxxabi-cmake/libcxxabi.a  \
	contrib/libunwind-cmake/libunwind.a  -Wl,--end-group  \
	-nodefaultlibs /usr/local/llvm/lib/clang/15.0.7/lib/x86_64-unknown-linux-gnu/libclang_rt.builtins.a  -lc -lm -lrt -lpthread -ldl 

Console output:
clang version 15.0.7
Target: x86_64-unknown-linux-gnu
Thread model: posix
InstalledDir: /usr/local/llvm/bin
Found candidate GCC installation: /home/jenkins/build/src/pontus/cmake/linux/../../contrib/sysroot/linux-x86_64/lib/gcc/x86_64-linux-gnu/9
Selected GCC installation: /home/jenkins/build/src/pontus/cmake/linux/../../contrib/sysroot/linux-x86_64/lib/gcc/x86_64-linux-gnu/9
Candidate multilib: .;@m64
Selected multilib: .;@m64
 "/usr/bin/ld.gold" --sysroot=/home/jenkins/build/src/pontus/cmake/linux/../../contrib/sysroot/linux-x86_64/x86_64-linux-gnu/libc -export-dynamic --hash-style=gnu --eh-frame-hdr -m elf_x86_64 -export-dynamic -dynamic-linker /lib64/ld-linux-x86-64.so.2 -o contrib/protobuf-cmake/protoc /home/jenkins/build/src/pontus/cmake/linux/../../contrib/sysroot/linux-x86_64/x86_64-linux-gnu/libc/usr/lib/../lib64/crt1.o /home/jenkins/build/src/pontus/cmake/linux/../../contrib/sysroot/linux-x86_64/x86_64-linux-gnu/libc/usr/lib/../lib64/crti.o /home/jenkins/build/src/pontus/cmake/linux/../../contrib/sysroot/linux-x86_64/lib/gcc/x86_64-linux-gnu/9/crtbegin.o -L/usr/local/llvm/bin/../lib/x86_64-unknown-linux-gnu -L/home/jenkins/build/src/pontus/cmake/linux/../../contrib/sysroot/linux-x86_64/lib/gcc/x86_64-linux-gnu/9 -L/home/jenkins/build/src/pontus/cmake/linux/../../contrib/sysroot/linux-x86_64/x86_64-linux-gnu/libc/lib/../lib64 -L/home/jenkins/build/src/pontus/cmake/linux/../../contrib/sysroot/linux-x86_64/x86_64-linux-gnu/libc/usr/lib/../lib64 -L/home/jenkins/build/src/pontus/cmake/linux/../../contrib/sysroot/linux-x86_64/x86_64-linux-gnu/libc/lib -L/home/jenkins/build/src/pontus/cmake/linux/../../contrib/sysroot/linux-x86_64/x86_64-linux-gnu/libc/usr/lib -no-pie --no-undefined contrib/protobuf-cmake/CMakeFiles/protoc.dir/__/protobuf/src/google/protobuf/compiler/main.cc.o contrib/protobuf-cmake/lib_libprotoc.a contrib/protobuf-cmake/lib_libprotobuf.a -lpthread contrib/zlib-ng-cmake/lib_zlib.a --start-group base/glibc-compatibility/libglibc-compatibility.a base/glibc-compatibility/memcpy/libmemcpy.a contrib/libcxx-cmake/libcxx.a contrib/libcxxabi-cmake/libcxxabi.a contrib/libunwind-cmake/libunwind.a --end-group /usr/local/llvm/lib/clang/15.0.7/lib/x86_64-unknown-linux-gnu/libclang_rt.builtins.a -lc -lm -lrt -lpthread -ldl /home/jenkins/build/src/pontus/cmake/linux/../../contrib/sysroot/linux-x86_64/lib/gcc/x86_64-linux-gnu/9/crtend.o /home/jenkins/build/src/pontus/cmake/linux/../../contrib/sysroot/linux-x86_64/x86_64-linux-gnu/libc/usr/lib/../lib64/crtn.o
clang-15: error: unable to execute command: Bus error (core dumped)
clang-15: error: linker command failed due to signal (use -v to see invocation)

strace file:
  upload

core file: 
  upload
[strace.txt](https://github.com/juicedata/juicefs/files/14176653/strace.txt)
[Uploading core.zip…]()

**What you expected to happen**:
Compile successful.

**How to reproduce it (as minimally and precisely as possible)**:
Not sure if you can successful reproduce it.
Just upload clang compile strace file and core file.

**Anything else we need to know?**

**Environment**:
- JuiceFS version ： 
juicefs version 1.1.2+2024-02-04.8dbd89a
- OS (e.g `cat /etc/os-release`):
NAME="CentOS Linux"
VERSION="7 (Core)"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="7"
PRETTY_NAME="CentOS Linux 7 (Core)"

- Kernel (e.g. `uname -a`):
Linux 0f07832ca6cc 6.1.0-17-amd64   （CentOS7 Docker in debian)

- Object storage (cloud provider and region, or self maintained):
minio

- Metadata engine info (version, cloud provider managed or self maintained):
redis

- Network connectivity (JuiceFS to metadata engine, JuiceFS to object storage):
- Others:

**Comment by davies** [comment]
Can you reproduce this failure by compiling a open source project? Then we can reproduce it and analyze the root cause.

**Comment by robotslacker** [comment]
maybe upload docker image and clickhouse source code to "百度网盘" can help you?
I'll upload them later.

**Comment by SandyXSD** [comment]
The docker image should be helpful.
