### ISSUE TITLE
Does community version supports metadata cache, data cache and read/write buffer ?

### ISSUE THREAD

**Issue by wengyao04** [juicedata/juicefs#4402]
Hi we are exploring juiceFS with the community version. We are curious if the community version supported the all caches documented in 
https://juicefs.com/docs/community/guide/cache/

- metadata cache
  - in kernel
  - in client memory
- read/write buffer 
- data cache
  - kernel space page cache
  - user space chunk cache

**Comment by solracsf** [comment]
Yes it does.
