### ISSUE TITLE
int overflows when compiling on arm32

### ISSUE THREAD

**Issue by marczz** [juicedata/juicefs#4406]
I tried to compile juicefs 1.1.2 on arm32 platforms; I tried on two systems:
- first an an armv5tel processor and go1.21.5 and gcc 10.2.1, 
-  second with an armvh i.e armv7l processor,  the same version of go 1.21.5 and gcc 12.2.0.

I got exactly the same result.

First tkiv, don't compile. So I tried first to compile juicefs.lite, which do not include extra libraries.

The result is 

```
pkg/object/eos.go:47:29: cannot use 5 << 30 (untyped int constant 5368709120) as int value in struct literal (overflows)
pkg/object/ks3.go:66:29: cannot use 5 << 30 (untyped int constant 5368709120) as int value in struct literal (overflows)
pkg/object/minio.go:49:29: cannot use 5 << 30 (untyped int constant 5368709120) as int value in struct literal (overflows)
pkg/object/qingstor.go:55:29: cannot use 5 << 30 (untyped int constant 5368709120) as int value in struct literal (overflows)
pkg/object/s3.go:74:29: cannot use 5 << 30 (untyped int constant 5368709120) as int value in struct literal (overflows)
pkg/object/scw.go:47:29: cannot use 5 << 30 (untyped int constant 5368709120) as int value in struct literal (overflows)
pkg/object/tos.go:53:29: cannot use 5 << 30 (untyped int constant 5368709120) as int value in struct literal (overflows)
make: *** [Makefile:31: juicefs.lite] Error 1
``` 

Additional info:
```
juicefs version 1.1.2
OS version machine 1 : Debian GNU/Linux 11 (bullseye)
OS version machine 2: Debian GNU/Linux 12 (bookworm)
kernel machine 1: Linux b3 5.10.177-1 #1 Mon Apr 17 06:42:38 UTC 2023 armv5tel GNU/Linux
kernel machine 2: Linux freedombox 6.1.0-18-armmp-lpae #1 SMP Debian 6.1.76-1 (2024-02-01) armv7l GNU/Linux
```

**Comment by davies** [comment]
There could be many places where a `int` is expected as int64, we JuiceFS may still not work in 32 bits platform even we fix the the above compile issue. 

What's your use case, and what does the arm32 system looks like?

**Comment by marczz** [comment]
As told above juicefs v1.0.3 compile without error on arm32, at least with a slightly reduced feature list, tikv don't compile, I have successfully compiled juicefs on my armv5l and armv5tel servers with a size of 24MB for juicefs.lite and 54M for full juicefs except key-value db (tikv,redis,etcd,) and some object data providers, but including the relational databases, gateway, smb, nfs, webdav with a 54MB binary.

Now to answer your question of use case.

I have a small nas heterogeneous cluster with 4 local machines 2 armv7, one old armv5tel,and arm64; and to hosted amd64 vps. Everything in a single lan through vpn. Presently the local data is managed with btrfs filesystems mounted on DRBD replicated notes, and exported to clients with nfs and samba. I use S3 compatible providers with restic backup,  rclone, and S3QL filesystem.

I want to reorganize my storage to provide a unified approach, more reliability thru redundancy, and some HA (in fact only a medium availability where I can fix quickly a failing node).

I was considering, and want to test two products that may fill my needs SeaweedFS and Juicefs. I yet installed seaweedfs wich compile flawlessly on arm32, with only tiny memory footprint for the three components master, volume, filler. 

This is a nice concept, with very interesting features like the hot/warm cache, and the minimal egress on object stores.
But the documentation is scattered in many unrelated document; sometime nearly contradictory, and it may be uneasy to master. And moreover, the system has to be carefully tuned to get a fault tolerant system.

A crucial feature for me is redundancy and reliability of data, and on Seaweedfs, Juicefs and similar products; the redundancy of the data is easily obtained by replication of data nodes, the metadata may be a single point of failure, usually (in JuiceFs or some SeaweedFs configuration) solved either by periodic database backup or continuous database backup. Seaweedfs also propose a database replication instead of distributed database.
And a main concern is to ensure coherence between Data and Metadata; even if your data is safe without the corresponding metadata is is just blob garbage.

I have appreciated the clarity of Juicefs Documentation, and I think it would be easier to deploy, and to achieve a good reliability. But my use case is obviously very far from large industrial deployments, and far from the user of RH Enterprise.

If you say that JuiceFs does not and will not support arm32, I will drop the test. 

But it would be useful to set clearly in the documentation, that JuiceFs only work with 64bits systems, presently the only proposed binary packages are 64bits, but we are invited to compile on other systems. 

Thank you @davies  for your answer.

**Comment by davies** [comment]
Right now we don't have a plan to support arm32, but can fix the small issues you find. Let's see how far we can go, thanks!

**Comment by marczz** [comment]
Thank you for this branch. Using the arm32 branch juicefs.lite compile without problem on both armhf and armv5l. If I try to compile juicefs with no tag, tikv has an integer overflow, with adding the tag notikv, juicefs compile without error. It is not important for me as I don't consider using tikv. I suppose that nobody will host tikv or redis on arm32 because the ram is usually limited, but one could want to use a key/value db hosted on an other server from the arm32 client. 

I did not yet tested the binaries, I don't know the build system, I see some test targets in the makefile, but I don't know exactly what they do, if you want I use them and if they are not too heavy for a tiny cpu, just let me know.
