### ISSUE TITLE
mount error on mac

### ISSUE THREAD

**Issue by lichunqiang** [juicedata/juicefs#4412]
**What happened**:

just follow the step from https://juicefs.com/docs/community/getting-started/standalone , when execute mount there is an error:

command `juicefs mount sqlite3://myjfs.db ~/jfs  -v`

output:
```
2024/02/21 12:40:47.413590 juicefs[73940] <DEBUG>: maxprocs: Leaving GOMAXPROCS=8: CPU quota undefined [maxprocs.go:47]
2024/02/21 12:40:47.414574 juicefs[73940] <INFO>: Meta address: sqlite3://myjfs.db [interface.go:497]
[xorm] [info]  2024/02/21 12:40:47.414709 PING DATABASE sqlite3
2024/02/21 12:40:47.418044 juicefs[73940] <DEBUG>: Creating file storage at endpoint /Users/light/.juicefs/local/ [object_storage.go:171]
2024/02/21 12:40:47.418101 juicefs[73940] <DEBUG>: Ensure directory /Users/light/.juicefs/local/ [file.go:336]
2024/02/21 12:40:47.418173 juicefs[73940] <INFO>: Data use file:///Users/light/.juicefs/local/myjfs/ [mount.go:605]
2024/02/21 12:40:47.418436 juicefs[73940] <INFO>: Disk cache (/Users/light/.juicefs/cache/05eaa5de-3d17-42d9-8b56-d3dd8d0017fd/): capacity (102400 MB), free ratio (10%), max pending pages (15) [disk_cache.go:114]
2024/02/21 12:40:47.418758 juicefs[73940] <DEBUG>: Scan /Users/light/.juicefs/cache/05eaa5de-3d17-42d9-8b56-d3dd8d0017fd/rawstaging to find staging blocks [disk_cache.go:619]
2024/02/21 12:40:47.418765 juicefs[73940] <DEBUG>: Scan /Users/light/.juicefs/cache/05eaa5de-3d17-42d9-8b56-d3dd8d0017fd/raw to find cached blocks [disk_cache.go:572]
2024/02/21 12:40:47.418835 juicefs[73940] <DEBUG>: Found 0 cached blocks (0 bytes) in /Users/light/.juicefs/cache/05eaa5de-3d17-42d9-8b56-d3dd8d0017fd/ with 276.428µs [disk_cache.go:604]
2024/02/21 12:40:47.423693 juicefs[73940] <INFO>: Create session 6 OK with version: 1.1.2+2024-02-04.8dbd89a [base.go:494]
2024/02/21 12:40:47.425111 juicefs[73940] <INFO>: Prometheus metrics listening on 127.0.0.1:9567 [mount.go:160]
2024/02/21 12:40:47.425221 juicefs[73940] <INFO>: Mounting volume myjfs at /Users/light/jfs ... [mount_unix.go:269]
2024/02/21 12:40:47.425289 juicefs[73940] <WARNING>: setpriority: permission denied [fuse.go:431]
2024/02/21 12:40:47.425395 juicefs[73940] <FATAL>: fuse: fuse: no FUSE mount utility found [mount_unix.go:272]
```

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**

**Environment**:
- JuiceFS version (use `juicefs --version`) or Hadoop Java SDK version:
> juicefs version 1.1.2+2024-02-04.8dbd89a
- Cloud provider or hardware configuration running JuiceFS:
- OS (e.g `cat /etc/os-release`): `mac os`
- Kernel (e.g. `uname -a`):
> Darwin limudeMacBook-Pro.local 23.1.0 Darwin Kernel Version 23.1.0: Mon Oct  9 21:27:27 PDT 2023; root:xnu-10002.41.9~6/RELEASE_X86_64 x86_64
- Object storage (cloud provider and region, or self maintained):
- Metadata engine info (version, cloud provider managed or self maintained):
- Network connectivity (JuiceFS to metadata engine, JuiceFS to object storage):
- Others:

**Comment by hanqingwu** [comment]
`setpriority: permission denied`
try sudo ?

**Comment by zhijian-pro** [comment]
What is the macfuse version?

**Comment by hanqingwu** [comment]
![image](https://github.com/juicedata/juicefs/assets/7521141/fbcd60a7-323a-4854-bd3d-9bee720333c2)
https://www.yii666.com/blog/345471.html

**Comment by lichunqiang** [comment]
![image](https://github.com/juicedata/juicefs/assets/2433916/a1a82cb5-55bb-400e-91a9-67a89423e65d)
