### ISSUE TITLE
add a "nullstorage" storage backend to easy to test the ops benchmark

### ISSUE THREAD

**Issue by hmy1229** [juicedata/juicefs#4417]
**What would you like to be added**:
add a "nullstorage" storage backend which just return true when recieve put/get object request
**Why is this needed**:
when we need to test the ops performance regardless the effect of storage backend，it's convenient

**Comment by davies** [comment]
Right now we can use `mem` or 'file' for tests, are they not enough?

**Comment by hmy1229** [comment]
> Right now we can use `mem` or 'file' for tests, are they not enough?
> ok，mem is enough, and i suggest to add the content of it in the official document.
