### ISSUE TITLE
clearer prompt when config acl

### ISSUE THREAD

**Issue by zhoucheng361** [juicedata/juicefs#4459]
**What would you like to be added**:
root@bench-01:~/juicefs2# ./juicefs config sqlite3://test.db --enable-acl False
2024/03/07 12:02:41.150031 juicefs[3633368] <INFO>: Meta address: sqlite3://test.db [interface.go:533]
Nothing changed.

should give more clearer prompt such as "acl config should not changed after format"

**Why is this needed**:

**Comment by davies** [comment]
`Nothing changed.` means all options, not just ACL.
