### ISSUE TITLE
Make on MacOS fails

### ISSUE THREAD

**Issue by larrypl** [juicedata/juicefs#449]
Error:

```
$ make
go build -ldflags="-s -w -X github.com/juicedata/juicefs/pkg/version.revision=bee415d -X github.com/juicedata/juicefs/pkg/version.revisionDate=2021-05-26 -X github.com/juicedata/juicefs/pkg/version.version=0.13.0-24"  -o juicefs ./cmd
# github.com/shirou/gopsutil/cpu
../../go/pkg/mod/github.com/shirou/gopsutil@v3.20.11+incompatible/cpu/cpu_darwin_cgo.go:13:5: error: 'TARGET_OS_MAC' is not defined, evaluates to 0 [-Werror,-Wundef-prefix=TARGET_OS_]
#if TARGET_OS_MAC
    ^
1 error generated.
make: *** [Makefile:28: juicefs] Error 2
```

**Comment by davies** [comment]
What's the version of macos?

**Comment by larrypl** [comment]
Sorry, that would help - 11.4, Darwin 20.5.0.

**Comment by xiaogaozi** [comment]
What's the version of LLVM? Please run `clang --version` and `which -a clang`. According to https://github.com/shirou/gopsutil/issues/976, it seems like your LLVM isn't Apple's version. For reference, here is my output:

```shell
$ sw_vers
ProductName:	macOS
ProductVersion:	11.4
BuildVersion:	20F71

$ clang --version
Apple clang version 12.0.5 (clang-1205.0.22.9)
Target: x86_64-apple-darwin20.5.0
Thread model: posix
InstalledDir: /Library/Developer/CommandLineTools/usr/bin

$ which -a clang
/usr/bin/clang
```

**Comment by xiaogaozi** [comment]
Or you could try gopsutil v3.21.3 (may [fix](https://github.com/shirou/gopsutil/pull/1042) this issue), run following commands to upgrade gopsutil:

```shell
$ pwd
~/go/src/github.com/juicedata/juicefs
$ go get github.com/shirou/gopsutil@v3.21.3
$ go get github.com/tklauser/go-sysconf
$ make -B
```

Let us know if this method could resolve your problem.

**Comment by xiaogaozi** [comment]
@larrypl We already upgrade gopsutil to v3.21.3 and release JuiceFS v0.13.1, you could use this version to test.

**Comment by larrypl** [comment]
Upgrading gopsutil fixed the problem!

It was likely the version of clang - it was MacPorts clang version 11.1.0.

`make test` has a bunch of failures; not sure that's expected. but that's a different issue. This issue is appropriately closed.

Thanks!

**Comment by gedw99** [comment]
i also just hit this bug on latest main code:

go: downloading github.com/tidwall/pretty v1.2.0
go: downloading github.com/tidwall/match v1.1.1
# github.com/shirou/gopsutil/cpu
/Users/apple/workspace/go/pkg/mod/github.com/shirou/gopsutil@v3.20.11+incompatible/cpu/cpu_darwin_cgo.go:13:5: warning: 'TARGET_OS_MAC' is not defined, evaluates to 0 [-Wundef-prefix=TARGET_OS_]

sw_vers
ProductName:	macOS
ProductVersion:	11.6.7
BuildVersion:	20G630
