### ISSUE TITLE
Windows Server 2019 - Exit 1 without any information

### ISSUE THREAD

**Issue by MircoT** [juicedata/juicefs#4565]
**What happened**:

After formatting a new FS on S3, I cannot mount the volume correctly.

**What you expected to happen**:

JuiceFS should not exit with return status `1`.

**How to reproduce it (as minimally and precisely as possible)**:

I don't know how this is reproducible. I simply follow this guide: [standalone](https://juicefs.com/docs/community/getting-started/standalone)

For the software, I used the pre-compiled executable: [installation](https://juicefs.com/docs/community/getting-started/installation#pre-compiled-windows-client)

**Anything else we need to know?**

Also, using the `--debug` option doesn't provide any further information. There is no explicit error in the output, the executable simply exits with status code 1.

`WinFSP` is installed, and it works. I used it with `rclone` and I have no problem to mount a remote S3 storage.

**Environment**:
- JuiceFS version: `1.1.2+2024-02-04.8dbd89a`
- OS: Windows Server 2019
- Object storage: S3
- Metadata engine info: SQLite

**Comment by SandyXSD** [comment]
<img width="962" alt="Screenshot 2024-03-25 at 13 47 36" src="https://github.com/juicedata/juicefs/assets/13882241/356c6c5f-cda6-40ff-b7a8-671a4142fc1b">
I mounted a test volume successfully on my machine (windows server 2022 though). Could you provide the detailed mount command and error  message in your setup?

**Comment by MircoT** [comment]
Hi @SandyXSD , I just noticed right now the _tip_ on the tutorial that on Windows you have to specify a **drive letter** as `mountpoint` and not a folder... Since I first tried the procedure using WSL, the command's arguments were the same, and that caused the problem.

Thank you for the support!
