### ISSUE TITLE
How to start webdav in k8s

### ISSUE THREAD

**Issue by yangdatianxia** [juicedata/juicefs#4583]
My k8s version is 1.18, and then I use the official juicefs helm chart as juicefs-csi-driver-0.19.8.tgz. During installation, the csi-driver of k8s was enabled, but I want to enable webdav, so how should I do it? Install this webdav and juicefs
, I enabled sc in my chart file and changed the following configuration:

![image](https://github.com/juicedata/juicefs/assets/28724448/a6f2e27b-62b1-45f2-baf8-45371cbad716)

Then execute helm install juicefs-csi-driver juicefs-csi-driver-0.19.8.tgz -n basicsoftware,
After the execution is completed, the containers are running.

![image](https://github.com/juicedata/juicefs/assets/28724448/9b537242-3c4f-4bbb-8bef-ec166baf101f)

But I didn’t see the container for webdav. How do I configure it?

**Comment by timfeirg** [comment]
I've add a bunch of generic k8s juicefs application examples in our docs, they are all based on enterprise edition but I'm sure you can use them as a reference to write your own, juicefs EE and CE are very similar.

https://juicefs.com/docs/zh/csi/guide/generic-applications
