### ISSUE TITLE
Does this mean it's a bug that files that exceed the quota are not automatically deleted?

### ISSUE THREAD

**Issue by chenmiao1991** [juicedata/juicefs#4586]
**What happened**:

when I try [Limit directory capacity](https://juicefs.com/docs/community/guide/quota/#limit-directory-capacity),  the failed files remain in the directory and the size is not correct.

**What you expected to happen**:

First, check the quota in advance for Disk quota exceeded error reporting, and then delete the failed files that were not written successfully.

**How to reproduce it (as minimally and precisely as possible)**:

```
#Set a quota of 1GB
$ juicefs quota set redis://xx --path /test --capacity 1
$ cd test
$ dd if=/dev/zero of=2G bs=1M count=2048
#it report 
dd: error writing '2G': Disk quota exceeded
dd: closing output file '2G': Disk quota exceeded

#But there will be a remaining failed 1GB size file.
$ ls -lh
total 1.0G
-rw-r--r-- 1 chenmiao chenmiao 1.0G Mar 26 18:04 2G
```

**Anything else we need to know?**

**Environment**:
- JuiceFS version (use `juicefs --version`) or Hadoop Java SDK version:
juicefs version 1.1.2+2024-02-04.8dbd89a
- Cloud provider or hardware configuration running JuiceFS:
- OS (e.g `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Object storage (cloud provider and region, or self maintained):
- Metadata engine info (version, cloud provider managed or self maintained):
- Network connectivity (JuiceFS to metadata engine, JuiceFS to object storage):
- Others:

**Comment by h0hmj** [comment]
no
what your `dd` command do is to open(create) a file and write multi 1M blocks. writes before 1GB will success.
you should try to understand the result of `strace dd if=/dev/zero of=2G bs=1M count=2048` .

`automatically deleted` should be done by program, rather than filesystem. programs open and write, occur `Disk quota exceeded` then handle the error, delete the file.

**Comment by chenmiao1991** [comment]
You are right, my mistake.
