### ISSUE TITLE
Question: Redis Sentinal Support

### ISSUE THREAD

**Issue by schmitch** [juicedata/juicefs#46]
Actually the FAQ states that https://github.com/juicedata/juicefs#can-i-use-redis-cluster but is there a way to at least use redis sentinal or is this considered unsafe (and could loose data) aswell?

**Comment by davies** [comment]
Replication and Failover should be safe and even be required to deploy Redis. The Sharding in Redis cluster is not supported, since distributed transaction is not supported in redis cluster.

**Comment by schmitch** [comment]
thanks for the info, I'm closing the issue, feel free to reopen, if you want to add something to the readme.md

**Comment by davies** [comment]
@schmitch Added this into FAQ, thanks!
