### ISSUE TITLE
/tmp/fuse_fd_comm.xxx files never got deleted

### ISSUE THREAD

**Issue by polyrabbit** [juicedata/juicefs#4620]
**What happened**:
After running `juicefs mount` several times, I find `/tmp/fuse_fd_comm.xxx` files are left behind even when main process exits.

**What you expected to happen**:
They should be deleted after process dies.

**How to reproduce it (as minimally and precisely as possible)**:
Run `juicefs mount` and kill the process. You will find the corresponding `/tmp/fuse_fd_comm.xxx` remains.

**Anything else we need to know?**
<img width="345" alt="image" src="https://github.com/juicedata/juicefs/assets/2657334/21d2122d-528d-443c-bcb0-5dabdc52b7a7">

**Environment**:
- JuiceFS version (use `juicefs --version`) or Hadoop Java SDK version:
  - 1.2.0-dev
- Cloud provider or hardware configuration running JuiceFS:
- OS (e.g `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Object storage (cloud provider and region, or self maintained):
- Metadata engine info (version, cloud provider managed or self maintained):
- Network connectivity (JuiceFS to metadata engine, JuiceFS to object storage):
- Others:

**Comment by SandyXSD** [comment]
As discussed offline, these files will be automatically cleared after node reboot. This is not a big issue and we'll leave it as it is.
