### ISSUE TITLE
the RSA key is at risk of storage leakage

### ISSUE THREAD

**Issue by xyb** [juicedata/juicefs#463]
**What would you like to be added**:
The RSA key should be stored in an encrypted form in a Redis or SQL database.

**Why is this needed**:
As described in the title, to avoid the risk of storage leakage.

**Comment by davies** [comment]
@xyb the RSA key should already be protected by a passphase. If we add another layer of encryption, how should we deal with key?

**Comment by xyb** [comment]
I'm not a security expert, but I think this is a big offline attack surface for hackers if Redis or SQL database is exposed, because the security would be completely dependent only on the private key passphrase, which openssl creates at a minimum of 4 characters only. I think we should protect the private key or make the passphrase more difficult to break by brute-force. This could be encrypting the private key in some form, or forcing the user to use a longer passphrase. Maybe we should ask someone on security.stackexchange.com?

**Comment by lipengchengcs** [comment]
If you mount juicefs or use juicefs on a specific machine, then you can use IAM Role to bind this machine to avoid using AKSK

**Comment by davies** [comment]
I think we should protect the AK/SK/RSA key from leaked AOF/RDB, so we can encrypt the `setting` using a predefined secret (or customized from environment variable).

To be backward compatible, we should still read the plain setting, encrypt the setting for new created volume (updating an encrypted setting).

**Comment by SandyXSD** [comment]
fixed by #1562
