### ISSUE TITLE
cmd: support using 'd' as the days unit  attr-cache entry-cache dir-entry-cache get-timeout 

### ISSUE THREAD

**Issue by YunhuiChen** [juicedata/juicefs#4637]
**What happened**:
2024/04/03 11:50:58.289859 juicefs[1166211] <FATAL>: invalid value "1d" for flag -attr-cache: parse error [main.go:31].
**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**

**Environment**:
- JuiceFS version (use `juicefs --version`) or Hadoop Java SDK version:
- Cloud provider or hardware configuration running JuiceFS:
- OS (e.g `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Object storage (cloud provider and region, or self maintained):
- Metadata engine info (version, cloud provider managed or self maintained):
- Network connectivity (JuiceFS to metadata engine, JuiceFS to object storage):
- Others:

**Comment by SandyXSD** [comment]
Fixed by #4641
