### ISSUE TITLE
write small files into metadata storage

### ISSUE THREAD

**Issue by aigc-anime** [juicedata/juicefs#4657]
What would you like to be added:
Can files smaller than 4KB be written to metadata storage (tikv) instead of s3?

Why is this needed:
This may improve IOPS for small files.

**Comment by SandyXSD** [comment]
This could potentially lead to exponential growth in the capacity demands of the metadata engine, which in many cases might prove to be counterproductive. We believe that it introduces additional complexity without delivering sufficient returns in most cases. Thus, for now we won't put it into our development roadmap.

Also we find that a similar feature in CephFS has been [declared deprecated](https://docs.ceph.com/en/reef/cephfs/experimental-features/#inline-data).
