### ISSUE TITLE
nfs:juicefs sync Failed to upload data to the nfs

### ISSUE THREAD

**Issue by YunhuiChen** [juicedata/juicefs#4661]
**What happened**:
./juicefs sync ./mc nfs://root@172.28.39.187:/minio2/share/mc
2024/04/08 13:49:03.454960 juicefs[2158329] <FATAL>: create nfs 172.28.39.187:/minio2/share/mc: unable to mount 172.28.39.187:/minio2/share/mc: MNT3ERR_NOENT [main.go:31]

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**

**Environment**:
- JuiceFS version (use `juicefs --version`) or Hadoop Java SDK version:
- Cloud provider or hardware configuration running JuiceFS:
- OS (e.g `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Object storage (cloud provider and region, or self maintained):
- Metadata engine info (version, cloud provider managed or self maintained):
- Network connectivity (JuiceFS to metadata engine, JuiceFS to object storage):
- Others:

**Comment by SandyXSD** [comment]
For now the NFS bucket (`172.28.39.187:/minio2/share/mc` in this case) must be exported.

**Comment by davies** [comment]
@SandyXSD We can try to mount with the parent dir, and use lower part as prefix
