### ISSUE TITLE
bucket can not have db port

### ISSUE THREAD

**Issue by wenerme** [juicedata/juicefs#4725]
**What happened**:

doc example

```bash
juicefs format \
    --storage postgres \
    --bucket "<host>:<port>/<db>[?parameters]"
```

but 

```
2024/04/18 00:48:49.504353 juicefs[3217] <FATAL>: object storage: parse url HOSR:PORT/DB?search_path=jfs failed: parse "HOSR:PORT/DB?search_path=jfs": first path segment in URL cannot contain colon [format.go:469]
```

**What you expected to happen**:

works as expected

**How to reproduce it (as minimally and precisely as possible)**:

format with port in bucket

**Anything else we need to know?**

**Environment**:
- JuiceFS version (use `juicefs --version`) or Hadoop Java SDK version: 1.1.2
- Cloud provider or hardware configuration running JuiceFS:
- OS (e.g `cat /etc/os-release`): any
- Kernel (e.g. `uname -a`): any
- Object storage (cloud provider and region, or self maintained):
- Metadata engine info (version, cloud provider managed or self maintained):
- Network connectivity (JuiceFS to metadata engine, JuiceFS to object storage):
- Others:

**Comment by zhijian-pro** [comment]
@wenerme  Please give the desensitized command line parameters for the actual run

**Comment by wenerme** [comment]
@zhijian-pro

```bash
juicefs format \
  --storage postgres --bucket "postgres://1.1.1.1:1234/dev?search_path=jfs" \
  "postgres://dev@1.1.1.1:1234/dev?search_path=jfs" \
  dev
```

**Comment by zhijian-pro** [comment]
Thanks for the feedback, this is a bug.

**Comment by wenerme** [comment]
@zhijian-pro Could you provide an estimated timeline for the next release? Thank you!

**Comment by zhijian-pro** [comment]
@wenerme Have been released

**Comment by wenerme** [comment]
> @wenerme Have been released

Not test yet, switch to using rclone for simple remote fs access
