### ISSUE TITLE
Smooth upgrade may cause EIO and file system corruption

### ISSUE THREAD

**Issue by YunhuiChen** [juicedata/juicefs#4739]
**What happened**:
A smooth upgrade may cause EIO and file system corruption

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

/juicefs format --storage minio --bucket  http://localhost:19000/gateway3 --access-key minioadmin --secret-key minioadmin redis://127.0.0.1:6379/1 test3 --trash-days 0

./juicefs mount redis://127.0.0.1:6379/1 /juicefs3 --cache-dir /data/cache3 --writeback=true --log-id 111 -d

fio --name=big-file-multi --directory=/juicefs3/ --rw=readwrite --refill_buffers --bs=1M --size=1G --numjobs=16

./juicefs mount redis://127.0.0.1:6379/1 /juicefs3/ --cache-dir /data/cache3 --writeback=true --log-id 111 -d

Log information:
[111] 2024/04/18 10:10:20.503002 juicefs[1948221] <ERROR>: read file 112647: input/output error [reader.go:123]

**Anything else we need to know?**

**Environment**:
- JuiceFS version (use `juicefs --version`) or Hadoop Java SDK version:
- Cloud provider or hardware configuration running JuiceFS:
- OS (e.g `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Object storage (cloud provider and region, or self maintained):
- Metadata engine info (version, cloud provider managed or self maintained):
- Network connectivity (JuiceFS to metadata engine, JuiceFS to object storage):
- Others:

**Comment by zhoucheng361** [comment]
will cause "Interrupted system call" when upgrade with list big_dir.
root@bench-01:~# ls /jfs/big_dir
ls: reading directory '/jfs/big_dir': Interrupted system call

**Comment by davies** [comment]
Fixed by #4773
