### ISSUE TITLE
Deleted tag cause misbehaviour of `go get`

### ISSUE THREAD

**Issue by colin-sitehost** [juicedata/juicefs#477]
**What happened**:
```
go get: added github.com/juicedata/juicefs v0.14.0
```
**What you expected to happen**:
```
go get: added github.com/juicedata/juicefs v0.13.1
```

**How to reproduce it (as minimally and precisely as possible)**:
```sh
go get github.com/juicedata/juicefs
```
**Anything else we need to know?**
it looks like you probably deleted that tag, which is not supported by `proxy.golang.org` (see the [FAQ](https://proxy.golang.org))

also, the current latest tag, `v0.14-dev` is not valid semver, thus is being ignored and mangled by the toolchain: (try `v0.14.0-alpha`)
```sh
[user@localhost ~]$ go get github.com/juicedata/juicefs@v0.14-dev
go: downloading github.com/juicedata/juicefs v0.13.2-0.20210527090717-42ac85ce406c
go get: downgraded github.com/juicedata/juicefs v0.14.0 => v0.13.2-0.20210527090717-42ac85ce406c
```

**Comment by xiaogaozi** [comment]
Sorry to the bother, like you said `proxy.golang.org` doesn't delete cache, so you must specify tag explicitly now. I think this issue will be fixed until we released v0.14.1.

**Comment by colin-sitehost** [comment]
let me be explicit, you should never delete tags, only add new ones. as confirmed by both the [faq](https://proxy.golang.org/) and semver [spec](https://semver.org/#what-do-i-do-if-i-accidentally-release-a-backwards-incompatible-change-as-a-minor-version), the correct resolution is to push a new tag that is greater than the broken/invalid/breaking one, `v0.14.1` that points at the last good tag, `v0.13.1`.

as such, I request that you push `v0.14.1`, pointed at 1737d4ed9d71715fe49bf60f2dc76d7f11927941 immediately. I am happy to assist with anything if you need it.

if you still have the tags locally, I strongly urge you to push them back up. I have the `v0.14-dev` tag if you would like it; however, they will forever exist on `proxy.golang.org` and it will be confusing for customers if they cannot find the tag in github.

**Comment by colin-sitehost** [comment]
I can understand your concerns for people not understanding what is going on, but I think that making the toolchain work should be the first goal. you can explain such things in an annotated commit or the release notes, feel free to use the linked articles as an explanation.

alternatively, you can push a new commit that invalidates both `v0.14.0` and itself, as [described here](https://blog.golang.org/go116-module-changes); this is a new feature to go1.16.

**Comment by colin-sitehost** [comment]
yes, to remove the `v0.14.0` release, you will need to cut a new release. you can see what the kubernetes team did for client-go repo in the [`v1.5.2` release](https://github.com/kubernetes/client-go/blob/v1.5.2/go.mod#L39). your `go.mod` would look like so:
```
module github.com/juicedata/juicefs

go 1.14

retract(
      v0.14.0 // invalid release
      v0.14.1 // retraction
)

require (
// ...
```

I would still push the `v0.14.0` tag back up to this repo, for consistency.

also, many people in this situation tend to skip the whole minor (or for a public release, major) and just move on to `v0.15.0`, as it leads to fewer questions.

**Comment by xiaogaozi** [comment]
Thanks for your suggestion, we'll consider it.

**Comment by davies** [comment]
@colin-sitehost We have released v0.14.2 to fix this mess, can you confirm that `go get` is working as expected now?

**Comment by colin-sitehost** [comment]
yes, everything is working as expected.

though I will note that you did not need to retract `v0.14.1`, since this (`v0.14.2`) was a real release, you could have just retracted the broken `v0.14.0`. the "only contains retractions" release is only useful for reverting to an old release, not skipping a broken one.

**Comment by colin-sitehost** [comment]
upon reviewing proxy.golang.org, it does look like there were at one time `v0.14.0` and `v0.14.1` tags on this repo, so I would still suggest pushing those for consistency, but go-get works.
