### ISSUE TITLE
Many disks are shutdown due to heavy workload

### ISSUE THREAD

**Issue by polyrabbit** [juicedata/juicefs#4779]
**What happened**:
During a heavy IO workload, we observed more than 280 pending write requests to the cache store, which overwhelmed the disk and caused slow IO. The bad disk dictator thus shuts it down forever even it recovers shortly. But worse, we lost the read cache forever.

![img_v3_02a9_4b8c5d10-9c4f-4503-bde9-561a7095c62g](https://github.com/juicedata/juicefs/assets/2657334/8ca8263b-733d-4187-9220-a516bd0c119b)

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**

**Environment**:
- JuiceFS version (use `juicefs --version`) or Hadoop Java SDK version:
1.2-beta1

**Comment by polyrabbit** [comment]
Thanks, but we already included this commit in our build:
<img width="786" alt="image" src="https://github.com/juicedata/juicefs/assets/2657334/9d7d76ab-90e1-43db-a295-1f9abded383c">

**Comment by polyrabbit** [comment]
When one disk cache store is shutdown. Will we lose staged files in that store?

**Comment by jiefenghuang** [comment]
files still exist.

**Comment by jiefenghuang** [comment]
Conclusion: There are two scenarios to consider. One is long-term high-load writing, for which writing directly to object storage is recommended (resource issue: disk-cache or object storage bandwidth). The other is short-term high-load writing, for which the concurrency limit can be lifted to redirect and distribute writes to the object storage. This issue will be temporarily closed for now.

**Comment by davies** [comment]
We should enable max-stage-write for this issue, maybe 10 as the default value.
