### ISSUE TITLE
Compile v1.1.2 failed on Linux

### ISSUE THREAD

**Issue by yuhr123** [juicedata/juicefs#4833]
**What happened**:

I am experiencing compilation issues with juicefs v1.1.2 on Arch Linux and Ubuntu Server 22.04, and I receive the following error message:

```output
...
go: downloading github.com/tidwall/match v1.1.1
# github.com/pyroscope-io/godeltaprof/internal/pprof
../go/pkg/mod/github.com/pyroscope-io/godeltaprof@v0.1.2/internal/pprof/delta_mutex.go:25:20: undefined: runtime_cyclesPerSecond
../go/pkg/mod/github.com/pyroscope-io/godeltaprof@v0.1.2/internal/pprof/proto.go:400:8: undefined: runtime_expandFinalInlineFrame
make: *** [Makefile:24: juicefs] Error 1
```

**How to reproduce it (as minimally and precisely as possible)**:

For Arch Linux: `yay -S juicefs`
For Ubuntu, pull the source code, switch to tag v1.1.2, and perform a manual compile.

**Environment**:
- go version go1.22.3 linux/amd64

**Comment by solracsf** [comment]
1.1.2 does not support Go 1.22, master does by https://github.com/juicedata/juicefs/pull/4340

**Comment by yuhr123** [comment]
> 1.1.2 does not support Go 1.22, master does by #4340

Thank you, I was able to successfully compile the client with Go 1.21.10.
