### ISSUE TITLE
inode used is incorrect with mysql meta engine.

### ISSUE THREAD

**Issue by zhoucheng361** [juicedata/juicefs#4862]
**What happened**:
```
root@bench-03:~/juicefs# ./juicefs format mysql://juicedata:juicedata@(127.0.0.1)/test mysql --enable-acl --trash-days 0
root@bench-03:~/juicefs# ./juicefs mount mysql://juicedata:juicedata@(127.0.0.1)/test /tmp/jfs2 -d
root@bench-03:~/juicefs# df -i
Filesystem              Inodes    IUsed       IFree IUse% Mounted on
/dev/vda1             19660800   747977    18912823    4% /
JuiceFS:mysql               81        0          81    0% /tmp/jfs2
root@bench-03:~/juicefs# ls -l /tmp/jfs2
total 4
-rw-r--r-- 1 root root    0 May 16 20:48 abc
-rw-r--r-- 1 root root    0 May 16 20:48 def
drwxr-xr-x 2 root root 4096 May 16 20:54 fsrand
```

**What you expected to happen**:
iUsed should be 3.

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**

**Environment**:
- JuiceFS version (use `juicefs --version`) or Hadoop Java SDK version:
- Cloud provider or hardware configuration running JuiceFS:
- OS (e.g `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Object storage (cloud provider and region, or self maintained):
- Metadata engine info (version, cloud provider managed or self maintained):
- Network connectivity (JuiceFS to metadata engine, JuiceFS to object storage):
- Others:

**Comment by davies** [comment]
the usage is updated in background, not accurate by design. So we have to leave it as it is.
