### ISSUE TITLE
If the mount point is abnormal, the debug command cannot obtain the config file

### ISSUE THREAD

**Issue by YunhuiChen** [juicedata/juicefs#4864]
**What happened**:
1、kill redis
2、2024/05/17 10:46:40.879406 juicefs[2490094] <WARNING>: failed to read config file: open /juicefs1/.jfs.config: input/output error [debug.go:134]
2024/05/17 10:46:40.879496 juicefs[2490094] <WARNING>: failed to unmarshal config file: unexpected end of JSON input [debug.go:138]
2024/05/17 10:47:02.867643 juicefs[2490094] <ERROR>: Failed to collect special file: failed to get volume config .jfs.config: signal: killed [debug.go:602]

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**

**Environment**:
- JuiceFS version (use `juicefs --version`) or Hadoop Java SDK version:
- Cloud provider or hardware configuration running JuiceFS:
- OS (e.g `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Object storage (cloud provider and region, or self maintained):
- Metadata engine info (version, cloud provider managed or self maintained):
- Network connectivity (JuiceFS to metadata engine, JuiceFS to object storage):
- Others:

**Comment by YunhuiChen** [comment]
Same situation at.stats

**Comment by zhijian-pro** [comment]
ref #5050

**Comment by zhijian-pro** [comment]
The mount point hang case is now handled correctly
