### ISSUE TITLE
S3 Gateway Cannot Be Started by Non-root Users

### ISSUE THREAD

**Issue by yuhr123** [juicedata/juicefs#4880]
**What happened**:

I am using JuiceFS v1.2.0-beta1, and when I start the S3 gateway as a regular user, an error occurs indicating that there is no write permission to the directory "/.sys/.minio.sys/tmp/xxx".

![image](https://github.com/juicedata/juicefs/assets/3388604/7ed41cf3-a6a6-4869-a6ff-0a200b3e54c1)

**How to reproduce it (as minimally and precisely as possible)**:

```sh
# Using a non-root user
export MINIO_ROOT_USER=admin
export MINIO_ROOT_PASSWORD=xxxx
juicefs gateway redis://xxx.com/1 0.0.0.0:9898
```

**Environment**:
- JuiceFS version (use `juicefs --version`) or Hadoop Java SDK version: juicefs version 1.2.0-beta1+2024-04-18.041e931
- Cloud provider or hardware configuration running JuiceFS:
- OS (e.g `cat /etc/os-release`): Ubuntu 22.04.4 LTS
- Kernel (e.g. `uname -a`): Linux ubuntu 5.15.0-106-generic
- Object storage (cloud provider and region, or self maintained):
- Metadata engine info (version, cloud provider managed or self maintained):
- Network connectivity (JuiceFS to metadata engine, JuiceFS to object storage):
- Others:

**Comment by zhijian-pro** [comment]
fix by https://github.com/juicedata/juicefs/pull/4891
