### ISSUE TITLE
Make hardcoded fetch 100 each worker user configurable

### ISSUE THREAD

**Issue by lxj616** [juicedata/juicefs#4881]
**What would you like to be added**:

https://github.com/juicedata/juicefs/blob/main/pkg/sync/cluster.go#L137-L166

Make 
```
				objs = append(objs, obj)
				if len(objs) > 100 {
					break LOOP
				}
```
User configurable

**Why is this needed**:

We are using `juicefs sync --workers` to get 16 very large files from tencent COS to KS3 local jfs

And as we have 8 workers, however 16 is lesser than 100, so all 16 files are using one worker instead of all

Currently our temporary solution is to ___PAD___ each big file with 99 empty files, which is, well, working at least

However it would be nicer if I can use `juicefs sync --workers` on 16 files directly, so

**Comment by davies** [comment]
We should have a limit on the total size of fetched keys.
