### ISSUE TITLE
[BUG] `juicefs sync` cmd running in k8s pod doesn't output fetch status in stdout/stderr

### ISSUE THREAD

**Issue by kidlj** [juicedata/juicefs#4907]
**What happened**:

When `juicefs sync` cmd runs in k8s pod, `kubectl logs <pod_name> -f` doesn't output fetch status, like manually running this cmd in terminal does. See the screenshot.

I used the `juicedata/mount:ce-v1.1.2` image for the test.

<img width="1428" alt="截屏2024-05-29 17 28 35" src="https://github.com/juicedata/juicefs-csi-driver/assets/300616/66e94d04-5111-4c8e-9b4d-0b92bd7f4903">

**What you expected to happen**:

`kubectl logs <juicefs_sync_pod> -f` shows the fetch status, like pending objects, fetch speed etc.

**How to reproduce it (as minimally and precisely as possible)**:

Running a pod using `juicedata/mount:ce-v1.1.2` image, and sync some files from ks3/oss/s3 to a container mount point.

**Anything else we need to know?**

**Environment**:
- JuiceFS CSI Driver version (which image tag did your CSI Driver use):
- Kubernetes version (e.g. `kubectl version`):
- Object storage (cloud provider and region):
- Metadata engine info (version, cloud provider managed or self maintained):
- Network connectivity (JuiceFS to metadata engine, JuiceFS to object storage):
- Others:

**Comment by davies** [comment]
This progress bar can only work with tty, so it's disabled when the stdout is not a tty.
