### ISSUE TITLE
Out of Memory 0.13.1

### ISSUE THREAD

**Issue by gallexme** [juicedata/juicefs#496]
**What happened**:  juicefs eating every last bit of memory + swap then gets killed by oomkiller

**What you expected to happen**: shouldnt it use less memory?

**How to reproduce it (as minimally and precisely as possible)**: store 8x104gb size files in juicefs, do rand reads on it, watch how memory consistently climbs until exhaustion

**Anything else we need to know?**
![image](https://user-images.githubusercontent.com/1122989/120688028-eb846300-c4a2-11eb-80ed-7637c63fc77e.png)

**Environment**:
- JuiceFS version (use `./juicefs --version`) or Hadoop Java SDK version: juicefs version 0.13.1 (2021-05-27T08:14:30Z 1737d4e)
- Cloud provider or hardware configuration running JuiceFS: 4 core, 16gb ram, backblaze b2
- OS (e.g: `cat /etc/os-release`): ubuntu 20.04.2 LTS (Focal Fossa)
- Kernel (e.g. `uname -a`):  5.4.0-73-generic #82-Ubuntu SMP Wed Apr 14 17:39:42 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
- Object storage (cloud provider and region): Backblaze B2 Europe
- Redis info (version, cloud provider managed or self maintained): self maintained latset, from docker
- Network connectivity (JuiceFS to Redis, JuiceFS to object storage): juicefs and redis are locally, 5gbit to backblaze b2
- Others:

**Comment by gallexme** [comment]
same issue with the s3 gateway 
![image](https://user-images.githubusercontent.com/1122989/120699153-52f4df80-c4b0-11eb-81db-e8c90e23aa20.png)

**Comment by davies** [comment]
How is the volume formatted and mounted?

There is a Go profile agent enabled, which listen on localhost:6060 by default, you can download the heap profile and analyze it:

```
$ wget localhost:6060/debug/pprof/heap
$ go tool pprof -lines -web heap
```

Can you post the screenshot here?

**Comment by gallexme** [comment]
doesnt seem to be the heap 
![profile001](https://user-images.githubusercontent.com/1122989/120768600-9edd6e00-c51c-11eb-95e9-8a60d6a14e43.png)


its happens mounted like that 
sudo juicefs mount -d redis://127.0.0.1:6379/1 /mnt/jfs

or as gateway 


its been formatted like
juicefs format --storage b2 --bucket http://juicefs-test --access-key XXXXXXXXX--secret-key XXXXXXXXXX redis://127.0.0.1:6379/1 juicefs-test

**Comment by davies** [comment]
How can we reproduce this behavior (how to generate the file and how to run random read workload)?

**Comment by gallexme** [comment]
> How can we reproduce this behavior (how to generate the file and how to run random read workload)?

I could give u access to the system, or provide downloads for the files, but maybe explaining how to do the random reads may be a bit more involved

**Comment by gallexme** [comment]
Does the kind of file really matter a lot?
I would assume any file of 100+gb would cause similar issues, maybe you could try to mount a  virtual disk image from juicefs  n try to read files from it?

It never drops the memory, not even when no process has any handles open on it

**Comment by davies** [comment]
It seems like a memory leak some where, we will try to reproduce it, thanks!

**Comment by gallexme** [comment]
also quick side question, how long does usually a garbage collection pass take?
(it doesnt seem to change in speed if i choose 10, 100, or 4 threads either)

its probably been garbage colleting for 24h nows, and still isnt done, with like a few leaked chunks found every few minutes
it uses only about 752MB of ram and 4% of cpu
![image](https://user-images.githubusercontent.com/1122989/120836064-7168e280-c565-11eb-839f-36800688f02e.png)

thats the current size of the bucket btw, it contains 1.4tb of files(14)
![image](https://user-images.githubusercontent.com/1122989/120836238-9fe6bd80-c565-11eb-820e-93f4f52d48db.png)

dunno if that could help for reproducing

**Comment by davies** [comment]
`juicefs gc` is scanning all keys in Redis to find out any leak. It's slow than expected, how many keys in the Redis?

**Comment by davies** [comment]
I have used the following random-read workload on 4 100G files, the used memory never go above 1.5GB.

```
fio --name=big-file-rand-read --directory=/jfs-ce/ --rw=randread --size=100G --filename=randread.bin --bs=64k --numjobs=4
```

So there are something related to your enviroment or B2.

**Comment by davies** [comment]
@gallexme After looking into the library talking to B2, realized that it's too heavy for JuiceFS (maybe memory leak), can you switch to use S3 API [1] to your B2 bucket?

Here is the steps:

1. umount JuiceFS
2. format the volume again as S3 (only change the storage type, bucket, access key and secret key):

```
./juicefs format REDIS-URL NAME --storage s3 --bucket ENDPOINT-of-B2 --access-key NEW-APP-ID-FOR-S3 --secret-key APP-KEY
```
3. mount it again

```
./juicefs mount NAME /jfs
```

Then run the workload again to see what happened.


[1] https://help.backblaze.com/hc/en-us/articles/360047425453

**Comment by gallexme** [comment]
Hmm we avoided the s3 interface on purpose, since the b2 was quite a a bit faster and lower latency In our testing(using s3 proxy to convert b2 to S3, then mounting it with goofys, which we used bevor juicefs)


Will try though. aybe juicefs approach makes it faster since it doesn't have to seek huge files on s3

**Comment by gallexme** [comment]
> `juicefs gc` is scanning all keys in Redis to find out any leak. It's slow than expected, how many keys in the Redis?

jfi 
![image](https://user-images.githubusercontent.com/1122989/120886511-acfbbf00-c5ee-11eb-9809-232d6db5bcaa.png) after few more hours
and soon after
![image](https://user-images.githubusercontent.com/1122989/120886524-b7b65400-c5ee-11eb-88ba-27a2862e02e9.png)

**Comment by davies** [comment]
@gallexme Can you check whether #500 fix the memory issue? I can't run the test long enough before reaching bandwidth cap from B2.

**Comment by gallexme** [comment]
> @gallexme Can you check whether #500 fix the memory issue? I can't run the test long enough before reaching bandwidth cap from B2.

#500 fixed it!
