### ISSUE TITLE
Is it possible to use  NBD as a backend storage?

### ISSUE THREAD

**Issue by wen-bing** [juicedata/juicefs#4997]
NBD:
https://github.com/NetworkBlockDevice/nbd

Since PolarDBFS can use NBD as a storage backend, Is it possible to use NBD as data storage for JuiceFS?

**Comment by jiefenghuang** [comment]
Yes. After configuring the ndb, you can treat it as a local device, and then specify the JuiceFS object storage to the local disk.

**Comment by davies** [comment]
NBD does not provide a object interface to work with, so we can't use that directly.
