### ISSUE TITLE
Backup tool for meta

### ISSUE THREAD

**Issue by davies** [juicedata/juicefs#50]
**What would you like to be added**:

Provide a tool to dump metadata as JSON format, then we can have other tool to assemble them and get data back.

**Why is this needed**:

In worsest case, if we lose Redis, we'd like to have a tool to get most of data back from S3.

**Comment by steven-varga** [comment]
Did you try [redis rdb tool](https://github.com/sripathikrishnan/redis-rdb-tools) reading back a redis dump? From the documentation: `rdb -c json /var/redis/6379/dump.rdb` 
it worked for me with a recent `redis v6.0.10`
