### ISSUE TITLE
using --writeback reading and writing speeds are slower

### ISSUE THREAD

**Issue by Tsan1024** [juicedata/juicefs#5005]
## using --writeback reading and writing speeds are slower instead of faster writing speed:

./juicefs mount sqlite3://myjfs.db ./test1 -d --writeback
![image](https://github.com/user-attachments/assets/d8ab5d51-03e2-4261-b172-0b43a2f2e531)

./juicefs mount sqlite3://myjfs.db ./test1
![image](https://github.com/user-attachments/assets/1b395b8f-24b8-423c-a921-6d3e083b1faa)

Environment:
- JuiceFS master branch:
- minio as base cloud:
- OS (e.g `VERSION="18.04.6 LTS (Bionic Beaver)"`):
- Kernel (e.g. `Linux DESKTOP-DCI4BQR 5.15.153.1-microsoft-standard-WSL2 #1 SMP Fri Mar 29 23:14:13 UTC 2024 x86_64 x86_64 x86_64 GNU/Linux`):
- Object storage (minio):
- Metadata engine info (version, cloud provider managed or self maintained):
- Network connectivity (JuiceFS to metadata engine, JuiceFS to object storage):
- Others:

**Comment by jiefenghuang** [comment]
Writeback will writing data to the disk and then uploading it to object storage in the background. 
Is your disk a cloud disk? The bandwidth should not be limited to just tens of MiB. Perhaps you can check the disk performance and the performance of the object storage. If the write bandwidth of the object storage is larger than that of the cloud disk, you may consider turning off writeback, depending on your scenario.
