### ISSUE TITLE
cant open s3 gateway webui,Bucket Name minio is invalid

### ISSUE THREAD

**Issue by Mangoyap** [juicedata/juicefs#5039]
**What happened**:
when i open s3 gateway, here is the error:
Bucket Name minio is invalid. Lowercase letters, period, hyphen, numerals are the only allowed characters and should be minimum 3 characters in length.
**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**
format a minio cluster ,with a name "minio",here is the format:
juicefs format \
--storage minio \
--shards 8 \
--bucket "http://minio.xxxxcom:80/jfs-%d" \
--access-key xxx \
--secret-key xxx \
--trash-days 0 \
redis://:xxx@localhost:6379/1 \
minio
**Environment**:
- JuiceFS version (use `juicefs --version`) or Hadoop Java SDK version:
- 1.1.3+2024-06-20.5c442dd
- Cloud provider or hardware configuration running JuiceFS:
- OS (e.g `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Object storage (cloud provider and region, or self maintained):
- minio cluster
- Metadata engine info (version, cloud provider managed or self maintained):
- redis
- Network connectivity (JuiceFS to metadata engine, JuiceFS to object storage):
- Others:
its ok to mount and the juicefs-gateway service is good.

**Comment by zhijian-pro** [comment]
'minio' is the bucket name reserved by s3gateway, you can enable multi-bucket mode or format a new volume with a different volume name
