### ISSUE TITLE
Failed when using Flink FileSink with JuiceFS Hadoop Java SDK

### ISSUE THREAD

**Issue by yelijing18** [juicedata/juicefs#5065]
**What happened**:
When I attempt to write to JuiceFS using Flink's FileSink, the write operation fails with the following error:
```
Exception in thread "main" java.lang.UnsupportedOperationException: Recoverable writers on Hadoop are only supported for HDFS
	at org.apache.flink.runtime.fs.hdfs.HadoopRecoverableWriter.checkSupportedFSSchemes(HadoopRecoverableWriter.java:64)
	at org.apache.flink.runtime.fs.hdfs.HadoopRecoverableWriter.<init>(HadoopRecoverableWriter.java:57)
	at org.apache.flink.runtime.fs.hdfs.HadoopFileSystem.createRecoverableWriter(HadoopFileSystem.java:215)
	at org.apache.flink.connector.file.sink.FileSink$RowFormatBuilder.createBucketWriter(FileSink.java:480)
	at org.apache.flink.connector.file.sink.FileSink$RowFormatBuilder.getCommittableSerializer(FileSink.java:471)
	at org.apache.flink.connector.file.sink.FileSink.getCommittableSerializer(FileSink.java:177)
...
```

**What you expected to happen**:

Successfully written to JuiceFS.

I'm not very familiar with how to submit a Pull Request for JuiceFS, so I've raised an Issue, hoping that you can fix it.

**How to reproduce it (as minimally and precisely as possible)**:

Simply use Flink's FileSink with JuiceFS:

``` java
var sinkPath = "jfs://defjfs/foo-bar";
    FileSink<String> fileSink =
        FileSink.forRowFormat(
                new Path(sinkPath), new SimpleStringEncoder<String>("UTF-8"))
            .withRollingPolicy(OnCheckpointRollingPolicy.build())
            .build();
```

**Anything else we need to know?**
JuiceFS uses PatchUtil to instrument and modify the constructor method of HadoopRecoverableWriter in Flink at runtime. Here is the code：https://github.com/juicedata/juicefs/blob/389b9b117c19e9baf39baa57222bc3e545f7678d/sdk/java/src/main/java/io/juicefs/JuiceFileSystem.java#L112

However, starting from Flink version 1.17, this logic has been abstracted into additional functions within Flink, which renders the JuiceFS modification ineffective, leading to the aforementioned issue. Please refer to the relevant code and commit in Flink:
- The relevant commit: https://github.com/apache/flink/commit/c8ecfadfb968ed805c033911c8a68d30f35f9eee#diff-a0c20a7aece5186bdc3ede7b90846998cd88ac5db4b55547de41bd5d6bc15958
- Flink before 1.16(no problem with juicefs): https://github.com/apache/flink/blob/664bd6760f256c4f252e3acb710c0de854568207/flink-filesystems/flink-hadoop-fs/src/main/java/org/apache/flink/runtime/fs/hdfs/HadoopRecoverableWriter.java#L58
- Flink  since 1.17(with this bug): https://github.com/apache/flink/blob/12b2c02bac99023acafc9fa159bfb5479c6d38a5/flink-filesystems/flink-hadoop-fs/src/main/java/org/apache/flink/runtime/fs/hdfs/HadoopRecoverableWriter.java#L57

**Environment**:
- JuiceFS version (use `juicefs --version`) or Hadoop Java SDK version: 1.1.2

**Comment by tangyoupeng** [comment]
fixed by https://github.com/juicedata/juicefs/pull/5147/files
