### ISSUE TITLE
Performance of master branch dropped by 20%?

### ISSUE THREAD

**Issue by polyrabbit** [juicedata/juicefs#5102]
Just benchmarked the master branch and found that the read performance is 20% slower than the 1.2 release branch. After reviewing recent changes, it seems this [PR](https://github.com/juicedata/juicefs/pull/5076) brings the regression - it increases IO size to 1MiB:

<img width="639" alt="image" src="https://github.com/user-attachments/assets/454b6323-bc49-4411-881e-a0f64457f479">

I don't understand why increasing IO size gets a lower read performance. The only related metric is goroutine count - less goroutines means less concurrency? but those two IO sizes are far less than BlockSize, I suppose it has nothing to do with readahead?

<img width="645" alt="image" src="https://github.com/user-attachments/assets/c02e4df9-b218-4564-a0dc-23b8bfe03653">

**Comment by solracsf** [comment]
_NB: Maybe also introduce a CI test that evaluates and detects performance regression too on each commit?_

**Comment by zhijian-pro** [comment]
fixed https://github.com/juicedata/juicefs/pull/5087

**Comment by polyrabbit** [comment]
I suppose it's not a *fix* but a *workaround*. We still don't know why the regression happens, but just leave the burden to users with another magic flag.

**Comment by davies** [comment]
The main branch changed the default behavior which cause the performance degradation, we have revert the change and introduce a flag for new behavior.
