### ISSUE TITLE
Add vultr object storage support

### ISSUE THREAD

**Issue by heartshare** [juicedata/juicefs#511]
**What would you like to be added**:  https://www.vultr.com/products/object-storage/

**Why is this needed**:  Fast & low latency for Hong Kong location if use Singapore region , time=**40.7** ms, Digital Ocean is  **70ms**. Thanks

**Comment by heartshare** [comment]
Even faster than GCP ? Measure your latency to GCP regions
play_arrow
REGION	MEDIAN LATENCY
Taiwan
asia-east1
44 ms
Seoul
asia-northeast3
48 ms
**Hong Kong
asia-east2
51 ms**
**Singapore
asia-southeast1
73 ms**

**Comment by davies** [comment]
Are your machine hosted in Vultr also? 

If your machines are hosted in Singapore, the Singapore region of from some vendors (AWS and others) should be way faster than others.

**Comment by heartshare** [comment]
Are your machine hosted in Vultr also?
No, VM host in Hong Kong local data center

**Comment by davies** [comment]
It's easy to support Vultr, but it's weird to see the GCP Hong Kong has longer latency than Vultr Singapore region.

**Comment by davies** [comment]
Since Vultr is S3 compatible, I think you can use it as S3: `--storage s3 --bucket https://BUCKET.REGION.vultrobjects.com`

**Comment by heartshare** [comment]
Great, Thanks

**Comment by heartshare** [comment]
I tested again at home 
HKBN HOME : 
Hong Kong
asia-east2
15 ms

Download speed from vultr
5.8 MB/秒 - 52.0 MB，總共 100 MB，還剩 8 秒
