### ISSUE TITLE
MinIO `external-identity-management-plugin` and `identity-access-management` is not working

### ISSUE THREAD

**Issue by shubham-kaushal** [juicedata/juicefs#5120]
**What happened**:

MinIO `external-identity-management-plugin` and `identity-access-management` is not working

MinIO Doc Link
https://min.io/docs/minio/linux/administration/identity-access-management/pluggable-authentication.html#minio-external-identity-management-plugin
and
https://min.io/docs/minio/linux/administration/identity-access-management/pluggable-authorization.html#

**What you expected to happen**:
Support `external-identity-management-plugin` https://min.io/docs/minio/linux/administration/identity-access-management/pluggable-authentication.html#minio-external-identity-management-plugin and https://min.io/docs/minio/linux/administration/identity-access-management/pluggable-authorization.html#

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**

**Environment**:
- JuiceFS version (use `juicefs --version`) or Hadoop Java SDK version:
- Cloud provider or hardware configuration running JuiceFS:
- OS (e.g `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Object storage (cloud provider and region, or self maintained):
- Metadata engine info (version, cloud provider managed or self maintained):
- Network connectivity (JuiceFS to metadata engine, JuiceFS to object storage):
- Others:

**Comment by zhijian-pro** [comment]
We currently do not support this feature, please refer to our documentation, we are not fully compatible with minio.
https://juicefs.com/docs/community/guide/gateway/#advanced-features

**Comment by shubham-kaushal** [comment]
@zhijian-pro Thank you for the response! I tried the suggested method from you and it's kinda complex and expensive solution. The best method will be to use the MinIO identity plugin as it will allow flexibility and an optimized way to authenticate.

Is there any plan to support the suggested identity plugins of MinIO?

**Comment by zhijian-pro** [comment]
No plan at the moment.
