### ISSUE TITLE
random read cause repeat prefetch same blocks

### ISSUE THREAD

**Issue by sjp00556** [juicedata/juicefs#5134]
**What happened**:
random read will cause repeat prefetch same blocks，which will case bandwidth amplification

**How to reproduce it (as minimally and precisely as possible)**:
fio -filename=./f1 -direct=1 -iodepth 1 -thread -rw=randread -ioengine=psync -bs=128K -size=100m -numjobs=1  -group_reporting -name=mytest

the same key may be prefetched repeatedly

![screenshot-20240903-000450](https://github.com/user-attachments/assets/9a685208-9ab6-4e2e-8d58-75453f212509)

**Comment by SandyXSD** [comment]
Fixed by #4947.
