### ISSUE TITLE
juicefs rmr deletion failed

### ISSUE THREAD

**Issue by gobraves** [juicedata/juicefs#5150]
**What happened**:
`juicefs rmr` deletion failed with an error: "permission denied"
![image](https://github.com/user-attachments/assets/cc225de8-5595-4a9a-96f0-78b229cae8e0)
**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**

**Environment**:
- JuiceFS version (use `juicefs --version`) or Hadoop Java SDK version:

juicefs version 1.2.1+2024-08-30.cd871d1

- Cloud provider or hardware configuration running JuiceFS:
- OS (e.g `cat /etc/os-release`):
fedora linux 40

- Kernel (e.g. `uname -a`):
`Linux fedora 6.10.7-200.fc40.x86_64 #1 SMP PREEMPT_DYNAMIC Fri Aug 30 00:08:59 UTC 2024 x86_64 GNU/Linux`

- Object storage (cloud provider and region, or self maintained):
- Metadata engine info (version, cloud provider managed or self maintained):
- Network connectivity (JuiceFS to metadata engine, JuiceFS to object storage):
- Others:

**Comment by zhijian-pro** [comment]
This date format file is a virtual file, cannot be manually deleted,and does not take up space, so do not worry about it, just delete the file below him.
```
juicefs rmr .trash/2022-11-30-10/

```

**Comment by gobraves** [comment]
I tried it yesterday, but it didn't work.
![image](https://github.com/user-attachments/assets/2e948c42-7ac8-4d2c-a882-77bf17bebc51)

**Comment by zhijian-pro** [comment]
https://juicefs.com/docs/zh/community/security/trash#permission
> 当 JuiceFS 客户端由非 root 用户启动时，需要在 mount 时指定 -o allow_root 参数，允许 root 用户访问文件系统，否则将无法正常清空回收站。

**Comment by zhijian-pro** [comment]
@gobraves  any update ？

**Comment by gobraves** [comment]
It doesn't seem to work with `-o allow_root`. But mounting as the root user and then performing the delete operation worked, thank you.

`juicefs mount 'mysql://neo:xxxxxxxxxxx@(192.168.88.17:3306)/juicefs'  test_fs/ -o allow_root`

![image](https://github.com/user-attachments/assets/372ae7a1-f395-4169-9895-c0f31d06f119)
