### ISSUE TITLE
StatFS in 1.1 is slower than 1.0

### ISSUE THREAD

**Issue by lidaohang** [juicedata/juicefs#5160]
###  现象
从v1.0.2 升级到v1.1.2 后时延增加
![image](https://github.com/user-attachments/assets/b1addb7c-15ab-44b8-8fc8-0fad4663820d)

![image](https://github.com/user-attachments/assets/dd43dcfd-6b3b-4b4e-a96a-ffadd9dbec60)

2024.09.12 15:38:56.590138 [uid:0,gid:0,pid:0] release (63583886189,864513): OK <0.000006>
2024.09.12 15:38:56.590664 [uid:11134431,gid:11134431,pid:1047485] open (63583886189): OK [fh:864517] <0.000005>
2024.09.12 15:38:56.595999 [uid:11134431,gid:11134431,pid:1047497] statfs (63583886189): OK (214144579207860224,74085796943851520,62834483652,21474836480) <0.061053>
2024.09.12 15:38:56.596434 [uid:11134431,gid:11134431,pid:1047497] flush (63583886189,864514,140594C29C22C0FD): OK <0.000001>

statfs： 610ms

代码：
![image](https://github.com/user-attachments/assets/382401b5-ebb8-4398-9cb4-9f1dedb8ecfc)

![image](https://github.com/user-attachments/assets/3ccc3358-be3f-438c-bccc-b6b5ec8a1a65)

v1.1.2 多了Access和quota功能， 这里会无条件请求元数据集群扫描是否有quota前缀的key。

总体来看： 多了2次GetAttr 和 一次 doGetQuota 操作。

**Comment by davies** [comment]
如果 statfs 的路径是挂载点，应该是没有性能差异的。1.1 引入了 子目录的 statfs 支持，用户返回 k8s 场景的动态 PV 的容量，才需要 检查是否有设置 quota。

为什么这里的 statfs 传入的路径不是根目录？是在 CSI 场景吗？

**Comment by lidaohang** [comment]
2024.09.12 15:38:56.528107 [uid:11134431,gid:11134431,pid:1047485] open (63583886189): OK [fh:864513] <0.003145>
2024.09.12 15:38:56.533309 [uid:11134431,gid:11134431,pid:1047497] statfs (63573439494): OK (214144578344566784,74085797807144960,62834483560,21474836480) <0.056234>
2024.09.12 15:38:56.534930 [uid:11134431,gid:11134431,pid:1047497] open (63583886189): OK [fh:864514] <0.000005>
2024.09.12 15:38:56.551082 [uid:11134431,gid:11134431,pid:1065137] statfs (63582979281): OK (214144578788904960,74085797362806784,62834483562,21474836480) <0.060747>
2024.09.12 15:38:56.551540 [uid:11134431,gid:11134431,pid:1065137] flush (63582979281,864511,6A347BFF5171A5EC): OK <0.000001>
2024.09.12 15:38:56.551563 [uid:0,gid:0,pid:0] release (63582979281,864511): OK <0.000003>
2024.09.12 15:38:56.551978 [uid:11134431,gid:11134431,pid:1065137] open (63582979281): OK [fh:864515] <0.000006>
2024.09.12 15:38:56.561404 [uid:11134431,gid:11134431,pid:1065135] statfs (63578771004): OK (214144578826194944,74085797325516800,62834483602,21474836480) <0.062525>
2024.09.12 15:38:56.561831 [uid:11134431,gid:11134431,pid:1065135] flush (63578771004,864512,685E0AEA6480174D): OK <0.000001>
2024.09.12 15:38:56.561853 [uid:0,gid:0,pid:0] release (63578771004,864512): OK <0.000005>
2024.09.12 15:38:56.562281 [uid:11134431,gid:11134431,pid:1065135] open (63578771004): OK [fh:864516] <0.000005>
2024.09.12 15:38:56.589668 [uid:11134431,gid:11134431,pid:1047485] statfs (63583886189): OK (214144579207860224,74085796943851520,62834483652,21474836480) <0.061538>
2024.09.12 15:38:56.590114 [uid:11134431,gid:11134431,pid:1047485] flush (63583886189,864513,D7D7ABDA37B7CD42): OK <0.000001>
2024.09.12 15:38:56.590138 [uid:0,gid:0,pid:0] release (63583886189,864513): OK <0.000006>
2024.09.12 15:38:56.590664 [uid:11134431,gid:11134431,pid:1047485] open (63583886189): OK [fh:864517] <0.000005>
2024.09.12 15:38:56.595999 [uid:11134431,gid:11134431,pid:1047497] statfs (63583886189): OK (214144579207860224,74085796943851520,62834483652,21474836480) <0.061053>
2024.09.12 15:38:56.596434 [uid:11134431,gid:11134431,pid:1047497] flush (63583886189,864514,140594C29C22C0FD): OK <0.000001>
2024.09.12 15:38:56.596452 [uid:0,gid:0,pid:0] release (63583886189,864514): OK <0.000003>
2024.09.12 15:38:56.596901 [uid:11134431,gid:11134431,pid:1047497] open (63583886189): OK [fh:864518] <0.000003>
2024.09.12 15:38:56.607780 [uid:11134431,gid:11134431,pid:1065137] statfs (63582979281): OK (214144579231469568,74085796920242176,62834483681,21474836480) <0.055786>
2024.09.12 15:38:56.609428 [uid:11134431,gid:11134431,pid:1065137] open (63569415047): OK [fh:864519] <0.000008>
2024.09.12 15:38:56.615838 [uid:11134431,gid:11134431,pid:1065135] statfs (63578771004): OK (214144579233255424,74085796918456320,62834483706,21474836480) <0.053541>
2024.09.12 15:38:56.616296 [uid:11134431,gid:11134431,pid:1065135] flush (63578771004,864516,685E0AEA6480174D): OK <0.000001>
2024.09.12 15:38:56.616315 [uid:0,gid:0,pid:0] release (63578771004,864516): OK <0.000003>
2024.09.12 15:38:56.616800 [uid:11134431,gid:11134431,pid:1065135] open (63578771004): OK [fh:864520] <0.000005>
2024.09.12 15:38:56.641882 [uid:11134431,gid:11134431,pid:1047485] statfs (63583886189): OK (214144579430674432,74085796721037312,62834483757,21474836480) <0.051201>
2024.09.12 15:38:56.642358 [uid:11134431,gid:11134431,pid:1047485] flush (63583886189,864517,D7D7ABDA37B7CD42): OK <0.000001>
2024.09.12 15:38:56.642380 [uid:0,gid:0,pid:0] release (63583886189,864517): OK <0.000005>
2024.09.12 15:38:56.642796 [uid:11134431,gid:11134431,pid:1047485] open (63583886189): OK [fh:864521] <0.000005>
2024.09.12 15:38:56.646647 [uid:11134431,gid:11134431,pid:1047497] statfs (63583886189): OK (214144579908354048,74085796243357696,62834483817,21474836480) <0.049729>
2024.09.12 15:38:56.647055 [uid:11134431,gid:11134431,pid:1047497] flush (63583886189,864518,140594C29C22C0FD): OK <0.000001>
2024.09.12 15:38:56.647076 [uid:0,gid:0,pid:0] release (63583886189,864518): OK <0.000005>
2024.09.12 15:38:56.647504 [uid:11134431,gid:11134431,pid:1047497] open (63583886189): OK [fh:864522] <0.000004>
2024.09.12 15:38:56.664065 [uid:11134431,gid:11134431,pid:1065137] statfs (63569415047): OK (214144579924480000,74085796227231744,62834483994,21474836480) <0.054616>
2024.09.12 15:38:56.664506 [uid:11134431,gid:11134431,pid:1065137] flush (63569415047,864519,6A347BFF5171A5EC): OK <0.000001>
2024.09.12 15:38:56.664532 [uid:0,gid:0,pid:0] release (63569415047,864519): OK <0.000007>
2024.09.12 15:38:56.665057 [uid:11134431,gid:11134431,pid:1065137] open (63569415047): OK [fh:864523] <0.000005>
2024.09.12 15:38:56.666755 [uid:11134431,gid:11134431,pid:1065135] statfs (63578771004): OK (214144580380561408,74085795771150336,62834484000,21474836480) <0.049940>
2024.09.12 15:38:56.668279 [uid:11134431,gid:11134431,pid:1065135] open (63575548551): OK [fh:864524] <0.000005>

目前使用方式是宿主机挂载跟目录，容器里面映射子目录。你看statfs 文件都不一样。
