### ISSUE TITLE
Fatal error and cannot view logs

### ISSUE THREAD

**Issue by Haivilo** [juicedata/juicefs#5166]
We keep receiving 
```
juicefs[19] <FATAL>: The mount point is not ready in 10 seconds, please check the log (/var/log/juicefs.log) or re-mount in foreground [mount_unix.go:57]
``` 
but since the log is in the container, we cannot check it when the pod is deleted. Is there a way to find the root cause?  
![Screenshot 2024-09-12 at 12 02 51 PM](https://github.com/user-attachments/assets/73f089f6-9db7-4b5b-b375-e4beb497ab76)

**Version**:
Helm Chart version: 0.19.4 (juicefs-csi-driver)
Juicefs version: v1.1.0

**Comment by Haivilo** [comment]
cc @yetone @bojiang

**Comment by zhijian-pro** [comment]
It is best to reproduce the error and then collect the log before deleting the pod

**Comment by polyrabbit** [comment]
@Haivilo We also had similar issues occasionally, and the log does not provide any clues. We patched the code to log the stack trace of the hanging mount process, so that we can see where it happens. Here is a recent stack trace:

```
juicefs[1] <FATAL>: The mount point is not ready in 10 seconds (tried to kill mount process 57), exit it [mount_unix.go:237]
SIGABRT: abort
PC=0x40998e m=0 sigcode=0

goroutine 0 gp=0x5916760 m=0 mp=0x5917780 [idle]:
runtime/internal/syscall.Syscall6()
	/usr/local/go/src/runtime/internal/syscall/asm_linux_amd64.s:36 +0xe fp=0x7fff8f879f38 sp=0x7fff8f879f30 pc=0x40998e
runtime/internal/syscall.EpollWait(0x5?, {0x7fff8f879fd4?, 0x100000010?, 0x1?}, 0x9bea3b2c?, 0x9bea3b2c?)
	/usr/local/go/src/runtime/internal/syscall/syscall_linux.go:55 +0x45 fp=0x7fff8f879f88 sp=0x7fff8f879f38 pc=0x409905
runtime.netpoll(0xc00006e008?)
	/usr/local/go/src/runtime/netpoll_epoll.go:118 +0xd2 fp=0x7fff8f87a618 sp=0x7fff8f879f88 pc=0x43df72
runtime.findRunnable()
	/usr/local/go/src/runtime/proc.go:3470 +0x8c5 fp=0x7fff8f87a790 sp=0x7fff8f87a618 pc=0x44a725
runtime.schedule()
	/usr/local/go/src/runtime/proc.go:3868 +0xb1 fp=0x7fff8f87a7c8 sp=0x7fff8f87a790 pc=0x44bc91
runtime.park_m(0xc001866540)
	/usr/local/go/src/runtime/proc.go:4036 +0x1ec fp=0x7fff8f87a820 sp=0x7fff8f87a7c8 pc=0x44c26c
runtime.mcall()
	/usr/local/go/src/runtime/asm_amd64.s:458 +0x4e fp=0x7fff8f87a838 sp=0x7fff8f87a820 pc=0x47b54e

goroutine 1 gp=0xc0000061c0 m=15 mp=0xc001280008 [syscall]:
syscall.Syscall(0x10c, 0xffffffffffffff9c, 0xc00136ef60, 0x1c0)
	/usr/local/go/src/syscall/syscall_linux.go:69 +0x25 fp=0xc0019beeb0 sp=0xc0019bee50 pc=0x497705
syscall.fchmodat(0xffffffffffffff9c, {0xc00136ee40?, 0xc00136ee40?}, 0x1c0)
	/usr/local/go/src/syscall/zsyscall_linux_amd64.go:48 +0x73 fp=0xc0019beef8 sp=0xc0019beeb0 pc=0x4931d3
syscall.Fchmodat(0x106?, {0xc00136ee40?, 0xc00136ef00?}, 0xf889f8?, 0x0?)
	/usr/local/go/src/syscall/syscall_linux.go:262 +0xbb fp=0xc0019bef40 sp=0xc0019beef8 pc=0x49049b
syscall.Chmod(...)
	/usr/local/go/src/syscall/syscall_linux.go:109
os.chmod.func1()
	/usr/local/go/src/os/file_posix.go:79 +0x6d fp=0xc0019bef78 sp=0xc0019bef40 pc=0x4cf24d
os.ignoringEINTR(...)
	/usr/local/go/src/os/file_posix.go:251
os.chmod({0xc00136ee40, 0x5f}, 0x0?)
	/usr/local/go/src/os/file_posix.go:78 +0x59 fp=0xc0019befd0 sp=0xc0019bef78 pc=0x4cf0f9
os.Chmod(...)
	/usr/local/go/src/os/file.go:594
github.com/juicedata/juicefs/pkg/chunk.changeMode({0xc00136ee40, 0x5f}, {0x4032ac8?, 0xc000f889c0?}, 0x1c0)
	/workspace/pkg/chunk/utils_unix.go:47 +0x9b fp=0xc0019bf018 sp=0xc0019befd0 pc=0x1f07cdb
github.com/juicedata/juicefs/pkg/chunk.(*cacheStore).createDir.func1()
	/workspace/pkg/chunk/disk_cache.go:600 +0x106 fp=0xc0019bf090 sp=0xc0019bf018 pc=0x1efa3a6
github.com/juicedata/juicefs/pkg/chunk.(*cacheStore).checkErr(0xc0013600e0, 0xc000fd4920)
	/workspace/pkg/chunk/disk_cache.go:230 +0x11b fp=0xc0019bf108 sp=0xc0019bf090 pc=0x1ef5adb
github.com/juicedata/juicefs/pkg/chunk.(*cacheStore).createDir(0xc0013600e0, {0xc00136ee40, 0x5f})
	/workspace/pkg/chunk/disk_cache.go:587 +0x7a fp=0xc0019bf128 sp=0xc0019bf108 pc=0x1efa25a
```

It shows the mount process stucks in `chunk.changeMode`, which means our local file system is not working properly.

I also submitted the patch to PR #5171. Hope it helps.

**Comment by Haivilo** [comment]
> @Haivilo We also had similar issues occasionally, and the log does not provide any clues. We patched the code to log the stack trace of the hanging mount process, so that we can see where it happens. Here is a recent stack trace:
> 
> ```
> juicefs[1] <FATAL>: The mount point is not ready in 10 seconds (tried to kill mount process 57), exit it [mount_unix.go:237]
> SIGABRT: abort
> PC=0x40998e m=0 sigcode=0
> 
> goroutine 0 gp=0x5916760 m=0 mp=0x5917780 [idle]:
> runtime/internal/syscall.Syscall6()
> 	/usr/local/go/src/runtime/internal/syscall/asm_linux_amd64.s:36 +0xe fp=0x7fff8f879f38 sp=0x7fff8f879f30 pc=0x40998e
> runtime/internal/syscall.EpollWait(0x5?, {0x7fff8f879fd4?, 0x100000010?, 0x1?}, 0x9bea3b2c?, 0x9bea3b2c?)
> 	/usr/local/go/src/runtime/internal/syscall/syscall_linux.go:55 +0x45 fp=0x7fff8f879f88 sp=0x7fff8f879f38 pc=0x409905
> runtime.netpoll(0xc00006e008?)
> 	/usr/local/go/src/runtime/netpoll_epoll.go:118 +0xd2 fp=0x7fff8f87a618 sp=0x7fff8f879f88 pc=0x43df72
> runtime.findRunnable()
> 	/usr/local/go/src/runtime/proc.go:3470 +0x8c5 fp=0x7fff8f87a790 sp=0x7fff8f87a618 pc=0x44a725
> runtime.schedule()
> 	/usr/local/go/src/runtime/proc.go:3868 +0xb1 fp=0x7fff8f87a7c8 sp=0x7fff8f87a790 pc=0x44bc91
> runtime.park_m(0xc001866540)
> 	/usr/local/go/src/runtime/proc.go:4036 +0x1ec fp=0x7fff8f87a820 sp=0x7fff8f87a7c8 pc=0x44c26c
> runtime.mcall()
> 	/usr/local/go/src/runtime/asm_amd64.s:458 +0x4e fp=0x7fff8f87a838 sp=0x7fff8f87a820 pc=0x47b54e
> 
> goroutine 1 gp=0xc0000061c0 m=15 mp=0xc001280008 [syscall]:
> syscall.Syscall(0x10c, 0xffffffffffffff9c, 0xc00136ef60, 0x1c0)
> 	/usr/local/go/src/syscall/syscall_linux.go:69 +0x25 fp=0xc0019beeb0 sp=0xc0019bee50 pc=0x497705
> syscall.fchmodat(0xffffffffffffff9c, {0xc00136ee40?, 0xc00136ee40?}, 0x1c0)
> 	/usr/local/go/src/syscall/zsyscall_linux_amd64.go:48 +0x73 fp=0xc0019beef8 sp=0xc0019beeb0 pc=0x4931d3
> syscall.Fchmodat(0x106?, {0xc00136ee40?, 0xc00136ef00?}, 0xf889f8?, 0x0?)
> 	/usr/local/go/src/syscall/syscall_linux.go:262 +0xbb fp=0xc0019bef40 sp=0xc0019beef8 pc=0x49049b
> syscall.Chmod(...)
> 	/usr/local/go/src/syscall/syscall_linux.go:109
> os.chmod.func1()
> 	/usr/local/go/src/os/file_posix.go:79 +0x6d fp=0xc0019bef78 sp=0xc0019bef40 pc=0x4cf24d
> os.ignoringEINTR(...)
> 	/usr/local/go/src/os/file_posix.go:251
> os.chmod({0xc00136ee40, 0x5f}, 0x0?)
> 	/usr/local/go/src/os/file_posix.go:78 +0x59 fp=0xc0019befd0 sp=0xc0019bef78 pc=0x4cf0f9
> os.Chmod(...)
> 	/usr/local/go/src/os/file.go:594
> github.com/juicedata/juicefs/pkg/chunk.changeMode({0xc00136ee40, 0x5f}, {0x4032ac8?, 0xc000f889c0?}, 0x1c0)
> 	/workspace/pkg/chunk/utils_unix.go:47 +0x9b fp=0xc0019bf018 sp=0xc0019befd0 pc=0x1f07cdb
> github.com/juicedata/juicefs/pkg/chunk.(*cacheStore).createDir.func1()
> 	/workspace/pkg/chunk/disk_cache.go:600 +0x106 fp=0xc0019bf090 sp=0xc0019bf018 pc=0x1efa3a6
> github.com/juicedata/juicefs/pkg/chunk.(*cacheStore).checkErr(0xc0013600e0, 0xc000fd4920)
> 	/workspace/pkg/chunk/disk_cache.go:230 +0x11b fp=0xc0019bf108 sp=0xc0019bf090 pc=0x1ef5adb
> github.com/juicedata/juicefs/pkg/chunk.(*cacheStore).createDir(0xc0013600e0, {0xc00136ee40, 0x5f})
> 	/workspace/pkg/chunk/disk_cache.go:587 +0x7a fp=0xc0019bf128 sp=0xc0019bf108 pc=0x1efa25a
> ```
> 
> It shows the mount process stucks in `chunk.changeMode`, which means our local file system is not working properly.
> 
> I also submitted the patch to PR #5171. Hope it helps.

Thanks for the insight! Our problem was solved by upgrading to the latest version. The root cause is still yet unknown.
