### ISSUE TITLE
method label of *ops_durations_histogram should not be removed

### ISSUE THREAD

**Issue by ddrid** [juicedata/juicefs#5168]
**What would you like to be added**:
In #4667, the method label of histogram *_ops_durations_histogram_seconds were removed and replaced with the *_ops_duration_seconds counter. However, this metric cannot be used to monitor the P50 and P99 latency for each operation. Additionally, the rate(counter) format does not accurately reflect the actual latency metrics. 

We should re-add the method labels to the fuse_ops_durations_histogram_seconds and meta_ops_durations_histogram_seconds metrics.

**Comment by davies** [comment]
We should limit the number metrics, otherwise it will be too slow to fetch these metrics from thousands of nodes. So we can't have these methods for histogram metrics, which already has tens of values.
