### ISSUE TITLE
调用juicefs gateway AssumeRole API 报AccessDenied

### ISSUE THREAD

**Issue by Enzozzzz** [juicedata/juicefs#5169]
juicefs Version: 1.2.1 
gateway启动方式： 依照文档
`export MINIO_ROOT_USER=admin`
`export MINIO_ROOT_PASSWORD=12345678`
`juicefs gateway redis://127.0.0.1:6379/1 127.0.0.1:9000`

启动完成后，admin用户访问gateway服务正常
![image](https://github.com/user-attachments/assets/43db8e0e-b2bf-477e-aed6-9f1ad8161eb3)

问题描述： admin账户可以使用正常的功能，对于请求AssumeRole API使用多种方式请求临时秘钥时，会报
An error occurred (AccessDenied) when calling the AssumeRole operation: Generating temporary credentials not allowed for this request.

方式1：aws cli
`aws --profile admin  --endpoint-url http://x.x.x.x:9000 sts assume-role --policy '{"Version":"2011-06-15","Statement":[{"Sid":"Stmt1","Effect":"Allow","Action":"s3:*","Resource":"arn:aws:s3:::*"}]}' --role-arn arn:xxx:xxx:xxx:xxxx --role-session-name anything`
方式2： 官网提供的示例：go程序

**Comment by zhijian-pro** [comment]
不要使用环境变量定义的用户，环境变量定义的用户无法直接创建秘钥
需要先创建一个用户，然后给他赋予 admin 权限，然后再为这个用户请求临时秘钥

**Comment by Enzozzzz** [comment]
> 不要使用环境变量定义的用户，环境变量定义的用户无法直接创建秘钥 需要先创建一个用户，然后给他赋予 admin 权限，然后再为这个用户请求临时秘钥

好的 感谢 问题解决
