### ISSUE TITLE
windows 11 arm64 builds

### ISSUE THREAD

**Issue by gedw99** [juicedata/juicefs#5170]
thanks ...

test it from a Mac using UTM. works perfectly ...

**Comment by zhijian-pro** [comment]
What can I do for you ？

**Comment by SandyXSD** [comment]
Glad it works. Windows on arm64 is not that widely used, and we don't have enough bandwidth to make sure it's always stable, so it won't be contained in the official release. You need to build it yourself, just like you already did. But feel free to contact us when you run into problems.
