### ISSUE TITLE
meta openfile add file type cache ttl

### ISSUE THREAD

**Issue by lidaohang** [juicedata/juicefs#5177]
元数据缓存，是否支持文件类型缓存不同的ttl时间。

**Comment by lidaohang** [comment]
// Attr represents attributes of a node.
type Attr struct {
	Flags     uint8  // reserved flags
	Typ       uint8  // type of a node
	Mode      uint16 // permission mode
	Uid       uint32 // owner id
	Gid       uint32 // group id of owner
	Rdev      uint32 // device number
	Atime     int64  // last access time
	Mtime     int64  // last modified time
	Ctime     int64  // last change time for meta
	Atimensec uint32 // nanosecond part of atime
	Mtimensec uint32 // nanosecond part of mtime
	Ctimensec uint32 // nanosecond part of ctime
	Nlink     uint32 // number of links (sub-directories or hardlinks)
	Length    uint64 // length of regular file

	Parent    Ino    // inode of parent; 0 means tracked by parentKey (for hardlinks)
	Full      bool   // the attributes are completed or not
	KeepCache bool   // whether to keep the cached page or not
	FileType  uint32 // type of a node
}
目前的方案是新增FileType 来支持。

**Comment by SandyXSD** [comment]
The `Typ` is already used to define the type of a node.

**Comment by SandyXSD** [comment]
Closing it since it's not a general requirement.
