### ISSUE TITLE
Can't write to register layer when using Juicefs as data root for docker

### ISSUE THREAD

**Issue by dclift** [juicedata/juicefs#5188]
**What happened**:

I changed the docker data directory to use a juicefs mount, ran the docker compose file for [immich](https://immich.app/docs/install/docker-compose) and got the following error related to [tar-split](https://github.com/vbatts/tar-split) when pulling the containers:

`failed to register layer: write /mnt/juice/docker-data/image/vfs/layerdb/tmp/write-set-2885405029/tar-split.json.gz: bad file descriptor`

Using the native file system as docker's data root works fine. 

**What you expected to happen**:

Over time Docker's data root can often grow quite large due to a variety of reasons, so would be nice to move it to juicefs and not worry about disk allocation/exhaustion when using smaller VMs, etc. 

**How to reproduce it (as minimally and precisely as possible)**:

Configure docker's data root in `/etc/docker/daemon.json`

```
{
    "data-root": "/mnt/juice/docker-data"
}
```

Restart the docker.service and then try to pull the containers:

```
wget -O docker-compose.yml https://github.com/immich-app/immich/releases/latest/download/docker-compose.yml

docker compose pull

docker compose create
```

**Anything else we need to know?**

**Environment**:
- JuiceFS version (use `juicefs --version`) or Hadoop Java SDK version: 2.1+2024-08-30.cd871d1
- Cloud provider or hardware configuration running JuiceFS: Hetzner Cloud
- OS (e.g `cat /etc/os-release`): Debian 12
- Kernel (e.g. `uname -a`): 6.1.106-3
- Object storage (cloud provider and region, or self maintained): B2
- Metadata engine info (version, cloud provider managed or self maintained): PostgreSQL 15.8
- Network connectivity (JuiceFS to metadata engine, JuiceFS to object storage):
- Others:

**Comment by davies** [comment]
@dclift Can you check the error of juicefs?

**Comment by dclift** [comment]
@davies 

Sure, `/var/log/juicefs.log` only displayed this warning:

`2024/09/26 12:47:09.204632 juicefs[912] <WARNING>: slow request: PUT chunks/0/892/892202_0_4194304 (req_id: "", err: <nil>, cost: 11.246311338s) [cached_store.go:667]`

I mount juicefs with a systemd.mount, so I remounted it with the with debug flag and tried to pull the containers again, and have attached the log here [juicefs.log](https://github.com/user-attachments/files/17154304/juicefs.log). The `failed to register layer` error occurred somewhere around 13:20:15.

**Comment by zhijian-pro** [comment]
@dclift Can you provide your mounting parameters ？ I used default parameters to mount pull and run images ok.

**Comment by dclift** [comment]
@zhijian-pro 


```
[Unit]
Description=Juicefs
Before=docker.service

[Mount]
Environment="META_PASSWORD={{ db_password }}"
What={{ db_location }}
Where=/mnt/juice
Type=juicefs
Options=_netdev,allow_other,writeback_cache,cache-size=35480,nofail

[Install]
WantedBy=remote-fs.target
WantedBy=multi-user.target
```

**Comment by zhijian-pro** [comment]
@dclift  I didn't repeat the problem, but you can add `enable-xattr` to your parameter, because I found a lot of requests for extended attributes from the access log, and you can try docker pull redis directly again.

**Comment by dclift** [comment]
Thanks @zhijian-pro 

I spun up a new vps with the systemd mount including the suggested parameters 
`Options=writeback,_netdev,enable-xattr,allow_other,writeback_cache,cache-size=35480,nofail`, ran as root to avoid any potential permissions issues and was able to pull the containers successfully. 

That said, the performance was poor so using juicefs as the docker data root might not be a viable use in any event. Took over two and half hours to pull.  I certainly could have made a mistake with the suggested parameters, but if this aligns with your experience please let me know.

![2024-09-27_06-03](https://github.com/user-attachments/assets/1eae5c5c-aa17-4cac-8ae5-c8c8b15a01d3)

![2024-09-27_04-06](https://github.com/user-attachments/assets/ddaee07c-50db-410b-bf0a-afc5bb18f668)

**Comment by davies** [comment]
There are many small files in docker images, the 'write' performance is much slower than local disk with in writeback mode, so we think JuiceFS can not perform well in this use case.

Another option: create a file in JuiceFS and use that as a loopback device (allocated using truncate), then the 'write' performance will be much better (kernel cache). You will need some local disk as cache to boost the read performance.

**Comment by dclift** [comment]
Thank you @davies, I agree, it seems JuiceFS just isn't ideal for this use case. I ran the test without writeback mode and it was only about 12% faster. 

I had previously researched a similar idea to your suggestion of a loopback device. Docker used to have a storage driver that did this, but unfortunately it has since been deprecated:  

https://github.com/docker/for-linux/issues/452

Thanks again for looking into this - JuiceFS is an amazing project by the way!

**Comment by davies** [comment]
> Sure, `/var/log/juicefs.log` only displayed this warning:
> 
> `2024/09/26 12:47:09.204632 juicefs[912] <WARNING>: slow request: PUT chunks/0/892/892202_0_4194304 (req_id: "", err: <nil>, cost: 11.246311338s) [cached_store.go:667]`
> 
> I mount juicefs with a systemd.mount, so I remounted it with the with debug flag and tried to pull the containers again, and have attached the log here [juicefs.log](https://github.com/user-attachments/files/17154304/juicefs.log). The `failed to register layer` error occurred somewhere around 13:20:15.

I looked into the error log, all the FUSE requests are normal, can't find anything that was related to `bad file descriptor`. 

We can't reproduce this failure.

**Comment by dclift** [comment]
No worries @davies, as discovered it's not an ideal use case for JuiceFS in any event so will go ahead and close this issue.
