### ISSUE TITLE
dial tcp: too many colons in address (IPv6)

### ISSUE THREAD

**Issue by angristan** [juicedata/juicefs#52]
I noticed this in my logs from time to time. It doesn't seem to cause big problems, but this error looks curious to me:
```
2021/01/13 20:44:57.482340 juicefs[81861] <WARNING>: upload chunks/0/12/12735_2_16777216: RequestError: send request failed
caused by: Put "https://sana-store.s3.fr-par.scw.cloud/seedbox/chunks/0/12/12735_2_16777216": dial tcp: address 2001:bc8:1002::30:443: too many colons in address (try 1)
2021/01/13 20:46:37.409525 juicefs[81861] <WARNING>: upload chunks/0/12/12829_3_16777216: RequestError: send request failed
caused by: Put "https://sana-store.s3.fr-par.scw.cloud/seedbox/chunks/0/12/12829_3_16777216": dial tcp: address 2001:bc8:1002::30:443: too many colons in address (try 1)
2021/01/13 21:09:19.104197 juicefs[81861] <WARNING>: upload chunks/0/13/13873_1_16777216: RequestError: send request failed
caused by: Put "https://sana-store.s3.fr-par.scw.cloud/seedbox/chunks/0/13/13873_1_16777216": dial tcp: address 2001:bc8:1002::30:443: too many colons in address (try 1)
2021/01/13 21:22:25.961086 juicefs[81861] <WARNING>: upload chunks/0/14/14410_1_16777216: RequestError: send request failed
caused by: Put "https://sana-store.s3.fr-par.scw.cloud/seedbox/chunks/0/14/14410_1_16777216": dial tcp: address 2001:bc8:1002::30:443: too many colons in address (try 1)
2021/01/13 21:59:58.166127 juicefs[81861] <WARNING>: upload chunks/0/15/15977_3_16777216: RequestError: send request failed
caused by: Put "https://sana-store.s3.fr-par.scw.cloud/seedbox/chunks/0/15/15977_3_16777216": dial tcp: address 2001:bc8:1002::30:443: too many colons in address (try 1)
```

I'm using Scaleway, the endpoint has these addresses:

```
➜  ~ dog s3.fr-par.scw.cloud
A s3.fr-par.scw.cloud. 22h51m22s   62.210.134.176
➜  ~ dog s3.fr-par.scw.cloud AAAA
AAAA s3.fr-par.scw.cloud. 23h59m21s   2001:bc8:1002::30
```

Maybe it uses IPv4 most of the time and fails on IPv6? 

Let me know if I can provide more info.

**Environment**:
- JuiceFS version (use `./juicefs --version`): `juicefs version 0.9.1-24 (2021-01-13 3dc45dc)`
- Cloud provider or hardware configuration running JuiceFS: dedicated server
- OS (e.g: `cat /etc/os-release`): Debian 10
- Kernel (e.g. `uname -a`): `Linux 4.19.0-13-amd64 #1 SMP Debian 4.19.160-2 (2020-11-28)`
- Object storage (cloud provider and region): Scaleway fr-par (https://s3.fr-par.scw.cloud)
- Redis info (version, cloud provider managed or self maintained): `v5.0.3`, self managed, installed from deb repo
- Network connectivity (JuiceFS to Redis, JuiceFS to object storage): local redis, 1 Gbps to object storage

**Comment by davies** [comment]
This is a bug in juicesync, fixed by https://github.com/juicedata/juicesync/commit/941ff49f2eb3c156125907a3f6dc75b9f7a8c2a5

Will upgrade syncsync to address this.

**Comment by angristan** [comment]
Thanks 👍
