### ISSUE TITLE
 Use juicefs to synchronize from Alibaba Cloud oss ​​to self-built minio

### ISSUE THREAD

**Issue by shora0** [juicedata/juicefs#5201]
When using juicefs to synchronize from Alibaba Cloud oss ​​to self-built minio, an error occurs. Where is the parameter area defined?

error message：AuthorizationHeaderMalformed: The authorization header is malformed; the region is wrong; expecting 'Hong_Kong'

**Comment by shora0** [comment]
<img width="754" alt="1png" src="https://github.com/user-attachments/assets/337571a5-9a1f-4ede-b636-27eef101fe00">

**Comment by SandyXSD** [comment]
Where is your OSS located? and what's the full sync command you used (ignore the keys)?

**Comment by shora0** [comment]
oss in Hong Kong  The self-built minio is also in Hong Kong

**Comment by shora0** [comment]
It is normal to connect to oss, but a region error occurs when connecting to minio.

**Comment by shora0** [comment]
juicefs format --storage minio --bucket http://10.100.1.10:9000/dba-test --access-key xKgYfnstPL6txFWdeaW --secret-key SNJ3rRWOudfvARipGeVufGa0tiipmu09Dg836a  redis://127.0.0.1:6379/1 myjfs  
status code: 400, request id: 17F9FFF25930782B, host id: 1166ad4377017adeecf2182ee6cab1dd6bde2b6f58d6179966c5b2b359901dfd, previous error: AuthorizationHeaderMalformed: The authorization header is malformed; the region is wrong; expecting 'Hong_Kong'

**Comment by zhijian-pro** [comment]
@shora0 
> The MINIO_REGION environment variable can be used to set the region of MinIO, if not set, the default is us-east-1.
try to set  MINIO_REGION ？

**Comment by shora0** [comment]
The MINIO_REGION environment variable has been set and is now normal.

zhijian ***@***.***> 于2024年10月8日周二 12:15写道：
