### ISSUE TITLE
Juicefs on GlusterFS 10.3 results in SIGSEGV and I/O corruption

### ISSUE THREAD

**Issue by karlkashofer** [juicedata/juicefs#5211]
**What happened**:
Using a Glusterfs backend with the current 10.3 gluster version gives SIGSEGV errors in juicefs.

![grafik](https://github.com/user-attachments/assets/d3cda547-367b-456b-9e27-0497a4e3dea1)

This leads to I/O errors, data corruption and performance degradation.

**How to reproduce it (as minimally and precisely as possible)**:
Build a gluster drive using current 10.3 gluster release. Use it as backend for juicefs. Apply load on the fs, watch juicefs.log

**Anything else we need to know?**
This is also mentioned in https://github.com/juicedata/juicefs/issues/4043
It would be great to fix this in juicefs, as not all installations can downgrade to gluster 10.1 and its difficult to maintain different versions in parallel.
Gluster release schedule: https://www.gluster.org/release-schedule/
**Environment**:
Debian docker images

**Comment by karlkashofer** [comment]
anything i can do to help ?

**Comment by jiefenghuang** [comment]
> anything i can do to help ?

@karlkashofer Hi, JuiceFS uses https://github.com/juicedata/gogfapi to access GlusterFS via the cgo (in pkg/object/gluster.go). We would be very glad if you could provide a Pull Request to implement gogfapi compatibility with the newer GlusterFS versions.
