### ISSUE TITLE
JuiceFS connection to s3 delay due to missing IMDSv2 in EKS cluster

### ISSUE THREAD

**Issue by cuichenli** [juicedata/juicefs#5222]
**What happened**:If the EKS cluster does not have IMDSv2 enabled, JuiceFS may experience a delay of approximately 4 minutes before successfully connecting to S3. To clarify, if a node in the cluster is not compatible with IMDSv2, the AWS client will attempt to connect to the V2 metadata store using commands similar to `curl -X PUT "http://169.254.169.254/latest/api/token"`

However, this connection will time out only after 4 minutes. During this time, the JuiceFS client will hang without providing any error message, which can be confusing, even though the connection will eventually succeed.

**What you expected to happen**: maybe detect if the cluster is IMDSv2 compatiable before trying to get the credentials, or let it fail quicker so user would not wait for 4 minutes.

**How to reproduce it (as minimally and precisely as possible)**: create one eks cluster with IMDSv2 disabled

**Comment by davies** [comment]
We may need to upgrade the aws sdk

**Comment by jiefenghuang** [comment]
ref: https://github.com/aws/aws-sdk-go/pull/3066 https://github.com/aws/aws-sdk-go/issues/2972
our custom client overwrite that timeout

**Comment by zhijian-pro** [comment]
@cuichenli 
What is the `metadata response hop limit` setting for your cluster ?
According to the [official document](https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/configuring-instance-metadata-options.html), the recommended setting is 2 . You can try this setting to see if it works.
In addition, when we create the environment, we can not completely disable v2. There are only two options,only use v2  or allow v1 & v2. so we can not completely simulate the situation of disabling v2. What is your configuration?

**Comment by zhijian-pro** [comment]
@cuichenli Can you test if this pull request #5231 solves your problem ?
