### ISSUE TITLE
Compile error with godeltaprof@v0.1.6

### ISSUE THREAD

**Issue by rafalste** [juicedata/juicefs#5290]
**What happened**:
Error during compilation:
```
[root@master juicefs]# make
go version
go version go1.23.2 (Red Hat 1.23.2-1.el9) linux/amd64
go build -ldflags="-s -w -X github.com/juicedata/juicefs/pkg/version.revision=cd871d19 -X github.com/juicedata/juicefs/pkg/version.revisionDate=2024-08-30"  -o juicefs .
# github.com/grafana/pyroscope-go/godeltaprof/internal/pprof
../go/pkg/mod/github.com/grafana/pyroscope-go/godeltaprof@v0.1.6/internal/pprof/delta_mutex.go:30:20: undefined: runtime_cyclesPerSecond
../go/pkg/mod/github.com/grafana/pyroscope-go/godeltaprof@v0.1.6/internal/pprof/proto.go:320:8: undefined: runtime_expandFinalInlineFrame
make: *** [Makefile:24: juicefs] Error 1
```
**Solution**:
Bump up the version of godeltaprof in go.mod to 0.1.8

**Environment**:
- JuiceFS version (use `juicefs --version`): 1.2.1+2024-08-30.cd871d19
- OS (e.g `cat /etc/os-release`): CentOS Stream 9
- Kernel (e.g. `uname -a`): 5.14.0-522.el9.x86_64

**Comment by jiefenghuang** [comment]
If you need support for Go 1.23, you can switch to the latest main branch.

**Comment by rafalste** [comment]
Hey @jiefenghuang, I used the latest JuiceFS stable release (v1.2.1) and Go version from Centos repo. In the [JuiceFS compilation documentation](https://juicefs.com/docs/community/getting-started/installation#unix-like-client) there is a dependency of `Go 1.20+` and no mention that 1.23 is too high.
Nevertheless, I just leave the solution here in case anyone else trips on the same issue. Feel free to close it.
Cheers!
