### ISSUE TITLE
Is that java/Scala project use jfs client on hadoop need hadoop environment?

### ISSUE THREAD

**Issue by ming-bug** [juicedata/juicefs#5307]
When I deploy a java project to visit jfs by java client. I found that if the java demo config with the docs as bellow not enough.
I have to add Hadoop-related configurations, otherwise it will report 'java.io.IOException: JuiceFS initialized failed for jfs://myjfs'.
So I want to know which hadoop-related configurations are needed.
Actually I might deploy my java project outside of my hadoop environment.
![image](https://github.com/user-attachments/assets/7a160648-2836-4533-b442-705695073be5)

**Comment by tangyoupeng** [comment]
hadoop common is needed because juicefs did not inclue this for version compatiable reason.

**Comment by ming-bug** [comment]
when I config hbase use jfs, the hbase master reboot failed and some log as bellow.
hacluster is my hdfs HA nameservices. Can you help me to resolve it, thanks
object storage: new HDFS client [hacluster]: no available namenodes: dial tcp: address hacluster: missing port in address [main.go:503] | io.juicefs.JuiceFileSystemImpl$LogCallBackImpl.call(JuiceFileSystemImpl.java:230)

**Comment by tangyoupeng** [comment]
did you use hdfs as the underlying storage？If so, you need configure HADOOP_CONF_DIR env

**Comment by ming-bug** [comment]
> did you use hdfs as the underlying storage？If so, you need configure HADOOP_CONF_DIR env

Hi, I found the problem is hdfs ha.
My ufs is hdfs ha, when I execute juicefs format as the doc by nameservice, the meta store bucket with hdfs://hacluster. And then hbase init failed and It mistakenly thinks hacluster is a namenode without port. Even though I export HADOOP_CONF_DIR. I'm not sure is it a bug. And then I format the juicefs on the other way, it is ok know.
![image](https://github.com/user-attachments/assets/2b67b39b-e1be-4a97-97b1-6a03421fbc75)

**Comment by ming-bug** [comment]
> > did you use hdfs as the underlying storage？If so, you need configure HADOOP_CONF_DIR env
> 
> Hi, I found the problem is hdfs ha. My ufs is hdfs ha, when I execute juicefs format as the doc by nameservice, the meta store bucket with hdfs://hacluster. And then hbase init failed and It mistakenly thinks hacluster is a namenode without port. Even though I export HADOOP_CONF_DIR. I'm not sure is it a bug. And then I format the juicefs on the other way, it is ok know. ![image](https://private-user-images.githubusercontent.com/64135839/389501043-2b67b39b-e1be-4a97-97b1-6a03421fbc75.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzI4NDI3ODIsIm5iZiI6MTczMjg0MjQ4MiwicGF0aCI6Ii82NDEzNTgzOS8zODk1MDEwNDMtMmI2N2IzOWItZTFiZS00YTk3LTk3YjEtNmEwMzQyMWZiYzc1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTI5VDAxMDgwMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWFmYjE1Y2FlMzc2N2Y5YzZkZTIwMmI1YmU0OTJkZGY4NWZhOTVmMDY1MGMxZmFiMzRjZjQ5N2E1MTQwN2YyZTEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.LzfXmd9v0SnVy--UdV9zOsu6coW3r9T-b2b6G4W4MWM)

I try a again found that both hdfs HA cluster format way can be used, thanks a lot
