### ISSUE TITLE
Request to Upgrade MinIO Version in JuiceFS

### ISSUE THREAD

**Issue by rampanwar97** [juicedata/juicefs#5310]
**upgrade Minio version in JuiceFs webUI **:

**I am using JuiceFS as a storage solution for Kubernetes, and I rely on the MinIO web UI provided by JuiceFS to access files. However, the current version of MinIO used by JuiceFS is outdated. I am requesting an upgrade to the latest stable MinIO version to improve security, performance, and feature availability.

Reasons for Upgrade
 1. **Outdated Version**: The current MinIO version might lack recent security patches and enhancements.
 2. **Improved Features**: Newer versions of MinIO come with additional features and optimizations that could enhance the user experience.
 3. **Compatibility**: Staying up-to-date ensures better compatibility with modern Kubernetes setups and workflows.**:

![Screenshot from 2024-11-20 23-23-52](https://github.com/user-attachments/assets/8105ed70-3964-44c5-bc4e-c9187d149aec)

Thank you for maintaining this excellent solution. Looking forward to your consideration!

**Comment by zhijian-pro** [comment]
Due to MinIO changing its open source license from Apache to AGPL, we are unable to use the code that has been modified after the license change.

**Comment by rampanwar97** [comment]
**got it.**

Thanks @zhijian-pro  for your response.
