### ISSUE TITLE
`systemctl reload xyz.mount` creates duplicate processes

### ISSUE THREAD

**Issue by aeblyve** [juicedata/juicefs#5324]
**What happened**:

I used `systemctl reload xyz.mount`, where `xyz.mount` is a SystemD JuiceFS mount unit. I was doing this to iterate on testing new mount options. However, multiple JuiceFS processes were building up, which meant that some processes using the mount point were using one set of options with one process, and some were using another.

```
root       30473       1  0 13:12 ?        Sl     0:00 /sbin/mount.juicefs META_URL /juicefs -o rw,remount,allow_other,writeback_cache,writeback,max-uploads=40,buffer-size=1024,backup-meta=0,_netdev
root       30488   30473  0 13:12 ?        S<l    0:02  \_ /usr/bin/juicefs META_URL /juicefs -o rw,remount,allow_other,writeback_cache,writeback,max-uploads=40,buffer-size=1024,backup-meta=0,_netdev
root       31004       1  0 13:23 ?        Sl     0:00 /sbin/mount.juicefs META_URL /juicefs -o rw,remount,allow_other,writeback,max-uploads=40,buffer-size=1024,backup-meta=0,_netdev
root       31018   31004  0 13:23 ?        S<l    0:01  \_ /usr/bin/juicefs META_URL /juicefs -o rw,remount,allow_other,writeback,max-uploads=40,buffer-size=1024,backup-meta=0,_netdev
root       31413       1  0 13:31 ?        Sl     0:00 /sbin/mount.juicefs META_URL /juicefs -o rw,remount,allow_other,writeback_cache,max-uploads=40,buffer-size=1024,backup-meta=0,_netdev
root       31427   31413  0 13:31 ?        S<l    0:02  \_ /usr/bin/juicefs META_URL /juicefs -o rw,remount,allow_other,writeback_cache,max-uploads=40,buffer-size=1024,backup-meta=0,_netdev
```

**What you expected to happen**:

The mount should be cleanly reloaded with the new mount options. One JuiceFS process should be working on the mount point. 

**How to reproduce it (as minimally and precisely as possible)**:

Set up a JuiceFS mount unit, call it `xyz.mount`. Then, do `systemctl reload xyz.mount` a few times. You should be able to see the juicefs processes building up with something like `ps aux | grep juicefs`

**Anything else we need to know?**

**Environment**:
- JuiceFS version (use `juicefs --version`) or Hadoop Java SDK version: 
`juicefs version 1.2.1+2024-08-30.cd871d1` 
- Cloud provider or hardware configuration running JuiceFS: 
AWS EC2 instance. 
- OS (e.g `cat /etc/os-release`):

```
NAME="AlmaLinux"
VERSION="8.10 (Cerulean Leopard)"
ID="almalinux"
ID_LIKE="rhel centos fedora"
VERSION_ID="8.10"
PLATFORM_ID="platform:el8"
PRETTY_NAME="AlmaLinux 8.10 (Cerulean Leopard)"
ANSI_COLOR="0;34"
LOGO="fedora-logo-icon"
CPE_NAME="cpe:/o:almalinux:almalinux:8::baseos"
HOME_URL="https://almalinux.org/"
DOCUMENTATION_URL="https://wiki.almalinux.org/"
BUG_REPORT_URL="https://bugs.almalinux.org/"

ALMALINUX_MANTISBT_PROJECT="AlmaLinux-8"
ALMALINUX_MANTISBT_PROJECT_VERSION="8.10"
REDHAT_SUPPORT_PRODUCT="AlmaLinux"
REDHAT_SUPPORT_PRODUCT_VERSION="8.10"
SUPPORT_END=2029-06-01
```

- Kernel (e.g. `uname -a`):
```
Linux hostname 4.18.0-553.27.1.el8_10.x86_64 #1 SMP Tue Nov 5 04:50:16 EST 2024 x86_64 x86_64 x86_64 GNU/Linu
```
- Object storage (cloud provider and region, or self maintained):
Amazon S3. 
- Metadata engine info (version, cloud provider managed or self maintained):
Redis on Amazon EC2, self maintained. Version 6.2.7
- Network connectivity (JuiceFS to metadata engine, JuiceFS to object storage):
Amazon EC2 IP networking, and networking to Amazon S3.

**Comment by jiefenghuang** [comment]
fuse option like writeback_cache cannot change when remount, you can check the logs like "<INFO>: different options, mount on top of it".
