### ISSUE TITLE
juicefs.umask configuration does not work

### ISSUE THREAD

**Issue by kyungwan-nam** [juicedata/juicefs#5336]
**What happened**: ``juicefs.umask`` does not work

**What you expected to happen**:

I set ``juicefs.umask``  as ``0022`` in ``core-site.xml``
https://juicefs.com/docs/community/hadoop_java_sdk#other-configurations
It should be ``644`` (``rw-r--r--``) when I upload a file to the JuiceFS using ``hdfs dfs -put``. but, it doesn't work. 
It works only if I set the ``fs.permissions.umask-mode`` 

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**

**Environment**:
- JuiceFS version (use `juicefs --version`) or Hadoop Java SDK version: 
- Cloud provider or hardware configuration running JuiceFS:
- OS (e.g `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Object storage (cloud provider and region, or self maintained):
- Metadata engine info (version, cloud provider managed or self maintained):
- Network connectivity (JuiceFS to metadata engine, JuiceFS to object storage):
- Others:

**Comment by kyungwan-nam** [comment]
``fs.permissions.umask-mode`` should be set as ``juicefs.umask``. 
when a file is created, the permission will be decided by ``fs.permissions.umask-mode``
https://github.com/apache/hadoop/blob/trunk/hadoop-common-project/hadoop-common/src/main/java/org/apache/hadoop/fs/FileSystem.java#L1233
PR: https://github.com/juicedata/juicefs/pull/5337

**Comment by tangyoupeng** [comment]
fs.permissions.umask-mode was applied before juicefs.umask takes effect when use hdfs shell command

**Comment by tangyoupeng** [comment]
Thanks, i missed the pr. Already merged.

**Comment by kyungwan-nam** [comment]
@tangyoupeng 
Thank you!
