### ISSUE TITLE
juicefs sync 从hdfs集群同步数据到jfs失败

### ISSUE THREAD

**Issue by ming-bug** [juicedata/juicefs#5347]
按照社区版文档同步，命令如下：
`myfs=redis://:test@mymaster,192.168.0.66,192.168.0.189:26379/3
juicefs sync hdfs://hacluster/lodcode/ jfs://myfs/ --ignore-existing -p 16`
其中redis配置为哨兵模式META-URL
报错如下：
![image](https://github.com/user-attachments/assets/f9f0aeb1-dc5e-4f7a-8091-a2d498cc3370)

**Comment by zhijian-pro** [comment]
看起来 myfs 环境变量没有生效。可以试试先 `export myfs=redis://:test@mymaster,192.168.0.66,192.168.0.189:26379/3` 然后 `juicefs sync hdfs://hacluster/lodcode/ jfs://myfs/ --ignore-existing -p 16`

**Comment by ming-bug** [comment]
> 看起来 myfs 环境变量没有生效。可以试试先 `export myfs=redis://:test@mymaster,192.168.0.66,192.168.0.189:26379/3` 然后 `juicefs sync hdfs://hacluster/lodcode/ jfs://myfs/ --ignore-existing -p 16`

谢谢，export有用，可以正常同步了
