### ISSUE TITLE
Different behavior of "sudo ls" on JuiceFS mount point 

### ISSUE THREAD

**Issue by anysql** [juicedata/juicefs#5375]
**What happened**:
One local file system, when we run "sudo ls", it will list the files of current directory, for example:

loufangxin@loufangxindeMBP juicefs % sudo ls
Password:
LICENSE			jfs			start.sh
README.md		juicefs
README_CN.md		mysql_meta_diff.txt

On Juice file system, get different result as following

loufangxin@loufangxindeMBP jfs % ls
AUL8LIC.DAT	AULDICT		SYSTEM01.dbf	aul8_macos.bin	db.txt
loufangxin@loufangxindeMBP jfs % sudo ls
ls: .: No such file or directory
loufangxin@loufangxindeMBP jfs % pwd
/Users/loufangxin/JuiceData/juicefs/jfs

**What you expected to happen**:

return the same result as "ls" command

**How to reproduce it (as minimally and precisely as possible)**:

See the above steps.

**Anything else we need to know?**

**Environment**:
- JuiceFS version (use `juicefs --version`) or Hadoop Java SDK version:
- Cloud provider or hardware configuration running JuiceFS:
- OS (e.g `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Object storage (cloud provider and region, or self maintained):
- Metadata engine info (version, cloud provider managed or self maintained):
- Network connectivity (JuiceFS to metadata engine, JuiceFS to object storage):
- Others:

loufangxin@loufangxindeMBP juicefs % ./juicefs --version
juicefs version 1.2.2+2024-12-02.92e1db2

**Comment by anysql** [comment]
Just found always mounted by "nosuid" option, maybe due to this option?

**Comment by davies** [comment]
By default, root can not access a mount point by other user  without option `--allow-other`, so this is expected.

**Comment by zhijian-pro** [comment]
mac version compatibility with fuse can also cause this issue, which does not exist under 15.2 (24C101) and fuse 4.8.3
