### ISSUE TITLE
<FATAL>: LOADING Redis is loading the dataset in memory.

### ISSUE THREAD

**Issue by zhoucheng361** [juicedata/juicefs#5391]
**What happened**:
redis.bak is the file dumped with ./juicefs dump --binary.
root@iZj6c7pdf6pza949nltqbiZ:~/juicefs# ./juicefs load redis://localhost/1 redis.bak --binary
2024/12/18 15:33:53.148225 juicefs[24572] <INFO>: Meta address: redis://localhost/1 [NewClient@interface.go:512]
2024/12/18 15:34:15.202065 juicefs[24572] <WARNING>: AOF is not enabled, you may lose data if Redis is not shutdown properly. [checkRedisInfo@info.go:84]
2024/12/18 15:34:35.092151 juicefs[24572] <ERROR>: Ping redis: LOADING Redis is loading the dataset in memory [checkServerConfig@redis.go:3625]
2024/12/18 15:35:15.483952 juicefs[24572] <FATAL>: LOADING Redis is loading the dataset in memory [main@main.go:31]
**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**

**Environment**:
- JuiceFS version (use `juicefs --version`) or Hadoop Java SDK version:
- Cloud provider or hardware configuration running JuiceFS:
- OS (e.g `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Object storage (cloud provider and region, or self maintained):
- Metadata engine info (version, cloud provider managed or self maintained):
- Network connectivity (JuiceFS to metadata engine, JuiceFS to object storage):
- Others:

**Comment by davies** [comment]
Redis is not ready to serve requests, we don't have anything to do.
