### ISSUE TITLE
Why juicefs client communicate with object store with https protocol instead of s3

### ISSUE THREAD

**Issue by gtarcoder** [juicedata/juicefs#54]
as the title says, since s3 is a standard protocol for object store, why use https protocol to communicate between juicefs client and object store?

**Comment by davies** [comment]
S3 is an API built on top of HTTP or HTTPS.

**Comment by gtarcoder** [comment]
> S3 is an API built on top of HTTP or HTTPS.

Thanks for the quick response:)
