### ISSUE TITLE
used inode incorrect when load with binary format

### ISSUE THREAD

**Issue by zhoucheng361** [juicedata/juicefs#5411]
**What happened**:
```
root@iZj6c7pdf6pza949nltqbiZ:~/juicefs# ./juicefs load mysql://juicedata:juicedata@(localhost:3306)/test  redis.bin --binary --threads 50
root@iZj6c7pdf6pza949nltqbiZ:~/juicefs# ./juicefs mount mysql://juicedata:juicedata@(localhost:3306)/test  /mysql -d
2024/12/20 14:01:38.864223 juicefs[40392] <INFO>: Meta address: mysql://juicedata:****@(localhost:3306)/test [NewClient@interface.go:512]
2024/12/20 14:01:38.869354 juicefs[40392] <INFO>: Data use file:///var/jfs/myjfs/ [mount@mount.go:635]
2024/12/20 14:01:39.370334 juicefs[40392] <INFO>: OK, myjfs is ready at /mysql [checkMountpoint@mount_unix.go:225]
root@iZj6c7pdf6pza949nltqbiZ:~/juicefs# df -i /mysql
Filesystem       Inodes IUsed    IFree IUse% Mounted on
JuiceFS:myjfs  10485760     0 10485760    0% /mysql
```

**What you expected to happen**:
IUsed shoudl not be 0.

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**

**Environment**:
- JuiceFS version (use `juicefs --version`) or Hadoop Java SDK version:
- Cloud provider or hardware configuration running JuiceFS:
- OS (e.g `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Object storage (cloud provider and region, or self maintained):
- Metadata engine info (version, cloud provider managed or self maintained):
- Network connectivity (JuiceFS to metadata engine, JuiceFS to object storage):
- Others:

**Comment by jiefenghuang** [comment]
same as #5396
