### ISSUE TITLE
config update not take effect in 6 second.

### ISSUE THREAD

**Issue by zhoucheng361** [juicedata/juicefs#5447]
**What happened**:
https://github.com/juicedata/juicefs/actions/runs/12496360301/job/34868010707

Reproduce steps：
```
root@bench-01:~/juicefs# df /jfs && ./juicefs config sqlite3://test.db --capacity 5 && sleep 6s && df /jfs
Filesystem     1K-blocks    Used Available Use% Mounted on
JuiceFS:myjfs    4194304 1048576   3145728  25% /jfs
2024/12/26 17:15:01.652726 juicefs[1124015] <INFO>: Meta address: sqlite3://test.db [NewClient@interface.go:511]
  capacity: 4.0 GiB -> 5.0 GiB
Filesystem     1K-blocks    Used Available Use% Mounted on
JuiceFS:myjfs    4194304 1048576   3145728  25% /jfs
```

**What you expected to happen**:
config update should take effect in 6 second as before.

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**

**Environment**:
- JuiceFS version (use `juicefs --version`) or Hadoop Java SDK version:
- Cloud provider or hardware configuration running JuiceFS:
- OS (e.g `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Object storage (cloud provider and region, or self maintained):
- Metadata engine info (version, cloud provider managed or self maintained):
- Network connectivity (JuiceFS to metadata engine, JuiceFS to object storage):
- Others:

**Comment by zhijian-pro** [comment]
This is a normal behavior, the default refresh time is 12 seconds. '--heartbeat' can adjust the behavior.

**Comment by zhoucheng361** [comment]
I already set --heartbeat=5

**Comment by zhoucheng361** [comment]
works for heartbeat=3s and sleep 6s to wait it to take effect.
