### ISSUE TITLE
Unstable transaction behavior possible for roTxn call

### ISSUE THREAD

**Issue by anysql** [juicedata/juicefs#5457]
**What would you like to be added**:

As session may be inherit from Context, it may be in middle of an active transaction, we should not rollback the transaction or retry the transaction, only the caller can make the decision.

func (m *dbMeta) roTxn(ctx context.Context, f func(s *xorm.Session) error) error {
        start := time.Now()
        defer func() { m.txDist.Observe(time.Since(start).Seconds()) }()
        var s *xorm.Session
        if v := ctx.Value(txSessionKey{}); v != nil {
                s = v.(*xorm.Session) // The caller should rollback or retry the transaction, not others
        } else {
                s = m.db.NewSession()
                defer s.Close()
        }

**Why is this needed**:

Make roTxn open a new session always.

**Comment by jiefenghuang** [comment]
removed in 2e734c9b54819026f28fa3a01bb72e4e6f256e04
