### ISSUE TITLE
Add disaster recovery documentation

### ISSUE THREAD

**Issue by njoerd114** [juicedata/juicefs#560]
**What would you like to be added**:
- Documentation on how to restore in case of a redis restore

**Why is this needed**:
- While the docs state to keep redis backups and that it's absolutely required to keep the metadata in case of issues, theres no documentation on how to deal with scenarios like this.

**Comment by davies** [comment]
@njoerd114 We just added a document on logical backup and restore for metadata.

For Redis, you can also use existing tools to backup Redis and restore it in case of disaster, once the Redis is restored, you can continue to mount it with the new `REDIS-URL`. 

`juicefs fsck` is also useful the verify that all the data are consistent after recovery.
