### ISSUE TITLE
add more comments to incomprehensible or core struct and logic

### ISSUE THREAD

**Issue by meilihao** [juicedata/juicefs#563]
I can't understand [`(*redisMeta) CopyFileRange`](https://github.com/juicedata/juicefs/blob/main/pkg/meta/redis.go#L2094), because i don't understand the meaning of [slice](https://github.com/juicedata/juicefs/blob/560ca656105571bd339e885c639c737ec83508fe/pkg/meta/slice.go#L20). 

What is the difference between slice.off and slice.pos?
What is the difference between slice.size and slice.len?

It is possible to add documentation for the core code logic details, not only the arch documentation?

**Comment by davies** [comment]
Sure, we are working on the naming and docs.
