### ISSUE TITLE
Helm Chart for K8S deploy

### ISSUE THREAD

**Issue by swartz-k** [juicedata/juicefs#60]
**What would you like to be added**:
Helm Chart for deploy juicefs in kubernetes

**Why is this needed**:
In my situation, I want use Chart for easily deploy and upgrade.
If possible, I can do something about that.

**Comment by davies** [comment]
@swartz-k The CSI driver is out , please try it : https://github.com/juicedata/juicefs-csi-driver

**Comment by swartz-k** [comment]
Thanks. On th way, about tomorrow.
