### ISSUE TITLE
rewrite file with dd cmd, number of objects duplicated in s3 backend

### ISSUE THREAD

**Issue by whans** [juicedata/juicefs#600]
**What happened**:
step one
dd if=/dev/zero of=/data/test bs=16M count=1000

replace step one
Number of objects duplicated in s3 backend

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:
step one
dd if=/dev/zero of=/data/test bs=16M count=1000

replace step one
**Anything else we need to know?**

**Environment**:
juicefs version 0.16-dev (2021-07-06 6f607a0)
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=18.04
DISTRIB_CODENAME=bionic
DISTRIB_DESCRIPTION="Ubuntu 18.04.5 LTS"
Linux 4.15.0-140-generic #144-Ubuntu
mysql meta engine

- JuiceFS version (use `./juicefs --version`) or Hadoop Java SDK version:
- Cloud provider or hardware configuration running JuiceFS:
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Object storage (cloud provider and region):
- Redis info (version, cloud provider managed or self maintained):
- Network connectivity (JuiceFS to Redis, JuiceFS to object storage):
- Others:

**Comment by davies** [comment]
@whans JuiceFS does not delete the overwritten blocks immediately, which will be compacted later or garbage collected by hand.

**Comment by whans** [comment]
@davies ok thanks 
with juicefs gc --delete it's work.
