### ISSUE TITLE
Optimize the implementation of KV transactions

### ISSUE THREAD

**Issue by Sandy4999** [juicedata/juicefs#617]
**What would you like to be added**:
Current implementation is quite preliminary, need optimization

**Why is this needed**:
For better performance, and more elegant code style

**Comment by davies** [comment]
We have enable the 1pc for TiKV, considering Async Commit also.

**Comment by Sandy4999** [comment]
|      | 1pc only | 1pc + async |
| ---- | ----- | ---------- |
| mkdir | 2174 | 1990 (0.92) |
| mvdir | 2315 | 2175 (0.94) |
| rmdir | 2469 | 2358 (0.96) |
| readdir_10 | 1087 | 1028 (0.95) |
| readdir_1k | 6688 | 6707 (1.00) |
| mknod | 2187 | 1973 (0.90) |
| create | 2118 | 2041 (0.96) |
| rename | 2328 | 2178 (0.94) |
| unlink | 2354 | 2211 (0.94) |
| lookup | 634 | 603 (0.95) |
| getattr | 322 | 303 (0.94) |
| setattr | 1883 | 1747 (0.93) |
| access | 317 | 302 (0.95) |
| setxattr | 1659 | 1542 (0.93) |
| getxattr | 314 | 304 (0.97) |
| removexattr | 2007 | 1913 (0.95) |
| listxattr_1 | 316 | 306 (0.97) |
| listxattr_10 | 334 | 327 (0.98) |
| link | 2117 | 1991 (0.94) |
| symlink | 2141 | 1995 (0.93) |
| newchunk | 1 | 1 (1.00) |
| write | 2335 | 2103 (0.90) |
| read_1 | 1 | 0 (0.00) |
| read_10 | 1 | 0 (0.00) |

**Comment by davies** [comment]
enabled async commit in #643
