### ISSUE TITLE
Connect juicefs to ceph object store without formatting volume?

### ISSUE THREAD

**Issue by gtarcoder** [juicedata/juicefs#64]
The quick start section in https://github.com/juicedata/juicefs says we should format the volume before to do anything, so I am wondering two questions:
1. can we use juicefs client to communicate with an existing object store and access those already existing data?
2. if I format volume using an existing object store, will the existing data on that object store be erased?

**Comment by davies** [comment]
Good question. 

> 1. can we use juicefs client to communicate with an existing object store and access those already existing data?

No. JuiceFS use a block based format to access object store, so existing object can't be accessed. You need to copy it to JuiceFS, so use other solution, for example, S3FS, or Rclone.

> 2. if I format volume using an existing object store, will the existing data on that object store be erased?

The format will initialize redis db, and check the permission on object store, just that. Existing objects will be TOUCHed.

**Comment by gtarcoder** [comment]
> Good question.
> 
> > 1. can we use juicefs client to communicate with an existing object store and access those already existing data?
> 
> No. JuiceFS use a block based format to access object store, so existing object can't be accessed. You need to copy it to JuiceFS, so use other solution, for example, S3FS, or Rclone.
> 
> > 1. if I format volume using an existing object store, will the existing data on that object store be erased?
> 
> The format will initialize redis db, and check the permission on object store, just that. Existing objects will NOT be TOUCHed.

Thanks for quick response
