### ISSUE TITLE
jfs_lseek doesn't work as expected when the whence = 2(move position of file descriptor relative to the end of the file)

### ISSUE THREAD

**Issue by HugoAhoy** [juicedata/juicefs#646]
**What happened**:

Function `long jfs_lseek(long pid, int fd, long pos, int whence)` seems produce wrong behavior when the `whence = 2`, which means move position of file descriptor relative to the end of the file.

If we use `jfs_open` open a file and write something by `jfs_write`. Then we called `jfs_lseek(pid, fd, 0, 2)`. But it doesn't move position of file descriptor to the end of the modified file, but move to the position of the end position of the unmodified file(the file length before `jfs_write()`).

We suspected this may be caused by [this line](https://github.com/juicedata/juicefs/blob/dffd1eff9f5069b9691cfcf613a66f7bde31e754/pkg/fs/fs.go#L762). It seems that `FileStat.info` won't be updated even if the something was written to the file. So `FileStat.info.Size()` will always return the same value, which is equal to the file size when the file is once opened. 

**What you expected to happen**:

`jfs_lseek(pid, fd, 0, 2)` will move position of file descriptor to the end of the opened file, no matter it's modified or not.

**How to reproduce it (as minimally and precisely as possible)**:

```python
# test 1
def test_lseek_end1(jfs, filename):
    CONTENT = b"hello"
    jfs.create(filename, 0o777)
    fd = jfs.open(filename, os.O_WRONLY)
    length = jfs.write(fd, CONTENT)
    assert length == len(CONTENT)

    # here raises Assertion Error, where 0 == 5
    assert jfs.lseek(fd, 0, os.SEEK_END) == length


# test 2
def test_lseek_end2(jfs, filename):
    CONTENT = b"hello"
    jfs.create(filename, 0o777)
    fd = jfs.open(filename, os.O_WRONLY)
    length = jfs.write(fd, CONTENT)
    jfs.close(fd)

    fd = jfs.open(filename, os.O_WRONLY | os.O_APPEND)
    assert jfs.lseek(fd, 0, os.SEEK_END) == length

    jfs.write(fd, CONTENT)
    assert jfs.lseek(fd, 0, os.SEEK_END) == length

    # here raises Assertion Error, where 5 == (2*5)
    assert jfs.lseek(fd, 0, os.SEEK_END) == 2 * length

```
**Anything else we need to know?**

1. The code snippet is written in Python, but the function is an easy python wrap of functions in `libjfs.so`. Here may I explain it.  
`jfs.XXX(args...)`(XXX is the function name) wraps the `jfs_XXX(pid, handle, args...)` or `jfs_XXX(pid, fd, args...)`. 
For example, `jfs.write(fd: int, content: bytes)` actually convert the `content` to a `Pointer buf` and call `jfs_writer(pid, fd, buf)`.  

2. We tested 2 versions of `libjfs.so` include `14.0`, `15.2`, the results are both wrong.

**Environment**:
- JuiceFS version (use `./juicefs --version`) or Hadoop Java SDK version:
```
juicefs version 0.12.1 (2021-04-15T08:18:25Z 7b4df23)
```
- Cloud provider or hardware configuration running JuiceFS:
- OS (e.g: `cat /etc/os-release`):
```
NAME="Ubuntu"
VERSION="18.04.3 LTS (Bionic Beaver)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 18.04.3 LTS"
VERSION_ID="18.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=bionic
UBUNTU_CODENAME=bionic
```
- Kernel (e.g. `uname -a`):
```
Linux determined-pare 4.15.0-55.60 #4 SMP Mon Mar 30 12:42:28 HKT 2020 x86_64 x86_64 x86_64 GNU/Linux
```
- Object storage (cloud provider and region):
- Redis info (version, cloud provider managed or self maintained):
- Network connectivity (JuiceFS to Redis, JuiceFS to object storage):
- Others:

**Comment by davies** [comment]
@HugoAhoy this should be fixed  by 8e5155d, please check with latest main branch, thanks!
