### ISSUE TITLE
Compare JuiceFS with LakeFS

### ISSUE THREAD

**Issue by Suave** [juicedata/juicefs#734]
[LakeFS](https://lakefs.io) - Atomic versioned data lake. Transform your object storage into a Git-like repository, lakeFS enables you to manage your data lake the way you manage your code. Run parallel pipelines for experimentation and CI/CD for your data.

What's different with JuiceFS?

**Comment by Sandy4999** [comment]
Simple conclusion:
- LakeFS: NOT POSIX-compatible. Users have to interact with it through certain CLIs or APIs. The usage pattern is more like object storage.
- JuiceFS: POSIX-compatible. Users can **mount** it and operate files through system calls. The usage pattern is more like local file systems.
