### ISSUE TITLE
Unimplemented opcode POLL

### ISSUE THREAD

**Issue by diluga** [juicedata/juicefs#740]
juicefs version 0.17 (2021-08-13 c49271a)
OS version：debian 4.9+Linux   4.19.0-16-amd64 #1 SMP Debian 4.19.181-1 (2021-03-19) x86_64 GNU/Linux

first：run juicefs with command：./juicefs mount --max-uploads=150 --io-retries=20  redis://127.0.0.1:6379/8 /mnt/jfs --debug

second: run golang application to write some to file：

```
package main

import (
    "os"
    "fmt"
)
func main() {
    fname := "/mnt/jfs/t1.txt"
    f, err := os.OpenFile(fname, os.O_CREATE|os.O_RDWR|os.O_APPEND, os.ModeAppend|os.ModePerm)
    if err != nil {
        fmt.Println(err)
    }
    f.WriteString("test")
    f.Close()
}
``` 

and got clinet error log "Unimplemented opcode POLL" below:

```
2021-08-17 15:42:49.230746 I | Unimplemented opcode POLL
2021/08/17 15:42:49.238966 juicefs[2994872] <DEBUG>: PUT chunks/0/321/321463_0_4 (%!s(<nil>), 0.008s)
```

it only happend when first mount /mnt/jfs。

**Comment by davies** [comment]
@diluga The logging level is INFO, and it says JuiceFS has not implement the POLL call, it's OK for most of the use cases.
