### ISSUE TITLE
Reduce CPU cost when using S3, MinIO. etc.

### ISSUE THREAD

**Issue by Sandy4999** [juicedata/juicefs#748]
When uploading objects to S3, it costs a lot of CPU resource to calculate sha256. We'd better take a look at the SDK to see if the over-cost could be avoid.
Also users report that MinIO consumes huge CPU as well, which is probably the same issue since we use aws-sdk to connect with MinIO.

**Comment by whans** [comment]
# fix from https://github.com/aws/aws-sdk-go/pull/3953

// import "github.com/aws/aws-sdk-go/aws/session"
// import "github.com/aws/aws-sdk-go/aws/request"

sess, err := session.NewSession()

sess.Handlers.Build.PushFront(func (r *request.Request) {
    if op := r.Operation.Name; r.ClientInfo.ServiceID != "S3" || !(op == "PutObject" || op == "UploadPart" ){
        return
    }

    if len(r.HTTPRequest.Header.Get("X-Amz-Content-Sha256")) != 0 {
        return
    }

    r.HTTPRequest.Header.Set("X-Amz-Content-Sha256", "UNSIGNED-PAYLOAD")
})

// create API clients, and have S3 PutObject and UploadPart automatically use unsigned payload.

**Comment by Sandy4999** [comment]
@whans Cool, thanks for the information!
