### ISSUE TITLE
meta/tikv: Panic when s3 connection refused

### ISSUE THREAD

**Issue by whans** [juicedata/juicefs#749]
caused by: Put "http://10.100.19.200:9000/bigtest0/jfsbigtest0/chunks/0/107/107004_0_16777216": dial tcp 10.100.19.200:9000: connect: connection refused (try 2)
2021/08/19 17:02:40.124499 juicefs[5551] <WARNING>: upload chunks/0/107/107004_1_16777216: RequestError: send request failed
caused by: Put "http://10.100.19.200:9000/bigtest0/jfsbigtest0/chunks/0/107/107004_1_16777216": dial tcp 10.100.19.200:9000: connect: connection refused (try 2)
2021/08/19 17:02:40.154833 juicefs[5551] <WARNING>: upload chunks/0/107/107003_3_16777216: RequestError: send request failed
caused by: Put "http://10.100.19.200:9000/bigtest0/jfsbigtest0/chunks/0/107/107003_3_16777216": dial tcp 10.100.19.200:9000: connect: connection refused (try 2)
2021/08/19 17:02:40.176505 juicefs[5551] <WARNING>: upload chunks/0/107/107004_3_16777216: RequestError: send request failed
caused by: Put "http://10.100.19.200:9000/bigtest0/jfsbigtest0/chunks/0/107/107004_3_16777216": dial tcp 10.100.19.200:9000: connect: connection refused (try 2)
2021/08/19 17:02:40.178509 juicefs[5551] <WARNING>: upload chunks/0/107/107004_2_16777216: RequestError: send request failed
caused by: Put "http://10.100.19.200:9000/bigtest0/jfsbigtest0/chunks/0/107/107004_2_16777216": dial tcp 10.100.19.200:9000: connect: connection refused (try 2)
2021/08/19 17:02:44.293334 juicefs[5551] <WARNING>: upload chunks/0/107/107001_2_16777216: RequestError: send request failed
caused by: Put "http://10.100.19.200:9000/bigtest0/jfsbigtest0/chunks/0/107/107001_2_16777216": dial tcp 10.100.19.200:9000: connect: connection refused (try 3)
2021/08/19 17:02:44.369792 juicefs[5551] <WARNING>: upload chunks/0/107/107001_3_16777216: RequestError: send request failed
caused by: Put "http://10.100.19.200:9000/bigtest0/jfsbigtest0/chunks/0/107/107001_3_16777216": dial tcp 10.100.19.200:9000: connect: connection refused (try 3)
2021/08/19 17:02:44.394803 juicefs[5551] <WARNING>: upload chunks/0/107/107003_2_16777216: RequestError: send request failed
caused by: Put "http://10.100.19.200:9000/bigtest0/jfsbigtest0/chunks/0/107/107003_2_16777216": dial tcp 10.100.19.200:9000: connect: connection refused (try 3)
2021/08/19 17:02:44.403039 juicefs[5551] <WARNING>: upload chunks/0/107/107003_0_16777216: RequestError: send request failed
caused by: Put "http://10.100.19.200:9000/bigtest0/jfsbigtest0/chunks/0/107/107003_0_16777216": dial tcp 10.100.19.200:9000: connect: connection refused (try 3)
2021/08/19 17:02:44.415271 juicefs[5551] <WARNING>: upload chunks/0/107/107001_0_16777216: RequestError: send request failed
caused by: Put "http://10.100.19.200:9000/bigtest0/jfsbigtest0/chunks/0/107/107001_0_16777216": dial tcp 10.100.19.200:9000: connect: connection refused (try 3)
2021/08/19 17:02:44.446457 juicefs[5551] <WARNING>: upload chunks/0/107/107001_1_16777216: RequestError: send request failed
caused by: Put "http://10.100.19.200:9000/bigtest0/jfsbigtest0/chunks/0/107/107001_1_16777216": dial tcp 10.100.19.200:9000: connect: connection refused (try 3)
2021/08/19 17:02:44.475872 juicefs[5551] <WARNING>: upload chunks/0/107/107004_1_16777216: RequestError: send request failed
caused by: Put "http://10.100.19.200:9000/bigtest0/jfsbigtest0/chunks/0/107/107004_1_16777216": dial tcp 10.100.19.200:9000: connect: connection refused (try 3)
2021/08/19 17:02:44.510447 juicefs[5551] <WARNING>: upload chunks/0/107/107003_1_16777216: RequestError: send request failed
caused by: Put "http://10.100.19.200:9000/bigtest0/jfsbigtest0/chunks/0/107/107003_1_16777216": dial tcp 10.100.19.200:9000: connect: connection refused (try 3)
2021/08/19 17:02:44.521198 juicefs[5551] <WARNING>: upload chunks/0/107/107004_0_16777216: RequestError: send request failed
caused by: Put "http://10.100.19.200:9000/bigtest0/jfsbigtest0/chunks/0/107/107004_0_16777216": dial tcp 10.100.19.200:9000: connect: connection refused (try 3)
2021/08/19 17:02:44.544587 juicefs[5551] <WARNING>: upload chunks/0/107/107004_2_16777216: RequestError: send request failed
caused by: Put "http://10.100.19.200:9000/bigtest0/jfsbigtest0/chunks/0/107/107004_2_16777216": dial tcp 10.100.19.200:9000: connect: connection refused (try 3)
2021/08/19 17:02:44.558376 juicefs[5551] <WARNING>: upload chunks/0/107/107003_3_16777216: RequestError: send request failed
caused by: Put "http://10.100.19.200:9000/bigtest0/jfsbigtest0/chunks/0/107/107003_3_16777216": dial tcp 10.100.19.200:9000: connect: connection refused (try 3)
2021/08/19 17:02:44.591641 juicefs[5551] <WARNING>: upload chunks/0/107/107004_3_16777216: RequestError: send request failed
caused by: Put "http://10.100.19.200:9000/bigtest0/jfsbigtest0/chunks/0/107/107004_3_16777216": dial tcp 10.100.19.200:9000: connect: connection refused (try 3)
2021/08/19 17:02:54.491627 juicefs[5551] <INFO>: slow operation: flush (119): OK <16.140475>
panic: 25

goroutine 906921 [running]:
github.com/juicedata/juicefs/pkg/meta.readSliceBuf(0xc0ee5e5140, 0x19, 0x20, 0xe, 0xc0ee5e5140, 0x19)
        /go/src/github.com/juicedata/juicefs/pkg/meta/slice.go:115 +0x1f6
github.com/juicedata/juicefs/pkg/meta.(*kvMeta).compactChunk(0xc000576000, 0xa, 0xaa)
        /go/src/github.com/juicedata/juicefs/pkg/meta/tkv.go:2153 +0x1f2
github.com/juicedata/juicefs/pkg/meta.(*kvMeta).compactChunk.func3(0xc000576000, 0xa, 0xaa)
        /go/src/github.com/juicedata/juicefs/pkg/meta/tkv.go:2223 +0x53
created by github.com/juicedata/juicefs/pkg/meta.(*kvMeta).compactChunk
        /go/src/github.com/juicedata/juicefs/pkg/meta/tkv.go:2220 +0x9ce

**What happened**:

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**

**Environment**:
- JuiceFS version (use `./juicefs --version`) or Hadoop Java SDK version:
- Cloud provider or hardware configuration running JuiceFS:
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Object storage (cloud provider and region):
- Redis info (version, cloud provider managed or self maintained):
- Network connectivity (JuiceFS to Redis, JuiceFS to object storage):
- Others:

**Comment by davies** [comment]
What's the version of TiKV? The data retrieved from TiKV is malformed, we are looking into that.

**Comment by whans** [comment]
tikv-v5.1.1-linux-amd64

**Comment by davies** [comment]
@whans How can you reproduce this? If possible, you can add a line the dump the corrupt value from TiKV when the length is not expected, that will help us to find the root cause.

**Comment by whans** [comment]
I will trying to get more info to find the root cause

**Comment by davies** [comment]
@whans @Sandy4999 found the bug, and #759 will fix that.
