### ISSUE TITLE
Measure code coverage by test

### ISSUE THREAD

**Issue by suzaku** [juicedata/juicefs#75]
**What would you like to be added**:

Measure code coverage by test.

**Why is this needed**:

Code coverage is not perfect, but it's a reasonably good metric for quality.

**Comment by davies** [comment]
Most of the code is covered by integration test, can we collect those?

**Comment by suzaku** [comment]
IMHO, it makes more sense to measure the coverage of unit tests, which usually verify more fine grained behaviors in modules not exposed in the user facing layer.

**Comment by zyfjeff** [comment]
We need to integrate coverage into GitHub Workflow.
