### ISSUE TITLE
Panic by unlock of unlocked mutex

### ISSUE THREAD

**Issue by whans** [juicedata/juicefs#750]
2021/08/19 17:15:11.811182 juicefs[9396] <INFO>: Meta address: tikv://10.100.19.200:2379,10.100.19.201:2379,10.100.19.202:2379,10.100.19.203:2379,10.100.19.204:2379,10.100.19.205:2379,10.100.19.206:2379,10.100.19.207:2379,10.100.19.208:2379/jfsbigtest0
[2021/08/19 17:15:11.811 +08:00] [INFO] [client.go:214] ["[pd] create pd client with endpoints"] [pd-address="[10.100.19.200:2379,10.100.19.201:2379,10.100.19.202:2379,10.100.19.203:2379,10.100.19.204:2379,10.100.19.205:2379,10.100.19.206:2379,10.100.19.207:2379,10.100.19.208:2379]"]
[2021/08/19 17:15:11.814 +08:00] [INFO] [base_client.go:346] ["[pd] switch leader"] [new-leader=http://10.100.19.205:2379] [old-leader=]
[2021/08/19 17:15:11.814 +08:00] [INFO] [base_client.go:126] ["[pd] init cluster id"] [cluster-id=6994716718439116526]
[2021/08/19 17:15:11.814 +08:00] [INFO] [client.go:238] ["[pd] create tso dispatcher"] [dc-location=global]
2021/08/19 17:15:11.820879 juicefs[9396] <INFO>: Data use 10.100.19.200:9000jfsbigtest0/
2021/08/19 17:15:11.821115 juicefs[9396] <INFO>: Disk cache (/var/jfsCache/a4814b94-c63d-4b3d-8c6e-e4248f466556/): capacity (1024 MB), free ratio (10%), max pending pages (75)
2021/08/19 17:15:11.866469 juicefs[9425] <INFO>: Meta address: tikv://10.100.19.200:2379,10.100.19.201:2379,10.100.19.202:2379,10.100.19.203:2379,10.100.19.204:2379,10.100.19.205:2379,10.100.19.206:2379,10.100.19.207:2379,10.100.19.208:2379/jfsbigtest0
[2021/08/19 17:15:11.866 +08:00] [INFO] [client.go:214] ["[pd] create pd client with endpoints"] [pd-address="[10.100.19.200:2379,10.100.19.201:2379,10.100.19.202:2379,10.100.19.203:2379,10.100.19.204:2379,10.100.19.205:2379,10.100.19.206:2379,10.100.19.207:2379,10.100.19.208:2379]"]
[2021/08/19 17:15:11.870 +08:00] [INFO] [base_client.go:346] ["[pd] switch leader"] [new-leader=http://10.100.19.205:2379] [old-leader=]
[2021/08/19 17:15:11.870 +08:00] [INFO] [base_client.go:126] ["[pd] init cluster id"] [cluster-id=6994716718439116526]
[2021/08/19 17:15:11.870 +08:00] [INFO] [client.go:238] ["[pd] create tso dispatcher"] [dc-location=global]
2021/08/19 17:15:11.879519 juicefs[9425] <INFO>: Data use 10.100.19.200:9000jfsbigtest0/
2021/08/19 17:15:11.879872 juicefs[9425] <INFO>: Disk cache (/var/jfsCache/a4814b94-c63d-4b3d-8c6e-e4248f466556/): capacity (1024 MB), free ratio (10%), max pending pages (75)
2021/08/19 17:15:11.905995 juicefs[9425] <INFO>: Mounting volume jfsbigtest0 at /mnt/jfs2 ...
2021/08/19 17:16:11.917070 juicefs[9425] <INFO>: cleanup session 10: %!s(<nil>)
fatal error: sync: unlock of unlocked mutex

goroutine 483122 [running]:
runtime.throw(0x2bd596a, 0x1e)
        /usr/lib/go-1.16/src/runtime/panic.go:1117 +0x72 fp=0xc003735bd8 sp=0xc003735ba8 pc=0x44a0f2
sync.throw(0x2bd596a, 0x1e)
        /usr/lib/go-1.16/src/runtime/panic.go:1103 +0x35 fp=0xc003735bf8 sp=0xc003735bd8 pc=0x47f475
sync.(*Mutex).unlockSlow(0xc000d21110, 0xffffffff)
        /usr/lib/go-1.16/src/sync/mutex.go:196 +0xd8 fp=0xc003735c20 sp=0xc003735bf8 pc=0x49dd38
sync.(*Mutex).Unlock(0xc000d21110)
        /usr/lib/go-1.16/src/sync/mutex.go:190 +0x48 fp=0xc003735c40 sp=0xc003735c20 pc=0x49dc48
runtime.call16(0x0, 0x2c715b0, 0xc07cd7e228, 0x800000008)
        /usr/lib/go-1.16/src/runtime/asm_amd64.s:550 +0x3e fp=0xc003735c60 sp=0xc003735c40 pc=0x4832be
runtime.reflectcallSave(0xc003735d98, 0x2c715b0, 0xc07cd7e228, 0x8)
        /usr/lib/go-1.16/src/runtime/panic.go:877 +0x58 fp=0xc003735c90 sp=0xc003735c60 pc=0x4496b8
runtime.runOpenDeferFrame(0xc0b7bda180, 0xc07cd7e1e0, 0x0)
        /usr/lib/go-1.16/src/runtime/panic.go:851 +0x62d fp=0xc003735d18 sp=0xc003735c90 pc=0x44938d
panic(0x26bfc40, 0x41c6908)
        /usr/lib/go-1.16/src/runtime/panic.go:965 +0x1b9 fp=0xc003735de0 sp=0xc003735d18 pc=0x449939
github.com/juicedata/juicefs/pkg/meta.readSliceBuf(0xc07cd235c0, 0x19, 0x20, 0xe, 0xc07cd235c0, 0x19)
        /root/src/juicefs/pkg/meta/slice.go:115 +0x1e6 fp=0xc003735e40 sp=0xc003735de0 pc=0x10f0686
github.com/juicedata/juicefs/pkg/meta.(*kvMeta).Read(0xc0007f2000, 0x3124b58, 0x4766100, 0xa, 0xaa, 0xc07f299e30, 0x0)
        /root/src/juicefs/pkg/meta/tkv.go:1829 +0x2ec fp=0xc003735f00 sp=0xc003735e40 pc=0x110e6ec
github.com/juicedata/juicefs/pkg/vfs.(*sliceReader).run(0xc000e0e690)
        /root/src/juicefs/pkg/vfs/reader.go:174 +0x1be fp=0xc003735fd8 sp=0xc003735f00 pc=0x19dacde
runtime.goexit()
        /usr/lib/go-1.16/src/runtime/asm_amd64.s:1371 +0x1 fp=0xc003735fe0 sp=0xc003735fd8 pc=0x484d21
created by github.com/juicedata/juicefs/pkg/vfs.(*fileReader).newSlice
        /root/src/juicefs/pkg/vfs/reader.go:321 +0x245

goroutine 1 [semacquire, 2 minutes]:
sync.runtime_Semacquire(0xc00072cadc)
        /usr/lib/go-1.16/src/runtime/sema.go:56 +0x45
sync.(*WaitGroup).Wait(0xc00072cadc)
        /usr/lib/go-1.16/src/sync/waitgroup.go:130 +0x65
github.com/hanwen/go-fuse/v2/fuse.(*Server).Serve(0xc00072c9a0)
        /root/go/pkg/mod/github.com/juicedata/go-fuse/v2@v2.1.1-0.20210629082323-0ec79f5f0a45/fuse/server.go:379 +0x5f
github.com/juicedata/juicefs/pkg/fuse.Serve(0xc0008de910, 0x0, 0x0, 0x3ff0000000000000, 0x3ff0000000000000, 0x3ff0000000000000, 0x0, 0x50cb51, 0x416a5a0)
        /root/src/juicefs/pkg/fuse/fuse.go:466 +0x49c
main.mount_main(0xc0008de910, 0x3137a18, 0xc0007f2000, 0x31077c0, 0xc00025c1e0, 0xc000798f00)
        /root/src/juicefs/cmd/mount_unix.go:129 +0x25c
main.mount(0xc000798f00, 0x1b, 0x38)
        /root/src/juicefs/cmd/mount.go:233 +0x175e
github.com/urfave/cli/v2.(*Command).Run(0xc000890120, 0xc000798780, 0x0, 0x0)
        /root/go/pkg/mod/github.com/urfave/cli/v2@v2.3.0/command.go:163 +0x4dd
github.com/urfave/cli/v2.(*App).RunContext(0xc0009189c0, 0x3101828, 0xc0000520a8, 0xc000f86380, 0x7, 0x8, 0x0, 0x0)
        /root/go/pkg/mod/github.com/urfave/cli/v2@v2.3.0/app.go:313 +0x810
github.com/urfave/cli/v2.(*App).Run(...)
        /root/go/pkg/mod/github.com/urfave/cli/v2@v2.3.0/app.go:224
main.main()
        /root/src/juicefs/cmd/main.go:99 +0x191c

goroutine 6 [sleep, 2 minutes]:
time.Sleep(0x8bb2c97000)
        /usr/lib/go-1.16/src/runtime/time.go:193 +0xd2
github.com/juicedata/juicefs/pkg/utils.init.0.func2()
        /root/src/juicefs/pkg/utils/alloc.go:77 +0x30
created by github.com/juicedata/juicefs/pkg/utils.init.0
        /root/src/juicefs/pkg/utils/alloc.go:75 +0xbe

**What happened**:

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**

**Environment**:
- JuiceFS version (use `./juicefs --version`) or Hadoop Java SDK version:
- Cloud provider or hardware configuration running JuiceFS:
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Object storage (cloud provider and region):
- Redis info (version, cloud provider managed or self maintained):
- Network connectivity (JuiceFS to Redis, JuiceFS to object storage):
- Others:

**Comment by Sandy4999** [comment]
It looks like some metadata (sliceBuf) stored in TiKV is broken. Any idea about reproducing procedures?

**Comment by davies** [comment]
This is duplicated to #749
