### ISSUE TITLE
Upgrare to Go 1.16/1.17

### ISSUE THREAD

**Issue by TennyZhuang** [juicedata/juicefs#767]
**What would you like to be added**:

Upgrade golang to 1.16 or 1.17

**Why is this needed**:

Currently, this project uses go 1.14, which is end of life in one year ago. Any security patch (both standard library and runtime) will not be picked into 1.14, it’s dangerous to build a production using an unmaintained toolchain.

Go 1.17 is released, and go 1.16 is still under maintenance. Both is ok.

**Comment by davies** [comment]
JuiceFS can be built with Go 1.14+, and you can use Go 1.16 as you wish.

The released binaries are built using Go 1.15 (since 0.15), we can upgrade that to Go 1.16 for JuiceFS 0.17.

Since all the source code and dependencies can be built with Go 1.14, we don't need to change that in go.mod.
