### ISSUE TITLE
Fix problems found by goreport

### ISSUE THREAD

**Issue by davies** [juicedata/juicefs#77]
**What would you like to be added**:

Fix some of the problem found by goreport

**Why is this needed**:

goreport can help us improve code quality.

**Comment by last-saiyan** [comment]
Hii @davies
i wanted to work on this

**Comment by xiaogaozi** [comment]
Do we need set a goal to measure if the report is OK? Like golint reach 80%.

**Comment by davies** [comment]
We have resolved most of them, close it.
