### ISSUE TITLE
JuiceFS CSI plugin for Kubernetes

### ISSUE THREAD

**Issue by chnliyong** [juicedata/juicefs#8]
**What would you like to be added**:
[CSI](https://github.com/container-storage-interface/spec/blob/master/spec.md) plugin for JuiceFS

**Why is this needed**:
As more and more applications are running on Kubernetes, CSI plugin is the de facto form to use third party storage like JuiceFS.

**Comment by FeynmanZhou** [comment]
Cool! I have subscribed to this issue. When the Juice CSI plugin is done, we are going to add support for JuiceFS CSI plugin on [KubeSphere](https://kubesphere.io/) container platform.

**Comment by SeaLife** [comment]
Coolio, i would probably use this with nomad :) Im subscribed too.

**Comment by targyz** [comment]
I found this project [juicefs-csi-driver](https://github.com/juicedata/juicefs-csi-driver)
It seems unmaintained and lack of some features (such as support of on-premise S3-compatible storage services like Minio) but it may be useful for someone.

**Comment by chnliyong** [comment]
> I found this project [juicefs-csi-driver](https://github.com/juicedata/juicefs-csi-driver)
> It seems unmaintained and lack of some features (such as support of on-premise S3-compatible storage services like Minio) but it may be useful for someone.

It's under maintained and our CSI driver will base on it, comming soon.
