### ISSUE TITLE
Use sync.map replace mutex

### ISSUE THREAD

**Issue by zyfjeff** [juicedata/juicefs#83]
**What would you like to be added**:

Use sync.map replace mutex, there are so many lock and unlock operations in our code that it's easy to forget that unlock causes deadlocks. Instead of mutex, use sync.map and atomic variable, Take the following code for example.

[prefetch.go](https://github.com/juicedata/juicefs/blob/main/pkg/chunk/prefetch.go)
[mem_cache.go](https://github.com/juicedata/juicefs/blob/main/pkg/chunk/mem_cache.go)
.....

**Why is this needed**:

**Comment by davies** [comment]
@zyfjeff sync.map could be used replace map, but we still need to make sure updating other counters are atomic.

Usually, `defer l.Unlock()` follower `l.Lock()`, so it's easy to use, and no deadlock at all, so I think this is the simple way to go.
