### ISSUE TITLE
Got an exception when I run bench command without any argument

### ISSUE THREAD

**Issue by Suave** [juicedata/juicefs#859]
when I run 

```
./juicefs bench
2021/09/26 11:04:01.522891 juicefs[58048] <FATAL>: Failed to create /jfs/__juicefs_benchmark_1632625441522789000__: mkdir /jfs: read-only file system
```

**What happened**:

if I run `bench` without any argument, got an exception.

**What you expected to happen**:

show me the help is more friendly.

**Environment**:
- JuiceFS version (use `./juicefs --version`) or Hadoop Java SDK version: v0.17-dev(2021-09-17 01ae8af4)

**Comment by SandyXSD** [comment]
The test path defaults to `/jfs`, which is not explicit.
We may either print a help info log, or remove the default value.

**Comment by SandyXSD** [comment]
```
./juicefs bench
2021/09/26 11:04:01.522891 juicefs[58048] <INFO>: Test path is not specified, using /jfs
2021/09/26 11:04:01.522891 juicefs[58048] <FATAL>: Failed to create /jfs/__juicefs_benchmark_1632625441522789000__: mkdir /jfs: read-only file system
```
like this?
