### ISSUE TITLE
Can JuiceFS be used in Fluid to run in K8s like Alluxio and JindoFS ?

### ISSUE THREAD

**Issue by zhangshuiyong** [juicedata/juicefs#868]

**Comment by zwwhdls** [comment]
Hi @zhangshuiyong , we are working on this. We will propose a PR to fluid project as soon as possible.

**Comment by xiaogaozi** [comment]
Hi @zhangshuiyong, `JuiceFSRuntime` is already supported in Fluid, please refer to the document ([Chinese](https://github.com/fluid-cloudnative/fluid/blob/master/docs/zh/samples/juicefs_runtime.md), [English](https://github.com/fluid-cloudnative/fluid/blob/master/docs/en/samples/juicefs_runtime.md)).
