### ISSUE TITLE
Metrics for JuiceFS

### ISSUE THREAD

**Issue by 201341** [juicedata/juicefs#87]
**What would you like to be added**:
webui for juicefs
**Why is this needed**:
it is easier to monitor the file meta info and s3 usage info for people who don't know how to use redis and s3 client.

**Comment by davies** [comment]
@201341  What does the Web UI should provide? Do you mean some kind of metrics to expose to Prometheus?

**Comment by 201341** [comment]
Yes, If the juicefs can expose to Prometheus, It is better. I want to know the s3 put/get/delete times, or the s3 cost, For file meta, I can get the info through the command "du, df, ls or such ...",  But the command can't get the history info if I want to know how many files are deleted, uploaded
