### ISSUE TITLE
Add Kubernetes Juicefs Operator

### ISSUE THREAD

**Issue by yuchen-sun** [juicedata/juicefs#871]
**What would you like to be added**:
Add an operator to make it easier for juicefs to run in kubernetes.
**Why is this needed**:
The csi driver that currently exists doesn't help users deal with the metadata server and S3 deployment issues, so maybe we can help users deal with these issues together.

**Comment by davies** [comment]
There are already operators for Redis/MySQL/Minio/TiKV, once these are deployed, what's the things missed for JuiceFS?

**Comment by yuchen-sun** [comment]
That's one way to think about it

Thanks @davies
