### ISSUE TITLE
JuiceFS fcntl parallel open-write-close test abnormal

### ISSUE THREAD

**Issue by zzouqb** [juicedata/juicefs#901]
**What happened**:
On A、B  server，installed juicefs 0.17.0,  mounted region buckets and looply executed open-write-close temp.txt test program parallel. (see attachment)
And at the same time, on A、B oepn new session to tail -f temp.txt, A、B shows different data, and differnt with the result by cat temp.txt when interrupt open-write-close manually.

**What you expected to happen**:
on A、B： the result of  tail -f temp.txt and cat temp.txt  should be same.

**How to reproduce it (as minimally and precisely as possible)**:
see attachment: test program

[**Anything](url) else we need to know?**

**Environment**:
- JuiceFS version (use `./juicefs --version`) or Hadoop Java SDK version:JuiceFS 0.17.0
- Cloud provider or hardware configuration running JuiceFS: QingCloud vm
- OS (e.g: `cat /etc/os-release`):Redhat7.9
- Kernel (e.g. `uname -a`):Kernel 3.10.0-1160.el7.x86_64
- Object storage (cloud provider and region):QingStor with  region bucket
- Redis info (version, cloud provider managed or self maintained):QingCLoud standalone redis 5.10.0
- Network connectivity (JuiceFS to Redis, JuiceFS to object storage): all Normal
- Others: fcntl.c //on A, change char buf[256]="BBBBBBBBBB\n"; to char buf[256]="AAAAAAAAAA\n";
#include <stdio.h>
#include <string.h>
#include <unistd.h>
#include <fcntl.h>
 
int main(int argc, char * argv[])
{
        pid_t pid;
        int ret;
        struct flock lock;
        int fd, count=1;
        pid = getpid();
 
		while{1){
        fd = open("/mnt/juicefs-r/temp.txt", O_APPEND | O_RDWR, 0644);
        if( fd < 0 ){
                perror("open file failed\n");
                return -1;
        }
 
        lock.l_len = 0;
        lock.l_start = 0;
        lock.l_type = F_WRLCK;
        lock.l_whence = SEEK_SET;
 
     		char buf[256]="BBBBBBBBBB\n";
        char string[32]="\0";
        printf("%d try to lock file\n", pid);
        ret = fcntl(fd, F_SETLKW, &lock);
        if(ret<0){
                perror("lock failed\n");
                return -1;
        }
        sprintf(string, "%d", count);     
        printf("%s %d locking file\n",string, pid);
   
        strcat(buf, string);
        ret = write(fd, buf, sizeof(buf));
        if(ret<0){
                perror("write failed\n");
                return -1;
        }
        printf("%d : %d write file %s\n", count, pid, buf);
        count++;

        lock.l_type = F_ULOCK;
        ret = fcntl(fd, F_SETLK, &lock);
        if(ret<0){
                perror("unlock failed\n");
                return -1;
        }
 
        printf("%d unlock file\n", pid);
        sleep(2);
        close(fd);
    }

        return 0;
}

**Comment by davies** [comment]
@zzouqb Thanks for reporting this bug, we will fix it soon.

**Comment by SandyXSD** [comment]
It's fixed by #902 for "one writer many readers", as all readers can see the same contents.
For multiple writers, it's possible for the program you provided to write at the same offset, which makes the `tail` command in different hosts display different contents (both are right, but one is overwritten soon by the other). The results of `cat` should be the same though.
An valid solution for multiple writers is to use a standalone lock file. Then the basic procedure of application program would be: 
1. lock the lock file
2. open, write, close the data file
3. unlock the lock file
