### ISSUE TITLE
[Proposal] Add JuiceFS CSI Driver Chart to KubeSphere App Store

### ISSUE THREAD

**Issue by FeynmanZhou** [juicedata/juicefs#927]
Hi JuiceFS team,

The tutorial [Install JuiceFS on KubeSphere](https://github.com/juicedata/juicefs/blob/main/docs/zh_cn/juicefs_on_kubesphere.md) inspired me a lot. If you would like to make JuiceFS CSI Driver much visible and easier to deploy in KubeSphere, I recommend you to add the Helm Chart of JuiceFS CSI Driver to the built-in KubeSphere App Store. You can raise a PR to add it to this [folder](https://github.com/kubesphere/helm-charts/tree/master/src/stable), then you will be able to see JuiceFS CSI Driver in KubeSphere 3.2.

**Comment by zwwhdls** [comment]
PR already merged.
