### ISSUE TITLE
Stop writeback when the disk is almost full

### ISSUE THREAD

**Issue by davies** [juicedata/juicefs#942]
Currently, we don't limit the capacity used for writeback, which may fill all the free space, and other application may fail.

We should stop the writeback when the disk is almost full (the free ration is below half of specified `free ratio`), because writeback should have higher priority than read cache.

**Comment by aland-zhang** [comment]
When the data is synchronized to the object storage, the write cache needs to be automatically cleaned up, otherwise the disk space will always be occupied

**Comment by SandyXSD** [comment]
After uploaded, the data in local disk will be converted to read cache, which will be evicted automatically in an LRU-like strategy.
