### ISSUE TITLE
Support directories with millions of files.

### ISSUE THREAD

**Issue by davies** [juicedata/juicefs#95]
**What would you like to be added**:

Currently, we fetch the attributes of files in single directory with single batch request to Redis, that could be slow or fail, and block other requests. 

We can split those into small batches, for example, 1000 per batch.

**Why is this needed**:

The number of files could  be millions, we don't want people be bited by that.

### Backlog

- [x] Call `MGET` with small batches #110 
- [x] Use `HSCAN` instead of `HGETALL` #128

**Comment by suzaku** [comment]
Any more detail for this issue? In what kind of operation are the file attributes fetched?

**Comment by davies** [comment]
When you do `ls`,  a Readdir() will  be called. When plus is true, it will fetch all the attributes in one batch.

**Comment by suzaku** [comment]
Got it, I can take a try on this one.

**Comment by suzaku** [comment]
If there are millions of files, we might run into trouble when the first `HGetAll` call is reached. Any idea how to work around it?

**Comment by davies** [comment]
Yes. Right now, we don't have a work around, that could be the next challenge.

**Comment by davies** [comment]
The second part is done by #128
