### ISSUE TITLE
Format error with sqlite in Ubuntu

### ISSUE THREAD

**Issue by sanwan** [juicedata/juicefs#960]
The error is 
![image](https://user-images.githubusercontent.com/1523269/140851438-feaab14b-5359-4ece-bfa9-0c95368e0ed9.png)

My os info is 
Distributor ID:	Ubuntu
Description:	Ubuntu 20.04.3 LTS
Release:	20.04
Codename:	focal

Juicefs info is 
wan@wan-VirtualBox:~/Downloads$ ./juicefs -version
juicefs version 0.17.1 (2021-10-28T05:30:05Z 4d11c4b)

**Comment by SandyXSD** [comment]
The `/tmp/bbb` is probably an existing file with invalid db permission. Remove it and re-run the `format` command with sudo will fix this.
