### ISSUE TITLE
Failed to set http_proxy

### ISSUE THREAD

**Issue by Roay** [juicedata/juicefs#963]
环境：juicefs v0.15版本
问题描述：设置代理后，format或mount过程中没有按照设置走代理转发
重现步骤：
1、安装tinyproxy并配置端口号、允许所有IP访问。
2、curl测试：curl http://gdoss.xstore.ctyun.cn，通过代理日志“/var/log/tinyproxy/tinyproxy.log”查看到get请求，并返回成功。
3、juicefs格式化正常返回，但**代理日志没有相关信息，即没有走代理**。命令如下：
`# sudo juicefs format --storage s3 --bucket=https://gdoss.xstore.ctyun.cn/tttt12 --access-key=xxxx --secret-key=xxxx --force  redis://:xxxx@192.168.10.10:1680/2 jfs`
4、juicefs挂载也是同样，正常挂载，但是代理日志没相关日志输出。

**Comment by Roay** [comment]
sudo导致

**Comment by davies** [comment]
@Roay 请问代理可以工作了？
