### ISSUE TITLE
JuiceFS can't working on redis-enterprise 

### ISSUE THREAD

**Issue by WPH95** [juicedata/juicefs#99]
```
root@ubuntu:/# ./juicefs --debug format --storage=s3 --bucket=https://juicefs-peter-test.s3.us-east-1.amazonaws.com     --access-key={} --secret-key={}   redis-enterprise.default.svc.cluster.local:8001 data
2021/01/21 08:21:50.811888 juicefs[3018] <INFO>: Meta address: redis://redis-enterprise.default.svc.cluster.local:8001
2021/01/21 08:21:50.816244 juicefs[3018] <WARNING>: parse info: ERR command not found
2021/01/21 08:21:50.816410 juicefs[3018] <FATAL>: Meta is not available: create session: ERR command not found
root@ubuntu:/# redis-cli
Could not connect to Redis at 127.0.0.1:6379: Connection refused
not connected>
root@ubuntu:/# redis-cli -h redis-enterprise.default.svc.cluster.local -p 8001
redis-enterprise.default.svc.cluster.local:8001> ping
PONG
redis-enterprise.default.svc.cluster.local:8001>
```

**Comment by davies** [comment]
How to get a redis-enterprise?

**Comment by davies** [comment]
It's weird that it does not support INFO command.

Do you use latest main branch or binary release?

**Comment by davies** [comment]
It looks like the `INCR` is also not supported, so there should be something wrong with Redis.

**Comment by WPH95** [comment]
https://github.com/RedisLabs/redis-enterprise-k8s-docs

**Comment by WPH95** [comment]
> It looks like the `INCR` is also not supported, so there should be something wrong with Redis.

Yep that's right. Use other redis instance to avoid it.
By the way, Error msg not helpful. I read the source code to understand what happened

**Comment by xiaogaozi** [comment]
It looks like this issue is related to specific instance of Redis Enterprise. Close the issue now and feel free to re-open it if needed.
